"use client";
import { FormEvent, useState } from "react";
import { AlertTriangle, BookOpenCheck, GitCompareArrows, Search, ShieldCheck, Sparkles, Workflow } from "lucide-react";
import { reviewerApi } from "@/lib/api";
import { useEventStream } from "@/lib/hooks/use-event-stream";
import type { AppealReconsideration, EvidenceSearchResult } from "@/lib/schemas";
import { AppealResolutionPanel } from "@/components/review/appeal-resolution-panel";

export default function AppealReviewPage(){
  const [claimId,setClaimId]=useState(""); const [appealId,setAppealId]=useState(""); const [data,setData]=useState<AppealReconsideration|null>(null);
  const [query,setQuery]=useState("What materially changed compared with the original locked evidence?"); const [searchResult,setSearchResult]=useState<EvidenceSearchResult|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const load=async(e?:FormEvent)=>{e?.preventDefault();if(!claimId||!appealId)return;setBusy(true);setError(null);try{setData(await reviewerApi.appealReconsideration(claimId,appealId))}catch(x){setError(x instanceof Error?x.message:"Appeal review unavailable")}finally{setBusy(false)}};
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError(null);try{await fn();await load()}catch(x){setError(x instanceof Error?x.message:"Action failed")}finally{setBusy(false)}};
  const recommendation=data?.recommendations.at(-1); const waiting=data?.checkpoints.find(x=>x.status==="waiting");
  const {state:streamState}=useEventStream(claimId&&appealId?`/api/reviewer/claims/${encodeURIComponent(claimId)}/events`:null,()=>{if(data)void load()});
  return <div className="space-y-5">
    <section className="card p-6 border-teal-400/20"><div className="flex items-start justify-between gap-4"><div><div className="panel-title">human-governed reconsideration · SSE {streamState}</div><h1 className="text-2xl font-bold mt-1">Independent Appeal Review</h1><p className="mt-2 max-w-4xl text-sm text-slate-400">Supplemental evidence is re-ingested into an appeal-specific immutable snapshot and compared with the original locked evidence. AI output is <b className="text-teal-300">Recommendation only</b>; only the assigned independent human appeal reviewer can affirm, modify or overturn.</p></div><ShieldCheck className="h-9 w-9 text-teal-300"/></div></section>
    <form onSubmit={load} className="card p-4 grid md:grid-cols-[1fr_1fr_auto] gap-3"><input className="input" value={claimId} onChange={e=>setClaimId(e.target.value)} placeholder="Claim ID"/><input className="input" value={appealId} onChange={e=>setAppealId(e.target.value)} placeholder="Appeal ID"/><button className="btn btn-primary" disabled={busy}><BookOpenCheck className="h-4 w-4"/>Open workbench</button></form>
    {error&&<div className="rounded-xl border border-rose-500/30 bg-rose-950/30 p-3 text-sm text-rose-200"><AlertTriangle className="inline h-4 w-4 mr-2"/>{error}</div>}
    {data&&<>
      <section className="grid sm:grid-cols-2 xl:grid-cols-5 gap-3"><Kpi label="Appeal status" value={data.appeal_status}/><Kpi label="Reviewer" value={data.assigned_reviewer_user_id||"unassigned"}/><Kpi label="Snapshot" value={data.evidence_snapshot?.status||"not built"}/><Kpi label="Changed facts" value={String(data.comparisons.filter(x=>x.comparison_type!=="corroborating").length)}/><Kpi label="Modalities" value={data.evidence_snapshot?.modalities.join(", ")||"—"}/></section>
      <section className="grid xl:grid-cols-2 gap-5">
        <div className="card p-5"><div className="flex justify-between"><div><div className="panel-title">Immutable evidence snapshot</div><h2 className="font-semibold mt-1">Original vs supplemental evidence</h2></div><GitCompareArrows className="text-teal-300"/></div><div className="mt-4 space-y-2 text-sm">{data.reingestions.length===0?<p className="text-slate-500">No supplemental evidence registered.</p>:data.reingestions.map(x=><div key={x.reingestion_id} className="rounded-xl border border-[#1f3852] p-3"><div className="flex justify-between"><b>{x.source_id}</b><span className={x.status==="ready"?"text-emerald-300":"text-amber-300"}>{x.status}</span></div><div className="text-xs text-slate-500 mt-1">v{x.source_version} · {x.modality} · {x.file_validation_status} · malware: {x.malware_verdict} · chunks {x.chunk_count}</div>{x.status!=="ready"&&<button className="btn btn-ghost mt-2" disabled={busy} onClick={()=>void act(()=>reviewerApi.reingestAppealEvidence(claimId,appealId,x.source_id))}>Validate & re-ingest</button>}</div>)}</div><button className="btn btn-primary mt-4" disabled={busy} onClick={()=>void act(()=>reviewerApi.buildAppealSnapshot(claimId,appealId))}>Lock appeal snapshot</button>{data.evidence_snapshot&&<div className="mono text-[10px] break-all text-slate-500 mt-3">{data.evidence_snapshot.snapshot_sha256}</div>}</div>
        <div className="card p-5"><div className="panel-title">Changed-fact analysis</div><div className="mt-3 space-y-2 max-h-[360px] overflow-auto">{data.comparisons.length===0?<p className="text-sm text-slate-500">Build the snapshot to compare evidence.</p>:data.comparisons.map(x=><div key={x.comparison_id} className="rounded-xl border border-[#1f3852] p-3"><div className="flex justify-between gap-2"><b className="text-sm">{x.field}</b><span className={x.severity==="material"?"text-amber-300 text-xs":"text-slate-400 text-xs"}>{x.comparison_type} · {x.severity}</span></div><p className="text-xs text-slate-400 mt-1">{x.description}</p><details className="mt-2 text-xs"><summary className="cursor-pointer text-teal-300">Citation drill-down ({x.citations.length})</summary><pre className="mt-2 whitespace-pre-wrap text-[10px] text-slate-500">{JSON.stringify(x.citations,null,2)}</pre></details></div>)}</div></div>
      </section>
      <section className="card p-5"><div className="flex justify-between"><div><div className="panel-title">Appeal-specific hybrid retrieval</div><h2 className="font-semibold mt-1">Original + supplemental evidence search</h2></div><Search className="text-teal-300"/></div><div className="flex gap-2 mt-4"><input className="input flex-1" value={query} onChange={e=>setQuery(e.target.value)}/><button className="btn btn-ghost" disabled={busy||!data.evidence_snapshot} onClick={()=>void(async()=>{setBusy(true);try{setSearchResult(await reviewerApi.searchAppealEvidence(claimId,appealId,query))}catch(x){setError(x instanceof Error?x.message:"Search failed")}finally{setBusy(false)}})()}>Search</button></div>{searchResult&&<div className="grid lg:grid-cols-2 gap-2 mt-4">{searchResult.items?.map((x)=><div key={x.item_id} className="rounded-xl bg-[#091727] border border-[#1f3852] p-3 text-xs"><div className="flex justify-between"><b>{x.source_scope} · v{x.source_version}</b><span>score {Number(x.score).toFixed(3)}</span></div><p className="text-slate-300 mt-2">{x.text_preview}</p><details className="mt-2"><summary className="text-teal-300 cursor-pointer">Citation</summary><pre className="text-[10px] whitespace-pre-wrap mt-1">{JSON.stringify(x.citation,null,2)}</pre></details></div>)}</div>}</section>
      <section className="grid xl:grid-cols-2 gap-5"><div className="card p-5"><div className="flex justify-between"><div><div className="panel-title">Recommendation-only agent</div><h2 className="font-semibold mt-1">Non-binding reconsideration support</h2></div><Sparkles className="text-teal-300"/></div><button className="btn btn-primary mt-4" disabled={busy||!data.evidence_snapshot} onClick={()=>void act(()=>reviewerApi.runAppealRecommendation(claimId,appealId,query))}>Run evidence-grounded recommendation</button>{recommendation&&<div className="mt-4 rounded-xl border border-teal-400/20 bg-teal-950/10 p-4"><div className="flex justify-between"><b>{recommendation.recommendation}</b><span className="text-xs text-teal-300">authority: {recommendation.adjudication_authority}</span></div><p className="text-sm text-slate-300 mt-2">{recommendation.recommendation_summary}</p><div className="text-xs text-slate-500 mt-2">Human review required: {String(recommendation.requires_human_review)} · confidence {recommendation.confidence.toFixed(2)}</div></div>}</div>
      <div className="card p-5"><div className="flex justify-between"><div><div className="panel-title">Durable human checkpoint</div><h2 className="font-semibold mt-1">Reviewer control & escalation</h2></div><Workflow className="text-teal-300"/></div>{waiting?<div className="mt-4"><p className="text-sm text-slate-300">Workflow is paused at <b>{waiting.stage}</b> and requires the assigned independent reviewer.</p><div className="mono text-[10px] text-slate-500 break-all mt-2">{waiting.state_sha256}</div><button className="btn btn-ghost mt-3" disabled={busy} onClick={()=>void act(()=>reviewerApi.resumeAppealCheckpoint(claimId,appealId,waiting.checkpoint_id))}>Resume checkpoint</button></div>:<p className="text-sm text-slate-500 mt-4">No waiting checkpoint.</p>}<div className="mt-4 flex flex-wrap gap-2"><button className="btn btn-ghost" disabled={busy} onClick={()=>void act(()=>reviewerApi.requestAppealEvidence(claimId,appealId,["itemized_bill"],"Additional itemized evidence is required before independent human resolution."))}>Request missing evidence</button><button className="btn btn-ghost" disabled={busy} onClick={()=>void act(()=>reviewerApi.escalateAppeal(claimId,appealId,"Material contradiction requires second-level independent human review."))}>Second-level escalation</button></div></div></section>
      <AppealResolutionPanel claimId={claimId} appealId={appealId} reconsideration={data}/>
      <section className="card p-5 border-emerald-500/20"><div className="panel-title">Authority boundary</div><p className="mt-2 text-sm text-slate-300">LLM: <b>false</b> · LangGraph: <b>false</b> · RAG: <b>false</b> · MCP: <b>false</b> for affirm/modify/overturn. Independent human required: <b className="text-emerald-300">{String(data.human_authority.independent_human_required)}</b>.</p></section>
    </>}
  </div>
}
function Kpi({label,value}:{label:string;value:string}){return <div className="card p-4"><div className="text-[11px] uppercase tracking-wider text-slate-500">{label}</div><div className="font-bold mt-2 truncate" title={value}>{value}</div></div>}
