from __future__ import annotations
from datetime import date, datetime
from decimal import Decimal
from sqlalchemy import Boolean, Date, DateTime, ForeignKey, Index, Integer, JSON, Numeric, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base

class AccountingPeriodModel(Base):
    __tablename__="accounting_periods"
    __table_args__=(UniqueConstraint("tenant_id","period_key",name="uq_accounting_period_key"),Index("ix_accounting_period_status","tenant_id","status","end_date"))
    period_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);period_key:Mapped[str]=mapped_column(String(20),nullable=False);start_date:Mapped[date]=mapped_column(Date,nullable=False);end_date:Mapped[date]=mapped_column(Date,nullable=False);status:Mapped[str]=mapped_column(String(20),nullable=False);lock_version:Mapped[int]=mapped_column(Integer,nullable=False,default=1);close_summary:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);close_sha256:Mapped[str|None]=mapped_column(String(64));closed_by_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);closed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class LedgerJournalModel(Base):
    __tablename__="ledger_journals"
    __table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_ledger_journal_idem"),UniqueConstraint("tenant_id","journal_sha256",name="uq_ledger_journal_sha"),Index("ix_ledger_journal_claim","tenant_id","claim_id","created_at"))
    journal_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False);payment_intent_id:Mapped[str|None]=mapped_column(ForeignKey("payment_intents.payment_intent_id",ondelete="RESTRICT"));period_id:Mapped[str]=mapped_column(ForeignKey("accounting_periods.period_id",ondelete="RESTRICT"),nullable=False);journal_type:Mapped[str]=mapped_column(String(60),nullable=False);source_type:Mapped[str]=mapped_column(String(60),nullable=False);source_id:Mapped[str]=mapped_column(String(180),nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);total_debits:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);total_credits:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);status:Mapped[str]=mapped_column(String(20),nullable=False);previous_journal_sha256:Mapped[str|None]=mapped_column(String(64));journal_sha256:Mapped[str]=mapped_column(String(64),nullable=False);posted_by_actor_type:Mapped[str]=mapped_column(String(50),nullable=False);posted_by_actor_id:Mapped[str]=mapped_column(String(128),nullable=False);idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False);trace_id:Mapped[str|None]=mapped_column(String(128));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class LedgerEntryModel(Base):
    __tablename__="ledger_entries"
    __table_args__=(UniqueConstraint("tenant_id","journal_id","entry_sequence",name="uq_ledger_entry_sequence"),Index("ix_ledger_entry_account","tenant_id","account_code","created_at"))
    entry_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);journal_id:Mapped[str]=mapped_column(ForeignKey("ledger_journals.journal_id",ondelete="RESTRICT"),nullable=False);claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False);entry_sequence:Mapped[int]=mapped_column(Integer,nullable=False);account_code:Mapped[str]=mapped_column(String(80),nullable=False);direction:Mapped[str]=mapped_column(String(6),nullable=False);amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);memo:Mapped[str]=mapped_column(String(500),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class ERARecordModel(Base):
    __tablename__="era_records"
    __table_args__=(UniqueConstraint("tenant_id","era_reference",name="uq_era_reference"),Index("ix_era_payment","tenant_id","payment_intent_id","received_at"))
    era_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False);payment_intent_id:Mapped[str]=mapped_column(ForeignKey("payment_intents.payment_intent_id",ondelete="RESTRICT"),nullable=False);era_reference:Mapped[str]=mapped_column(String(180),nullable=False);payment_reference:Mapped[str]=mapped_column(String(180),nullable=False);provider_ref:Mapped[str]=mapped_column(String(160),nullable=False);paid_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);remittance_payload:Mapped[dict]=mapped_column(JSON,nullable=False);payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);received_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class EFTRecordModel(Base):
    __tablename__="eft_records"
    __table_args__=(UniqueConstraint("tenant_id","eft_reference",name="uq_eft_reference"),Index("ix_eft_payment","tenant_id","payment_intent_id","received_at"))
    eft_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False);payment_intent_id:Mapped[str]=mapped_column(ForeignKey("payment_intents.payment_intent_id",ondelete="RESTRICT"),nullable=False);eft_reference:Mapped[str]=mapped_column(String(180),nullable=False);bank_reference:Mapped[str]=mapped_column(String(180),nullable=False);trace_number:Mapped[str]=mapped_column(String(180),nullable=False);amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False);payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);received_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class PaymentReconciliationModel(Base):
    __tablename__="payment_reconciliations"
    __table_args__=(UniqueConstraint("tenant_id","payment_intent_id",name="uq_payment_reconciliation_intent"),Index("ix_payment_recon_status","tenant_id","status","updated_at"))
    reconciliation_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False);payment_intent_id:Mapped[str]=mapped_column(ForeignKey("payment_intents.payment_intent_id",ondelete="RESTRICT"),nullable=False);expected_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);era_total:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);eft_total:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);matched_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);unmatched_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);reference_match:Mapped[bool]=mapped_column(Boolean,nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False);era_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list);eft_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list);journal_id:Mapped[str|None]=mapped_column(ForeignKey("ledger_journals.journal_id",ondelete="RESTRICT"));reconciliation_sha256:Mapped[str]=mapped_column(String(64),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);reconciled_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class ReturnedPaymentModel(Base):
    __tablename__="returned_payments";__table_args__=(UniqueConstraint("tenant_id","return_reference",name="uq_return_reference"),)
    return_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False);payment_intent_id:Mapped[str]=mapped_column(ForeignKey("payment_intents.payment_intent_id",ondelete="RESTRICT"),nullable=False);return_reference:Mapped[str]=mapped_column(String(180),nullable=False);return_code:Mapped[str]=mapped_column(String(80),nullable=False);amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);reason:Mapped[str]=mapped_column(Text,nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False);journal_id:Mapped[str|None]=mapped_column(ForeignKey("ledger_journals.journal_id",ondelete="RESTRICT"));received_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class AccountingAdjustmentModel(Base):
    __tablename__="accounting_adjustments";__table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_accounting_adjustment_idem"),Index("ix_accounting_adjustment_status","tenant_id","status","created_at"))
    adjustment_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False);payment_intent_id:Mapped[str]=mapped_column(ForeignKey("payment_intents.payment_intent_id",ondelete="RESTRICT"),nullable=False);adjustment_type:Mapped[str]=mapped_column(String(30),nullable=False);amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);reason_code:Mapped[str]=mapped_column(String(80),nullable=False);rationale:Mapped[str]=mapped_column(Text,nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False);requested_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);approved_by_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"));journal_id:Mapped[str|None]=mapped_column(ForeignKey("ledger_journals.journal_id",ondelete="RESTRICT"));idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class ProviderRemittanceStatusModel(Base):
    __tablename__="provider_remittance_status";__table_args__=(UniqueConstraint("tenant_id","payment_intent_id",name="uq_provider_remittance_intent"),)
    status_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False);payment_intent_id:Mapped[str]=mapped_column(ForeignKey("payment_intents.payment_intent_id",ondelete="RESTRICT"),nullable=False);provider_ref:Mapped[str]=mapped_column(String(160),nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False);remitted_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);latest_era_reference:Mapped[str|None]=mapped_column(String(180));latest_eft_reference:Mapped[str|None]=mapped_column(String(180));updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class AccountingReconciliationQueueModel(Base):
    __tablename__="accounting_reconciliation_queue";__table_args__=(UniqueConstraint("tenant_id","payment_intent_id",name="uq_accounting_queue_intent"),Index("ix_accounting_queue_aging","tenant_id","status","age_days"))
    queue_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False);payment_intent_id:Mapped[str]=mapped_column(ForeignKey("payment_intents.payment_intent_id",ondelete="RESTRICT"),nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False);age_days:Mapped[int]=mapped_column(Integer,nullable=False);aging_bucket:Mapped[str]=mapped_column(String(20),nullable=False);priority:Mapped[int]=mapped_column(Integer,nullable=False);exception_codes:Mapped[list]=mapped_column(JSON,nullable=False,default=list);assigned_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);closed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
