from __future__ import annotations
from datetime import datetime
from sqlalchemy import Boolean, DateTime, ForeignKey, Index, Integer, JSON, Numeric, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base

class AppealDecisionPacketModel(Base):
    __tablename__="appeal_decision_packets"
    __table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_appeal_decision_packet_idempotency"),UniqueConstraint("tenant_id","appeal_id","packet_version",name="uq_appeal_decision_packet_version"),Index("ix_appeal_decision_packet","tenant_id","appeal_id","created_at"))
    packet_id:Mapped[str]=mapped_column(String(128),primary_key=True); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True); claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False,index=True); appeal_id:Mapped[str]=mapped_column(ForeignKey("appeal_cases.appeal_id",ondelete="CASCADE"),nullable=False,index=True)
    primary_reviewer_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False); second_reviewer_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=True)
    snapshot_id:Mapped[str]=mapped_column(ForeignKey("appeal_evidence_snapshots.snapshot_id",ondelete="RESTRICT"),nullable=False); snapshot_sha256:Mapped[str]=mapped_column(String(64),nullable=False); recommendation_run_id:Mapped[str|None]=mapped_column(ForeignKey("appeal_reconsideration_runs.reconsideration_run_id",ondelete="RESTRICT"),nullable=True)
    outcome:Mapped[str]=mapped_column(String(30),nullable=False); controlling_decision:Mapped[str]=mapped_column(String(40),nullable=False); rationale:Mapped[str]=mapped_column(Text,nullable=False); reason_codes:Mapped[list]=mapped_column(JSON,nullable=False,default=list); citation_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list); resolved_comparison_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list); annotation_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list); checkpoint_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list)
    original_approved_amount:Mapped[float]=mapped_column(Numeric(14,2),nullable=False); reconsidered_approved_amount:Mapped[float]=mapped_column(Numeric(14,2),nullable=False); financial_delta:Mapped[float]=mapped_column(Numeric(14,2),nullable=False); material_financial_change:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False)
    recommendation_disagreement:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False); recommendation_disagreement_reason:Mapped[str|None]=mapped_column(Text,nullable=True); completeness:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict); blocker_codes:Mapped[list]=mapped_column(JSON,nullable=False,default=list); dual_control_required:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False)
    status:Mapped[str]=mapped_column(String(40),nullable=False,default="draft"); packet_version:Mapped[int]=mapped_column(Integer,nullable=False,default=1); expected_appeal_version:Mapped[int]=mapped_column(Integer,nullable=False); locked_payload_sha256:Mapped[str|None]=mapped_column(String(64),nullable=True); final_resolution_id:Mapped[str|None]=mapped_column(String(128),nullable=True); idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False); trace_id:Mapped[str|None]=mapped_column(String(128),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); locked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); closed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)

class AppealDecisionSecondReviewModel(Base):
    __tablename__="appeal_decision_second_reviews"; __table_args__=(UniqueConstraint("tenant_id","packet_id","reviewer_user_id",name="uq_appeal_decision_second_review"),)
    second_review_id:Mapped[str]=mapped_column(String(128),primary_key=True); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True); claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False); appeal_id:Mapped[str]=mapped_column(ForeignKey("appeal_cases.appeal_id",ondelete="CASCADE"),nullable=False); packet_id:Mapped[str]=mapped_column(ForeignKey("appeal_decision_packets.packet_id",ondelete="CASCADE"),nullable=False); reviewer_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False); action:Mapped[str]=mapped_column(String(20),nullable=False); rationale:Mapped[str]=mapped_column(Text,nullable=False); packet_version:Mapped[int]=mapped_column(Integer,nullable=False); payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class AppealFinalResolutionModel(Base):
    __tablename__="appeal_final_resolutions"; __table_args__=(UniqueConstraint("tenant_id","appeal_id",name="uq_appeal_final_resolution_once"),UniqueConstraint("tenant_id","idempotency_key",name="uq_appeal_final_resolution_idempotency"),)
    resolution_id:Mapped[str]=mapped_column(String(128),primary_key=True); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True); claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False); appeal_id:Mapped[str]=mapped_column(ForeignKey("appeal_cases.appeal_id",ondelete="RESTRICT"),nullable=False); packet_id:Mapped[str]=mapped_column(ForeignKey("appeal_decision_packets.packet_id",ondelete="RESTRICT"),nullable=False); primary_reviewer_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False); second_reviewer_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=True); outcome:Mapped[str]=mapped_column(String(30),nullable=False); controlling_decision:Mapped[str]=mapped_column(String(40),nullable=False); original_approved_amount:Mapped[float]=mapped_column(Numeric(14,2),nullable=False); reconsidered_approved_amount:Mapped[float]=mapped_column(Numeric(14,2),nullable=False); financial_delta:Mapped[float]=mapped_column(Numeric(14,2),nullable=False); reconsideration_snapshot_sha256:Mapped[str]=mapped_column(String(64),nullable=False); packet_locked_sha256:Mapped[str]=mapped_column(String(64),nullable=False); provenance:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict); payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False); supersedes_history_version_id:Mapped[str|None]=mapped_column(String(128),nullable=True); history_version_id:Mapped[str|None]=mapped_column(String(128),nullable=True); notice_id:Mapped[str|None]=mapped_column(String(128),nullable=True); idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False); trace_id:Mapped[str|None]=mapped_column(String(128),nullable=True); resolved_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class AppealResolutionAuditEventModel(Base):
    __tablename__="appeal_resolution_audit_events"; __table_args__=(UniqueConstraint("tenant_id","appeal_id","sequence",name="uq_appeal_resolution_audit_sequence"),UniqueConstraint("tenant_id","idempotency_key",name="uq_appeal_resolution_audit_idempotency"),)
    audit_event_id:Mapped[str]=mapped_column(String(128),primary_key=True); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True); claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False); appeal_id:Mapped[str]=mapped_column(ForeignKey("appeal_cases.appeal_id",ondelete="CASCADE"),nullable=False); packet_id:Mapped[str|None]=mapped_column(ForeignKey("appeal_decision_packets.packet_id",ondelete="SET NULL"),nullable=True); sequence:Mapped[int]=mapped_column(Integer,nullable=False); event_type:Mapped[str]=mapped_column(String(100),nullable=False); actor_type:Mapped[str]=mapped_column(String(30),nullable=False); actor_id:Mapped[str]=mapped_column(String(128),nullable=False); payload:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict); previous_event_sha256:Mapped[str|None]=mapped_column(String(64),nullable=True); event_sha256:Mapped[str]=mapped_column(String(64),nullable=False); idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False); trace_id:Mapped[str|None]=mapped_column(String(128),nullable=True); occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
