from __future__ import annotations
from datetime import datetime
from decimal import Decimal
from sqlalchemy import Boolean, DateTime, ForeignKey, Index, Integer, JSON, Numeric, String, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base

class FinancialAuthorizationPacketModel(Base):
    __tablename__="financial_authorization_packets"
    __table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_fin_packet_idem"),Index("ix_fin_packet_claim","tenant_id","claim_id","packet_version"))
    packet_id:Mapped[str]=mapped_column(String(128),primary_key=True); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True); claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False)
    packet_version:Mapped[int]=mapped_column(Integer,nullable=False); status:Mapped[str]=mapped_column(String(40),nullable=False); controlling_source_type:Mapped[str]=mapped_column(String(60),nullable=False); controlling_source_id:Mapped[str]=mapped_column(String(128),nullable=False); decision_history_version_id:Mapped[str]=mapped_column(ForeignKey("decision_history_versions.history_version_id",ondelete="RESTRICT"),nullable=False); decision_history_sha256:Mapped[str]=mapped_column(String(64),nullable=False); evidence_snapshot_sha256:Mapped[str]=mapped_column(String(64),nullable=False)
    controlling_decision:Mapped[str]=mapped_column(String(40),nullable=False); claim_total_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False); approved_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False); member_responsibility:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False); payer_responsibility:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False); currency:Mapped[str]=mapped_column(String(3),nullable=False); line_reconciliation:Mapped[list]=mapped_column(JSON,nullable=False,default=list)
    prepared_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False); authorized_by_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=True); authorization_rationale:Mapped[str|None]=mapped_column(String(5000),nullable=True); locked_payload_sha256:Mapped[str|None]=mapped_column(String(64),nullable=True); authorized_payload_sha256:Mapped[str|None]=mapped_column(String(64),nullable=True); idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False); trace_id:Mapped[str|None]=mapped_column(String(128),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); locked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); authorized_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)

class RemittanceArtifactModel(Base):
    __tablename__="remittance_artifacts"; __table_args__=(UniqueConstraint("tenant_id","packet_id","artifact_type",name="uq_remit_packet_type"),)
    artifact_id:Mapped[str]=mapped_column(String(128),primary_key=True); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True); claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False); packet_id:Mapped[str]=mapped_column(ForeignKey("financial_authorization_packets.packet_id",ondelete="CASCADE"),nullable=False); artifact_type:Mapped[str]=mapped_column(String(40),nullable=False); format_version:Mapped[str]=mapped_column(String(40),nullable=False); content:Mapped[dict]=mapped_column(JSON,nullable=False); content_sha256:Mapped[str]=mapped_column(String(64),nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class PaymentHoldModel(Base):
    __tablename__="payment_holds"; __table_args__=(Index("ix_payment_hold_claim","tenant_id","claim_id","active"),)
    hold_id:Mapped[str]=mapped_column(String(128),primary_key=True); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True); claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False); hold_type:Mapped[str]=mapped_column(String(60),nullable=False); reason_code:Mapped[str]=mapped_column(String(100),nullable=False); rationale:Mapped[str]=mapped_column(String(5000),nullable=False); active:Mapped[bool]=mapped_column(Boolean,nullable=False,default=True); placed_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False); released_by_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); released_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)

class PaymentIntentModel(Base):
    __tablename__="payment_intents"; __table_args__=(UniqueConstraint("tenant_id","packet_id",name="uq_payment_intent_packet"),UniqueConstraint("tenant_id","payment_fingerprint",name="uq_payment_fingerprint"),UniqueConstraint("tenant_id","idempotency_key",name="uq_payment_intent_idem"),Index("ix_payment_intent_status","tenant_id","status","created_at"))
    payment_intent_id:Mapped[str]=mapped_column(String(128),primary_key=True); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True); claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False); packet_id:Mapped[str]=mapped_column(ForeignKey("financial_authorization_packets.packet_id",ondelete="RESTRICT"),nullable=False); amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False); currency:Mapped[str]=mapped_column(String(3),nullable=False); payee_ref:Mapped[str]=mapped_column(String(160),nullable=False); status:Mapped[str]=mapped_column(String(40),nullable=False); payment_fingerprint:Mapped[str]=mapped_column(String(64),nullable=False); external_instruction_id:Mapped[str|None]=mapped_column(String(180),nullable=True); adapter_name:Mapped[str|None]=mapped_column(String(80),nullable=True); idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); submitted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); settled_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)

class FinancialHandoffModel(Base):
    __tablename__="financial_handoffs"; __table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_fin_handoff_idem"),)
    handoff_id:Mapped[str]=mapped_column(String(128),primary_key=True); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True); claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False); payment_intent_id:Mapped[str]=mapped_column(ForeignKey("payment_intents.payment_intent_id",ondelete="CASCADE"),nullable=False); adapter_name:Mapped[str]=mapped_column(String(80),nullable=False); instruction_sha256:Mapped[str]=mapped_column(String(64),nullable=False); external_instruction_id:Mapped[str]=mapped_column(String(180),nullable=False); status:Mapped[str]=mapped_column(String(40),nullable=False); idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False); trace_id:Mapped[str|None]=mapped_column(String(128),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class SettlementEventModel(Base):
    __tablename__="settlement_events"; __table_args__=(UniqueConstraint("tenant_id","provider_event_id",name="uq_settlement_provider_event"),Index("ix_settlement_intent","tenant_id","payment_intent_id","occurred_at"))
    settlement_event_id:Mapped[str]=mapped_column(String(128),primary_key=True); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True); claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False); payment_intent_id:Mapped[str]=mapped_column(ForeignKey("payment_intents.payment_intent_id",ondelete="CASCADE"),nullable=False); provider_event_id:Mapped[str]=mapped_column(String(180),nullable=False); status:Mapped[str]=mapped_column(String(40),nullable=False); settled_amount:Mapped[Decimal|None]=mapped_column(Numeric(14,2),nullable=True); currency:Mapped[str|None]=mapped_column(String(3),nullable=True); external_reference:Mapped[str|None]=mapped_column(String(180),nullable=True); payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False); occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); received_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class FinancialReconciliationExceptionModel(Base):
    __tablename__="financial_reconciliation_exceptions"; __table_args__=(Index("ix_fin_recon_open","tenant_id","status","created_at"),)
    exception_id:Mapped[str]=mapped_column(String(128),primary_key=True); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True); claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False); payment_intent_id:Mapped[str]=mapped_column(ForeignKey("payment_intents.payment_intent_id",ondelete="CASCADE"),nullable=False); exception_type:Mapped[str]=mapped_column(String(80),nullable=False); expected:Mapped[dict]=mapped_column(JSON,nullable=False); observed:Mapped[dict]=mapped_column(JSON,nullable=False); status:Mapped[str]=mapped_column(String(30),nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); resolved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); resolved_by_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=True)

class PaymentVoidReissueModel(Base):
    __tablename__="payment_void_reissues"; __table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_void_reissue_idem"),)
    request_id:Mapped[str]=mapped_column(String(128),primary_key=True); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True); claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False); payment_intent_id:Mapped[str]=mapped_column(ForeignKey("payment_intents.payment_intent_id",ondelete="CASCADE"),nullable=False); action:Mapped[str]=mapped_column(String(30),nullable=False); status:Mapped[str]=mapped_column(String(30),nullable=False); reason:Mapped[str]=mapped_column(String(5000),nullable=False); requested_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False); approved_by_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=True); replacement_payment_intent_id:Mapped[str|None]=mapped_column(ForeignKey("payment_intents.payment_intent_id",ondelete="SET NULL"),nullable=True); idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)

class FinancialAuditEventModel(Base):
    __tablename__="financial_audit_events"; __table_args__=(UniqueConstraint("tenant_id","claim_id","sequence",name="uq_fin_audit_sequence"),UniqueConstraint("tenant_id","idempotency_key",name="uq_fin_audit_idem"))
    audit_event_id:Mapped[str]=mapped_column(String(128),primary_key=True); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True); claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False); sequence:Mapped[int]=mapped_column(Integer,nullable=False); event_type:Mapped[str]=mapped_column(String(80),nullable=False); actor_type:Mapped[str]=mapped_column(String(40),nullable=False); actor_id:Mapped[str]=mapped_column(String(128),nullable=False); payload:Mapped[dict]=mapped_column(JSON,nullable=False); previous_event_sha256:Mapped[str|None]=mapped_column(String(64),nullable=True); event_sha256:Mapped[str]=mapped_column(String(64),nullable=False); idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False); occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class FinancialTaskModel(Base):
    __tablename__="financial_tasks"; __table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_fin_task_idem"),Index("ix_fin_task_queue","tenant_id","status","due_at"))
    task_id:Mapped[str]=mapped_column(String(128),primary_key=True); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True); claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False); payment_intent_id:Mapped[str|None]=mapped_column(ForeignKey("payment_intents.payment_intent_id",ondelete="CASCADE"),nullable=True); task_type:Mapped[str]=mapped_column(String(60),nullable=False); status:Mapped[str]=mapped_column(String(30),nullable=False); priority:Mapped[int]=mapped_column(Integer,nullable=False); due_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); assigned_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=True); idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
