from __future__ import annotations
from datetime import date,datetime
from sqlalchemy import Boolean,Date,DateTime,Float,ForeignKey,Index,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base

class DisputeEvidenceReingestionModel(Base):
    __tablename__="dispute_evidence_reingestions";__table_args__=(UniqueConstraint("tenant_id","dispute_id","source_kind","source_id","source_version",name="uq_dispute_reingestion_source_version"),Index("ix_dispute_reingestion","tenant_id","dispute_id","status"))
    reingestion_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False,index=True);dispute_id:Mapped[str]=mapped_column(ForeignKey("provider_disputes.dispute_id",ondelete="CASCADE"),nullable=False,index=True);claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False,index=True);source_kind:Mapped[str]=mapped_column(String(24),nullable=False);source_id:Mapped[str]=mapped_column(String(256),nullable=False);source_version:Mapped[str]=mapped_column(String(128),nullable=False);modality:Mapped[str]=mapped_column(String(30),nullable=False);media_type:Mapped[str]=mapped_column(String(160),nullable=False);content_sha256:Mapped[str]=mapped_column(String(64),nullable=False);file_validation_status:Mapped[str]=mapped_column(String(30),nullable=False);malware_verdict:Mapped[str]=mapped_column(String(40),nullable=False);extraction_status:Mapped[str]=mapped_column(String(30),nullable=False);chunk_count:Mapped[int]=mapped_column(Integer,nullable=False,default=0);chunk_manifest:Mapped[list]=mapped_column(JSON,nullable=False,default=list);embedding_model:Mapped[str]=mapped_column(String(120),nullable=False);embedding_dimensions:Mapped[int]=mapped_column(Integer,nullable=False);embedding_input_sha256s:Mapped[list]=mapped_column(JSON,nullable=False,default=list);index_version:Mapped[str]=mapped_column(String(80),nullable=False);retrieval_namespace:Mapped[str]=mapped_column(String(180),nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False);error_code:Mapped[str|None]=mapped_column(String(80));error_detail:Mapped[str|None]=mapped_column(Text);trace_id:Mapped[str|None]=mapped_column(String(128));started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class DisputeEvidenceSnapshotModel(Base):
    __tablename__="dispute_evidence_snapshots";__table_args__=(UniqueConstraint("tenant_id","dispute_id","snapshot_version",name="uq_dispute_snapshot_version"),UniqueConstraint("tenant_id","snapshot_sha256",name="uq_dispute_snapshot_sha"),Index("ix_dispute_snapshot","tenant_id","dispute_id","created_at"))
    snapshot_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);dispute_id:Mapped[str]=mapped_column(ForeignKey("provider_disputes.dispute_id",ondelete="CASCADE"),nullable=False,index=True);claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False);recovery_evidence_pack_sha256:Mapped[str]=mapped_column(String(64),nullable=False);provider_sources:Mapped[list]=mapped_column(JSON,nullable=False,default=list);policy_sources:Mapped[list]=mapped_column(JSON,nullable=False,default=list);modalities:Mapped[list]=mapped_column(JSON,nullable=False,default=list);source_count:Mapped[int]=mapped_column(Integer,nullable=False);snapshot_version:Mapped[int]=mapped_column(Integer,nullable=False);snapshot_sha256:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False);created_by_actor_type:Mapped[str]=mapped_column(String(30),nullable=False);created_by_actor_id:Mapped[str]=mapped_column(String(128),nullable=False);trace_id:Mapped[str|None]=mapped_column(String(128));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);locked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class ProviderAgreementVersionModel(Base):
    __tablename__="provider_agreement_versions";__table_args__=(UniqueConstraint("tenant_id","provider_organization_id","agreement_key","version",name="uq_provider_agreement_version"),Index("ix_provider_agreement_effective","tenant_id","provider_organization_id","effective_from","effective_to"))
    agreement_version_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);provider_organization_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);agreement_key:Mapped[str]=mapped_column(String(160),nullable=False);version:Mapped[str]=mapped_column(String(80),nullable=False);title:Mapped[str]=mapped_column(String(300),nullable=False);effective_from:Mapped[date]=mapped_column(Date,nullable=False);effective_to:Mapped[date|None]=mapped_column(Date);status:Mapped[str]=mapped_column(String(30),nullable=False);content_text:Mapped[str]=mapped_column(Text,nullable=False);metadata_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);content_sha256:Mapped[str]=mapped_column(String(64),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class ReimbursementPolicyVersionModel(Base):
    __tablename__="reimbursement_policy_versions";__table_args__=(UniqueConstraint("tenant_id","policy_key","version",name="uq_reimbursement_policy_version"),Index("ix_reimbursement_policy_effective","tenant_id","effective_from","effective_to"))
    policy_version_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);policy_key:Mapped[str]=mapped_column(String(160),nullable=False);version:Mapped[str]=mapped_column(String(80),nullable=False);title:Mapped[str]=mapped_column(String(300),nullable=False);effective_from:Mapped[date]=mapped_column(Date,nullable=False);effective_to:Mapped[date|None]=mapped_column(Date);status:Mapped[str]=mapped_column(String(30),nullable=False);content_text:Mapped[str]=mapped_column(Text,nullable=False);metadata_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);content_sha256:Mapped[str]=mapped_column(String(64),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class DisputeEvidenceComparisonModel(Base):
    __tablename__="dispute_evidence_comparisons";__table_args__=(Index("ix_dispute_comparison","tenant_id","dispute_id","comparison_type"),)
    comparison_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);dispute_id:Mapped[str]=mapped_column(ForeignKey("provider_disputes.dispute_id",ondelete="CASCADE"),nullable=False,index=True);snapshot_id:Mapped[str]=mapped_column(ForeignKey("dispute_evidence_snapshots.snapshot_id",ondelete="CASCADE"),nullable=False);comparison_type:Mapped[str]=mapped_column(String(30),nullable=False);field:Mapped[str]=mapped_column(String(120),nullable=False);recovery_source_ref:Mapped[str|None]=mapped_column(String(256));provider_source_ref:Mapped[str]=mapped_column(String(256),nullable=False);recovery_value_sha256:Mapped[str|None]=mapped_column(String(64));provider_value_sha256:Mapped[str]=mapped_column(String(64),nullable=False);severity:Mapped[str]=mapped_column(String(30),nullable=False);confidence:Mapped[float]=mapped_column(Float,nullable=False);description:Mapped[str]=mapped_column(Text,nullable=False);citations:Mapped[list]=mapped_column(JSON,nullable=False,default=list);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class DisputeRAGRunModel(Base):
    __tablename__="dispute_rag_runs";__table_args__=(Index("ix_dispute_rag_run","tenant_id","dispute_id","created_at"),)
    run_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);dispute_id:Mapped[str]=mapped_column(ForeignKey("provider_disputes.dispute_id",ondelete="CASCADE"),nullable=False,index=True);snapshot_id:Mapped[str]=mapped_column(ForeignKey("dispute_evidence_snapshots.snapshot_id",ondelete="RESTRICT"),nullable=False);query_sha256:Mapped[str]=mapped_column(String(64),nullable=False);strategy:Mapped[str]=mapped_column(String(100),nullable=False);candidate_count:Mapped[int]=mapped_column(Integer,nullable=False);selected_count:Mapped[int]=mapped_column(Integer,nullable=False);citation_coverage:Mapped[float]=mapped_column(Float,nullable=False);contradiction_count:Mapped[int]=mapped_column(Integer,nullable=False);changed_fact_count:Mapped[int]=mapped_column(Integer,nullable=False);pack_sha256:Mapped[str]=mapped_column(String(64),nullable=False);trace_id:Mapped[str|None]=mapped_column(String(128));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class DisputeRAGItemModel(Base):
    __tablename__="dispute_rag_items";__table_args__=(Index("ix_dispute_rag_item","tenant_id","run_id","rank"),)
    item_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);dispute_id:Mapped[str]=mapped_column(ForeignKey("provider_disputes.dispute_id",ondelete="CASCADE"),nullable=False);run_id:Mapped[str]=mapped_column(ForeignKey("dispute_rag_runs.run_id",ondelete="CASCADE"),nullable=False);source_scope:Mapped[str]=mapped_column(String(30),nullable=False);source_id:Mapped[str]=mapped_column(String(256),nullable=False);source_version:Mapped[str]=mapped_column(String(128),nullable=False);modality:Mapped[str]=mapped_column(String(30),nullable=False);rank:Mapped[int]=mapped_column(Integer,nullable=False);score:Mapped[float]=mapped_column(Float,nullable=False);content_sha256:Mapped[str]=mapped_column(String(64),nullable=False);text_preview:Mapped[str]=mapped_column(Text,nullable=False);citation:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);retrieval_sources:Mapped[list]=mapped_column(JSON,nullable=False,default=list);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class DisputeRecommendationRunModel(Base):
    __tablename__="dispute_recommendation_runs";__table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_dispute_recommendation_idem"),Index("ix_dispute_recommendation","tenant_id","dispute_id","created_at"))
    recommendation_run_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);dispute_id:Mapped[str]=mapped_column(ForeignKey("provider_disputes.dispute_id",ondelete="CASCADE"),nullable=False,index=True);snapshot_id:Mapped[str]=mapped_column(ForeignKey("dispute_evidence_snapshots.snapshot_id",ondelete="RESTRICT"),nullable=False);rag_run_id:Mapped[str]=mapped_column(ForeignKey("dispute_rag_runs.run_id",ondelete="RESTRICT"),nullable=False);graph_thread_id:Mapped[str]=mapped_column(String(160),nullable=False);agent_name:Mapped[str]=mapped_column(String(80),nullable=False);prompt_version:Mapped[str]=mapped_column(String(80),nullable=False);recommendation:Mapped[str]=mapped_column(String(50),nullable=False);confidence:Mapped[float]=mapped_column(Float,nullable=False);summary:Mapped[str]=mapped_column(Text,nullable=False);recommendation_sha256:Mapped[str]=mapped_column(String(64),nullable=False);evidence_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list);policy_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list);contradiction_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list);changed_fact_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list);missing_evidence:Mapped[list]=mapped_column(JSON,nullable=False,default=list);requires_human_review:Mapped[bool]=mapped_column(Boolean,nullable=False,default=True);adjudication_authority:Mapped[str]=mapped_column(String(20),nullable=False,default="none");idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False);trace_id:Mapped[str|None]=mapped_column(String(128));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class DisputeReviewCheckpointModel(Base):
    __tablename__="dispute_review_checkpoints";__table_args__=(UniqueConstraint("tenant_id","thread_id","checkpoint_version",name="uq_dispute_checkpoint_version"),Index("ix_dispute_checkpoint","tenant_id","dispute_id","status"))
    checkpoint_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);dispute_id:Mapped[str]=mapped_column(ForeignKey("provider_disputes.dispute_id",ondelete="CASCADE"),nullable=False,index=True);thread_id:Mapped[str]=mapped_column(String(160),nullable=False);checkpoint_version:Mapped[int]=mapped_column(Integer,nullable=False);stage:Mapped[str]=mapped_column(String(80),nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False);state_metadata:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);state_sha256:Mapped[str]=mapped_column(String(64),nullable=False);requires_human_action:Mapped[bool]=mapped_column(Boolean,nullable=False,default=True);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);resumed_by_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"));resumed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class DisputeMissingEvidenceRequestModel(Base):
    __tablename__="dispute_missing_evidence_requests";__table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_dispute_missing_evidence_idem"),Index("ix_dispute_missing_evidence","tenant_id","dispute_id","status"))
    request_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);dispute_id:Mapped[str]=mapped_column(ForeignKey("provider_disputes.dispute_id",ondelete="CASCADE"),nullable=False,index=True);requested_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);document_types:Mapped[list]=mapped_column(JSON,nullable=False,default=list);rationale:Mapped[str]=mapped_column(Text,nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False);idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);satisfied_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class ProviderDisputeResponseModel(Base):
    __tablename__="provider_dispute_responses";__table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_provider_dispute_response_idem"),Index("ix_provider_dispute_response","tenant_id","dispute_id","created_at"))
    response_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);dispute_id:Mapped[str]=mapped_column(ForeignKey("provider_disputes.dispute_id",ondelete="CASCADE"),nullable=False,index=True);request_id:Mapped[str|None]=mapped_column(ForeignKey("dispute_missing_evidence_requests.request_id",ondelete="SET NULL"));provider_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);statement:Mapped[str]=mapped_column(Text,nullable=False);evidence_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list);body_sha256:Mapped[str]=mapped_column(String(64),nullable=False);idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class DisputeEvaluationCaseModel(Base):
    __tablename__="dispute_evaluation_cases";__table_args__=(UniqueConstraint("tenant_id","case_key",name="uq_dispute_eval_case_key"),)
    evaluation_case_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);case_key:Mapped[str]=mapped_column(String(160),nullable=False);scenario:Mapped[str]=mapped_column(String(120),nullable=False);modalities:Mapped[list]=mapped_column(JSON,nullable=False,default=list);expected_changed_facts:Mapped[list]=mapped_column(JSON,nullable=False,default=list);expected_contradictions:Mapped[list]=mapped_column(JSON,nullable=False,default=list);expected_policy_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list);expected_recommendation:Mapped[str]=mapped_column(String(50),nullable=False);requires_human_resolution:Mapped[bool]=mapped_column(Boolean,nullable=False,default=True);dataset_version:Mapped[str]=mapped_column(String(40),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
