from __future__ import annotations
from datetime import datetime
from decimal import Decimal
from sqlalchemy import Boolean,DateTime,ForeignKey,Index,Integer,JSON,Numeric,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base

class ProviderDisputeDecisionPacketModel(Base):
    __tablename__="provider_dispute_decision_packets";__table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_provider_dispute_packet_idem"),UniqueConstraint("tenant_id","dispute_id","packet_version",name="uq_provider_dispute_packet_version"),Index("ix_provider_dispute_packet","tenant_id","dispute_id","created_at"))
    packet_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False,index=True);dispute_id:Mapped[str]=mapped_column(ForeignKey("provider_disputes.dispute_id",ondelete="CASCADE"),nullable=False,index=True);claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False);primary_resolver_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);second_resolver_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"));snapshot_id:Mapped[str]=mapped_column(ForeignKey("dispute_evidence_snapshots.snapshot_id",ondelete="RESTRICT"),nullable=False);snapshot_sha256:Mapped[str]=mapped_column(String(64),nullable=False);recommendation_run_id:Mapped[str|None]=mapped_column(ForeignKey("dispute_recommendation_runs.recommendation_run_id",ondelete="RESTRICT"));outcome:Mapped[str]=mapped_column(String(40),nullable=False);rationale:Mapped[str]=mapped_column(Text,nullable=False);reason_codes:Mapped[list]=mapped_column(JSON,nullable=False,default=list);citation_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list);resolved_comparison_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list);checkpoint_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list);original_target_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);amended_target_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);financial_delta:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);material_target_change:Mapped[bool]=mapped_column(Boolean,nullable=False);recommendation_disagreement:Mapped[bool]=mapped_column(Boolean,nullable=False);recommendation_disagreement_reason:Mapped[str|None]=mapped_column(Text);completeness:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);blocker_codes:Mapped[list]=mapped_column(JSON,nullable=False,default=list);dual_control_required:Mapped[bool]=mapped_column(Boolean,nullable=False);status:Mapped[str]=mapped_column(String(40),nullable=False);packet_version:Mapped[int]=mapped_column(Integer,nullable=False);expected_case_version:Mapped[int]=mapped_column(Integer,nullable=False);locked_payload_sha256:Mapped[str|None]=mapped_column(String(64));final_resolution_id:Mapped[str|None]=mapped_column(String(128));idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False);trace_id:Mapped[str|None]=mapped_column(String(128));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);locked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));closed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class ProviderDisputeSecondReviewModel(Base):
    __tablename__="provider_dispute_second_reviews";__table_args__=(UniqueConstraint("tenant_id","packet_id","reviewer_user_id",name="uq_provider_dispute_second_review"),)
    second_review_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);dispute_id:Mapped[str]=mapped_column(ForeignKey("provider_disputes.dispute_id",ondelete="CASCADE"),nullable=False);packet_id:Mapped[str]=mapped_column(ForeignKey("provider_dispute_decision_packets.packet_id",ondelete="CASCADE"),nullable=False);reviewer_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);action:Mapped[str]=mapped_column(String(20),nullable=False);rationale:Mapped[str]=mapped_column(Text,nullable=False);packet_version:Mapped[int]=mapped_column(Integer,nullable=False);payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RecoveryPositionVersionModel(Base):
    __tablename__="recovery_position_versions";__table_args__=(UniqueConstraint("tenant_id","recovery_case_id","sequence",name="uq_recovery_position_sequence"),)
    position_version_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False,index=True);dispute_id:Mapped[str|None]=mapped_column(ForeignKey("provider_disputes.dispute_id",ondelete="SET NULL"));sequence:Mapped[int]=mapped_column(Integer,nullable=False);target_recovery_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);source_type:Mapped[str]=mapped_column(String(80),nullable=False);source_id:Mapped[str]=mapped_column(String(128),nullable=False);supersedes_position_version_id:Mapped[str|None]=mapped_column(String(128));previous_payload_sha256:Mapped[str|None]=mapped_column(String(64));payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);created_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);effective_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class ProviderDisputeFinalResolutionModel(Base):
    __tablename__="provider_dispute_final_resolutions";__table_args__=(UniqueConstraint("tenant_id","dispute_id",name="uq_provider_dispute_final_once"),UniqueConstraint("tenant_id","idempotency_key",name="uq_provider_dispute_final_idem"))
    resolution_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);dispute_id:Mapped[str]=mapped_column(ForeignKey("provider_disputes.dispute_id",ondelete="RESTRICT"),nullable=False);packet_id:Mapped[str]=mapped_column(ForeignKey("provider_dispute_decision_packets.packet_id",ondelete="RESTRICT"),nullable=False);primary_resolver_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);second_resolver_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"));outcome:Mapped[str]=mapped_column(String(40),nullable=False);original_target_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);amended_target_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);financial_delta:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);snapshot_sha256:Mapped[str]=mapped_column(String(64),nullable=False);packet_locked_sha256:Mapped[str]=mapped_column(String(64),nullable=False);position_version_id:Mapped[str]=mapped_column(ForeignKey("recovery_position_versions.position_version_id",ondelete="RESTRICT"),nullable=False);correspondence_id:Mapped[str|None]=mapped_column(String(128));reversal_referral_id:Mapped[str|None]=mapped_column(String(128));provenance:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False);trace_id:Mapped[str|None]=mapped_column(String(128));resolved_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RecoveryAmendmentReferralModel(Base):
    __tablename__="recovery_amendment_referrals";__table_args__=(UniqueConstraint("tenant_id","resolution_id",name="uq_recovery_amendment_resolution"),)
    reversal_referral_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);dispute_id:Mapped[str]=mapped_column(ForeignKey("provider_disputes.dispute_id",ondelete="RESTRICT"),nullable=False);resolution_id:Mapped[str]=mapped_column(ForeignKey("provider_dispute_final_resolutions.resolution_id",ondelete="RESTRICT"),nullable=False);referral_type:Mapped[str]=mapped_column(String(80),nullable=False);destination:Mapped[str]=mapped_column(String(80),nullable=False);amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);reason_code:Mapped[str]=mapped_column(String(100),nullable=False);status:Mapped[str]=mapped_column(String(40),nullable=False);external_reference:Mapped[str|None]=mapped_column(String(180));verified_by_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"));verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);created_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class ProviderDisputeResolutionAuditEventModel(Base):
    __tablename__="provider_dispute_resolution_audit_events";__table_args__=(UniqueConstraint("tenant_id","dispute_id","sequence",name="uq_provider_dispute_resolution_audit_seq"),UniqueConstraint("tenant_id","idempotency_key",name="uq_provider_dispute_resolution_audit_idem"))
    audit_event_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);dispute_id:Mapped[str]=mapped_column(ForeignKey("provider_disputes.dispute_id",ondelete="CASCADE"),nullable=False);packet_id:Mapped[str|None]=mapped_column(ForeignKey("provider_dispute_decision_packets.packet_id",ondelete="SET NULL"));sequence:Mapped[int]=mapped_column(Integer,nullable=False);event_type:Mapped[str]=mapped_column(String(120),nullable=False);actor_type:Mapped[str]=mapped_column(String(40),nullable=False);actor_id:Mapped[str]=mapped_column(String(128),nullable=False);payload:Mapped[dict]=mapped_column(JSON,nullable=False);previous_event_sha256:Mapped[str|None]=mapped_column(String(64));event_sha256:Mapped[str]=mapped_column(String(64),nullable=False);idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False);trace_id:Mapped[str|None]=mapped_column(String(128));occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
