from __future__ import annotations
from datetime import datetime
from decimal import Decimal
from sqlalchemy import Boolean, DateTime, ForeignKey, Index, Integer, JSON, Numeric, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base

class RecoveryCaseModel(Base):
    __tablename__="recovery_cases"
    __table_args__=(UniqueConstraint("tenant_id","source_proposal_id",name="uq_recovery_source_proposal"),Index("ix_recovery_case_queue","tenant_id","status","priority"),Index("ix_recovery_claim","tenant_id","claim_id"))
    recovery_case_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False);financial_investigation_case_id:Mapped[str]=mapped_column(ForeignKey("financial_investigation_cases.case_id",ondelete="RESTRICT"),nullable=False);source_proposal_id:Mapped[str]=mapped_column(ForeignKey("financial_remediation_proposals.proposal_id",ondelete="RESTRICT"),nullable=False);referral_type:Mapped[str]=mapped_column(String(80),nullable=False);referral_id:Mapped[str]=mapped_column(String(128),nullable=False);recovery_type:Mapped[str]=mapped_column(String(80),nullable=False);provider_organization_id:Mapped[str|None]=mapped_column(String(128));currency:Mapped[str]=mapped_column(String(3),nullable=False);identified_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);target_recovery_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);recovered_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False,default=Decimal("0"));status:Mapped[str]=mapped_column(String(40),nullable=False);priority:Mapped[int]=mapped_column(Integer,nullable=False);assigned_investigator_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="SET NULL"));case_version:Mapped[int]=mapped_column(Integer,nullable=False,default=1);effectiveness_score:Mapped[int]=mapped_column(Integer,nullable=False,default=0);last_verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);closed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));closure_reason_code:Mapped[str|None]=mapped_column(String(100));closure_rationale:Mapped[str|None]=mapped_column(Text)

class RecoveryEvidencePackModel(Base):
    __tablename__="recovery_evidence_packs";__table_args__=(UniqueConstraint("tenant_id","recovery_case_id","pack_version",name="uq_recovery_pack_version"),)
    evidence_pack_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False,index=True);pack_version:Mapped[int]=mapped_column(Integer,nullable=False);evidence_items:Mapped[list]=mapped_column(JSON,nullable=False,default=list);citations:Mapped[list]=mapped_column(JSON,nullable=False,default=list);source_sha256:Mapped[str]=mapped_column(String(64),nullable=False);payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RecoveryLeaseModel(Base):
    __tablename__="recovery_leases"
    recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);investigator_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);lease_token_sha256:Mapped[str]=mapped_column(String(64),nullable=False);lease_version:Mapped[int]=mapped_column(Integer,nullable=False,default=1);acquired_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RecoveryOutcomeModel(Base):
    __tablename__="recovery_outcomes";__table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_outcome_idem"),Index("ix_recovery_outcome_case","tenant_id","recovery_case_id","occurred_at"))
    outcome_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);outcome_type:Mapped[str]=mapped_column(String(80),nullable=False);source_type:Mapped[str]=mapped_column(String(80),nullable=False);source_id:Mapped[str]=mapped_column(String(180),nullable=False);amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);status:Mapped[str]=mapped_column(String(40),nullable=False);external_reference:Mapped[str|None]=mapped_column(String(180));details:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);idempotency_key:Mapped[str]=mapped_column(String(160),nullable=False);recorded_by_actor_type:Mapped[str]=mapped_column(String(50),nullable=False);recorded_by_actor_id:Mapped[str|None]=mapped_column(String(128));occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class ProviderDisputeModel(Base):
    __tablename__="provider_disputes";__table_args__=(UniqueConstraint("tenant_id","external_reference",name="uq_provider_dispute_external"),Index("ix_provider_dispute_queue","tenant_id","status","submitted_at"))
    dispute_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False);provider_organization_id:Mapped[str]=mapped_column(String(128),nullable=False);external_reference:Mapped[str]=mapped_column(String(180),nullable=False);disputed_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);reason_code:Mapped[str]=mapped_column(String(100),nullable=False);statement:Mapped[str]=mapped_column(Text,nullable=False);evidence_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list);evidence_pack_sha256:Mapped[str]=mapped_column(String(64),nullable=False);material:Mapped[bool]=mapped_column(Boolean,nullable=False);status:Mapped[str]=mapped_column(String(40),nullable=False);submitted_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);assigned_resolver_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="SET NULL"));resolution_outcome:Mapped[str|None]=mapped_column(String(80));resolution_rationale:Mapped[str|None]=mapped_column(Text);resolution_amount:Mapped[Decimal|None]=mapped_column(Numeric(14,2));payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);submitted_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);resolved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class RecoveryCorrespondenceModel(Base):
    __tablename__="recovery_correspondence";__table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_correspondence_idem"),)
    correspondence_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);dispute_id:Mapped[str|None]=mapped_column(ForeignKey("provider_disputes.dispute_id",ondelete="SET NULL"));direction:Mapped[str]=mapped_column(String(20),nullable=False);channel:Mapped[str]=mapped_column(String(30),nullable=False);subject:Mapped[str]=mapped_column(String(300),nullable=False);body:Mapped[str]=mapped_column(Text,nullable=False);external_message_id:Mapped[str|None]=mapped_column(String(180));body_sha256:Mapped[str]=mapped_column(String(64),nullable=False);actor_type:Mapped[str]=mapped_column(String(50),nullable=False);actor_id:Mapped[str|None]=mapped_column(String(128));idempotency_key:Mapped[str]=mapped_column(String(160),nullable=False);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RecoveryTaskModel(Base):
    __tablename__="recovery_tasks";__table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_task_idem"),Index("ix_recovery_task_queue","tenant_id","status","due_at"))
    task_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);task_type:Mapped[str]=mapped_column(String(80),nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False);priority:Mapped[int]=mapped_column(Integer,nullable=False);due_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);assigned_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="SET NULL"));idempotency_key:Mapped[str]=mapped_column(String(160),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class RecoveryAuditEventModel(Base):
    __tablename__="recovery_audit_events";__table_args__=(UniqueConstraint("tenant_id","recovery_case_id","sequence",name="uq_recovery_audit_sequence"),UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_audit_idem"))
    audit_event_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False);sequence:Mapped[int]=mapped_column(Integer,nullable=False);event_type:Mapped[str]=mapped_column(String(110),nullable=False);actor_type:Mapped[str]=mapped_column(String(50),nullable=False);actor_id:Mapped[str|None]=mapped_column(String(128));payload:Mapped[dict]=mapped_column(JSON,nullable=False);previous_event_sha256:Mapped[str|None]=mapped_column(String(64));event_sha256:Mapped[str]=mapped_column(String(64),nullable=False);idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RecoveryEvaluationCaseModel(Base):
    __tablename__="recovery_evaluation_cases"
    evaluation_case_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False);scenario_type:Mapped[str]=mapped_column(String(80),nullable=False);input_payload:Mapped[dict]=mapped_column(JSON,nullable=False);expected_controls:Mapped[dict]=mapped_column(JSON,nullable=False);payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
