from __future__ import annotations
from datetime import datetime
from decimal import Decimal
from sqlalchemy import Boolean,DateTime,ForeignKey,Index,Integer,JSON,Numeric,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base

class RecoverySettlementCaseModel(Base):
    __tablename__="recovery_settlement_cases";__table_args__=(UniqueConstraint("tenant_id","recovery_case_id",name="uq_recovery_settlement_case"),Index("ix_recovery_settlement_queue","tenant_id","status","updated_at"))
    settlement_case_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="RESTRICT"),nullable=False);claim_id:Mapped[str]=mapped_column(ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False);provider_organization_id:Mapped[str|None]=mapped_column(String(128));final_resolution_id:Mapped[str]=mapped_column(ForeignKey("provider_dispute_final_resolutions.resolution_id",ondelete="RESTRICT"),nullable=False);position_version_id:Mapped[str]=mapped_column(ForeignKey("recovery_position_versions.position_version_id",ondelete="RESTRICT"),nullable=False);position_payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);target_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);verified_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False,default=Decimal("0"));remaining_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);status:Mapped[str]=mapped_column(String(40),nullable=False);case_version:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);certified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class RecoverySettlementEvidenceModel(Base):
    __tablename__="recovery_settlement_evidence";__table_args__=(UniqueConstraint("tenant_id","external_reference",name="uq_recovery_settlement_external_ref"),UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_settlement_evidence_idem"),Index("ix_recovery_settlement_evidence","tenant_id","settlement_case_id","status"))
    settlement_evidence_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);settlement_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_settlement_cases.settlement_case_id",ondelete="CASCADE"),nullable=False);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="RESTRICT"),nullable=False);evidence_type:Mapped[str]=mapped_column(String(50),nullable=False);amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);installment_sequence:Mapped[int]=mapped_column(Integer,nullable=False);external_reference:Mapped[str]=mapped_column(String(180),nullable=False);bank_reference:Mapped[str|None]=mapped_column(String(180));remittance_reference:Mapped[str|None]=mapped_column(String(180));provider_reference:Mapped[str|None]=mapped_column(String(180));evidence_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list);evidence_payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(40),nullable=False);reference_match:Mapped[bool|None]=mapped_column(Boolean);verification_rationale:Mapped[str|None]=mapped_column(Text);submitted_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);verified_by_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"));idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class RecoveryLedgerCorrelationModel(Base):
    __tablename__="recovery_ledger_correlations";__table_args__=(UniqueConstraint("tenant_id","settlement_evidence_id","journal_id",name="uq_recovery_ledger_correlation"),)
    correlation_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);settlement_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_settlement_cases.settlement_case_id",ondelete="CASCADE"),nullable=False);settlement_evidence_id:Mapped[str]=mapped_column(ForeignKey("recovery_settlement_evidence.settlement_evidence_id",ondelete="RESTRICT"),nullable=False);journal_id:Mapped[str]=mapped_column(ForeignKey("ledger_journals.journal_id",ondelete="RESTRICT"),nullable=False);period_id:Mapped[str]=mapped_column(ForeignKey("accounting_periods.period_id",ondelete="RESTRICT"),nullable=False);amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False);correlation_payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);verified_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RecoverySettlementExceptionModel(Base):
    __tablename__="recovery_settlement_exceptions";__table_args__=(UniqueConstraint("tenant_id","settlement_case_id","exception_code","status",name="uq_recovery_settlement_exception_state"),Index("ix_recovery_settlement_exception_queue","tenant_id","status","created_at"))
    exception_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);settlement_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_settlement_cases.settlement_case_id",ondelete="CASCADE"),nullable=False);exception_code:Mapped[str]=mapped_column(String(80),nullable=False);severity:Mapped[str]=mapped_column(String(20),nullable=False);details:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);status:Mapped[str]=mapped_column(String(30),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);resolved_by_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"));resolved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class RecoveryCompletionCertificateModel(Base):
    __tablename__="recovery_completion_certificates";__table_args__=(UniqueConstraint("tenant_id","settlement_case_id",name="uq_recovery_completion_certificate"),UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_completion_certificate_idem"))
    certificate_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);settlement_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_settlement_cases.settlement_case_id",ondelete="RESTRICT"),nullable=False);recovery_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_cases.recovery_case_id",ondelete="RESTRICT"),nullable=False);accounting_period_id:Mapped[str]=mapped_column(ForeignKey("accounting_periods.period_id",ondelete="RESTRICT"),nullable=False);prepared_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);approved_by_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"));target_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);verified_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);remaining_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);reason_codes:Mapped[list]=mapped_column(JSON,nullable=False,default=list);rationale:Mapped[str]=mapped_column(Text,nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False);payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False);prepared_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);certified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class RecoverySettlementCorrespondenceModel(Base):
    __tablename__="recovery_settlement_correspondence";__table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_settlement_corr_idem"),)
    correspondence_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);settlement_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_settlement_cases.settlement_case_id",ondelete="CASCADE"),nullable=False);direction:Mapped[str]=mapped_column(String(20),nullable=False);channel:Mapped[str]=mapped_column(String(30),nullable=False);subject:Mapped[str]=mapped_column(String(300),nullable=False);body:Mapped[str]=mapped_column(Text,nullable=False);external_message_id:Mapped[str|None]=mapped_column(String(180));body_sha256:Mapped[str]=mapped_column(String(64),nullable=False);actor_id:Mapped[str]=mapped_column(String(128),nullable=False);idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RecoverySettlementTaskModel(Base):
    __tablename__="recovery_settlement_tasks";__table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_settlement_task_idem"),Index("ix_recovery_settlement_task_queue","tenant_id","status","due_at"))
    task_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);settlement_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_settlement_cases.settlement_case_id",ondelete="CASCADE"),nullable=False);task_type:Mapped[str]=mapped_column(String(80),nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False);priority:Mapped[int]=mapped_column(Integer,nullable=False);due_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class RecoverySettlementAuditEventModel(Base):
    __tablename__="recovery_settlement_audit_events";__table_args__=(UniqueConstraint("tenant_id","settlement_case_id","sequence",name="uq_recovery_settlement_audit_seq"),UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_settlement_audit_idem"))
    audit_event_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);settlement_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_settlement_cases.settlement_case_id",ondelete="CASCADE"),nullable=False);sequence:Mapped[int]=mapped_column(Integer,nullable=False);event_type:Mapped[str]=mapped_column(String(120),nullable=False);actor_type:Mapped[str]=mapped_column(String(50),nullable=False);actor_id:Mapped[str|None]=mapped_column(String(128));payload:Mapped[dict]=mapped_column(JSON,nullable=False);previous_event_sha256:Mapped[str|None]=mapped_column(String(64));event_sha256:Mapped[str]=mapped_column(String(64),nullable=False);idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RecoverySettlementEvaluationCaseModel(Base):
    __tablename__="recovery_settlement_evaluation_cases"
    evaluation_case_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False);scenario_type:Mapped[str]=mapped_column(String(80),nullable=False);input_payload:Mapped[dict]=mapped_column(JSON,nullable=False);expected_controls:Mapped[dict]=mapped_column(JSON,nullable=False);payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
