from __future__ import annotations
from datetime import date, datetime
from decimal import Decimal
from sqlalchemy import Date, DateTime, ForeignKey, Index, Integer, JSON, Numeric, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base

class ProviderRecoveryBalanceStatementModel(Base):
    __tablename__="provider_recovery_balance_statements"
    __table_args__=(UniqueConstraint("tenant_id","provider_organization_id","source_watermark_sha256",name="uq_provider_balance_statement_watermark"),UniqueConstraint("tenant_id","provider_organization_id","statement_version",name="uq_provider_balance_statement_version"),Index("ix_provider_balance_statement","tenant_id","provider_organization_id","created_at"))
    statement_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);provider_organization_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);statement_version:Mapped[int]=mapped_column(Integer,nullable=False);as_of_date:Mapped[date]=mapped_column(Date,nullable=False);currency:Mapped[str]=mapped_column(String(3),nullable=False);target_recovery:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);verified_recovery:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);remaining_balance:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);under_recovery_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);over_recovery_amount:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);open_case_count:Mapped[int]=mapped_column(Integer,nullable=False);certified_case_count:Mapped[int]=mapped_column(Integer,nullable=False);aging_summary:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);case_lines:Mapped[list]=mapped_column(JSON,nullable=False,default=list);source_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list);source_watermark_sha256:Mapped[str]=mapped_column(String(64),nullable=False);payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);created_by_actor_type:Mapped[str]=mapped_column(String(60),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RecoverySettlementAnalyticsSnapshotModel(Base):
    __tablename__="recovery_settlement_analytics_snapshots"
    __table_args__=(UniqueConstraint("tenant_id","scope_type","scope_id","source_watermark_sha256",name="uq_recovery_settlement_analytics_watermark"),Index("ix_recovery_settlement_analytics_scope","tenant_id","scope_type","scope_id","created_at"))
    snapshot_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);scope_type:Mapped[str]=mapped_column(String(30),nullable=False);scope_id:Mapped[str]=mapped_column(String(128),nullable=False);metrics:Mapped[dict]=mapped_column(JSON,nullable=False);anomalies:Mapped[list]=mapped_column(JSON,nullable=False,default=list);citations:Mapped[list]=mapped_column(JSON,nullable=False,default=list);source_watermark_sha256:Mapped[str]=mapped_column(String(64),nullable=False);payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);created_by_actor_type:Mapped[str]=mapped_column(String(60),nullable=False,default="deterministic_read_only_intelligence");created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RecoverySettlementExceptionInvestigationModel(Base):
    __tablename__="recovery_settlement_exception_investigations"
    __table_args__=(Index("ix_recovery_settlement_exception_investigation","tenant_id","settlement_case_id","created_at"),)
    investigation_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);settlement_case_id:Mapped[str]=mapped_column(ForeignKey("recovery_settlement_cases.settlement_case_id",ondelete="CASCADE"),nullable=False);exception_code:Mapped[str]=mapped_column(String(100),nullable=False);severity:Mapped[str]=mapped_column(String(20),nullable=False);explanation:Mapped[str]=mapped_column(Text,nullable=False);factors:Mapped[list]=mapped_column(JSON,nullable=False,default=list);citations:Mapped[list]=mapped_column(JSON,nullable=False,default=list);recommendations:Mapped[list]=mapped_column(JSON,nullable=False,default=list);accounting_authority:Mapped[str]=mapped_column(String(20),nullable=False,default="none");fund_movement_authority:Mapped[str]=mapped_column(String(20),nullable=False,default="none");payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RecoveryCloseoutReportModel(Base):
    __tablename__="recovery_closeout_reports"
    __table_args__=(UniqueConstraint("tenant_id","report_scope","scope_id","source_watermark_sha256",name="uq_recovery_closeout_report_watermark"),Index("ix_recovery_closeout_report","tenant_id","report_scope","scope_id","created_at"))
    report_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);report_scope:Mapped[str]=mapped_column(String(30),nullable=False);scope_id:Mapped[str]=mapped_column(String(128),nullable=False);report_version:Mapped[int]=mapped_column(Integer,nullable=False);manifest:Mapped[dict]=mapped_column(JSON,nullable=False);source_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list);source_watermark_sha256:Mapped[str]=mapped_column(String(64),nullable=False);manifest_sha256:Mapped[str]=mapped_column(String(64),nullable=False);created_by_actor_type:Mapped[str]=mapped_column(String(60),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class ProviderBalanceStatementDeliveryModel(Base):
    __tablename__="provider_balance_statement_deliveries"
    __table_args__=(UniqueConstraint("tenant_id","statement_id",name="uq_provider_balance_statement_delivery"),UniqueConstraint("tenant_id","idempotency_key",name="uq_provider_balance_statement_delivery_idem"))
    delivery_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);statement_id:Mapped[str]=mapped_column(ForeignKey("provider_recovery_balance_statements.statement_id",ondelete="RESTRICT"),nullable=False);provider_organization_id:Mapped[str]=mapped_column(String(128),nullable=False);channel:Mapped[str]=mapped_column(String(30),nullable=False,default="portal");released_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);delivery_payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);idempotency_key:Mapped[str]=mapped_column(String(180),nullable=False);delivered_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RecoverySettlementCopilotRunModel(Base):
    __tablename__="recovery_settlement_copilot_runs"
    __table_args__=(Index("ix_recovery_settlement_copilot","tenant_id","requested_by_user_id","created_at"),)
    run_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);requested_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);query_text:Mapped[str]=mapped_column(Text,nullable=False);answer_text:Mapped[str]=mapped_column(Text,nullable=False);citations:Mapped[list]=mapped_column(JSON,nullable=False,default=list);retrieval_strategy:Mapped[str]=mapped_column(String(120),nullable=False);source_watermark_sha256:Mapped[str]=mapped_column(String(64),nullable=False);accounting_authority:Mapped[str]=mapped_column(String(20),nullable=False,default="none");fund_movement_authority:Mapped[str]=mapped_column(String(20),nullable=False,default="none");payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
