from __future__ import annotations
from datetime import datetime
from sqlalchemy import Boolean, DateTime, ForeignKey, Index, Integer, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base

class RegulatoryRemediationPlanModel(Base):
    __tablename__="regulatory_remediation_plans"
    __table_args__=(UniqueConstraint("tenant_id","finding_id","plan_version",name="uq_reg_rem_plan_version"),Index("ix_reg_rem_plan_status","tenant_id","status","due_at"),)
    plan_id:Mapped[str]=mapped_column(String(128),primary_key=True)
    tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True)
    examination_case_id:Mapped[str]=mapped_column(ForeignKey("regulatory_examination_cases.examination_case_id",ondelete="CASCADE"),nullable=False)
    finding_id:Mapped[str]=mapped_column(ForeignKey("regulatory_examination_findings.finding_id",ondelete="RESTRICT"),nullable=False)
    finding_code:Mapped[str]=mapped_column(String(120),nullable=False)
    plan_version:Mapped[int]=mapped_column(Integer,nullable=False)
    status:Mapped[str]=mapped_column(String(40),nullable=False,default="draft")
    root_cause:Mapped[str]=mapped_column(Text,nullable=False)
    corrective_action_summary:Mapped[str]=mapped_column(Text,nullable=False)
    preventive_action_summary:Mapped[str]=mapped_column(Text,nullable=False)
    control_redesign_proposal:Mapped[str]=mapped_column(Text,nullable=False)
    financial_impact_analysis:Mapped[str]=mapped_column(Text,nullable=False)
    accounting_impact_analysis:Mapped[str]=mapped_column(Text,nullable=False)
    risk_score:Mapped[int]=mapped_column(Integer,nullable=False)
    risk_level:Mapped[str]=mapped_column(String(20),nullable=False)
    ai_assisted:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False)
    ai_recommendation:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict)
    ai_authority:Mapped[str]=mapped_column(String(20),nullable=False,default="none")
    owner_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False)
    prepared_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False)
    approved_by_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"))
    approval_rationale:Mapped[str|None]=mapped_column(Text)
    previous_plan_sha256:Mapped[str|None]=mapped_column(String(64))
    plan_sha256:Mapped[str]=mapped_column(String(64),nullable=False)
    due_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
    created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
    approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
    updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RegulatoryRemediationTaskModel(Base):
    __tablename__="regulatory_remediation_tasks"
    __table_args__=(UniqueConstraint("tenant_id","plan_id","task_key",name="uq_reg_rem_task_key"),)
    task_id:Mapped[str]=mapped_column(String(128),primary_key=True)
    tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True)
    plan_id:Mapped[str]=mapped_column(ForeignKey("regulatory_remediation_plans.plan_id",ondelete="CASCADE"),nullable=False)
    task_key:Mapped[str]=mapped_column(String(120),nullable=False)
    task_type:Mapped[str]=mapped_column(String(50),nullable=False)
    description:Mapped[str]=mapped_column(Text,nullable=False)
    owner_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False)
    dependency_keys:Mapped[list]=mapped_column(JSON,nullable=False,default=list)
    status:Mapped[str]=mapped_column(String(30),nullable=False,default="open")
    due_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
    evidence_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list)
    created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
    completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class RegulatoryRemediationCheckpointModel(Base):
    __tablename__="regulatory_remediation_checkpoints"
    __table_args__=(UniqueConstraint("tenant_id","plan_id","checkpoint_key",name="uq_reg_rem_checkpoint_key"),)
    checkpoint_id:Mapped[str]=mapped_column(String(128),primary_key=True)
    tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True)
    plan_id:Mapped[str]=mapped_column(ForeignKey("regulatory_remediation_plans.plan_id",ondelete="CASCADE"),nullable=False)
    checkpoint_key:Mapped[str]=mapped_column(String(120),nullable=False)
    checkpoint_type:Mapped[str]=mapped_column(String(50),nullable=False)
    evidence_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list)
    source_watermark_sha256:Mapped[str]=mapped_column(String(64),nullable=False)
    payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False)
    created_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False)
    locked_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RegulatoryControlRetestModel(Base):
    __tablename__="regulatory_control_retests"
    __table_args__=(UniqueConstraint("tenant_id","plan_id","control_key","retest_sequence",name="uq_reg_rem_retest_seq"),)
    retest_id:Mapped[str]=mapped_column(String(128),primary_key=True)
    tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True)
    plan_id:Mapped[str]=mapped_column(ForeignKey("regulatory_remediation_plans.plan_id",ondelete="CASCADE"),nullable=False)
    control_key:Mapped[str]=mapped_column(String(120),nullable=False)
    retest_sequence:Mapped[int]=mapped_column(Integer,nullable=False)
    methodology:Mapped[str]=mapped_column(Text,nullable=False)
    expected_result:Mapped[str]=mapped_column(Text,nullable=False)
    observed_result:Mapped[str]=mapped_column(Text,nullable=False)
    outcome:Mapped[str]=mapped_column(String(20),nullable=False)
    evidence_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list)
    retested_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False)
    payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False)
    retested_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RegulatoryRemediationWaiverModel(Base):
    __tablename__="regulatory_remediation_waivers"
    __table_args__=(UniqueConstraint("tenant_id","plan_id","waiver_key",name="uq_reg_rem_waiver_key"),)
    waiver_id:Mapped[str]=mapped_column(String(128),primary_key=True)
    tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True)
    plan_id:Mapped[str]=mapped_column(ForeignKey("regulatory_remediation_plans.plan_id",ondelete="CASCADE"),nullable=False)
    waiver_key:Mapped[str]=mapped_column(String(120),nullable=False)
    waiver_type:Mapped[str]=mapped_column(String(40),nullable=False)
    rationale:Mapped[str]=mapped_column(Text,nullable=False)
    risk_acceptance:Mapped[str]=mapped_column(Text,nullable=False)
    status:Mapped[str]=mapped_column(String(30),nullable=False,default="pending")
    requested_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False)
    decided_by_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"))
    decision_rationale:Mapped[str|None]=mapped_column(Text)
    expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
    created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
    decided_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class RegulatoryRemediationFollowupModel(Base):
    __tablename__="regulatory_remediation_followups"
    __table_args__=(UniqueConstraint("tenant_id","plan_id","response_version",name="uq_reg_rem_followup_version"),)
    followup_id:Mapped[str]=mapped_column(String(128),primary_key=True)
    tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True)
    plan_id:Mapped[str]=mapped_column(ForeignKey("regulatory_remediation_plans.plan_id",ondelete="CASCADE"),nullable=False)
    response_version:Mapped[int]=mapped_column(Integer,nullable=False)
    status:Mapped[str]=mapped_column(String(30),nullable=False,default="draft")
    response_text:Mapped[str]=mapped_column(Text,nullable=False)
    cited_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list)
    prepared_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False)
    approved_by_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"))
    previous_response_sha256:Mapped[str|None]=mapped_column(String(64))
    response_sha256:Mapped[str]=mapped_column(String(64),nullable=False)
    approval_rationale:Mapped[str|None]=mapped_column(Text)
    created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
    approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class RegulatoryRemediationClosureCertificationModel(Base):
    __tablename__="regulatory_remediation_closure_certifications"
    __table_args__=(UniqueConstraint("tenant_id","plan_id","certification_sequence",name="uq_reg_rem_close_cert_seq"),)
    certification_id:Mapped[str]=mapped_column(String(128),primary_key=True)
    tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True)
    plan_id:Mapped[str]=mapped_column(ForeignKey("regulatory_remediation_plans.plan_id",ondelete="CASCADE"),nullable=False)
    certification_sequence:Mapped[int]=mapped_column(Integer,nullable=False)
    conclusion:Mapped[str]=mapped_column(String(30),nullable=False)
    closure_rationale:Mapped[str]=mapped_column(Text,nullable=False)
    certified_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False)
    source_watermark_sha256:Mapped[str]=mapped_column(String(64),nullable=False)
    previous_certification_sha256:Mapped[str|None]=mapped_column(String(64))
    certification_sha256:Mapped[str]=mapped_column(String(64),nullable=False)
    certified_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RegulatoryRemediationAuditEventModel(Base):
    __tablename__="regulatory_remediation_audit_events"
    __table_args__=(UniqueConstraint("tenant_id","plan_id","sequence",name="uq_reg_rem_audit_seq"),)
    audit_event_id:Mapped[str]=mapped_column(String(128),primary_key=True)
    tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True)
    plan_id:Mapped[str]=mapped_column(ForeignKey("regulatory_remediation_plans.plan_id",ondelete="CASCADE"),nullable=False)
    sequence:Mapped[int]=mapped_column(Integer,nullable=False)
    event_type:Mapped[str]=mapped_column(String(100),nullable=False)
    actor_type:Mapped[str]=mapped_column(String(60),nullable=False)
    actor_id:Mapped[str]=mapped_column(String(128),nullable=False)
    details:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict)
    previous_event_sha256:Mapped[str|None]=mapped_column(String(64))
    event_sha256:Mapped[str]=mapped_column(String(64),nullable=False)
    occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
