from __future__ import annotations
from datetime import datetime
from sqlalchemy import Boolean, DateTime, ForeignKey, Index, Integer, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base

class EnterpriseControlModel(Base):
    __tablename__="enterprise_control_library"
    __table_args__=(UniqueConstraint("tenant_id","control_key","control_version",name="uq_enterprise_control_version"),)
    control_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True)
    control_key:Mapped[str]=mapped_column(String(120),nullable=False);control_version:Mapped[int]=mapped_column(Integer,nullable=False);name:Mapped[str]=mapped_column(String(240),nullable=False);description:Mapped[str]=mapped_column(Text,nullable=False);control_family:Mapped[str]=mapped_column(String(120),nullable=False);owner_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False,default="active");created_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RegulatoryControlFindingMapModel(Base):
    __tablename__="regulatory_control_finding_maps"
    __table_args__=(UniqueConstraint("tenant_id","control_id","plan_id",name="uq_reg_port_control_plan"),)
    mapping_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);control_id:Mapped[str]=mapped_column(ForeignKey("enterprise_control_library.control_id",ondelete="RESTRICT"),nullable=False);plan_id:Mapped[str]=mapped_column(ForeignKey("regulatory_remediation_plans.plan_id",ondelete="RESTRICT"),nullable=False);mapping_rationale:Mapped[str]=mapped_column(Text,nullable=False);mapped_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);mapped_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RegulatoryPortfolioSnapshotModel(Base):
    __tablename__="regulatory_portfolio_snapshots"
    __table_args__=(UniqueConstraint("tenant_id","period_key","snapshot_version",name="uq_reg_port_snapshot_version"),Index("ix_reg_port_snapshot_period","tenant_id","period_key","created_at"),)
    snapshot_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);period_key:Mapped[str]=mapped_column(String(120),nullable=False);snapshot_version:Mapped[int]=mapped_column(Integer,nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False,default="prepared");plan_count:Mapped[int]=mapped_column(Integer,nullable=False);open_plan_count:Mapped[int]=mapped_column(Integer,nullable=False);overdue_task_count:Mapped[int]=mapped_column(Integer,nullable=False);repeat_finding_count:Mapped[int]=mapped_column(Integer,nullable=False);recurring_root_cause_count:Mapped[int]=mapped_column(Integer,nullable=False);systemic_cluster_count:Mapped[int]=mapped_column(Integer,nullable=False);average_risk_score:Mapped[int]=mapped_column(Integer,nullable=False);portfolio_risk_score:Mapped[int]=mapped_column(Integer,nullable=False);control_effectiveness_pct:Mapped[int]=mapped_column(Integer,nullable=False);critical_path:Mapped[list]=mapped_column(JSON,nullable=False,default=list);portfolio_metrics:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);source_watermark_sha256:Mapped[str]=mapped_column(String(64),nullable=False);prepared_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RegulatorySystemicRiskClusterModel(Base):
    __tablename__="regulatory_systemic_risk_clusters"
    __table_args__=(UniqueConstraint("tenant_id","snapshot_id","cluster_key",name="uq_reg_port_cluster_key"),)
    cluster_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);snapshot_id:Mapped[str]=mapped_column(ForeignKey("regulatory_portfolio_snapshots.snapshot_id",ondelete="CASCADE"),nullable=False);cluster_key:Mapped[str]=mapped_column(String(200),nullable=False);cluster_type:Mapped[str]=mapped_column(String(50),nullable=False);severity:Mapped[str]=mapped_column(String(20),nullable=False);member_plan_ids:Mapped[list]=mapped_column(JSON,nullable=False,default=list);member_count:Mapped[int]=mapped_column(Integer,nullable=False);recommendation:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RegulatoryControlTestingCampaignModel(Base):
    __tablename__="regulatory_control_testing_campaigns"
    __table_args__=(UniqueConstraint("tenant_id","snapshot_id","campaign_key",name="uq_reg_port_campaign_key"),)
    campaign_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);snapshot_id:Mapped[str]=mapped_column(ForeignKey("regulatory_portfolio_snapshots.snapshot_id",ondelete="RESTRICT"),nullable=False);campaign_key:Mapped[str]=mapped_column(String(120),nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False,default="open");methodology:Mapped[str]=mapped_column(Text,nullable=False);control_ids:Mapped[list]=mapped_column(JSON,nullable=False,default=list);prepared_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);due_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class RegulatoryControlTestingResultModel(Base):
    __tablename__="regulatory_control_testing_results"
    __table_args__=(UniqueConstraint("tenant_id","campaign_id","control_id",name="uq_reg_port_test_control"),)
    result_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);campaign_id:Mapped[str]=mapped_column(ForeignKey("regulatory_control_testing_campaigns.campaign_id",ondelete="CASCADE"),nullable=False);control_id:Mapped[str]=mapped_column(ForeignKey("enterprise_control_library.control_id",ondelete="RESTRICT"),nullable=False);outcome:Mapped[str]=mapped_column(String(20),nullable=False);observations:Mapped[str]=mapped_column(Text,nullable=False);evidence_refs:Mapped[list]=mapped_column(JSON,nullable=False,default=list);tested_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);payload_sha256:Mapped[str]=mapped_column(String(64),nullable=False);tested_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RegulatoryRiskAcceptanceModel(Base):
    __tablename__="regulatory_portfolio_risk_acceptances"
    __table_args__=(UniqueConstraint("tenant_id","snapshot_id","risk_key",name="uq_reg_port_risk_key"),)
    acceptance_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);snapshot_id:Mapped[str]=mapped_column(ForeignKey("regulatory_portfolio_snapshots.snapshot_id",ondelete="CASCADE"),nullable=False);risk_key:Mapped[str]=mapped_column(String(200),nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False,default="pending");rationale:Mapped[str]=mapped_column(Text,nullable=False);requested_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);decided_by_user_id:Mapped[str|None]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"));decision_rationale:Mapped[str|None]=mapped_column(Text);expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);decided_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class RegulatoryManagementAttestationModel(Base):
    __tablename__="regulatory_management_attestations"
    __table_args__=(UniqueConstraint("tenant_id","snapshot_id",name="uq_reg_port_management_attestation"),)
    attestation_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);snapshot_id:Mapped[str]=mapped_column(ForeignKey("regulatory_portfolio_snapshots.snapshot_id",ondelete="CASCADE"),nullable=False);conclusion:Mapped[str]=mapped_column(String(30),nullable=False);rationale:Mapped[str]=mapped_column(Text,nullable=False);attested_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);source_watermark_sha256:Mapped[str]=mapped_column(String(64),nullable=False);attestation_sha256:Mapped[str]=mapped_column(String(64),nullable=False);attested_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RegulatoryPortfolioCertificationModel(Base):
    __tablename__="regulatory_portfolio_certifications"
    __table_args__=(UniqueConstraint("tenant_id","snapshot_id","certification_sequence",name="uq_reg_port_cert_seq"),)
    certification_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);snapshot_id:Mapped[str]=mapped_column(ForeignKey("regulatory_portfolio_snapshots.snapshot_id",ondelete="CASCADE"),nullable=False);certification_sequence:Mapped[int]=mapped_column(Integer,nullable=False);conclusion:Mapped[str]=mapped_column(String(30),nullable=False);rationale:Mapped[str]=mapped_column(Text,nullable=False);certified_by_user_id:Mapped[str]=mapped_column(ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False);source_watermark_sha256:Mapped[str]=mapped_column(String(64),nullable=False);previous_certification_sha256:Mapped[str|None]=mapped_column(String(64));certification_sha256:Mapped[str]=mapped_column(String(64),nullable=False);certified_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class RegulatoryPortfolioAuditEventModel(Base):
    __tablename__="regulatory_portfolio_audit_events"
    __table_args__=(UniqueConstraint("tenant_id","snapshot_id","sequence",name="uq_reg_port_audit_seq"),)
    audit_event_id:Mapped[str]=mapped_column(String(128),primary_key=True);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True);snapshot_id:Mapped[str]=mapped_column(ForeignKey("regulatory_portfolio_snapshots.snapshot_id",ondelete="CASCADE"),nullable=False);sequence:Mapped[int]=mapped_column(Integer,nullable=False);event_type:Mapped[str]=mapped_column(String(100),nullable=False);actor_type:Mapped[str]=mapped_column(String(60),nullable=False);actor_id:Mapped[str]=mapped_column(String(128),nullable=False);details:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);previous_event_sha256:Mapped[str|None]=mapped_column(String(64));event_sha256:Mapped[str]=mapped_column(String(64),nullable=False);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
