"use client";
import { useEffect,useState } from "react";
import { AlertTriangle, FileSearch2 } from "lucide-react";
import { portalApi } from "@/lib/api";
import type { ProviderDisputeListItem, ProviderDisputeWorkbench } from "@/lib/portal-operations-schemas";
const message=(e:unknown)=>e instanceof Error?e.message:String(e);
export function ProviderDisputeCenter(){
 const [items,setItems]=useState<ProviderDisputeListItem[]|null>(null),[wb,setWb]=useState<ProviderDisputeWorkbench|null>(null),[statement,setStatement]=useState(""),[error,setError]=useState("");
 useEffect(()=>{portalApi.providerDisputes().then(x=>{setItems(x);setError("")}).catch(e=>{setItems([]);setError(message(e))})},[]);
 const open=async(x:ProviderDisputeListItem)=>{try{setWb(await portalApi.providerDisputeWorkbench(x.recovery_case_id,x.dispute_id));setError("")}catch(e){setError(message(e))}};
 const respond=async()=>{if(!wb||!statement.trim())return;const req=wb.missing_evidence_requests.find(x=>x.status==="open");if(!req){setError("No open evidence request is available for this dispute.");return}try{await portalApi.respondProviderDispute(wb.recovery_case_id,wb.dispute_id,{request_id:req.request_id,statement,evidence_refs:[]});setStatement("");setWb(await portalApi.providerDisputeWorkbench(wb.recovery_case_id,wb.dispute_id));setError("")}catch(e){setError(message(e))}};
 return <section className="mt-6 card p-5"><div className="flex gap-2 items-center"><FileSearch2 className="h-5 w-5 text-teal-700"/><h2 className="text-xl font-semibold">Provider dispute evidence requests</h2></div><p className="text-sm text-slate-500 mt-1">Submit supplemental responses for independent human recovery-dispute review.</p>{error&&<div role="alert" className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700"><AlertTriangle className="inline h-4 w-4 mr-2"/>{error}</div>}
  {items===null?<PortalState text="Loading provider disputes…"/>:items.length===0?<PortalState text="No provider dispute evidence requests are currently open."/>:<div className="grid md:grid-cols-[320px_1fr] gap-4 mt-4"><div>{items.map(x=><button key={x.dispute_id} className="w-full text-left border border-slate-200 rounded-xl p-3 mb-2 hover:border-teal-500" onClick={()=>void open(x)}><b>{x.external_reference}</b><div className="text-xs text-slate-500">{x.status} · {x.disputed_amount} {x.currency}</div></button>)}</div><div>{wb?<><div className="text-sm">{wb.notice}</div>{wb.missing_evidence_requests.length?wb.missing_evidence_requests.map(x=><div key={x.request_id} className="mt-3 p-3 border border-slate-200 rounded-xl"><b>Requested: {x.document_types.join(", ")}</b><div className="text-sm text-slate-500">{x.rationale}</div><div className="text-xs mt-1">{x.status}</div></div>):<PortalState text="No additional evidence is currently requested for this dispute."/>}<label className="block mt-3"><span className="text-sm font-semibold">Provider response</span><textarea className="input mt-2 min-h-28" value={statement} onChange={e=>setStatement(e.target.value)} placeholder="Response for the independent human reviewer"/></label><button className="btn btn-primary mt-2" disabled={!statement.trim()} onClick={()=>void respond()}>Submit response</button></>:<PortalState text="Select a dispute to view its evidence requests and response history."/>}</div></div>}
 </section>;
}
function PortalState({text}:{text:string}){return <div className="mt-4 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4 text-sm text-slate-500">{text}</div>}
