"use client";
import { useEffect,useState } from "react";
import { AlertTriangle } from "lucide-react";
import { portalApi } from "@/lib/api";
import type { SettlementCase, SettlementWorkbench } from "@/lib/portal-operations-schemas";
export function RecoverySettlementCenter(){
 const [items,setItems]=useState<SettlementCase[]|null>(null),[wb,setWb]=useState<SettlementWorkbench|null>(null),[amount,setAmount]=useState(""),[reference,setReference]=useState(""),[error,setError]=useState("");
 useEffect(()=>{portalApi.recoverySettlements().then(x=>{setItems(x);setError("")}).catch(e=>{setItems([]);setError(e instanceof Error?e.message:"Recovery settlements unavailable")})},[]);
 const open=async(x:SettlementCase)=>{try{setWb(await portalApi.recoverySettlement(x.settlement_case_id));setError("")}catch(e){setError(e instanceof Error?e.message:"Settlement details unavailable")}};
 const submit=async()=>{if(!wb||!amount||!reference)return;try{await portalApi.submitRecoverySettlementEvidence(wb.case.settlement_case_id,{evidence_type:"bank_repayment",amount,currency:wb.case.currency,installment_sequence:wb.evidence.length+1,external_reference:reference,bank_reference:reference,remittance_reference:null,provider_reference:wb.case.provider_organization_id,evidence_refs:[],occurred_at:null});setAmount("");setReference("");setWb(await portalApi.recoverySettlement(wb.case.settlement_case_id));setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to submit repayment evidence")}};
 return <section className="mt-6 card p-5"><h2 className="text-xl font-semibold">Recovery repayment evidence</h2><p className="text-sm text-slate-500 mt-1">Submit external repayment/remittance evidence for human finance verification. This portal never initiates collection or a bank transaction.</p>{error&&<div role="alert" className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700"><AlertTriangle className="inline h-4 w-4 mr-2"/>{error}</div>}{items===null?<State text="Loading recovery settlement cases…"/>:items.length===0?<State text="No recovery settlement evidence requests are available."/>:<div className="grid md:grid-cols-[320px_1fr] gap-4 mt-4"><div>{items.map(x=><button key={x.settlement_case_id} className="w-full text-left border border-slate-200 rounded-xl p-3 mb-2 hover:border-teal-500" onClick={()=>void open(x)}><b>{x.status}</b><div className="text-xs text-slate-500">target {x.target_amount} · remaining {x.remaining_amount} {x.currency}</div></button>)}</div><div>{wb?<><div className="text-sm">{wb.notice}</div><div className="mt-3 text-sm">Verified {wb.case.verified_amount} / {wb.case.target_amount} {wb.case.currency}</div><label className="block mt-3"><span className="text-sm font-semibold">Repayment amount</span><input inputMode="decimal" className="input mt-2" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/></label><label className="block mt-2"><span className="text-sm font-semibold">Bank/external reference</span><input className="input mt-2" value={reference} onChange={e=>setReference(e.target.value)} placeholder="External reference"/></label><button className="btn btn-primary mt-3" disabled={!amount||!reference} onClick={()=>void submit()}>Submit repayment evidence</button></>:<State text="Select a settlement case to submit external repayment evidence."/>}</div></div>}</section>
}
function State({text}:{text:string}){return <div className="mt-4 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4 text-sm text-slate-500">{text}</div>}
