"use client";
import { FormEvent, useState } from "react";
import { BadgeDollarSign, LockKeyhole, ShieldCheck, TriangleAlert } from "lucide-react";
import { reviewerApi } from "@/lib/api";
import { useEventStream } from "@/lib/hooks/use-event-stream";
import type { FinancialHandoff } from "@/lib/schemas";

export default function FinancialOperationsPage(){
  const [claimId,setClaimId]=useState("");const [data,setData]=useState<FinancialHandoff|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [rationale,setRationale]=useState("Independent human finance approver confirms the immutable controlling human decision and financial reconciliation.");const [payee,setPayee]=useState("provider:org-a");
  const load=async(e?:FormEvent)=>{e?.preventDefault();if(!claimId)return;setBusy(true);setError(null);try{setData(await reviewerApi.financialHandoff(claimId))}catch(x){setError(x instanceof Error?x.message:"Financial handoff unavailable")}finally{setBusy(false)}};
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError(null);try{await fn();await load()}catch(x){setError(x instanceof Error?x.message:"Financial action failed")}finally{setBusy(false)}};
  const {state}=useEventStream(claimId?`/api/reviewer/claims/${encodeURIComponent(claimId)}/events`:null,()=>{if(data)void load()});const p=data?.packet;const intent=data?.payment_intents.at(-1);
  return <div className="space-y-5">
    <section className="card p-6 border-emerald-400/20"><div className="flex justify-between gap-4"><div><div className="panel-title">human-authorized financial handoff · SSE {state}</div><h1 className="text-2xl font-bold mt-1">Financial Operations & Reconciliation</h1><p className="text-sm text-slate-400 mt-2 max-w-4xl">Transforms the latest controlling <b>human</b> claim decision into immutable remittance artifacts and a separately human-authorized financial instruction. AI, agents, MCP tools and workers cannot authorize or execute fund movement.</p></div><BadgeDollarSign className="h-9 w-9 text-emerald-300"/></div></section>
    <form onSubmit={load} className="card p-4 flex gap-3"><input className="input flex-1" value={claimId} onChange={e=>setClaimId(e.target.value)} placeholder="Claim ID"/><button className="btn btn-primary" disabled={busy}>Open financial record</button></form>
    {error&&<div className="rounded-xl border border-rose-500/30 bg-rose-950/20 p-3 text-sm text-rose-200"><TriangleAlert className="inline h-4 w-4 mr-2"/>{error}</div>}
    {data&&<>
      <section className="grid md:grid-cols-4 gap-3"><Kpi label="Packet" value={p?.status||"not prepared"}/><Kpi label="Approved" value={p?`${p.approved_amount} ${p.currency}`:"—"}/><Kpi label="Member responsibility" value={p?`${p.member_responsibility} ${p.currency}`:"—"}/><Kpi label="Payment" value={intent?.status||"none"}/></section>
      <section className="grid xl:grid-cols-2 gap-5"><div className="card p-5"><div className="panel-title">Immutable financial authorization packet</div>{!p?<button className="btn btn-primary mt-4" disabled={busy} onClick={()=>void act(()=>reviewerApi.prepareFinancialPacket(claimId))}>Prepare from controlling decision</button>:<div className="space-y-3 mt-4 text-sm"><div>Decision: <b>{p.controlling_decision}</b></div><div className="mono text-[10px] break-all text-slate-500">decision {p.decision_history_sha256}</div><div className="mono text-[10px] break-all text-slate-500">evidence {p.evidence_snapshot_sha256}</div><div className="flex gap-2 flex-wrap">{p.status==="draft"&&<button className="btn btn-primary" disabled={busy} onClick={()=>void act(()=>reviewerApi.lockFinancialPacket(claimId,p.packet_id,p.packet_version))}><LockKeyhole className="h-4 w-4"/>Lock packet</button>}{["pending_authorization","held"].includes(p.status)&&<><input className="input flex-1 min-w-[260px]" value={rationale} onChange={e=>setRationale(e.target.value)}/><button className="btn btn-primary" disabled={busy} onClick={()=>void act(()=>reviewerApi.authorizeFinancialPacket(claimId,p.packet_id,rationale))}>Human finance authorize</button></>}{p.status==="authorized"&&!intent&&<><input className="input" value={payee} onChange={e=>setPayee(e.target.value)}/><button className="btn btn-primary" disabled={busy} onClick={()=>void act(()=>reviewerApi.stagePaymentIntent(claimId,p.packet_id,payee))}>Stage payment intent</button></>}</div></div>}</div>
      <div className="card p-5"><div className="panel-title">Remittance & responsibility</div><div className="mt-3 space-y-2">{data.remittance_artifacts.map((a)=><details key={a.artifact_id} className="rounded-xl border border-[#1f3852] p-3"><summary className="cursor-pointer text-sm font-semibold">{a.artifact_type} · {a.format_version}</summary><pre className="text-[10px] mt-2 overflow-auto whitespace-pre-wrap text-slate-400">{JSON.stringify(a.content,null,2)}</pre></details>)}</div></div></section>
      {intent&&<section className="card p-5"><div className="panel-title">Authorized instruction & external status</div><div className="flex justify-between gap-3 mt-3"><div className="text-sm"><b>{intent.payment_intent_id}</b><div className="text-slate-500">{intent.amount} {intent.currency} · {intent.status}</div></div>{intent.status==="ready_for_handoff"&&<button className="btn btn-primary" disabled={busy} onClick={()=>void act(()=>reviewerApi.handoffPaymentIntent(claimId,intent.payment_intent_id))}>Idempotent handoff</button>}</div></section>}
      <section className="grid xl:grid-cols-2 gap-5"><div className="card p-5"><div className="panel-title">Reconciliation exceptions</div><div className="mt-3 space-y-2 text-sm">{data.exceptions.length?data.exceptions.map((x)=><div key={x.exception_id} className="rounded-xl border border-amber-500/20 p-3"><b>{x.exception_type}</b><div className="text-xs text-slate-500 mt-1">{x.status}</div></div>):<p className="text-slate-500">No open reconciliation exceptions.</p>}</div></div><div className="card p-5"><div className="panel-title">Operational tasks & SLA</div><div className="mt-3 space-y-2 text-sm">{data.tasks.map((x)=><div key={x.task_id} className="flex justify-between rounded-xl border border-[#1f3852] p-3"><span>{x.task_type}</span><span className="text-slate-500">{x.status}</span></div>)}</div></div></section>
      <section className="card p-5 border-emerald-500/20"><div className="flex gap-2 items-center"><ShieldCheck className="text-emerald-300"/><div className="panel-title">Financial authority boundary</div></div><p className="text-sm text-slate-300 mt-3">LLM authorize funds: <b>false</b> · LangGraph: <b>false</b> · RAG: <b>false</b> · MCP: <b>false</b> · worker: <b>false</b> · adapter: <b>false</b>. Separate human finance approver required: <b className="text-emerald-300">true</b>.</p></section>
    </>}
  </div>
}
function Kpi({label,value}:{label:string;value:string}){return <div className="card p-4"><div className="text-[11px] uppercase tracking-wider text-slate-500">{label}</div><div className="font-bold mt-2 truncate">{value}</div></div>}
