"use client";
import { useEffect,useState } from "react";
import { AlertTriangle,FileSearch2,LockKeyhole,ShieldCheck } from "lucide-react";
import { reviewerApi } from "@/lib/api";
import type { FinancialInvestigationQueueItem, FinancialInvestigationWorkbench } from "@/lib/schemas";

export default function FinancialInvestigationsPage(){
  const [queue,setQueue]=useState<FinancialInvestigationQueueItem[]>([]);const [caseId,setCaseId]=useState("");const [wb,setWb]=useState<FinancialInvestigationWorkbench|null>(null);const [lease,setLease]=useState("");const [rootCause,setRootCause]=useState("reconciliation_mismatch");const [rationale,setRationale]=useState("Human investigation reviewed the immutable cited financial evidence and determined the root cause using governed source records.");const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
  const loadQueue=async()=>{try{setQueue(await reviewerApi.financialInvestigationQueue())}catch(e){setError(e instanceof Error?e.message:"Queue unavailable")}};
  const load=async(id=caseId)=>{if(!id)return;try{const x=await reviewerApi.financialInvestigationWorkbench(id);setWb(x);setCaseId(id)}catch(e){setError(e instanceof Error?e.message:"Case unavailable")}};
  useEffect(()=>{void loadQueue();const es=new EventSource("/api/reviewer/queue/events");es.onmessage=()=>void loadQueue();const refresh=()=>{void loadQueue();if(caseId)void load(caseId)};["financial_investigation.case.created","financial_investigation.lease.acquired","financial_investigation.root_cause.classified","financial_investigation.remediation.proposed","financial_investigation.remediation.second_approved","financial_investigation.remediation.referred","financial_investigation.case.closed"].forEach(t=>es.addEventListener(t,refresh));return()=>es.close()},[caseId]);
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError(null);try{await fn();await load();await loadQueue()}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}};
  const acquire=()=>act(async()=>{const r=await reviewerApi.acquireFinancialInvestigationLease(caseId,wb.case.case_version);setLease(r.lease_token)});
  return <div className="space-y-5">
    <section className="card p-6 border-amber-400/20"><div className="flex justify-between gap-4"><div><div className="panel-title">human-controlled payment integrity</div><h1 className="text-2xl font-bold mt-1">Payment Integrity Investigations</h1><p className="text-sm text-slate-400 mt-2 max-w-5xl">Durable anomaly-to-case investigations with immutable evidence packs, exclusive investigator leases, root-cause classification, annotations, governed remediation referrals and material dual approval. AI authority: recommendation only.</p></div><FileSearch2 className="h-9 w-9 text-amber-300"/></div></section>
    {error&&<div className="card p-3 border-red-500/30 text-red-300 text-sm">{error}</div>}
    <section className="grid xl:grid-cols-[360px_1fr] gap-5"><div className="card p-4"><div className="panel-title">Investigation SLA queue</div><div className="space-y-2 mt-3">{queue.map((c)=><button key={c.case_id} className="w-full text-left rounded-xl border border-[#20364e] p-3 hover:border-teal-400" onClick={()=>void load(c.case_id)}><div className="flex justify-between"><b>{c.anomaly_code}</b><span>{c.anomaly_score}/100</span></div><div className="text-xs text-slate-500">{c.case_id} · {c.status}</div><div className="text-xs mt-1">priority {c.priority}{c.sla_breached&&<span className="text-red-300"> · SLA breached</span>}</div></button>)}</div></div>
    <div className="space-y-5">{!wb?<div className="card p-8 text-slate-500">Select a financial investigation case.</div>:<>
      <section className="card p-5"><div className="flex justify-between"><div><div className="panel-title">Case · {wb.case.case_type}</div><h2 className="text-xl font-semibold">{wb.case.anomaly_code} · {wb.case.severity}</h2></div><span className="badge">v{wb.case.case_version} · {wb.case.status}</span></div><div className="grid md:grid-cols-3 gap-3 mt-4 text-sm"><div>Claim <b>{wb.case.claim_id}</b></div><div>Cluster <b>{wb.cluster.length}</b> cases</div><div>Root cause <b>{wb.case.root_cause_code||"pending human classification"}</b></div></div>{!lease&&<button className="btn btn-primary mt-4" disabled={busy} onClick={acquire}><LockKeyhole className="h-4 w-4"/>Acquire exclusive lease</button>}</section>
      <section className="card p-5"><div className="panel-title">Immutable evidence pack</div>{wb.evidence_pack?<><div className="mono text-[10px] break-all text-slate-500 mt-2">SHA-256 {wb.evidence_pack.payload_sha256}</div><div className="grid md:grid-cols-2 gap-2 mt-3">{wb.evidence_pack.evidence_items.map((x,i:number)=><div key={i} className="rounded-xl border border-[#20364e] p-3 text-sm"><b>{x.type}</b><div className="text-xs text-slate-500 break-all">{x.id}</div></div>)}</div></>:<p>No pack.</p>}</section>
      <section className="grid xl:grid-cols-2 gap-5"><div className="card p-5"><div className="panel-title">Root cause · human decision</div><select className="input mt-3 w-full" value={rootCause} onChange={e=>setRootCause(e.target.value)}>{["duplicate_payment","overpayment","provider_billing_pattern","reconciliation_mismatch","returned_payment","reserve_inadequacy","accounting_control_gap","data_quality","no_issue_found","other"].map(x=><option key={x}>{x}</option>)}</select><textarea className="input mt-3 w-full min-h-28" value={rationale} onChange={e=>setRationale(e.target.value)}/><button className="btn btn-primary mt-3" disabled={busy||!lease} onClick={()=>void act(()=>reviewerApi.classifyFinancialRootCause(caseId,{root_cause_code:rootCause,rationale,ai_disagreement_rationale:rootCause!==(wb.case.ai_recommendation?.recommended_root_cause)?"Human reviewer disagrees after inspecting the cited governed evidence.":null,expected_case_version:wb.case.case_version,lease_token:lease}))}>Record human root cause</button><div className="text-xs text-slate-500 mt-3">AI recommendation: {wb.case.ai_recommendation?.recommended_root_cause||"none"}</div></div>
      <div className="card p-5"><div className="panel-title">Remediation</div><p className="text-sm text-slate-400 mt-2">Material payment holds, void/reissue, adjustment and recoupment referrals require an independent finance approver. This workspace never moves funds or posts journals directly.</p>{wb.remediation_proposals.map((p)=><div key={p.proposal_id} className="rounded-xl border border-[#20364e] p-3 mt-3 text-sm"><div className="flex justify-between"><b>{p.remediation_type}</b><span>{p.status}</span></div><div>{p.amount} {p.currency} · material {String(p.material)}</div><div className="text-xs text-slate-500">referral {p.referral_type||"pending"} {p.referral_id||""}</div></div>)}</div></section>
      <section className="grid xl:grid-cols-2 gap-5"><div className="card p-5"><div className="panel-title">Human annotations</div>{wb.annotations.map((a)=><div key={a.annotation_id} className="border-b border-[#20364e] py-2 text-sm"><b>{a.target_type}</b> · {a.body}</div>)}</div><div className="card p-5"><div className="panel-title">SLA & immutable audit chain</div>{wb.tasks.map((t)=><div key={t.task_id} className="text-sm py-1">{t.task_type} · {t.status} · due {String(t.due_at)}</div>)}<div className="mt-3 text-xs text-slate-500">{wb.audit_chain.length} hash-chained audit events</div></div></section>
      <section className="card p-5 border-emerald-500/20"><div className="flex gap-2 items-center"><ShieldCheck className="text-emerald-300"/><div className="panel-title">Authority boundary</div></div><p className="text-sm text-slate-300 mt-3">AI/LLM/LangGraph/RAG/MCP/background workers cannot change adjudication, accounting journals, reserves, payment authorization, or movement of funds. Human investigation and independent approval gates remain mandatory.</p></section>
    </>}</div></section>
  </div>;
}
