"use client";
import { useEffect,useState } from "react";
import { RefreshCcw,ShieldCheck,Scale,Clock3 } from "lucide-react";
import { reviewerApi } from "@/lib/api";
import type { RecoveryOperationsPortfolio, RecoveryOperationsWorkbench, RecoveryQueueItem } from "@/lib/schemas";

export default function RecoveryOperationsPage(){
  const [queue,setQueue]=useState<RecoveryQueueItem[]>([]),[portfolio,setPortfolio]=useState<RecoveryOperationsPortfolio|null>(null),[wb,setWb]=useState<RecoveryOperationsWorkbench|null>(null),[caseId,setCaseId]=useState(""),[lease,setLease]=useState(""),[error,setError]=useState("");
  const loadQueue=async()=>{try{const [q,p]=await Promise.all([reviewerApi.recoveryOperationsQueue(),reviewerApi.recoveryOperationsPortfolio()]);setQueue(q);setPortfolio(p)}catch(e){setError(e instanceof Error?e.message:"Load failed")}};
  const load=async(id:string)=>{setCaseId(id);try{setWb(await reviewerApi.recoveryOperationsWorkbench(id));setError("")}catch(e){setError(e instanceof Error?e.message:"Load failed")}};
  useEffect(()=>{void loadQueue();const es=new EventSource("/api/reviewer/queue/events");const refresh=()=>{void loadQueue();if(caseId)void load(caseId)};["recovery.case.created","recovery.lease.acquired","recovery.remediation.verified","recovery.amount.recorded","recovery.dispute.submitted","recovery.dispute.resolved","recovery.correspondence.recorded","recovery.case.closed"].forEach(t=>es.addEventListener(t,refresh));return()=>es.close()},[caseId]);
  const acquire=async()=>{if(!wb)return;try{const r=await reviewerApi.acquireRecoveryLease(caseId,wb.case.case_version);setLease(r.lease_token);await load(caseId)}catch(e){setError(e instanceof Error?e.message:"Lease failed")}};
  const verify=async()=>{try{await reviewerApi.verifyRecoveryOutcome(caseId,lease);await load(caseId)}catch(e){setError(e instanceof Error?e.message:"Verification failed")}};
  return <div className="space-y-5">
    <section className="card p-6 border-emerald-400/20"><div className="flex justify-between gap-4"><div><div className="panel-title">governed recovery verification</div><h1 className="text-2xl font-bold mt-1">Recovery & Provider Disputes</h1><p className="text-sm text-slate-400 mt-2 max-w-5xl">Track recoupment, adjustment, hold and void/reissue outcomes; reconcile partial recoveries; manage provider disputes with immutable evidence and independent human resolution. AI and workers cannot collect funds or change accounting.</p></div><RefreshCcw className="h-9 w-9 text-emerald-300"/></div></section>
    {error&&<div className="card p-3 text-red-300">{error}</div>}
    <section className="grid md:grid-cols-4 gap-3">{[["Cases",portfolio?.cases],["Open",portfolio?.open_cases],["Identified",portfolio?.identified_leakage],["Verified recovered",portfolio?.verified_recovered]].map(([k,v])=><div className="card p-4" key={String(k)}><div className="text-xs text-slate-500">{k}</div><div className="text-xl font-bold mt-1">{String(v??0)}</div></div>)}</section>
    <section className="grid xl:grid-cols-[360px_1fr] gap-5"><div className="card p-4"><div className="panel-title">Recovery aging / SLA queue</div><div className="space-y-2 mt-3">{queue.map((c)=><button key={c.recovery_case_id} className="w-full text-left rounded-xl border border-[#20364e] p-3 hover:border-emerald-400" onClick={()=>void load(c.recovery_case_id)}><div className="flex justify-between"><b>{c.recovery_type}</b><span>{c.status}</span></div><div className="text-xs text-slate-500">{c.recovery_case_id}</div><div className="text-xs mt-1">{c.recovered_amount}/{c.identified_amount} {c.currency} · disputes {c.open_disputes}{c.sla_breached&&<span className="text-red-300"> · SLA breached</span>}</div></button>)}</div></div>
    <div className="space-y-5">{!wb?<div className="card p-8 text-slate-500">Select a recovery case.</div>:<>
      <section className="card p-5"><div className="flex justify-between"><div><div className="panel-title">Recovery case</div><h2 className="text-xl font-semibold">{wb.case.recovery_type}</h2></div><span className="badge">v{wb.case.case_version} · {wb.case.status}</span></div><div className="grid md:grid-cols-4 gap-3 mt-4 text-sm"><div>Identified <b>{wb.case.identified_amount} {wb.case.currency}</b></div><div>Recovered <b>{wb.case.recovered_amount}</b></div><div>Effectiveness <b>{wb.effectiveness.recovered_vs_identified_percent}%</b></div><div>Aging <b>{wb.aging.bucket}</b></div></div>{!lease&&<button className="btn btn-primary mt-4" onClick={()=>void acquire()}>Acquire recovery lease</button>} {lease&&<button className="btn btn-primary mt-4" onClick={()=>void verify()}>Verify downstream remediation</button>}</section>
      <section className="grid xl:grid-cols-2 gap-5"><div className="card p-5"><div className="panel-title">Immutable evidence & downstream state</div><div className="mono text-[10px] break-all text-slate-500 mt-2">{wb.evidence_pack?.payload_sha256}</div><div className="mt-3 text-sm">Referral: <b>{wb.downstream_state.source_type}</b> · {wb.downstream_state.status}</div>{wb.evidence_pack?.citations?.map((x,i:number)=><div key={i} className="text-xs mt-2 border-t border-[#20364e] pt-2">{x.type} · {x.id}</div>)}</div><div className="card p-5"><div className="panel-title">Recovery outcomes</div>{wb.outcomes.map((x)=><div key={x.outcome_id} className="py-2 border-b border-[#20364e] text-sm"><b>{x.outcome_type}</b> · {x.status}<div className="text-xs text-slate-500">{x.amount} {x.currency} · {x.external_reference||x.source_id}</div></div>)}</div></section>
      <section className="grid xl:grid-cols-2 gap-5"><div className="card p-5"><div className="flex items-center gap-2"><Scale className="h-4 w-4 text-amber-300"/><div className="panel-title">Provider disputes</div></div>{wb.disputes.map((d)=><div key={d.dispute_id} className="rounded-xl border border-[#20364e] p-3 mt-3 text-sm"><div className="flex justify-between"><b>{d.reason_code}</b><span>{d.status}</span></div><div>{d.disputed_amount} {d.currency} · material {String(d.material)}</div><div className="text-xs text-slate-500">resolution {d.resolution_outcome||"pending independent human"}</div></div>)}</div><div className="card p-5"><div className="flex items-center gap-2"><Clock3 className="h-4 w-4"/><div className="panel-title">SLA / provenance</div></div>{wb.tasks.map((t)=><div key={t.task_id} className="text-sm py-1">{t.task_type} · {t.status} · {t.sla_breached?"BREACHED":"on track"}</div>)}<div className="text-xs text-slate-500 mt-3">{wb.audit_chain.length} hash-chained recovery audit events</div></div></section>
      <section className="card p-5 border-emerald-500/20"><div className="flex items-center gap-2"><ShieldCheck className="text-emerald-300"/><div className="panel-title">Authority boundary</div></div><p className="text-sm mt-3 text-slate-300">Provider dispute resolution is independent-human only. AI/LLM/LangGraph/RAG/MCP and recovery workers cannot approve accounting changes, authorize payments, collect funds, or move money.</p></section>
    </>}</div></section>
  </div>
}
