from __future__ import annotations
from fastapi import APIRouter, Depends, Header
from app.domain.regulatory_examination_reauthorized_enterprise_remediation_reexecution import reauthorized_enterprise_remediation_reexecution_contract
from app.schemas.regulatory_examination_reauthorized_enterprise_remediation_reexecution import *
from app.services.regulatory_examination_reauthorized_enterprise_remediation_reexecution import RegulatoryExaminationReauthorizedEnterpriseRemediationReExecutionService
router=APIRouter(prefix="/regulatory-examination-reauthorized-enterprise-remediation-re-execution",tags=["regulatory-examination-reauthorized-enterprise-remediation-re-execution"])
def svc(x_tenant_id:str=Header(default="default")): return RegulatoryExaminationReauthorizedEnterpriseRemediationReExecutionService(None,x_tenant_id)
@router.get("/model")
def model(): return reauthorized_enterprise_remediation_reexecution_contract()
@router.post("/programs")
def programs(req:EnterpriseRemediationReExecutionProgramCreate,s=Depends(svc),x_actor_id:str=Header(default="human-user")): return s.create_program(x_actor_id,req.model_dump())
@router.post("/progress")
def progress(req:EnterpriseRemediationReExecutionAnalysisRequest,s=Depends(svc)): return s.progress(req.model_dump())
@router.post("/root-cause-treatments")
def root_treatments(req:EnterpriseRemediationReExecutionAnalysisRequest,s=Depends(svc)): return s.root_cause_treatments(req.model_dump())
@router.post("/control-retransformation")
def control(req:EnterpriseRemediationReExecutionAnalysisRequest,s=Depends(svc)): return s.control_retransformation(req.model_dump())
@router.post("/deployment-sequence")
def sequence(req:EnterpriseRemediationReExecutionAnalysisRequest,s=Depends(svc)): return s.deployment_sequence(req.model_dump())
@router.post("/commitment-alignment")
def commitments(req:EnterpriseRemediationReExecutionAnalysisRequest,s=Depends(svc)): return s.commitment_alignment(req.model_dump())
@router.post("/critical-path")
def critical(req:EnterpriseRemediationReExecutionAnalysisRequest,s=Depends(svc)): return s.critical_path(req.model_dump())
@router.post("/implementation-drift")
def drift(req:EnterpriseRemediationReExecutionAnalysisRequest,s=Depends(svc)): return s.detect_drift(req.model_dump())
@router.post("/systemic-recovery-kpis")
def kpis(req:EnterpriseRemediationReExecutionAnalysisRequest,s=Depends(svc)): return s.kpis(req.model_dump())
@router.post("/enterprise-control-validation")
def validation(req:EnterpriseRemediationReExecutionAnalysisRequest,s=Depends(svc)): return s.enterprise_validation(req.model_dump())
@router.post("/blocker-escalation")
def blockers(req:EnterpriseRemediationReExecutionAnalysisRequest,s=Depends(svc)): return s.blocker_escalation(req.model_dump())
@router.post("/control-retransformation-approvals")
def approve(req:ControlRetransformationApprovalCreate,s=Depends(svc),x_actor_id:str=Header(default="human-user")): return s.approve_control_retransformation(x_actor_id,req.model_dump())
@router.post("/implementation-checkpoints")
def checkpoint(req:ImplementationCheckpointCreate,s=Depends(svc),x_actor_id:str=Header(default="human-user")): return s.create_checkpoint(x_actor_id,req.model_dump())
@router.post("/independent-recovery-effectiveness-assurance")
def assurance(req:IndependentRecoveryEffectivenessAssuranceCreate,s=Depends(svc),x_actor_id:str=Header(default="human-user")): return s.independent_assurance(x_actor_id,req.model_dump())
@router.post("/execution-readiness")
def readiness(req:ExecutionReadinessRequest,s=Depends(svc)): return s.readiness(req.model_dump())
@router.post("/executive-supervisory-reviews")
def exec_review(req:ExecutiveSupervisoryReviewCreate,s=Depends(svc),x_actor_id:str=Header(default="human-user")): return s.executive_review(x_actor_id,req.model_dump())
@router.post("/dashboard-summary")
def dashboard(req:EnterpriseRemediationReExecutionAnalysisRequest,s=Depends(svc)): return s.dashboard(req.model_dump())
@router.post("/audit-export")
def audit(req:AuditExportRequest,s=Depends(svc)): return s.audit_export(req.model_dump())
