"use client";
import { useEffect, useState } from "react";
import { ShieldCheck } from "lucide-react";
import { reviewerApi } from "@/lib/api";
import { ActionDialog, type DialogField } from "@/components/ui/action-dialog";
import type { SupervisionCase, SupervisionDashboard } from "@/lib/regulatory-schemas";

type Spec={title:string;description:string;fields:DialogField[];submitLabel:string;run:(v:Record<string,string>)=>Promise<void>};
const message=(e:unknown)=>e instanceof Error?e.message:String(e);
export default function RegulatorySupervisionPage(){
 const [data,setData]=useState<SupervisionDashboard|null>(null),[error,setError]=useState(""),[dialog,setDialog]=useState<Spec|null>(null),[busy,setBusy]=useState(false);
 const refresh=async()=>{try{setData(await reviewerApi.regulatorySupervisionDashboard());setError("")}catch(e){setError(message(e))}};
 useEffect(()=>{void refresh();const es=new EventSource("/api/reviewer/queue/events");const h=()=>void refresh();es.addEventListener("review-event",h);return()=>es.close()},[]);
 const submit=async(v:Record<string,string>)=>{if(!dialog)return;setBusy(true);try{await dialog.run(v);setDialog(null);await refresh()}catch(e){setError(message(e))}finally{setBusy(false)}};
 const prepare=async(c:SupervisionCase)=>{try{await reviewerApi.prepareRegulatorySupervisionAttestation(c.case_id,c.case_version);await refresh()}catch(e){setError(message(e))}};
 const classify=(c:SupervisionCase)=>setDialog({title:"Classify regulator rejection",description:"A human reviewer records the rejection root cause; AI may recommend but cannot make this authoritative classification.",submitLabel:"Record classification",fields:[{name:"root",label:"Root cause",type:"select",defaultValue:"schema_validation",options:[{value:"schema_validation",label:"Schema validation"},{value:"evidence_gap",label:"Evidence gap"},{value:"control_failure",label:"Control failure"},{value:"submission_error",label:"Submission error"}]},{name:"rationale",label:"Human root-cause rationale",type:"textarea",required:true}],run:async v=>{await reviewerApi.classifyRegulatoryRejection(c.case_id,{root_cause:v.root,rationale:v.rationale,expected_case_version:c.case_version})}});
 const effectiveness=(c:SupervisionCase)=>setDialog({title:"Verify amendment effectiveness",description:"Document why the acknowledged amendment resolves the identified supervisory issue.",submitLabel:"Record effectiveness",fields:[{name:"rationale",label:"Effectiveness rationale",type:"textarea",required:true}],run:async v=>{await reviewerApi.recordRegulatoryAmendmentEffectiveness(c.case_id,{effectiveness:"effective",rationale:v.rationale,expected_case_version:c.case_version})}});
 const certify=(c:SupervisionCase)=>{if(!c.latest_attestation)return;setDialog({title:"Independent supervisory certification",description:"Certification is a non-delegable human control and is recorded separately from automated reconciliation.",submitLabel:"Certify reconciliation",fields:[{name:"rationale",label:"Independent certification rationale",type:"textarea",required:true}],run:async v=>{await reviewerApi.certifyRegulatorySupervision(c.case_id,c.latest_attestation!.attestation_id,{conclusion:c.opened_reason==="regulator_rejection"?"reconciled_after_amendment":"reconciled",rationale:v.rationale,expected_case_version:c.case_version})}})};
 return <div className="space-y-5"><header><div className="panel-title">Regulatory operations</div><h1 className="text-2xl font-bold mt-1">Regulatory Supervisory Control</h1><p className="text-sm text-slate-400 mt-2">Certified package → human release → transport/ACK → deterministic reconciliation → independent human supervisory certification.</p></header><section className="card p-4"><div className="flex gap-2 items-center font-semibold"><ShieldCheck className="h-4 w-4 text-teal-300"/>Authority boundary</div><p className="text-sm text-slate-400 mt-2">AI, agents and workers are monitoring/recommendation-only. They cannot certify reconciliation or authorize regulatory submissions.</p></section>{error&&<div role="alert" className="card border-rose-500/30 p-3 text-rose-200">{error}</div>}
 {data?<><section className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3">{Object.entries(data.kpis).map(([k,v])=><Metric key={k} label={k} value={String(v??0)}/>)}</section><section className="card p-4"><h2 className="font-semibold">Supervisory reconciliation queue</h2><div className="space-y-2 mt-3">{data.cases.length===0?<State text="No supervisory reconciliation cases."/>:data.cases.map(c=><article key={c.case_id} className="rounded-xl border border-[#233b55] p-3 text-sm"><div className="flex justify-between gap-3"><b>{c.case_id}</b><span className="badge">{c.status}</span></div><div className="text-slate-400">{c.opened_reason} · ACK {c.acknowledgment_status??"pending"} · version {c.case_version}</div><div className="text-xs text-slate-500 mt-1 break-all">source {c.source_snapshot_sha256}</div>{c.latest_attestation&&<div className="mt-2 text-xs">Control effectiveness {c.latest_attestation.control_effectiveness_pct}% · blockers {c.latest_attestation.material_blockers.length}</div>}<div className="flex flex-wrap gap-2 mt-3">{c.opened_reason==="regulator_rejection"&&!c.rejection_root_cause&&<button className="btn" onClick={()=>classify(c)}>Classify rejection</button>}{c.opened_reason==="regulator_rejection"&&c.rejection_root_cause&&c.amendment_effectiveness!=="effective"&&<button className="btn" onClick={()=>effectiveness(c)}>Verify amendment</button>}<button className="btn" onClick={()=>void prepare(c)}>Prepare controls</button>{c.latest_attestation&&c.latest_attestation.material_blockers.length===0&&c.status!=="certified"&&<button className="btn btn-primary" onClick={()=>certify(c)}>Independent human certify</button>}</div></article>)}</div></section><section className="grid md:grid-cols-2 gap-4"><section className="card p-4"><h2 className="font-semibold">Compliance exceptions</h2>{data.exceptions.length?data.exceptions.slice(0,8).map(x=><div key={x.exception_id} className="text-sm border-b border-[#233b55] py-2">{x.exception_code} · {x.material?"material":"non-material"} · {x.status}</div>):<State text="No open compliance exceptions."/>}</section><section className="card p-4"><h2 className="font-semibold">Regulatory calendar</h2>{data.deadlines.length?data.deadlines.slice(0,8).map(x=><div key={x.deadline_id} className="text-sm border-b border-[#233b55] py-2">{x.deadline_key} · {String(x.due_date)} · {x.status}</div>):<State text="No upcoming regulatory deadlines."/>}</section></section></>:<State text="Loading supervisory controls…"/>}
 <ActionDialog open={Boolean(dialog)} title={dialog?.title??""} description={dialog?.description} fields={dialog?.fields??[]} submitLabel={dialog?.submitLabel} busy={busy} onClose={()=>setDialog(null)} onSubmit={submit}/></div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="card p-4"><div className="text-xs text-slate-500 capitalize">{label.replaceAll("_"," ")}</div><div className="text-xl font-semibold mt-1">{value}</div></div>}
function State({text}:{text:string}){return <div className="rounded-xl border border-dashed border-[#31506f] p-4 text-sm text-slate-500 mt-3">{text}</div>}
