"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, FileLock2, Scale, ShieldCheck, UserRoundCheck } from "lucide-react";
import { APIError, reviewerApi } from "@/lib/api";
import type { AppealReconsideration, AppealResolution } from "@/lib/schemas";

const pretty=(v:string)=>v.replaceAll("_"," ");
export function AppealResolutionPanel({claimId,appealId,reconsideration}:{claimId:string;appealId:string;reconsideration:AppealReconsideration}){
  const [state,setState]=useState<AppealResolution|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  const [outcome,setOutcome]=useState("modify");const [decision,setDecision]=useState("partial_approve");const [amount,setAmount]=useState("0.00");const [reasonCodes,setReasonCodes]=useState("evidence_contradicts,human_judgment");const [rationale,setRationale]=useState("");const [disagreement,setDisagreement]=useState("");const [secondRationale,setSecondRationale]=useState("");
  const load=useCallback(async()=>{if(!claimId||!appealId)return;try{setState(await reviewerApi.appealResolution(claimId,appealId))}catch(e){setError(e instanceof Error?e.message:"Appeal resolution unavailable")}},[claimId,appealId]);
  useEffect(()=>{void load()},[load,reconsideration.appeal_version]);
  const citations=useMemo(()=>reconsideration.latest_rag?.items?.map((x)=>String(x.item_id))||[],[reconsideration.latest_rag]);
  const resolvedComparisons=useMemo(()=>reconsideration.comparisons.filter(x=>x.severity==="material").map(x=>x.comparison_id),[reconsideration.comparisons]);
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError(null);try{await fn();await load()}catch(e){setError(e instanceof APIError?`Operation failed (${e.status}): ${e.message}`:e instanceof Error?e.message:"Operation failed")}finally{setBusy(false)}};
  const packet=state?.packet;const final=state?.final_resolution;
  const prepare=()=>act(()=>reviewerApi.saveAppealResolutionPacket(claimId,appealId,{outcome,controlling_decision:decision,rationale,reason_codes:reasonCodes.split(",").map(x=>x.trim()).filter(Boolean),citation_refs:citations,resolved_comparison_refs:resolvedComparisons,annotation_refs:reconsideration.annotations.map((x)=>String(x.annotation_id)),checkpoint_refs:reconsideration.checkpoints.map(x=>x.checkpoint_id),reconsidered_approved_amount:amount,recommendation_disagreement_reason:disagreement||null,expected_appeal_version:state?.appeal_version??reconsideration.appeal_version,expected_packet_version:null}));
  return <section className="card p-5 border-emerald-500/20">
    <div className="flex items-start justify-between gap-4"><div><div className="panel-title">governed final appeal closure</div><h2 className="font-semibold mt-1">Evidence-bound human resolution</h2><p className="text-sm text-slate-400 mt-2">The controlling outcome can be created only from the locked reconsideration snapshot. Material contradictions, missing evidence and invalid citations block locking; overturns/material financial changes require a second independent human reviewer.</p></div><ShieldCheck className="text-emerald-300"/></div>
    {error&&<div className="mt-4 rounded-xl border border-rose-500/30 bg-rose-950/20 p-3 text-sm text-rose-200">{error}</div>}
    <div className="grid md:grid-cols-4 gap-3 mt-4"><Mini label="Appeal version" value={String(state?.appeal_version??reconsideration.appeal_version)}/><Mini label="Packet" value={packet?.status||"not prepared"}/><Mini label="Citations" value={String(citations.length)}/><Mini label="Authority" value="human only"/></div>
    {!packet&&<div className="mt-4 grid md:grid-cols-3 gap-3"><select className="input" value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="affirm">Affirm</option><option value="modify">Modify</option><option value="overturn">Overturn</option></select><select className="input" value={decision} onChange={e=>setDecision(e.target.value)}><option value="approve">Approve</option><option value="deny">Deny</option><option value="partial_approve">Partial approve</option></select><input className="input" type="number" step="0.01" min="0" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Approved amount"/><input className="input md:col-span-3" value={reasonCodes} onChange={e=>setReasonCodes(e.target.value)} placeholder="reason codes, comma separated"/><textarea className="input md:col-span-3 min-h-24" value={rationale} onChange={e=>setRationale(e.target.value)} placeholder="Evidence-backed human rationale"/><textarea className="input md:col-span-3 min-h-20" value={disagreement} onChange={e=>setDisagreement(e.target.value)} placeholder="Required only when human outcome disagrees with recommendation"/><button className="btn btn-primary md:col-span-3" disabled={busy||citations.length===0||rationale.trim().length<20} onClick={()=>void prepare()}><Scale className="h-4 w-4"/>Prepare evidence-bound decision packet</button></div>}
    {packet&&<div className="mt-4 rounded-xl border border-[#24435d] p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="font-semibold">{pretty(packet.outcome)} → {pretty(packet.controlling_decision)}</div><div className="text-xs text-slate-500 mt-1">Primary reviewer {packet.primary_reviewer_user_id} · packet v{packet.packet_version}</div></div><span className="badge">{pretty(packet.status)}</span></div><div className="grid md:grid-cols-4 gap-2 mt-3"><Mini label="Original amount" value={packet.original_approved_amount}/><Mini label="Reconsidered" value={packet.reconsidered_approved_amount}/><Mini label="Delta" value={packet.financial_delta}/><Mini label="Dual control" value={String(packet.dual_control_required)}/></div>{packet.blocker_codes.length>0&&<div className="mt-3 text-sm text-amber-200">Blocking: {packet.blocker_codes.join(", ")}</div>}<div className="mono text-[10px] break-all text-slate-500 mt-3">snapshot {packet.snapshot_sha256}{packet.locked_payload_sha256&&` · locked ${packet.locked_payload_sha256}`}</div>
      {(["draft","blocked"].includes(packet.status))&&<button className="btn btn-primary mt-3" disabled={busy} onClick={()=>void act(()=>reviewerApi.lockAppealResolutionPacket(claimId,appealId,packet.packet_id,packet.packet_version))}><FileLock2 className="h-4 w-4"/>Validate & lock</button>}
      {packet.status==="pending_second_review"&&<div className="mt-3 flex gap-2"><input className="input flex-1" value={secondRationale} onChange={e=>setSecondRationale(e.target.value)} placeholder="Independent second-review rationale"/><button className="btn" disabled={busy||secondRationale.trim().length<20} onClick={()=>void act(()=>reviewerApi.secondReviewAppealResolution(claimId,appealId,packet.packet_id,{action:"approve",rationale:secondRationale,expected_packet_version:packet.packet_version}))}><UserRoundCheck className="h-4 w-4"/>Second-review approve</button></div>}
      {(["locked","second_review_approved"].includes(packet.status))&&<button className="btn btn-primary mt-3" disabled={busy} onClick={()=>void act(()=>reviewerApi.closeAppealResolution(claimId,appealId,packet.packet_id,{expected_packet_version:packet.packet_version,expected_appeal_version:state?.appeal_version??reconsideration.appeal_version}))}><CheckCircle2 className="h-4 w-4"/>Close controlling human resolution</button>}
    </div>}
    {final&&<div className="mt-4 rounded-xl border border-emerald-500/30 bg-emerald-950/10 p-4"><div className="text-xs uppercase text-emerald-300">Controlling decision version</div><div className="font-bold mt-1">{pretty(final.outcome)} → {pretty(final.controlling_decision)}</div><div className="text-sm text-slate-400 mt-2">Original {final.original_approved_amount} → reconsidered {final.reconsidered_approved_amount} · delta {final.financial_delta}</div><div className="text-xs mono text-slate-500 mt-2">history {final.history_version_id} · resolution {final.resolution_id}</div>{final.notice_id&&<button className="btn btn-primary mt-3" disabled={busy} onClick={()=>void act(()=>reviewerApi.releaseAppealResolutionNotice(claimId,appealId,final.notice_id))}>Human release reconsideration notice</button>}</div>}
    {state&&<details className="mt-4 text-xs"><summary className="cursor-pointer text-teal-300">Immutable supersession & audit chains</summary><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap text-[10px] text-slate-500">{JSON.stringify({supersession_chain:state.supersession_chain,audit_chain:state.audit_chain},null,2)}</pre></details>}
  </section>
}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#091727] border border-[#1f3852] p-3"><div className="text-[11px] uppercase tracking-wider text-slate-500">{label}</div><div className="font-bold mt-1 break-all">{value}</div></div>}
