"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AlertOctagon, ArrowLeft, Bot, CheckCircle2, Clock3, FileSearch, GitBranch, HeartPulse, LockKeyhole, MessageSquareText, RefreshCw, Scale, ShieldAlert, ShieldCheck, TimerReset, UnlockKeyhole, XCircle } from "lucide-react";
import { APIError, reviewerApi } from "@/lib/api";
import { useEventStream } from "@/lib/hooks/use-event-stream";
import type { Workbench } from "@/lib/schemas";
import { MultimodalInvestigation } from "@/components/review/multimodal-investigation";
import { GovernedDecisionPanel } from "@/components/review/governed-decision-panel";
import { PostDecisionOperations } from "@/components/review/post-decision-operations";

type Tab = "overview" | "multimodal" | "evidence" | "investigation" | "governance" | "timeline" | "decision" | "post-decision";
const tabs: Array<{ key: Tab; label: string }> = [
  { key: "overview", label: "Overview" }, { key: "multimodal", label: "Multimodal" }, { key: "evidence", label: "Evidence" },
  { key: "investigation", label: "Advanced Investigation" }, { key: "governance", label: "Governance" }, { key: "timeline", label: "Timeline" }, { key: "decision", label: "Decision" }, { key: "post-decision", label: "Post-decision" }
];

function fmtDate(value?: string | null) { return value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; }
function money(value: string, currency: string) { const n = Number(value); return Number.isFinite(n) ? new Intl.NumberFormat(undefined, { style: "currency", currency }).format(n) : `${currency} ${value}`; }
function pct(value: number) { return `${Math.round(value * 100)}%`; }
function pretty(value: string) { return value.replaceAll("_", " "); }
function badge(status: string) { const v=status.toLowerCase(); return v.includes("critical")||v.includes("deny")||v.includes("block")||v.includes("breach") ? "badge badge-critical" : v.includes("high")||v.includes("warning")||v.includes("pending") ? "badge badge-high" : v.includes("complete")||v.includes("pass")||v.includes("approve")||v.includes("match") ? "badge badge-low" : "badge badge-normal"; }

export function ClaimWorkbench({ claimId }: { claimId: string }) {
  const [data, setData] = useState<Workbench | null>(null);
  const [tab, setTab] = useState<Tab>("overview");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [lockToken, setLockToken] = useState<string | null>(null);
  const [lockUntil, setLockUntil] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const load = useCallback(async () => {
    try { setError(null); setData(await reviewerApi.workbench(claimId)); }
    catch (e) { setError(e instanceof Error ? e.message : "Workbench unavailable"); }
    finally { setLoading(false); }
  }, [claimId]);
  useEffect(() => { void load(); }, [load]);
  const { state: streamState } = useEventStream(`/api/reviewer/claims/${encodeURIComponent(claimId)}/events`, () => { void load(); });

  useEffect(() => {
    if (!lockToken) return;
    const interval = setInterval(async () => {
      try { const renewed = await reviewerApi.renewLock(claimId, lockToken, 300); setLockUntil(renewed.locked_until); }
      catch { setLockToken(null); setLockUntil(null); }
    }, 180_000);
    return () => clearInterval(interval);
  }, [claimId, lockToken]);

  const run = async (action: () => Promise<unknown>, { refresh = true } = {}) => {
    setBusy(true); setError(null);
    try { await action(); if (refresh) await load(); }
    catch (e) { setError(e instanceof APIError ? `Operation failed (${e.status}): ${e.message}` : e instanceof Error ? e.message : "Operation failed"); }
    finally { setBusy(false); }
  };

  if (loading && !data) return <div className="card p-8 text-slate-400">Loading claim workbench…</div>;
  if (!data) return <div className="card p-8"><div className="text-rose-200 font-semibold">Claim workbench unavailable</div><div className="muted mt-2">{error}</div><Link href="/review/claims" className="btn mt-5"><ArrowLeft className="h-4 w-4" />Back to queue</Link></div>;

  const openContradictions = data.graph.contradictions.filter((c) => c.status === "open");
  const pendingApprovals = data.mcp_approvals.filter((a) => a.status === "pending");
  const overdue = data.sla.filter((s) => s.seconds_remaining <= 0 && s.status !== "completed");
  const evidenceIds = data.evidence.map((e) => e.evidence_id);

  return <div className="space-y-5">
    <div className="flex flex-col xl:flex-row xl:items-start justify-between gap-4">
      <div className="flex items-start gap-3"><Link href="/review/claims" className="btn btn-ghost mt-0.5" aria-label="Back to queue"><ArrowLeft className="h-4 w-4" /></Link><div><div className="panel-title">Human review workbench</div><div className="flex flex-wrap items-center gap-3 mt-1"><h1 className="text-3xl font-bold mono">{data.claim.claim_id}</h1><span className={badge(data.claim.status)}>{pretty(data.claim.status)}</span><span className="badge">v{data.claim.status_version}</span></div><div className="text-sm text-slate-400 mt-2">Service {data.claim.service_from || "—"} → {data.claim.service_to || "—"} · {money(data.claim.total_amount, data.claim.currency)}</div></div></div>
      <div className="flex flex-wrap items-center gap-2"><span className="badge"><span className={`h-2 w-2 rounded-full ${streamState === "open" ? "bg-emerald-300" : "bg-amber-300"}`} />{streamState === "open" ? "Realtime connected" : "Realtime reconnecting"}</span><button className="btn" onClick={() => void load()}><RefreshCw className="h-4 w-4" />Refresh</button>{!lockToken ? <button disabled={busy} className="btn btn-primary" onClick={() => run(async () => { const lock=await reviewerApi.acquireLock(claimId); setLockToken(lock.lock_token); setLockUntil(lock.locked_until); await reviewerApi.beginReview(claimId, lock.lock_token); })}><LockKeyhole className="h-4 w-4" />Start review</button> : <button disabled={busy} className="btn" onClick={() => run(async () => { await reviewerApi.releaseLock(claimId, lockToken); setLockToken(null); setLockUntil(null); })}><UnlockKeyhole className="h-4 w-4" />Release lock</button>}</div>
    </div>

    {error && <div className="rounded-xl border border-rose-500/30 bg-rose-950/30 p-3 text-sm text-rose-200"><AlertOctagon className="inline h-4 w-4 mr-2" />{error}</div>}
    {lockToken && <div className="rounded-xl border border-teal-400/25 bg-teal-950/20 px-4 py-3 flex items-center justify-between gap-3 text-sm"><div className="flex items-center gap-2"><LockKeyhole className="h-4 w-4 text-teal-300" /><span className="font-semibold">Exclusive review lease active</span><span className="text-slate-400">Token stays in browser memory only.</span></div><span className="mono text-xs text-slate-400">until {fmtDate(lockUntil)}</span></div>}

    <div className="grid md:grid-cols-2 xl:grid-cols-5 gap-3">
      <Metric title="Evidence" value={String(data.evidence.length)} detail={`${data.evidence.filter(e=>e.authoritative).length} authoritative`} icon={<FileSearch className="h-4 w-4" />} />
      <Metric title="Evidence quality" value={data.guardrail ? pct(data.guardrail.evidence_quality) : "—"} detail={data.guardrail?.decision || "No guardrail run"} icon={<ShieldCheck className="h-4 w-4" />} />
      <Metric title="Contradictions" value={String(openContradictions.length)} detail="Open graph conflicts" icon={<Scale className="h-4 w-4" />} warning={openContradictions.length>0} />
      <Metric title="SLA overdue" value={String(overdue.length)} detail={`${data.sla.length} active/known timers`} icon={<Clock3 className="h-4 w-4" />} warning={overdue.length>0} />
      <Metric title="Approvals" value={String(pendingApprovals.length)} detail="MCP actions waiting" icon={<ShieldAlert className="h-4 w-4" />} warning={pendingApprovals.length>0} />
    </div>

    <div className="border-b border-[#233b55] overflow-x-auto scrollbar"><div className="flex gap-1 min-w-max">{tabs.map((item) => <button key={item.key} onClick={() => setTab(item.key)} className={`px-4 py-3 text-sm font-semibold border-b-2 ${tab===item.key ? "border-teal-300 text-teal-200" : "border-transparent text-slate-400 hover:text-white"}`}>{item.label}</button>)}</div></div>

    {tab === "overview" && <Overview data={data} />}
    {tab === "multimodal" && <MultimodalInvestigation claimId={claimId} lockToken={lockToken} />}
    {tab === "evidence" && <Evidence data={data} />}
    {tab === "investigation" && <AdvancedInvestigation data={data} />}
    {tab === "governance" && <Governance data={data} claimId={claimId} reload={load} />}
    {tab === "timeline" && <Timeline data={data} />}
    {tab === "decision" && <GovernedDecisionPanel claimId={claimId} lockToken={lockToken} workbench={data} />}
    {tab === "post-decision" && <PostDecisionOperations claimId={claimId} />}
  </div>;
}

function Metric({ title, value, detail, icon, warning=false }: { title:string; value:string; detail:string; icon:React.ReactNode; warning?:boolean }) { return <div className="card p-4"><div className="flex items-center justify-between"><div className="panel-title">{title}</div><div className={warning ? "text-amber-300" : "text-slate-500"}>{icon}</div></div><div className={`metric mt-2 ${warning ? "text-amber-200" : ""}`}>{value}</div><div className="text-xs muted mt-1">{detail}</div></div>; }

function Overview({ data }: { data: Workbench }) { return <div className="grid xl:grid-cols-[1.15fr_.85fr] gap-5">
  <div className="space-y-5"><section className="card p-5"><div className="flex items-center justify-between"><div><div className="panel-title">AI decision support</div><div className="text-xl font-bold mt-1">{data.decision_support.recommendation ? pretty(data.decision_support.recommendation) : "No recommendation"}</div></div><Bot className="h-7 w-7 text-sky-300" /></div><p className="mt-3 text-sm text-slate-400">Advisory only. Human reviewer authority remains final, and disagreement requires an override rationale.</p></section>
  <section className="card p-5"><div className="panel-title">Open contradictions</div><div className="mt-4 space-y-3">{data.graph.contradictions.filter(c=>c.status==="open").length===0 ? <Empty text="No open graph contradictions." /> : data.graph.contradictions.filter(c=>c.status==="open").map(c=><div key={c.contradiction_id} className="rounded-xl border border-amber-500/25 bg-amber-950/15 p-4"><div className="flex justify-between gap-2"><div className="font-semibold">{c.field_name}</div><span className={badge(c.severity)}>{c.severity}</span></div><div className="grid sm:grid-cols-2 gap-3 mt-3 text-sm"><div><div className="text-xs text-slate-500">Source A</div><pre className="mt-1 whitespace-pre-wrap text-slate-300">{JSON.stringify(c.left_value,null,2)}</pre></div><div><div className="text-xs text-slate-500">Source B</div><pre className="mt-1 whitespace-pre-wrap text-slate-300">{JSON.stringify(c.right_value,null,2)}</pre></div></div></div>)}</div></section></div>
  <div className="space-y-5"><SLACard data={data}/><section className="card p-5"><div className="panel-title">Review notes</div><div className="mt-4 space-y-3 max-h-80 overflow-y-auto scrollbar">{data.review_notes.length===0?<Empty text="No reviewer notes yet."/>:data.review_notes.slice().reverse().map(n=><div key={n.note_id} className="border-l-2 border-sky-400/40 pl-3"><div className="text-sm text-slate-200 whitespace-pre-wrap">{n.body}</div><div className="text-[11px] text-slate-500 mt-1">{n.note_type} · {fmtDate(n.created_at)}</div></div>)}</div></section></div>
</div>; }

function Evidence({ data }: { data: Workbench }) { return <div className="grid xl:grid-cols-2 gap-5"><section className="card p-5"><div className="panel-title">Source artifacts</div><div className="mt-4 space-y-3">{data.evidence.map(e=><div key={e.evidence_id} className="rounded-xl border border-[#233b55] p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-semibold">{e.document_type}</div><div className="text-xs text-slate-500 mono mt-1">{e.evidence_id}</div></div><div className="flex gap-1"><span className="badge">v{e.evidence_version}</span>{e.authoritative&&<span className="badge badge-low">authoritative</span>}</div></div><div className="grid sm:grid-cols-2 gap-2 mt-3 text-xs text-slate-400"><div>Media: {e.media_type}</div><div>Source: {e.source_type}</div><div className="sm:col-span-2 mono truncate" title={e.content_sha256}>SHA {e.content_sha256.slice(0,18)}…</div></div></div>)}</div></section>
<section className="card p-5"><div className="panel-title">Evidence pack & citations</div>{!data.evidence_pack?<div className="mt-4"><Empty text="No immutable evidence pack is bound to this claim."/></div>:<><div className="grid grid-cols-3 gap-3 mt-4"><Mini label="Confidence" value={pct(data.evidence_pack.confidence)}/><Mini label="Coverage" value={pct(data.evidence_pack.coverage)}/><Mini label="No evidence" value={data.evidence_pack.no_evidence?"Yes":"No"}/></div><div className="mt-4 space-y-3">{data.evidence_pack.items.map(i=><div key={i.evidence_key} className="rounded-xl bg-[#091727] border border-[#1f3852] p-4"><div className="flex justify-between gap-3"><div><span className="font-semibold mono">{i.evidence_key}</span><div className="text-xs text-slate-500 mt-1">{i.source_type} · {i.source_id} · v{i.source_version || "—"}</div></div><span className="badge">authority {i.authority_rank}</span></div><pre className="mt-3 text-xs text-slate-300 whitespace-pre-wrap break-words">{JSON.stringify(i.citation,null,2)}</pre><div className="text-xs text-slate-500 mt-2">Evidence confidence {pct(i.confidence)}</div></div>)}</div></>}</section></div>; }

function AdvancedInvestigation({ data }: { data: Workbench }) {
  const [view,setView]=useState<"clinical"|"evidence-graph"|"orchestration">("clinical");
  const choices=[{key:"clinical" as const,label:"Clinical verification",detail:"FHIR and hospital source reconciliation"},{key:"evidence-graph" as const,label:"Evidence relationships",detail:"Graph reasoning and contradiction analysis"},{key:"orchestration" as const,label:"AI orchestration",detail:"Specialist-agent execution and findings"}];
  return <div className="space-y-4"><section className="card p-4"><div className="panel-title">Advanced Investigation</div><p className="text-sm text-slate-400 mt-2">Technical evidence and AI execution details are available for investigators and interview/demo drill-down without overwhelming the core reviewer decision flow.</p><div className="grid md:grid-cols-3 gap-2 mt-4">{choices.map(x=><button key={x.key} onClick={()=>setView(x.key)} className={`text-left rounded-xl border p-3 ${view===x.key?"border-teal-400/50 bg-teal-400/10":"border-[#233b55] hover:border-[#4f779c]"}`}><div className="font-semibold text-sm">{x.label}</div><div className="text-xs text-slate-500 mt-1">{x.detail}</div></button>)}</div></section>{view==="clinical"&&<FHIR data={data}/>} {view==="evidence-graph"&&<Graph data={data}/>} {view==="orchestration"&&<Agents data={data}/>}</div>;
}

function FHIR({ data }: { data: Workbench }) { return <section className="card p-5"><div className="flex items-center gap-2"><HeartPulse className="h-5 w-5 text-rose-300"/><div className="panel-title">Hospital / FHIR cross-verification</div></div><div className="grid lg:grid-cols-2 gap-4 mt-5">{data.fhir_verifications.length===0?<Empty text="No FHIR cross-verification records."/>:data.fhir_verifications.map(v=><div key={v.verification_id} className="rounded-xl border border-[#233b55] p-4"><div className="flex justify-between gap-2"><div className="font-semibold mono text-sm">{v.verification_id}</div><span className={badge(v.status)}>{pretty(v.status)}</span></div><div className="text-sm mt-3">Confidence <b>{pct(Number(v.confidence))}</b></div><pre className="mt-3 text-xs text-slate-300 whitespace-pre-wrap overflow-auto max-h-80 scrollbar">{JSON.stringify(v.findings,null,2)}</pre></div>)}</div></section>; }

function Graph({ data }: { data: Workbench }) { return <div className="grid xl:grid-cols-[1.15fr_.85fr] gap-5"><section className="card p-5"><div className="flex items-center gap-2"><GitBranch className="h-5 w-5 text-violet-300"/><div className="panel-title">Authoritative evidence graph</div></div><div className="mt-4 max-h-[650px] overflow-auto scrollbar space-y-2">{data.graph.edges.length===0?<Empty text="No graph edges for this claim."/>:data.graph.edges.map((e,idx)=><div key={`${e.source}-${e.relationship}-${e.target}-${idx}`} className="grid grid-cols-[1fr_auto_1fr] items-center gap-3 rounded-xl border border-[#1f3852] bg-[#091727] p-3 text-sm"><span className="mono break-all">{e.source}</span><span className="badge text-violet-200">{pretty(e.relationship)}</span><span className="mono break-all text-right">{e.target}</span></div>)}</div></section><section className="card p-5"><div className="panel-title">Graph contradictions</div><div className="mt-4 space-y-3">{data.graph.contradictions.map(c=><div key={c.contradiction_id} className="rounded-xl border border-amber-500/25 p-3"><div className="flex justify-between"><span className="font-semibold">{c.field_name}</span><span className={badge(c.severity)}>{c.severity}</span></div><div className="text-xs text-slate-500 mt-2">{c.status}</div></div>)}</div></section></div>; }

function Agents({ data }: { data: Workbench }) { return <div className="space-y-5"><section className="card p-5"><div className="flex items-center justify-between"><div><div className="panel-title">LangGraph workflow</div><div className="text-lg font-semibold mt-1">{data.agent_workflow?.status ? pretty(data.agent_workflow.status) : "No workflow"}</div></div>{data.agent_workflow&&<span className="badge mono">{data.agent_workflow.workflow_id}</span>}</div>{data.agent_workflow&&<div className="grid sm:grid-cols-3 gap-3 mt-4"><Mini label="Selected" value={String(data.agent_workflow.selected_agents.length)}/><Mini label="Completed" value={String(data.agent_workflow.completed_agents.length)}/><Mini label="Failed" value={String(data.agent_workflow.failed_agents.length)}/></div>}</section><section className="grid lg:grid-cols-2 2xl:grid-cols-3 gap-4">{data.agent_findings.map((f,idx)=><div key={`${f.agent_name}-${idx}`} className="card p-4"><div className="flex justify-between gap-2"><div className="font-semibold">{pretty(f.agent_name)}</div><span className="badge">{pct(f.confidence)}</span></div>{f.requires_human_review&&<div className="mt-2 text-xs text-amber-300"><ShieldAlert className="inline h-3.5 w-3.5 mr-1"/>Human review required</div>}<div className="flex flex-wrap gap-1 mt-3">{f.risk_flags.map(r=><span className="text-xs px-2 py-1 rounded bg-rose-950/30 text-rose-200" key={r}>{pretty(r)}</span>)}</div><div className="mt-3 text-[11px] text-slate-500">Evidence: {f.evidence_keys.join(", ") || "none"}</div></div>)}</section></div>; }

function Governance({ data, claimId, reload }: { data: Workbench; claimId:string; reload:()=>Promise<void> }) { return <div className="grid xl:grid-cols-2 gap-5"><section className="card p-5"><div className="panel-title">Grounding guardrails</div>{!data.guardrail?<div className="mt-4"><Empty text="No grounding guardrail run."/></div>:<div className="mt-4 space-y-4"><div className="flex justify-between"><div><div className="text-xl font-bold">{pretty(data.guardrail.decision)}</div><div className="muted text-xs mono mt-1">{data.guardrail.run_id}</div></div><span className={badge(data.guardrail.decision)}>{data.guardrail.answerable?"answerable":"not answerable"}</span></div><div className="grid grid-cols-2 gap-3"><Mini label="Evidence quality" value={pct(data.guardrail.evidence_quality)}/><Mini label="Material conflicts" value={String(data.guardrail.unresolved_material_contradictions)}/></div><div className="flex flex-wrap gap-2">{data.guardrail.escalation_reasons.map(r=><span className="badge badge-high" key={r}>{pretty(r)}</span>)}</div></div>}</section><section className="card p-5"><div className="panel-title">MCP approvals</div><div className="mt-4 space-y-3">{data.mcp_approvals.length===0?<Empty text="No controlled tool approvals."/>:data.mcp_approvals.map(a=><div key={a.approval_id} className="rounded-xl border border-[#233b55] p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-semibold">{a.tool_name}</div><div className="text-xs mono text-slate-500 mt-1">{a.approval_id}</div><div className="text-xs text-slate-500 mt-1">Expires {fmtDate(a.expires_at)}</div></div><span className={badge(a.status)}>{a.status}</span></div>{a.status==="pending"&&<div className="flex gap-2 mt-3"><button className="btn btn-primary" onClick={async()=>{await reviewerApi.decideApproval(claimId,a.approval_id,"approve");await reload();}}><CheckCircle2 className="h-4 w-4"/>Approve</button><button className="btn btn-danger" onClick={async()=>{await reviewerApi.decideApproval(claimId,a.approval_id,"reject");await reload();}}><XCircle className="h-4 w-4"/>Reject</button></div>}</div>)}</div></section></div>; }

function Timeline({ data }: { data: Workbench }) { return <section className="card p-5"><div className="panel-title">Complete claim timeline</div><div className="mt-5 max-w-4xl">{data.timeline.length===0?<Empty text="No timeline entries."/>:<div className="border-l border-[#31506f] ml-2 space-y-5">{data.timeline.slice().reverse().map((e,idx)=><div key={`${e.at}-${e.type}-${idx}`} className="relative pl-6"><span className="absolute -left-[5px] top-1 h-2.5 w-2.5 rounded-full bg-sky-300 ring-4 ring-[#07111f]"/><div className="flex flex-wrap gap-2 items-center"><span className="font-semibold text-sm">{pretty(e.summary)}</span><span className="badge">{e.type}</span></div><div className="text-xs text-slate-500 mt-1">{fmtDate(e.at)}{e.actor_id?` · ${e.actor_id}`:""}</div></div>)}</div>}</div></section>; }

function SLACard({ data }: { data: Workbench }) { return <section className="card p-5"><div className="flex items-center gap-2"><TimerReset className="h-5 w-5 text-amber-300"/><div className="panel-title">SLA countdowns</div></div><div className="mt-4 space-y-3">{data.sla.length===0?<Empty text="No claim SLA timers."/>:data.sla.map(t=><div key={t.timer_id} className="flex items-center justify-between rounded-xl border border-[#233b55] p-3"><div><div className="font-semibold text-sm">{pretty(t.timer_type)}</div><div className="text-xs text-slate-500 mt-1">Due {fmtDate(t.due_at)}</div></div><div className="text-right"><div className={`font-bold mono ${t.seconds_remaining<=0?"text-rose-300":"text-slate-200"}`}>{t.seconds_remaining<=0?"OVERDUE":duration(t.seconds_remaining)}</div><div className="text-[11px] text-slate-500">{t.status}</div></div></div>)}</div></section>; }

function DecisionPanel({ data, claimId, lockToken, busy, run, evidenceIds }: { data:Workbench; claimId:string; lockToken:string|null; busy:boolean; run:(fn:()=>Promise<unknown>,opts?:{refresh?:boolean})=>Promise<void>; evidenceIds:string[] }) {
  const [note, setNote]=useState(""); const [noteType,setNoteType]=useState("general"); const [requestDocs,setRequestDocs]=useState("medical_bill,eob"); const [requestRationale,setRequestRationale]=useState("");
  const [decision,setDecision]=useState("approve"); const [rationale,setRationale]=useState(""); const [reason,setReason]=useState("human_judgment"); const [override,setOverride]=useState("");
  const ai=data.decision_support.recommendation; const expected=ai==="support_approval"?"approve":ai==="support_denial"?"deny":ai==="pending_documents"?"request_information":null; const needsOverride=Boolean(expected&&decision!==expected);
  const requireLock=()=>{if(!lockToken) throw new Error("Acquire the exclusive review lease before changing claim review state."); return lockToken;};
  const submitNote=(e:FormEvent)=>{e.preventDefault();void run(async()=>{await reviewerApi.addNote(claimId,requireLock(),{note_type:noteType,body:note,evidence_refs:[]});setNote("");});};
  return <div className="grid xl:grid-cols-[.75fr_1.25fr] gap-5"><div className="space-y-5"><section className="card p-5"><div className="panel-title">Reviewer note</div><form className="mt-4 space-y-3" onSubmit={submitNote}><select className="input" value={noteType} onChange={e=>setNoteType(e.target.value)}><option value="general">General</option><option value="evidence">Evidence</option><option value="escalation">Escalation</option><option value="decision">Decision</option></select><textarea className="input min-h-28" value={note} onChange={e=>setNote(e.target.value)} placeholder="Document your review reasoning…" required/><button disabled={busy||!lockToken} className="btn"><MessageSquareText className="h-4 w-4"/>Add immutable note</button></form></section><section className="card p-5"><div className="panel-title">Request more evidence</div><form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();void run(async()=>{await reviewerApi.requestEvidence(claimId,requireLock(),{rationale:requestRationale,requested_document_types:requestDocs.split(",").map(x=>x.trim()).filter(Boolean),evidence_snapshot_ids:evidenceIds});setRequestRationale("");});}}><input className="input" value={requestDocs} onChange={e=>setRequestDocs(e.target.value)} placeholder="medical_bill,eob"/><textarea className="input min-h-24" value={requestRationale} onChange={e=>setRequestRationale(e.target.value)} placeholder="Why additional evidence is required" required/><button disabled={busy||!lockToken||!evidenceIds.length} className="btn"><FileSearch className="h-4 w-4"/>Request evidence</button></form></section></div>
  <section className="card p-5 border-teal-400/20"><div className="flex items-center justify-between"><div><div className="panel-title">Human decision</div><h3 className="text-xl font-bold mt-1">Reviewer authority gate</h3></div><ShieldCheck className="h-7 w-7 text-teal-300"/></div><div className="mt-4 rounded-xl bg-[#091727] border border-[#1f3852] p-4 text-sm"><div className="text-xs text-slate-500">AI recommendation</div><div className="font-semibold mt-1">{ai?pretty(ai):"No recommendation"}</div><div className="text-xs text-slate-500 mt-2">Advisory only. Final action is executed through the deterministic claim lifecycle.</div></div><form className="mt-5 space-y-4" onSubmit={e=>{e.preventDefault();void run(async()=>{await reviewerApi.decision(claimId,requireLock(),{decision,rationale,reason_codes:[reason],evidence_snapshot_ids:evidenceIds,expected_claim_status_version:data.claim.status_version,override_reason:needsOverride?override:undefined});setLockUntilFromDecision();});}}>
    <label className="block"><span className="text-sm font-semibold">Decision</span><select className="input mt-2" value={decision} onChange={e=>setDecision(e.target.value)}><option value="approve">Approve</option><option value="deny">Deny</option><option value="partial_approve">Partial approve</option><option value="escalate">Escalate</option></select></label>
    <label className="block"><span className="text-sm font-semibold">Reason code</span><select className="input mt-2" value={reason} onChange={e=>setReason(e.target.value)}>{["evidence_supports","evidence_contradicts","policy_coverage","coding_issue","duplicate_risk","fraud_waste_signal","missing_documents","human_judgment","other"].map(r=><option value={r} key={r}>{pretty(r)}</option>)}</select></label>
    <label className="block"><span className="text-sm font-semibold">Rationale</span><textarea className="input mt-2 min-h-32" value={rationale} onChange={e=>setRationale(e.target.value)} placeholder="Document the evidence-backed human rationale" required/></label>
    {needsOverride&&<label className="block rounded-xl border border-amber-500/30 bg-amber-950/15 p-4"><span className="text-sm font-semibold text-amber-200">AI override reason required</span><div className="text-xs text-slate-400 mt-1">Your decision differs from the advisory recommendation.</div><textarea className="input mt-3 min-h-24" value={override} onChange={e=>setOverride(e.target.value)} placeholder="Explain why human judgment overrides the AI recommendation" required/></label>}
    <div className="flex items-center justify-between gap-3 pt-2"><div className="text-xs text-slate-500">Evidence snapshot: {evidenceIds.length} artifact(s) · claim version {data.claim.status_version}</div><button disabled={busy||!lockToken||!evidenceIds.length||!rationale||needsOverride&&!override} className="btn btn-primary"><CheckCircle2 className="h-4 w-4"/>Record human decision</button></div>
  </form></section></div>;
  function setLockUntilFromDecision(){/* lease remains server-side until explicit release/expiry; UI reloads through run() */}
}

function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#091727] border border-[#1f3852] p-3"><div className="text-[11px] uppercase tracking-wider text-slate-500">{label}</div><div className="font-bold mt-1">{value}</div></div>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-[#31506f] p-5 text-sm text-slate-500">{text}</div>}
function duration(total:number){const s=Math.max(0,total);const h=Math.floor(s/3600);const m=Math.floor((s%3600)/60);const sec=Math.floor(s%60);return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}`}
