"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, FileLock2, GitCompareArrows, LockKeyhole, Scale, Send, ShieldCheck, UserCheck } from "lucide-react";
import { APIError, reviewerApi } from "@/lib/api";
import type { GovernedClosure, MultimodalReview, ReviewerSession, Workbench } from "@/lib/schemas";

const reasonCodes=["evidence_supports","evidence_contradicts","policy_coverage","coding_issue","duplicate_risk","fraud_waste_signal","missing_documents","human_judgment","other"];
const pretty=(v:string)=>v.replaceAll("_"," ");
const fmt=(v?:string|null)=>v?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";

export function GovernedDecisionPanel({claimId,lockToken,workbench}:{claimId:string;lockToken:string|null;workbench:Workbench}){
  const [state,setState]=useState<GovernedClosure|null>(null); const [mm,setMM]=useState<MultimodalReview|null>(null); const [session,setSession]=useState<ReviewerSession|null>(null);
  const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const [decision,setDecision]=useState("approve"); const [rationale,setRationale]=useState(""); const [reason,setReason]=useState("human_judgment"); const [approvedAmount,setApprovedAmount]=useState(""); const [disagreement,setDisagreement]=useState(""); const [escalationQueue,setEscalationQueue]=useState("senior_medical_claims"); const [secondRationale,setSecondRationale]=useState("");
  const load=useCallback(async()=>{try{setError(null);const [g,m,s]=await Promise.all([reviewerApi.governedClosure(claimId),reviewerApi.multimodalReview(claimId),reviewerApi.session()]);setState(g);setMM(m);setSession(s)}catch(e){setError(e instanceof Error?e.message:"Governed closure unavailable")}},[claimId]);
  useEffect(()=>{void load()},[load]);
  const packet=state?.decision_packet; const validation=state?.validation; const expectedAI=packet?.ai_recommendation==="support_approval"?"approve":packet?.ai_recommendation==="support_denial"?"deny":packet?.ai_recommendation==="pending_documents"?"request_information":null;
  const selectedExpectedAI=workbench.decision_support.recommendation==="support_approval"?"approve":workbench.decision_support.recommendation==="support_denial"?"deny":workbench.decision_support.recommendation==="pending_documents"?"request_information":null;
  const needsDisagreement=Boolean(selectedExpectedAI&&selectedExpectedAI!==decision);
  const mmRefs=useMemo(()=>({finding_refs:mm?.agent_findings.map(x=>x.finding_id)||[],annotation_refs:mm?.annotations.map(x=>x.annotation_id)||[],inconsistency_refs:mm?.inconsistencies.map(x=>x.inconsistency_id)||[],checkpoint_refs:mm?.checkpoint?[mm.checkpoint.checkpoint_id]:[]}),[mm]);
  const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError(null);try{await fn();await load()}catch(e){setError(e instanceof APIError?`Operation failed (${e.status}): ${e.message}`:e instanceof Error?e.message:"Operation failed")}finally{setBusy(false)}};
  const save=(e:FormEvent)=>{e.preventDefault();if(!lockToken){setError("Acquire the exclusive reviewer lease before authoring a decision packet.");return}void run(()=>reviewerApi.saveDecisionPacket(claimId,lockToken,{decision,rationale,reason_codes:[reason],evidence_snapshot_ids:workbench.evidence.map(e=>e.evidence_id),...mmRefs,approved_amount:decision==="partial_approve"?approvedAmount:undefined,partial_line_decisions:[],ai_disagreement_reason:needsDisagreement?disagreement:undefined,escalation_queue:decision==="escalate"?escalationQueue:undefined,expected_claim_status_version:workbench.claim.status_version,expected_packet_version:packet?.packet_version}))};
  if(!state)return <section className="card p-5"><div className="panel-title">Governed claim closure</div><div className="mt-4 text-sm text-slate-400">{error||"Loading governed decision state…"}</div></section>;
  const isPrimary=Boolean(packet&&session?.user_id===packet.primary_reviewer_user_id); const isSecond=Boolean(packet&&session?.user_id!==packet.primary_reviewer_user_id);
  return <div className="space-y-5">
    {error&&<div className="rounded-xl border border-rose-500/30 bg-rose-950/30 p-3 text-sm text-rose-200"><AlertTriangle className="inline h-4 w-4 mr-2"/>{error}</div>}
    <section className="card p-5 border-teal-400/20"><div className="flex flex-col lg:flex-row lg:items-start justify-between gap-4"><div><div className="panel-title">Human authority boundary</div><h3 className="text-xl font-bold mt-1">Governed multimodal claim resolution</h3><p className="text-sm text-slate-400 mt-2 max-w-3xl">AI agents, LangGraph, RAG and MCP may contribute evidence and advisory findings. They cannot approve, deny, partially approve, financially execute, or close this claim.</p></div><ShieldCheck className="h-8 w-8 text-teal-300"/></div><div className="grid md:grid-cols-3 gap-3 mt-5"><Mini label="Claim version" value={`v${state.claim.status_version}`}/><Mini label="Packet version" value={packet?`v${packet.packet_version}`:"Not created"}/><Mini label="Decision state" value={packet?pretty(packet.status):"Draft not started"}/></div></section>

    <div className="grid xl:grid-cols-[1.25fr_.75fr] gap-5"><section className="card p-5"><div className="flex items-center gap-2"><FileLock2 className="h-5 w-5 text-sky-300"/><div className="panel-title">Reviewer decision packet</div></div><form className="mt-5 space-y-4" onSubmit={save}><label className="block"><span className="text-sm font-semibold">Human decision</span><select className="input mt-2" value={decision} onChange={e=>setDecision(e.target.value)} disabled={Boolean(packet&&packet.status!=="draft"&&packet.status!=="rejected_second_review")}><option value="approve">Approve</option><option value="deny">Deny</option><option value="partial_approve">Partial approve</option><option value="request_information">Request information</option><option value="escalate">Escalate</option></select></label><label className="block"><span className="text-sm font-semibold">Mandatory reason code</span><select className="input mt-2" value={reason} onChange={e=>setReason(e.target.value)}>{reasonCodes.map(r=><option key={r} value={r}>{pretty(r)}</option>)}</select></label><label className="block"><span className="text-sm font-semibold">Evidence-backed human rationale</span><textarea className="input mt-2 min-h-32" value={rationale} onChange={e=>setRationale(e.target.value)} placeholder="Document why the bound evidence supports this human decision." required/></label>{decision==="partial_approve"&&<label className="block"><span className="text-sm font-semibold">Approved amount</span><input className="input mt-2" type="number" min="0" step="0.01" value={approvedAmount} onChange={e=>setApprovedAmount(e.target.value)} required/></label>}{needsDisagreement&&<label className="block rounded-xl border border-amber-500/30 bg-amber-950/15 p-4"><span className="text-sm font-semibold text-amber-200">AI-vs-human disagreement reason</span><div className="text-xs text-slate-400 mt-1">Advisory AI suggests {pretty(selectedExpectedAI||"")}; the human reviewer remains authoritative.</div><textarea className="input mt-3 min-h-24" value={disagreement} onChange={e=>setDisagreement(e.target.value)} required/></label>}{decision==="escalate"&&<label className="block"><span className="text-sm font-semibold">Escalation route</span><input className="input mt-2" value={escalationQueue} onChange={e=>setEscalationQueue(e.target.value)} required/></label>}<div className="rounded-xl border border-[#233b55] bg-[#091727] p-3 text-xs text-slate-400">Packet binds {workbench.evidence.length} evidence artifact(s), {mmRefs.finding_refs.length} multimodal finding(s), {mmRefs.annotation_refs.length} human annotation(s), and {mmRefs.inconsistency_refs.length} cross-modal inconsistency record(s).</div><button disabled={busy||!lockToken||rationale.trim().length<10||(needsDisagreement&&disagreement.trim().length<10)} className="btn"><FileLock2 className="h-4 w-4"/>{packet?"Create next packet version":"Create decision packet"}</button></form></section>

    <section className="card p-5"><div className="flex items-center gap-2"><Scale className="h-5 w-5 text-amber-300"/><div className="panel-title">Evidence completeness & blockers</div></div>{!packet?<Empty text="Create a packet to run closure validation."/>:<div className="mt-4 space-y-3"><Mini label="Snapshot SHA-256" value={`${packet.evidence_snapshot_sha256.slice(0,12)}…`}/><Mini label="AI recommendation" value={packet.ai_recommendation?pretty(packet.ai_recommendation):"none"}/><Mini label="Dual control" value={packet.dual_control_required?"required":"not required yet"}/><div><div className="text-xs uppercase text-slate-500">Current blockers</div><div className="flex flex-wrap gap-2 mt-2">{(validation?.blockers||packet.blocker_codes).length===0?<span className="badge badge-low">none detected</span>:(validation?.blockers||packet.blocker_codes).map(x=><span key={x} className="badge badge-critical">{pretty(x)}</span>)}</div></div>{validation&&<div className="text-xs text-slate-400 space-y-1"><div>Graph conflicts: {String(validation.details.material_graph_conflicts??0)}</div><div>Unresolved multimodal conflicts: {String(validation.details.unresolved_multimodal_conflicts??0)}</div><div>Missing modalities: {(validation.details.missing_modalities||[]).join(", ")||"none"}</div><div>Waiting durable checkpoints: {String(validation.details.waiting_checkpoints??0)}</div></div>}{packet.status==="draft"&&<button disabled={busy||!lockToken||!isPrimary} className="btn btn-primary w-full" onClick={()=>void run(()=>reviewerApi.validateDecisionPacket(claimId,packet.packet_id,lockToken!,packet.packet_version))}><LockKeyhole className="h-4 w-4"/>Validate & lock packet</button>}</div>}</section></div>

    {packet?.status==="pending_second_review"&&<section className="card p-5 border-amber-400/25"><div className="flex items-center gap-2"><UserCheck className="h-5 w-5 text-amber-300"/><div><div className="panel-title">Dual-control second review</div><h3 className="font-bold mt-1">Independent reviewer approval required</h3></div></div><p className="text-sm text-slate-400 mt-3">The primary reviewer cannot self-approve this packet. A different authenticated claims reviewer must verify the locked payload hash and record a second-review rationale.</p>{isSecond?<div className="mt-4 space-y-3"><textarea className="input min-h-24" value={secondRationale} onChange={e=>setSecondRationale(e.target.value)} placeholder="Independent review rationale"/><div className="flex gap-2"><button className="btn btn-primary" disabled={busy||secondRationale.trim().length<10} onClick={()=>void run(()=>reviewerApi.secondReviewDecisionPacket(claimId,packet.packet_id,{action:"approve",rationale:secondRationale,expected_packet_version:packet.packet_version}))}><CheckCircle2 className="h-4 w-4"/>Approve second review</button><button className="btn" disabled={busy||secondRationale.trim().length<10} onClick={()=>void run(()=>reviewerApi.secondReviewDecisionPacket(claimId,packet.packet_id,{action:"request_changes",rationale:secondRationale,expected_packet_version:packet.packet_version}))}><GitCompareArrows className="h-4 w-4"/>Request changes</button></div></div>:<div className="mt-4 badge badge-high">Signed in as primary reviewer — second review must be performed by another reviewer.</div>}</section>}

    {packet?.status==="ready_to_close"&&<section className="card p-5 border-emerald-400/25"><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-emerald-300"/><div><div className="panel-title">Governed closure</div><h3 className="font-bold mt-1">Packet validated and ready for human execution</h3></div></div><div className="grid md:grid-cols-3 gap-3 mt-4"><Mini label="Locked payload" value={`${packet.locked_payload_sha256?.slice(0,12)}…`}/><Mini label="Primary reviewer" value={packet.primary_reviewer_user_id}/><Mini label="Second reviewer" value={packet.second_reviewer_user_id||"not required"}/></div><button className="btn btn-primary mt-4" disabled={busy||!lockToken||!isPrimary} onClick={()=>void run(()=>reviewerApi.closeDecisionPacket(claimId,packet.packet_id,lockToken!,{expected_packet_version:packet.packet_version,expected_claim_status_version:state.claim.status_version}))}><Send className="h-4 w-4"/>Execute human governed closure</button><div className="text-xs text-slate-500 mt-3">This persists the authorized human decision and claim lifecycle transition only. It does not execute payment or any automated financial transaction.</div></section>}

    {(packet?.status==="closed"||packet?.status==="escalated")&&<section className="card p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-teal-300"/><div className="panel-title">Decision provenance & post-decision delivery</div></div><div className="grid md:grid-cols-4 gap-3 mt-4"><Mini label="Decision" value={pretty(packet.decision)}/><Mini label="Decision ID" value={packet.decision_id||"—"}/><Mini label="Closed" value={fmt(packet.closed_at)}/><Mini label="Audit events" value={String(state.audit_chain.length)}/></div><div className="mt-4 space-y-2">{state.notifications.map(n=><div key={n.notification_id} className="rounded-xl border border-[#233b55] p-3 flex justify-between gap-3"><span className="text-sm">{pretty(n.audience)}</span><span className="badge">{pretty(n.status)}</span></div>)}</div></section>}

    <section className="card p-5"><div className="panel-title">Immutable adjudication audit chain</div><div className="mt-4 space-y-3">{state.audit_chain.length===0?<Empty text="No governed adjudication events yet."/>:state.audit_chain.map(a=><div key={a.audit_event_id} className="rounded-xl border border-[#233b55] p-3"><div className="flex justify-between gap-3"><span className="font-semibold text-sm">#{a.sequence} · {pretty(a.event_type)}</span><span className="text-xs text-slate-500">{fmt(a.occurred_at)}</span></div><div className="text-[11px] mono text-slate-500 mt-2">{a.event_sha256}</div></div>)}</div></section>
  </div>;
}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#091727] border border-[#1f3852] p-3"><div className="text-[10px] uppercase tracking-wider text-slate-500">{label}</div><div className="font-semibold text-sm mt-1 break-all">{value}</div></div>}
function Empty({text}:{text:string}){return <div className="mt-4 rounded-xl border border-dashed border-[#31506f] p-4 text-sm text-slate-500">{text}</div>}
