"use client";
import { FormEvent, MutableRefObject, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, AudioLines, Boxes, Braces, FileImage, FileText, Film, Focus, GitCompareArrows, Highlighter, Link2, MessageSquarePlus, RefreshCw, ScanSearch, ShieldCheck } from "lucide-react";
import { APIError, reviewerApi } from "@/lib/api";
import { useEventStream } from "@/lib/hooks/use-event-stream";
import type { MultimodalReview } from "@/lib/schemas";

type MMItem=MultimodalReview["items"][number];
const fmt=(v?:string|null)=>v?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
const pct=(n:number)=>`${Math.round(n*100)}%`;
const pretty=(s:string)=>s.replaceAll("_"," ");
const sev=(s:string)=>s.includes("critical")||s.includes("material")?"badge badge-critical":s.includes("high")||s.includes("warning")?"badge badge-high":"badge badge-normal";
const anchorText=(c:Record<string,unknown>)=>[
  typeof c.page_number==="number"?`page ${c.page_number}`:null,
  Array.isArray(c.bbox)?`bbox [${c.bbox.join(", ")}]`:null,
  typeof c.start_ms==="number"?`${(c.start_ms/1000).toFixed(1)}s${typeof c.end_ms==="number"?`–${(c.end_ms/1000).toFixed(1)}s`:""}`:null,
  typeof c.frame_index==="number"?`frame ${c.frame_index}`:null,
  c.fhir_resource_type?`${c.fhir_resource_type}/${c.fhir_logical_id||"?"} v${c.fhir_version_id||"?"}`:null,
].filter(Boolean).join(" · ")||"source-level citation";

export function MultimodalInvestigation({claimId,lockToken}:{claimId:string;lockToken:string|null}){
  const [data,setData]=useState<MultimodalReview|null>(null); const [selected,setSelected]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{try{setError(null);const d=await reviewerApi.multimodalReview(claimId);setData(d);setSelected(cur=>cur&&d.items.some(i=>i.item_id===cur)?cur:d.items[0]?.item_id||null);}catch(e){setError(e instanceof Error?e.message:"Multimodal investigation unavailable");}finally{setLoading(false)}},[claimId]);
  useEffect(()=>{void load()},[load]);
  const {state}=useEventStream(`/api/reviewer/claims/${encodeURIComponent(claimId)}/events`,()=>void load());
  const item=useMemo(()=>data?.items.find(i=>i.item_id===selected)||null,[data,selected]);
  const missing=useMemo(()=>{if(!data?.latest_pack)return[];const have=new Set(data.latest_pack.modalities);return Array.from(new Set(data.investigations.flatMap(x=>x.required_modalities))).filter(x=>!have.has(x));},[data]);
  if(loading&&!data)return <div className="card p-6 text-slate-400">Loading multimodal investigation…</div>;
  if(!data)return <div className="card p-6"><div className="font-semibold text-rose-200">Multimodal investigation unavailable</div><div className="muted mt-2">{error}</div></div>;
  return <div className="space-y-5">
    <div className="grid md:grid-cols-2 xl:grid-cols-5 gap-3">
      <MMMetric label="Evidence pack" value={data.latest_pack?.answerability?pretty(data.latest_pack.answerability):"None"} detail={data.latest_pack?`${data.latest_pack.modalities.length} modalities`:`No multimodal pack`} />
      <MMMetric label="Modality coverage" value={data.latest_pack?pct(data.latest_pack.modality_coverage):"—"} detail={`${data.items.length} selected evidence items`} />
      <MMMetric label="Cross-modal conflicts" value={String(data.inconsistencies.length)} detail="Persisted inconsistency signals" warn={data.inconsistencies.length>0}/>
      <MMMetric label="Agent investigations" value={String(data.investigations.length)} detail={`${data.investigations.filter(i=>i.human_review_required).length} require review`} warn={data.investigations.some(i=>i.human_review_required)}/>
      <MMMetric label="Annotations" value={String(data.annotations.length)} detail={data.traceability.final_decision_human_only?"Final decision remains human-only":"Governance warning"}/>
    </div>

    {(missing.length>0||data.checkpoint)&&<div className="grid lg:grid-cols-2 gap-4">
      {missing.length>0&&<section className="rounded-2xl border border-amber-500/30 bg-amber-950/15 p-4"><div className="flex gap-2 items-center font-semibold text-amber-200"><AlertTriangle className="h-5 w-5"/>Missing required modality</div><div className="mt-2 text-sm text-slate-300">The current multimodal evidence pack is missing required evidence: <strong>{missing.map(pretty).join(", ")}</strong>. This is a deterministic human-review condition.</div></section>}
      {data.checkpoint&&<section className="rounded-2xl border border-sky-500/25 bg-sky-950/15 p-4"><div className="flex items-center justify-between gap-3"><div><div className="text-xs uppercase tracking-wider text-sky-300">Durable checkpoint</div><div className="font-semibold mt-1">{pretty(data.checkpoint.reason)}</div></div><span className={sev(data.checkpoint.status)}>{data.checkpoint.status}</span></div><div className="text-xs text-slate-400 mt-2 mono">{data.checkpoint.checkpoint_id}</div><div className="text-xs text-slate-500 mt-1">Created {fmt(data.checkpoint.created_at)}</div></section>}
    </div>}

    <div className="grid 2xl:grid-cols-[.72fr_1.45fr_.83fr] gap-5 items-start">
      <section className="card p-4 2xl:sticky 2xl:top-5"><div className="flex items-center justify-between"><div className="panel-title">Cross-modal evidence</div><span className={`badge ${state==="open"?"badge-low":"badge-high"}`}>{state==="open"?"live":"reconnecting"}</span></div><div className="mt-4 max-h-[760px] overflow-auto space-y-2 pr-1 scrollbar">{data.items.length===0?<Empty text="No multimodal evidence items in the latest pack."/>:data.items.map(i=><button key={i.item_id} onClick={()=>setSelected(i.item_id)} className={`w-full text-left rounded-xl border p-3 transition ${selected===i.item_id?"border-teal-300/60 bg-teal-950/20":"border-[#233b55] hover:border-[#31506f]"}`}><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2">{icon(i.modality)}<span className="font-semibold text-sm">{pretty(i.modality)}</span></div><span className="text-xs mono text-slate-500">#{i.rank}</span></div><div className="text-xs text-slate-400 mt-2 line-clamp-2">{anchorText(i.citation)}</div><div className="flex gap-2 mt-2"><span className="badge">{pretty(i.domain)}</span><span className="badge">{pct(i.confidence)}</span></div></button>)}</div></section>
      <section className="space-y-5">{item?<EvidenceViewer claimId={claimId} item={item}/>:<div className="card p-8"><Empty text="Select an evidence item to inspect its source and citation."/></div>}<FHIRCompare data={data} onSelect={setSelected}/><Inconsistencies data={data} onSelect={setSelected} claimId={claimId}/><AgentTrace data={data} onSelect={setSelected}/></section>
      <section className="space-y-5"><Provenance data={data}/><AnnotationPanel data={data} claimId={claimId} lockToken={lockToken} selected={item} reload={load}/></section>
    </div>
  </div>;
}

function EvidenceViewer({claimId,item}:{claimId:string;item:MMItem}){
  const mediaRef=useRef<HTMLMediaElement|null>(null);
  const c=item.citation as Record<string,unknown>; const start=typeof c.start_ms==="number"?c.start_ms/1000:0;
  const seek=()=>{const el=mediaRef.current;if(el){el.currentTime=start;void el.play().catch(()=>{})}};
  const contentUrl=item.evidence_id?`/api/reviewer/claims/${encodeURIComponent(claimId)}/evidence/${encodeURIComponent(item.evidence_id)}/content`:"";
  const bbox=Array.isArray(c.bbox)?c.bbox.join(","):"";
  const pdfPreviewUrl=item.evidence_id?`/api/reviewer/claims/${encodeURIComponent(claimId)}/review/evidence/${encodeURIComponent(item.evidence_id)}/page-preview?page_number=${Number(c.page_number||1)}${bbox?`&bbox=${encodeURIComponent(bbox)}`:""}`:"";
  return <section className="card overflow-hidden"><div className="p-5 border-b border-[#233b55]"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="panel-title">Evidence visualization</div><h3 className="font-bold text-lg mt-1">{pretty(item.modality)} · {item.evidence_key}</h3><div className="text-sm text-slate-400 mt-1">{anchorText(c)}</div></div><div className="flex gap-2"><span className="badge">authority {item.authority_rank}</span><span className="badge">confidence {pct(item.confidence)}</span></div></div></div>
    <div className="p-5 grid lg:grid-cols-[1.4fr_.6fr] gap-5 min-h-[360px]"><div className="rounded-xl border border-[#233b55] bg-black/20 overflow-hidden flex items-center justify-center min-h-[320px]">{!item.evidence_id?<FHIRViewer item={item}/>:renderMedia(item.media_type||"application/octet-stream",contentUrl,c,mediaRef,seek,pdfPreviewUrl)}</div><div className="space-y-4"><div><div className="panel-title">Citation anchor</div><pre className="mt-2 text-xs rounded-xl bg-[#07111f] border border-[#233b55] p-3 overflow-auto whitespace-pre-wrap">{JSON.stringify(c,null,2)}</pre></div>{Array.isArray(c.bbox)&&<BBoxMap bbox={c.bbox} metadata={item.metadata}/>}<div><div className="panel-title">Source identity</div><div className="mt-2 text-xs space-y-1 text-slate-400"><div><strong className="text-slate-300">Source:</strong> {item.source_id}</div><div><strong className="text-slate-300">Version:</strong> {item.source_version}</div><div className="break-all"><strong className="text-slate-300">SHA-256:</strong> {item.content_sha256}</div></div></div>{item.display_text&&<div><div className="panel-title">Extracted / transcript evidence</div><div className="mt-2 rounded-xl border border-[#233b55] bg-[#07111f] p-3 text-sm text-slate-300 whitespace-pre-wrap max-h-52 overflow-auto">{item.display_text}</div></div>}{item.modality==="table"&&item.structured_data&&Object.keys(item.structured_data).length>0&&<div><div className="panel-title">Invoice / table structure</div><pre className="mt-2 text-xs rounded-xl bg-[#07111f] border border-[#233b55] p-3 overflow-auto whitespace-pre-wrap max-h-52">{JSON.stringify(item.structured_data,null,2)}</pre></div>}</div></div>
  </section>;
}

function renderMedia(media:string,url:string,c:Record<string,unknown>,ref:MutableRefObject<HTMLMediaElement|null>,seek:()=>void,pdfPreviewUrl:string){
  if(media.startsWith("image/"))return <img src={url} alt="Claim evidence preview" className="max-h-[640px] max-w-full object-contain"/>;
  if(media==="application/pdf")return <img src={pdfPreviewUrl} alt={`PDF page ${Number(c.page_number||1)} with cited bounding box highlighted`} className="max-h-[720px] max-w-full object-contain"/>;
  if(media.startsWith("audio/"))return <div className="w-full p-6"><audio ref={x=>{ref.current=x}} controls preload="metadata" className="w-full" src={url}/><button onClick={seek} className="btn mt-4"><Focus className="h-4 w-4"/>Jump to cited timecode</button></div>;
  if(media.startsWith("video/"))return <div className="w-full p-4"><video ref={x=>{ref.current=x}} controls preload="metadata" className="w-full max-h-[560px] rounded-lg" src={url}/><button onClick={seek} className="btn mt-3"><Focus className="h-4 w-4"/>Jump to cited timecode/frame</button></div>;
  return <div className="p-6 text-sm text-slate-400">Browser preview is unavailable for {media}. Citation and provenance remain available.</div>;
}
function FHIRViewer({item}:{item:MMItem}){return <div className="w-full h-full p-5"><div className="flex items-center gap-2 text-sky-200 font-semibold"><Braces className="h-5 w-5"/>FHIR versioned evidence</div><pre className="mt-4 text-xs overflow-auto whitespace-pre-wrap rounded-xl border border-[#233b55] bg-[#07111f] p-4">{JSON.stringify(item.fhir_resource||{citation:item.citation,metadata:item.metadata,source_id:item.source_id,source_version:item.source_version},null,2)}</pre></div>}
function BBoxMap({bbox,metadata}:{bbox:number[];metadata:Record<string,unknown>}){const [x0,y0,x1,y1]=bbox.map(Number);const pw=Number(metadata.page_width||metadata.width||Math.max(x1,1));const ph=Number(metadata.page_height||metadata.height||Math.max(y1,1));const norm=(v:number,total:number)=>Math.max(0,Math.min(100,(v/Math.max(total,1))*100));return <div><div className="panel-title">Page / image bbox highlight</div><div className="relative mt-2 aspect-[4/5] rounded-xl border border-[#31506f] bg-[#0a1727] overflow-hidden"><div className="absolute inset-3 border border-dashed border-slate-600 rounded"/><div aria-label="cited bounding box" className="absolute border-2 border-amber-300 bg-amber-300/15 shadow-[0_0_0_2px_rgba(251,191,36,.15)]" style={{left:`${norm(x0,pw)}%`,top:`${norm(y0,ph)}%`,width:`${Math.max(2,norm(x1-x0,pw))}%`,height:`${Math.max(2,norm(y1-y0,ph))}%`}}/></div><div className="text-[11px] text-slate-500 mt-1">Normalized citation overlay; original media remains read-only.</div></div>}

function Inconsistencies({data,onSelect,claimId}:{data:MultimodalReview;onSelect:(id:string)=>void;claimId:string}){const byId=new Map(data.items.map(x=>[x.item_id,x]));const first=data.inconsistencies[0];return <section className="card p-5"><div className="flex gap-2 items-center"><GitCompareArrows className="h-5 w-5 text-rose-300"/><div className="panel-title">Cross-modal inconsistencies</div></div>{first&&<div className="mt-4 grid md:grid-cols-2 gap-3"><MiniEvidencePreview claimId={claimId} item={byId.get(first.left_item_id)} label="Evidence A"/><MiniEvidencePreview claimId={claimId} item={byId.get(first.right_item_id)} label="Evidence B"/></div>}<div className="mt-4 space-y-3">{data.inconsistencies.length===0?<Empty text="No persisted cross-modal inconsistencies in the latest pack."/>:data.inconsistencies.map(x=><div key={x.inconsistency_id} className="rounded-xl border border-rose-500/20 bg-rose-950/10 p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-semibold">{pretty(x.code)}</div><div className="text-sm text-slate-400">Field: {pretty(x.field)} · confidence {pct(x.confidence)}</div></div><span className={sev(x.severity)}>{x.severity}</span></div><div className="grid md:grid-cols-2 gap-3 mt-3">{[x.left_item_id,x.right_item_id].map((id,idx)=>{const i=byId.get(id);return <button key={id} onClick={()=>onSelect(id)} className="text-left rounded-lg border border-[#233b55] p-3 hover:border-sky-400/40"><div className="text-[11px] uppercase text-slate-500">{idx===0?"Evidence A":"Evidence B"}</div><div className="font-semibold text-sm mt-1">{i?pretty(i.modality):id}</div><div className="text-xs text-slate-400 mt-1">{i?anchorText(i.citation):"Open evidence item"}</div></button>})}</div></div>)}</div></section>}

function AgentTrace({data,onSelect}:{data:MultimodalReview;onSelect:(id:string)=>void}){return <section className="card p-5"><div className="flex gap-2 items-center"><ScanSearch className="h-5 w-5 text-violet-300"/><div className="panel-title">Multimodal agent findings & citation drill-down</div></div><div className="mt-4 space-y-3">{data.agent_findings.length===0?<Empty text="No agent findings cite multimodal evidence yet."/>:data.agent_findings.map(f=><div key={f.finding_id} className="rounded-xl border border-[#233b55] p-4"><div className="flex justify-between gap-3"><div><div className="font-semibold">{pretty(f.agent_name)}</div><div className="text-xs text-slate-500 mt-1 mono">{f.finding_id}</div></div><div className="flex gap-2"><span className="badge">{pct(f.confidence)}</span>{f.requires_human_review&&<span className="badge badge-high">human review</span>}</div></div><div className="flex flex-wrap gap-2 mt-3">{f.multimodal_evidence.map((e)=><button key={e.item_id} onClick={()=>onSelect(e.item_id)} className="badge hover:border-teal-300"><Link2 className="h-3 w-3"/>{e.evidence_key} · {anchorText(e.citation||{})}</button>)}</div></div>)}</div></section>}

function MiniEvidencePreview({claimId,item,label}:{claimId:string;item:MMItem|undefined;label:string}){if(!item)return <div className="rounded-xl border border-[#233b55] p-4"><div className="text-xs text-slate-500">{label}</div><div className="text-sm mt-2">Evidence item unavailable.</div></div>;const c=item.citation as Record<string,unknown>;const media=item.media_type||"";const url=item.evidence_id?`/api/reviewer/claims/${encodeURIComponent(claimId)}/evidence/${encodeURIComponent(item.evidence_id)}/content`:"";const bbox=Array.isArray(c.bbox)?c.bbox.join(","):"";const page=item.evidence_id?`/api/reviewer/claims/${encodeURIComponent(claimId)}/review/evidence/${encodeURIComponent(item.evidence_id)}/page-preview?page_number=${Number(c.page_number||1)}${bbox?`&bbox=${encodeURIComponent(bbox)}`:""}`:"";return <div className="rounded-xl border border-[#233b55] overflow-hidden"><div className="px-3 py-2 border-b border-[#233b55] flex justify-between"><span className="text-xs font-semibold">{label} · {pretty(item.modality)}</span><span className="text-[10px] text-slate-500">{anchorText(c)}</span></div><div className="h-48 bg-black/20 flex items-center justify-center overflow-hidden">{media.startsWith("image/")?<img src={url} alt={`${label} evidence`} className="max-h-full max-w-full object-contain"/>:media==="application/pdf"?<img src={page} alt={`${label} PDF cited page`} className="max-h-full max-w-full object-contain"/>:item.fhir_resource?<pre className="text-[10px] p-3 overflow-auto max-h-full w-full whitespace-pre-wrap">{JSON.stringify(item.fhir_resource.canonical_resource||item.fhir_resource,null,2)}</pre>:<div className="text-xs text-slate-400 p-4">{item.display_text||anchorText(c)}</div>}</div></div>}

function FHIRCompare({data,onSelect}:{data:MultimodalReview;onSelect:(id:string)=>void}){const items=data.items.filter(i=>i.modality==="fhir").slice(0,2);if(items.length===0)return null;return <section className="card p-5"><div className="flex items-center gap-2"><Braces className="h-5 w-5 text-sky-300"/><div className="panel-title">FHIR resource/version comparison</div></div><div className={`mt-4 grid ${items.length>1?"md:grid-cols-2":"grid-cols-1"} gap-3`}>{items.map(i=><button key={i.item_id} onClick={()=>onSelect(i.item_id)} className="text-left rounded-xl border border-[#233b55] p-3 hover:border-sky-400/40"><div className="font-semibold text-sm">{String(i.citation.fhir_resource_type||"FHIR")} / {String(i.citation.fhir_logical_id||i.source_id)}</div><div className="text-xs text-slate-400 mt-1">Version {String(i.citation.fhir_version_id||i.source_version)}</div><pre className="mt-3 text-[10px] whitespace-pre-wrap max-h-44 overflow-auto rounded-lg bg-[#07111f] p-2">{JSON.stringify(i.fhir_resource?.canonical_resource||i.fhir_resource||i.metadata,null,2)}</pre></button>)}</div></section>}

function Provenance({data}:{data:MultimodalReview}){return <section className="card p-5"><div className="flex items-center gap-2"><Boxes className="h-5 w-5 text-sky-300"/><div className="panel-title">Investigation provenance</div></div>{data.latest_pack?<div className="mt-4"><div className="font-semibold">Pack {data.latest_pack.pack_id}</div><div className="text-xs text-slate-500 mt-1 break-all">SHA-256 {data.latest_pack.pack_sha256}</div><div className="grid grid-cols-2 gap-2 mt-3"><Small label="Confidence" value={pct(data.latest_pack.confidence)}/><Small label="Citations" value={pct(data.latest_pack.citation_coverage)}/></div></div>:<div className="mt-4"><Empty text="No multimodal evidence pack."/></div>}<div className="mt-5 space-y-3">{data.investigations.map(x=><div key={x.investigation_id} className="rounded-xl border border-[#233b55] p-3"><div className="flex justify-between gap-2"><span className="font-semibold text-sm">{pretty(x.agent_name)}</span><span className={x.human_review_required?"badge badge-high":"badge badge-low"}>{x.answerability}</span></div><div className="text-xs text-slate-500 mt-2">Required: {x.required_modalities.map(pretty).join(", ")||"none"}</div>{x.escalation_reasons.length>0&&<div className="flex flex-wrap gap-1 mt-2">{x.escalation_reasons.map(r=><span className="badge badge-high" key={r}>{pretty(r)}</span>)}</div>}</div>)}</div></section>}

function AnnotationPanel({data,claimId,lockToken,selected,reload}:{data:MultimodalReview;claimId:string;lockToken:string|null;selected:MMItem|null;reload:()=>Promise<void>}){
  const options=[...(selected?[{type:"multimodal_item",id:selected.item_id,label:`Evidence ${selected.evidence_key}`,anchor:selected.citation}]:[]),...data.inconsistencies.map(x=>({type:"inconsistency",id:x.inconsistency_id,label:`Conflict ${pretty(x.code)}`,anchor:{left_item_id:x.left_item_id,right_item_id:x.right_item_id}})),...data.agent_findings.map(x=>({type:"agent_finding",id:x.finding_id,label:`Finding ${pretty(x.agent_name)}`,anchor:{evidence_keys:x.evidence_keys}})),...(data.checkpoint?[{type:"checkpoint",id:data.checkpoint.checkpoint_id,label:`Checkpoint ${pretty(data.checkpoint.reason)}`,anchor:data.checkpoint.metadata}]:[])];
  const [body,setBody]=useState("");const [kind,setKind]=useState("note");const [targetKey,setTargetKey]=useState("");const [busy,setBusy]=useState(false);const [err,setErr]=useState<string|null>(null);
  useEffect(()=>{if(selected)setTargetKey(`multimodal_item:${selected.item_id}`)},[selected?.item_id]);
  const chosen=options.find(o=>`${o.type}:${o.id}`===targetKey)||options[0];
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!chosen||!lockToken)return;setBusy(true);setErr(null);try{await reviewerApi.addMultimodalAnnotation(claimId,lockToken,{target_type:chosen.type,target_id:chosen.id,annotation_kind:kind,anchor:chosen.anchor as Record<string,unknown>,body,tags:[]});setBody("");await reload()}catch(x){setErr(x instanceof APIError?`Annotation failed (${x.status}): ${x.message}`:x instanceof Error?x.message:"Annotation failed")}finally{setBusy(false)}};
  return <section className="card p-5"><div className="flex items-center gap-2"><MessageSquarePlus className="h-5 w-5 text-teal-300"/><div className="panel-title">Reviewer annotations</div></div><form className="mt-4 space-y-3" onSubmit={submit}><select className="input" value={targetKey} onChange={e=>setTargetKey(e.target.value)}>{options.length===0?<option value="">No traceable targets</option>:options.map(o=><option value={`${o.type}:${o.id}`} key={`${o.type}:${o.id}`}>{o.label}</option>)}</select><select className="input" value={kind} onChange={e=>setKind(e.target.value)}><option value="note">Note</option><option value="highlight">Highlight</option><option value="question">Question</option><option value="resolution">Resolution</option></select><textarea className="input min-h-24" value={body} onChange={e=>setBody(e.target.value)} placeholder={chosen?`Annotate ${chosen.label}`:"Select a traceable target"} disabled={!chosen} required/><button disabled={busy||!lockToken||!chosen||!body} className="btn"><Highlighter className="h-4 w-4"/>Add immutable annotation</button>{!lockToken&&<div className="text-xs text-amber-300">Acquire the exclusive review lease before annotating evidence or investigation findings.</div>}{err&&<div className="text-xs text-rose-300">{err}</div>}</form><div className="mt-5 space-y-2 max-h-72 overflow-auto">{data.annotations.length===0?<Empty text="No multimodal reviewer annotations."/>:data.annotations.slice().reverse().map(a=><div key={a.annotation_id} className="rounded-xl border border-[#233b55] p-3"><div className="flex justify-between gap-2"><span className="font-semibold text-sm">{pretty(a.annotation_kind)}</span><span className="text-[11px] text-slate-500">{fmt(a.created_at)}</span></div><div className="text-sm text-slate-300 mt-2 whitespace-pre-wrap">{a.body}</div><div className="text-[11px] mono text-slate-500 mt-2">{a.target_type}:{a.target_id}</div></div>)}</div></section>
}

function MMMetric({label,value,detail,warn=false}:{label:string;value:string;detail:string;warn?:boolean}){return <div className="card p-4"><div className="panel-title">{label}</div><div className={`metric mt-2 ${warn?"text-amber-200":""}`}>{value}</div><div className="text-xs text-slate-500 mt-1">{detail}</div></div>}
function Small({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-[#091727] border border-[#1f3852] p-2"><div className="text-[10px] uppercase text-slate-500">{label}</div><div className="font-bold text-sm mt-1">{value}</div></div>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-[#31506f] p-4 text-sm text-slate-500">{text}</div>}
function icon(m:string){if(m==="image")return <FileImage className="h-4 w-4 text-emerald-300"/>;if(m==="audio")return <AudioLines className="h-4 w-4 text-fuchsia-300"/>;if(m==="video")return <Film className="h-4 w-4 text-rose-300"/>;if(m==="fhir")return <Braces className="h-4 w-4 text-sky-300"/>;return <FileText className="h-4 w-4 text-amber-200"/>}
