"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AlertTriangle, BellRing, CheckCircle2, Clock3, GitCommitHorizontal, MailCheck, RefreshCw, RotateCcw, Scale, ShieldCheck, UserRoundCheck } from "lucide-react";
import { APIError, reviewerApi } from "@/lib/api";
import type { PostDecision, ReviewerSession } from "@/lib/schemas";

const pretty=(v:string)=>v.replaceAll("_"," ");
const fmt=(v?:string|null)=>v?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";

export function PostDecisionOperations({claimId}:{claimId:string}){
  const [data,setData]=useState<PostDecision|null>(null); const [session,setSession]=useState<ReviewerSession|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setError(null);const [d,s]=await Promise.all([reviewerApi.postDecision(claimId),reviewerApi.session()]);setData(d);setSession(s)}catch(e){setError(e instanceof Error?e.message:"Post-decision operations unavailable")}},[claimId]);
  useEffect(()=>{void load()},[load]);
  const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError(null);try{await fn();await load()}catch(e){setError(e instanceof APIError?`Operation failed (${e.status}): ${e.message}`:e instanceof Error?e.message:"Operation failed")}finally{setBusy(false)}};
  if(!data)return <section className="card p-5"><div className="panel-title">Post-decision operations</div><div className="mt-4 text-sm text-slate-400">{error||"Loading communications and appeals…"}</div></section>;
  return <div className="space-y-5">
    {error&&<div className="rounded-xl border border-rose-500/30 bg-rose-950/30 p-3 text-sm text-rose-200"><AlertTriangle className="inline h-4 w-4 mr-2"/>{error}</div>}
    <section className="card p-5 border-teal-400/20"><div className="flex items-start justify-between gap-4"><div><div className="panel-title">Post-decision human authority</div><h3 className="text-xl font-bold mt-1">Communications, appeals & reconsideration</h3><p className="text-sm text-slate-400 mt-2 max-w-4xl">AI may organize evidence, retrieve policy context, summarize, or help draft communication text. It cannot release a notice, reopen an appeal, affirm, modify, overturn, approve, deny, or financially adjudicate a claim.</p></div><ShieldCheck className="h-8 w-8 text-teal-300"/></div><div className="grid md:grid-cols-4 gap-3 mt-5"><Mini label="Notices" value={String(data.notices.length)}/><Mini label="Appeals" value={String(data.appeals.length)}/><Mini label="Open tasks" value={String(data.tasks.length)}/><Mini label="History versions" value={String(data.decision_history.length)}/></div></section>

    <div className="grid xl:grid-cols-[1fr_1fr] gap-5"><section className="card p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><MailCheck className="h-5 w-5 text-sky-300"/><div className="panel-title">Decision notices</div></div><button className="btn btn-ghost" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>Refresh</button></div><div className="mt-4 space-y-3">{data.notices.length===0?<Empty text="No decision notice has been generated."/>:data.notices.map(n=><div key={n.notice_id} className="rounded-xl border border-[#233b55] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-semibold">{n.resolution_id?"Appeal resolution notice":"Original decision notice"}</div><div className="text-xs mono text-slate-500 mt-1">{n.notice_id}</div><div className="text-xs text-slate-500 mt-1">Template {n.template_key} v{n.template_version} · audience {n.audience}</div></div><span className="badge">{pretty(n.status)}</span></div><div className="grid sm:grid-cols-2 gap-2 mt-3"><Mini label="Evidence snapshot" value={`${n.evidence_snapshot_sha256.slice(0,12)}…`}/><Mini label="Delivery" value={n.delivery_status?`${pretty(n.delivery_status)} · ${n.delivery_attempts} attempt(s)`:"not queued"}/></div>{n.status==="draft"&&<button disabled={busy} className="btn btn-primary mt-3" onClick={()=>void run(()=>reviewerApi.releaseDecisionNotice(claimId,n.notice_id))}><UserRoundCheck className="h-4 w-4"/>Human release notice</button>}</div>)}</div></section>

    <section className="card p-5"><div className="flex items-center gap-2"><Clock3 className="h-5 w-5 text-amber-300"/><div className="panel-title">Reviewer task queue & SLA</div></div><div className="mt-4 space-y-3">{data.tasks.length===0?<Empty text="No open post-decision tasks."/>:data.tasks.map(t=><div key={t.task_id} className={`rounded-xl border p-3 ${t.sla_breached?"border-rose-500/40 bg-rose-950/15":"border-[#233b55]"}`}><div className="flex items-start justify-between gap-3"><div><div className="font-semibold text-sm">{pretty(t.task_type)}</div><div className="text-xs text-slate-500 mt-1">Due {fmt(t.due_at)} · priority {t.priority}</div><div className="text-xs mono text-slate-500 mt-1">{t.appeal_id||t.notice_id||t.task_id}</div></div><span className={t.sla_breached?"badge badge-critical":"badge"}>{t.sla_breached?"SLA breached":"open"}</span></div></div>)}</div></section></div>

    <section className="card p-5"><div className="flex items-center gap-2"><Scale className="h-5 w-5 text-amber-300"/><div className="panel-title">Appeal & reconsideration cases</div></div><div className="mt-4 space-y-4">{data.appeals.length===0?<Empty text="No appeal has been filed for this claim."/>:data.appeals.map(a=><AppealCard key={a.appeal_id} claimId={claimId} appeal={a} currentUser={session?.user_id||""} busy={busy} run={run}/>)}</div></section>

    <div className="grid xl:grid-cols-[1.1fr_.9fr] gap-5"><section className="card p-5"><div className="flex items-center gap-2"><GitCommitHorizontal className="h-5 w-5 text-teal-300"/><div className="panel-title">Immutable decision history</div></div><div className="mt-4 space-y-3">{data.decision_history.length===0?<Empty text="Decision history is created after governed closure."/>:data.decision_history.map((h,i)=><div key={h.history_version_id} className="rounded-xl border border-[#233b55] p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-semibold">v{h.sequence} · {pretty(h.source_type)}</div><div className="text-sm text-slate-300 mt-1">Controlling outcome: <b>{pretty(h.decision)}</b></div><div className="text-xs text-slate-500 mt-1">Human reviewer {h.human_reviewer_user_id} · {fmt(h.effective_at)}</div></div><span className="badge">#{h.sequence}</span></div><div className="text-xs mono text-slate-500 mt-3">hash {h.version_sha256.slice(0,20)}…{i>0&&` · prev ${h.previous_version_sha256?.slice(0,12)}…`}</div></div>)}</div></section>
    <section className="card p-5"><div className="flex items-center gap-2"><BellRing className="h-5 w-5 text-sky-300"/><div className="panel-title">Correspondence provenance</div></div><div className="mt-4 space-y-3">{data.correspondence.length===0?<Empty text="No external correspondence recorded."/>:data.correspondence.slice().reverse().map(c=><div key={c.correspondence_id} className="rounded-xl border border-[#233b55] p-3"><div className="flex justify-between gap-3"><div><div className="font-semibold text-sm">{pretty(c.direction)} · {c.channel}</div><div className="text-xs text-slate-500 mt-1">{c.audience} · {fmt(c.occurred_at)}</div></div><span className="badge">SHA bound</span></div><div className="text-xs mono text-slate-500 mt-2">{c.payload_sha256.slice(0,20)}…</div></div>)}</div></section></div>

    <section className="card p-5 border-teal-400/20"><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-teal-300"/><div className="panel-title">End-to-end traceability</div></div><div className="grid md:grid-cols-3 gap-3 mt-4"><Mini label="Trace nodes" value={String(data.traceability.nodes.length)}/><Mini label="Trace edges" value={String(data.traceability.edges.length)}/><Mini label="Final resolution" value={data.traceability.final_resolution_human_only?"human only":"invalid"}/></div><p className="text-sm text-slate-400 mt-4">Original evidence → locked original human decision → released notice → appeal → supplemental evidence → independent human reconsideration → immutable controlling-resolution history.</p></section>
  </div>;
}

function AppealCard({claimId,appeal,currentUser,busy,run}:{claimId:string;appeal:PostDecision["appeals"][number];currentUser:string;busy:boolean;run:(fn:()=>Promise<unknown>)=>Promise<void>}){
  const [reviewer,setReviewer]=useState("");const [assignmentReason,setAssignmentReason]=useState("");const [reopenReason,setReopenReason]=useState("");
  const mine=appeal.assigned_reviewer_user_id===currentUser;
  const assign=(e:FormEvent)=>{e.preventDefault();void run(()=>reviewerApi.assignAppeal(claimId,appeal.appeal_id,{reviewer_user_id:reviewer,assignment_reason:assignmentReason,expected_appeal_version:appeal.appeal_version}))};
  return <div className="rounded-xl border border-[#233b55] p-4"><div className="flex flex-col lg:flex-row lg:items-start justify-between gap-3"><div><div className="font-semibold">Appeal {appeal.appeal_id}</div><div className="text-xs text-slate-500 mt-1">Filed {fmt(appeal.submitted_at)} · deadline {fmt(appeal.appeal_due_at)} · version {appeal.appeal_version}</div><div className="flex flex-wrap gap-2 mt-2">{appeal.grounds.map(g=><span className="badge" key={g}>{pretty(g)}</span>)}<span className="badge">{appeal.supplemental_evidence.length} supplemental evidence</span></div></div><span className="badge">{pretty(appeal.status)}</span></div>
    <div className="mt-4 rounded-xl bg-[#091727] border border-[#1f3852] p-3 text-sm"><div className="text-xs uppercase text-slate-500">Independent reviewer</div><div className="font-semibold mt-1">{appeal.assigned_reviewer_user_id||"Not assigned"}</div></div>
    {!appeal.assigned_reviewer_user_id&&appeal.status!=="rejected_untimely"&&<form onSubmit={assign} className="mt-4 grid lg:grid-cols-[.7fr_1.3fr_auto] gap-2"><input className="input" placeholder="Independent reviewer user ID" value={reviewer} onChange={e=>setReviewer(e.target.value)} required/><input className="input" placeholder="Assignment reason" value={assignmentReason} onChange={e=>setAssignmentReason(e.target.value)} required minLength={10}/><button disabled={busy} className="btn"><UserRoundCheck className="h-4 w-4"/>Assign</button></form>}
    {mine&&["submitted","triage","late_pending_review","waiting_supplemental_evidence"].includes(appeal.status)&&<div className="mt-4 flex gap-2"><input className="input" placeholder="Reopening rationale" value={reopenReason} onChange={e=>setReopenReason(e.target.value)}/><button disabled={busy||reopenReason.trim().length<10} className="btn btn-primary" onClick={()=>void run(()=>reviewerApi.reopenAppeal(claimId,appeal.appeal_id,{expected_appeal_version:appeal.appeal_version,rationale:reopenReason}))}><RotateCcw className="h-4 w-4"/>Reopen for reconsideration</button></div>}
    {mine&&appeal.status==="in_review"&&<div className="mt-4 rounded-xl border border-teal-500/25 bg-teal-950/10 p-4"><div className="font-semibold text-teal-100">Governed final appeal resolution</div><p className="text-sm text-slate-400 mt-2">Final affirm/modify/overturn actions are completed in the evidence-bound Appeal workbench, where citation validation, contradiction blocking and dual control are enforced.</p><a className="btn btn-primary mt-3 inline-flex" href={`/review/appeals?claim_id=${encodeURIComponent(claimId)}&appeal_id=${encodeURIComponent(appeal.appeal_id)}`}><Scale className="h-4 w-4"/>Open governed appeal workbench</a></div>}
    {appeal.resolution&&<div className="mt-4 rounded-xl border border-teal-400/20 bg-teal-950/10 p-4"><div className="text-xs uppercase text-teal-300">Final reconsideration resolution</div><div className="font-bold mt-1">{pretty(appeal.resolution.outcome)} → {pretty(appeal.resolution.controlling_decision)}</div><div className="text-xs text-slate-500 mt-1">Human reviewer {appeal.resolution.reviewer_user_id} · {fmt(appeal.resolution.resolved_at)}</div></div>}
  </div>
}

function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#091727] border border-[#1f3852] p-3"><div className="text-[11px] uppercase tracking-wider text-slate-500">{label}</div><div className="font-bold mt-1 break-all">{value}</div></div>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-[#31506f] p-5 text-sm text-slate-500">{text}</div>}
