"""Security, privacy and compliance governance persistence.
Revision ID: 0021_security_privacy_devsecops
Revises: 0020_llmops_observability
"""
from alembic import op
import sqlalchemy as sa
revision="0021_security_privacy_devsecops"; down_revision="0020_llmops_observability"; branch_labels=None; depends_on=None
TABLES=("data_retention_policies","data_disposition_requests","audit_export_manifests","security_readiness_runs","encryption_key_references")
def rls(t):
    op.execute(f'ALTER TABLE "{t}" ENABLE ROW LEVEL SECURITY'); op.execute(f'ALTER TABLE "{t}" FORCE ROW LEVEL SECURITY'); op.execute(f'CREATE POLICY {t}_tenant_isolation ON "{t}" USING (tenant_id = current_setting(\'app.current_tenant_id\', true)) WITH CHECK (tenant_id = current_setting(\'app.current_tenant_id\', true))')
def upgrade():
    op.create_table("data_retention_policies",sa.Column("policy_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("policy_key",sa.String(120),nullable=False),sa.Column("version",sa.String(40),nullable=False),sa.Column("resource_type",sa.String(80),nullable=False),sa.Column("classification",sa.String(40),nullable=False),sa.Column("retention_days",sa.Integer(),nullable=False),sa.Column("disposition",sa.String(40),nullable=False),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("effective_from",sa.DateTime(timezone=True),nullable=False),sa.Column("effective_to",sa.DateTime(timezone=True)),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","policy_key","version",name="uq_retention_policy_version")); op.create_index("ix_retention_tenant_active","data_retention_policies",["tenant_id","active"])
    op.create_table("data_disposition_requests",sa.Column("request_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("policy_id",sa.String(128),sa.ForeignKey("data_retention_policies.policy_id",ondelete="RESTRICT"),nullable=False),sa.Column("resource_type",sa.String(80),nullable=False),sa.Column("resource_id",sa.String(160),nullable=False),sa.Column("classification",sa.String(40),nullable=False),sa.Column("requested_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("status",sa.String(30),nullable=False),sa.Column("dry_run",sa.Boolean(),nullable=False),sa.Column("idempotency_key",sa.String(160),nullable=False),sa.Column("reason",sa.Text(),nullable=False),sa.Column("executed_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_disposition_idem")); op.create_index("ix_disposition_tenant_status","data_disposition_requests",["tenant_id","status"])
    op.create_table("audit_export_manifests",sa.Column("export_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("requested_by",sa.String(128),nullable=False),sa.Column("from_time",sa.DateTime(timezone=True),nullable=False),sa.Column("to_time",sa.DateTime(timezone=True),nullable=False),sa.Column("record_count",sa.Integer(),nullable=False),sa.Column("root_sha256",sa.String(64),nullable=False),sa.Column("signature_hmac_sha256",sa.String(64),nullable=False),sa.Column("export_object_key",sa.String(512)),sa.Column("classification",sa.String(40),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False)); op.create_index("ix_audit_export_tenant_created","audit_export_manifests",["tenant_id","created_at"])
    op.create_table("security_readiness_runs",sa.Column("run_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("candidate_version",sa.String(160),nullable=False),sa.Column("decision",sa.String(20),nullable=False),sa.Column("critical_findings",sa.Integer(),nullable=False),sa.Column("high_findings",sa.Integer(),nullable=False),sa.Column("control_pass_rate",sa.String(20),nullable=False),sa.Column("report_sha256",sa.String(64),nullable=False),sa.Column("controls_version",sa.String(80),nullable=False),sa.Column("details",sa.JSON(),nullable=False),sa.Column("run_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False)); op.create_index("ix_security_readiness_tenant_created","security_readiness_runs",["tenant_id","created_at"])
    op.create_table("encryption_key_references",sa.Column("key_ref_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("provider",sa.String(40),nullable=False),sa.Column("purpose",sa.String(80),nullable=False),sa.Column("external_key_id",sa.String(512),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("activated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("rotate_after",sa.DateTime(timezone=True),nullable=False),sa.Column("retired_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","purpose","external_key_id",name="uq_keyref_external")); op.create_index("ix_keyref_tenant_status","encryption_key_references",["tenant_id","status"])
    for t in TABLES: rls(t)
    for t in ("audit_export_manifests","security_readiness_runs"): op.execute(f'CREATE TRIGGER {t}_immutable BEFORE UPDATE OR DELETE ON "{t}" FOR EACH ROW EXECUTE FUNCTION medclaimiq_reject_immutable_change()')
def downgrade():
    for t in reversed(TABLES): op.drop_table(t)
