"""governed evidence-bound final appeal resolution
Revision ID: 0034_appeal_resolution_governance
Revises: 0033_appeal_evidence_reconsideration
"""
from alembic import op
import sqlalchemy as sa
revision="0034_appeal_resolution_governance"; down_revision="0033_appeal_evidence_reconsideration"; branch_labels=None; depends_on=None

def _rls(table):
    op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY');op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY');op.execute(f'''CREATE POLICY {table}_tenant_isolation ON "{table}" USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))''')

def upgrade():
    op.create_table("appeal_decision_packets",
      sa.Column("packet_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("appeal_id",sa.String(128),sa.ForeignKey("appeal_cases.appeal_id",ondelete="CASCADE"),nullable=False),sa.Column("primary_reviewer_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("second_reviewer_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("snapshot_id",sa.String(128),sa.ForeignKey("appeal_evidence_snapshots.snapshot_id",ondelete="RESTRICT"),nullable=False),sa.Column("snapshot_sha256",sa.String(64),nullable=False),sa.Column("recommendation_run_id",sa.String(128),sa.ForeignKey("appeal_reconsideration_runs.reconsideration_run_id",ondelete="RESTRICT")),sa.Column("outcome",sa.String(30),nullable=False),sa.Column("controlling_decision",sa.String(40),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("reason_codes",sa.JSON(),nullable=False),sa.Column("citation_refs",sa.JSON(),nullable=False),sa.Column("resolved_comparison_refs",sa.JSON(),nullable=False),sa.Column("annotation_refs",sa.JSON(),nullable=False),sa.Column("checkpoint_refs",sa.JSON(),nullable=False),sa.Column("original_approved_amount",sa.Numeric(14,2),nullable=False),sa.Column("reconsidered_approved_amount",sa.Numeric(14,2),nullable=False),sa.Column("financial_delta",sa.Numeric(14,2),nullable=False),sa.Column("material_financial_change",sa.Boolean(),nullable=False),sa.Column("recommendation_disagreement",sa.Boolean(),nullable=False),sa.Column("recommendation_disagreement_reason",sa.Text()),sa.Column("completeness",sa.JSON(),nullable=False),sa.Column("blocker_codes",sa.JSON(),nullable=False),sa.Column("dual_control_required",sa.Boolean(),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("packet_version",sa.Integer(),nullable=False),sa.Column("expected_appeal_version",sa.Integer(),nullable=False),sa.Column("locked_payload_sha256",sa.String(64)),sa.Column("final_resolution_id",sa.String(128)),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("trace_id",sa.String(128)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("locked_at",sa.DateTime(timezone=True)),sa.Column("closed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_appeal_decision_packet_idempotency"),sa.UniqueConstraint("tenant_id","appeal_id","packet_version",name="uq_appeal_decision_packet_version"))
    op.create_index("ix_appeal_decision_packet","appeal_decision_packets",["tenant_id","appeal_id","created_at"])
    op.create_table("appeal_decision_second_reviews",sa.Column("second_review_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("appeal_id",sa.String(128),sa.ForeignKey("appeal_cases.appeal_id",ondelete="CASCADE"),nullable=False),sa.Column("packet_id",sa.String(128),sa.ForeignKey("appeal_decision_packets.packet_id",ondelete="CASCADE"),nullable=False),sa.Column("reviewer_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("action",sa.String(20),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("packet_version",sa.Integer(),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","packet_id","reviewer_user_id",name="uq_appeal_decision_second_review"))
    op.create_table("appeal_final_resolutions",sa.Column("resolution_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("appeal_id",sa.String(128),sa.ForeignKey("appeal_cases.appeal_id",ondelete="RESTRICT"),nullable=False),sa.Column("packet_id",sa.String(128),sa.ForeignKey("appeal_decision_packets.packet_id",ondelete="RESTRICT"),nullable=False),sa.Column("primary_reviewer_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("second_reviewer_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("outcome",sa.String(30),nullable=False),sa.Column("controlling_decision",sa.String(40),nullable=False),sa.Column("original_approved_amount",sa.Numeric(14,2),nullable=False),sa.Column("reconsidered_approved_amount",sa.Numeric(14,2),nullable=False),sa.Column("financial_delta",sa.Numeric(14,2),nullable=False),sa.Column("reconsideration_snapshot_sha256",sa.String(64),nullable=False),sa.Column("packet_locked_sha256",sa.String(64),nullable=False),sa.Column("provenance",sa.JSON(),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("supersedes_history_version_id",sa.String(128)),sa.Column("history_version_id",sa.String(128)),sa.Column("notice_id",sa.String(128)),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("trace_id",sa.String(128)),sa.Column("resolved_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","appeal_id",name="uq_appeal_final_resolution_once"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_appeal_final_resolution_idempotency"))
    op.create_table("appeal_resolution_audit_events",sa.Column("audit_event_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("appeal_id",sa.String(128),sa.ForeignKey("appeal_cases.appeal_id",ondelete="CASCADE"),nullable=False),sa.Column("packet_id",sa.String(128),sa.ForeignKey("appeal_decision_packets.packet_id",ondelete="SET NULL")),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(100),nullable=False),sa.Column("actor_type",sa.String(30),nullable=False),sa.Column("actor_id",sa.String(128),nullable=False),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("previous_event_sha256",sa.String(64)),sa.Column("event_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("trace_id",sa.String(128)),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","appeal_id","sequence",name="uq_appeal_resolution_audit_sequence"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_appeal_resolution_audit_idempotency"))
    for t in ("appeal_decision_packets","appeal_decision_second_reviews","appeal_final_resolutions","appeal_resolution_audit_events"):_rls(t)
    for t in ("appeal_decision_second_reviews","appeal_final_resolutions","appeal_resolution_audit_events"):
        op.execute(f'CREATE TRIGGER {t}_immutable BEFORE UPDATE OR DELETE ON "{t}" FOR EACH ROW EXECUTE FUNCTION medclaimiq_reject_immutable_change()')

def downgrade():
    for t in ("appeal_resolution_audit_events","appeal_final_resolutions","appeal_decision_second_reviews","appeal_decision_packets"):op.drop_table(t)
