"""Release 40: controlling-decision financial handoff and reconciliation.

Revision ID: 0035_financial_handoff_reconciliation
Revises: 0034_appeal_resolution_governance
"""
from alembic import op
import sqlalchemy as sa
revision="0035_financial_handoff_reconciliation"; down_revision="0034_appeal_resolution_governance"; branch_labels=None; depends_on=None
TABLES=[
("financial_authorization_packets",[
 sa.Column("packet_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("packet_version",sa.Integer(),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("controlling_source_type",sa.String(60),nullable=False),sa.Column("controlling_source_id",sa.String(128),nullable=False),sa.Column("decision_history_version_id",sa.String(128),sa.ForeignKey("decision_history_versions.history_version_id",ondelete="RESTRICT"),nullable=False),sa.Column("decision_history_sha256",sa.String(64),nullable=False),sa.Column("evidence_snapshot_sha256",sa.String(64),nullable=False),sa.Column("controlling_decision",sa.String(40),nullable=False),sa.Column("claim_total_amount",sa.Numeric(14,2),nullable=False),sa.Column("approved_amount",sa.Numeric(14,2),nullable=False),sa.Column("member_responsibility",sa.Numeric(14,2),nullable=False),sa.Column("payer_responsibility",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("line_reconciliation",sa.JSON(),nullable=False),sa.Column("prepared_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("authorized_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("authorization_rationale",sa.Text()),sa.Column("locked_payload_sha256",sa.String(64)),sa.Column("authorized_payload_sha256",sa.String(64)),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("trace_id",sa.String(128)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("locked_at",sa.DateTime(timezone=True)),sa.Column("authorized_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_fin_packet_idem")]),
("remittance_artifacts",[sa.Column("artifact_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("packet_id",sa.String(128),sa.ForeignKey("financial_authorization_packets.packet_id",ondelete="CASCADE"),nullable=False),sa.Column("artifact_type",sa.String(40),nullable=False),sa.Column("format_version",sa.String(40),nullable=False),sa.Column("content",sa.JSON(),nullable=False),sa.Column("content_sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","packet_id","artifact_type",name="uq_remit_packet_type")]),
("payment_holds",[sa.Column("hold_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("hold_type",sa.String(60),nullable=False),sa.Column("reason_code",sa.String(100),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("placed_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("released_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("released_at",sa.DateTime(timezone=True))]),
("payment_intents",[sa.Column("payment_intent_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("packet_id",sa.String(128),sa.ForeignKey("financial_authorization_packets.packet_id",ondelete="RESTRICT"),nullable=False),sa.Column("amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("payee_ref",sa.String(160),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("payment_fingerprint",sa.String(64),nullable=False),sa.Column("external_instruction_id",sa.String(180)),sa.Column("adapter_name",sa.String(80)),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("submitted_at",sa.DateTime(timezone=True)),sa.Column("settled_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","packet_id",name="uq_payment_intent_packet"),sa.UniqueConstraint("tenant_id","payment_fingerprint",name="uq_payment_fingerprint"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_payment_intent_idem")]),
("financial_handoffs",[sa.Column("handoff_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("payment_intent_id",sa.String(128),sa.ForeignKey("payment_intents.payment_intent_id",ondelete="CASCADE"),nullable=False),sa.Column("adapter_name",sa.String(80),nullable=False),sa.Column("instruction_sha256",sa.String(64),nullable=False),sa.Column("external_instruction_id",sa.String(180),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("trace_id",sa.String(128)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_fin_handoff_idem")]),
("settlement_events",[sa.Column("settlement_event_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("payment_intent_id",sa.String(128),sa.ForeignKey("payment_intents.payment_intent_id",ondelete="CASCADE"),nullable=False),sa.Column("provider_event_id",sa.String(180),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("settled_amount",sa.Numeric(14,2)),sa.Column("currency",sa.String(3)),sa.Column("external_reference",sa.String(180)),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("received_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","provider_event_id",name="uq_settlement_provider_event")]),
("financial_reconciliation_exceptions",[sa.Column("exception_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("payment_intent_id",sa.String(128),sa.ForeignKey("payment_intents.payment_intent_id",ondelete="CASCADE"),nullable=False),sa.Column("exception_type",sa.String(80),nullable=False),sa.Column("expected",sa.JSON(),nullable=False),sa.Column("observed",sa.JSON(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("resolved_at",sa.DateTime(timezone=True)),sa.Column("resolved_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"))]),
("payment_void_reissues",[sa.Column("request_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("payment_intent_id",sa.String(128),sa.ForeignKey("payment_intents.payment_intent_id",ondelete="CASCADE"),nullable=False),sa.Column("action",sa.String(30),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("reason",sa.Text(),nullable=False),sa.Column("requested_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("approved_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("replacement_payment_intent_id",sa.String(128),sa.ForeignKey("payment_intents.payment_intent_id",ondelete="SET NULL")),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_void_reissue_idem")]),
("financial_audit_events",[sa.Column("audit_event_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(80),nullable=False),sa.Column("actor_type",sa.String(40),nullable=False),sa.Column("actor_id",sa.String(128),nullable=False),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("previous_event_sha256",sa.String(64)),sa.Column("event_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","claim_id","sequence",name="uq_fin_audit_sequence"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_fin_audit_idem")]),
("financial_tasks",[sa.Column("task_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("payment_intent_id",sa.String(128),sa.ForeignKey("payment_intents.payment_intent_id",ondelete="CASCADE")),sa.Column("task_type",sa.String(60),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("priority",sa.Integer(),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True),nullable=False),sa.Column("assigned_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_fin_task_idem")]),]

def upgrade():
    # Expand RBAC with finance-specific segregation-of-duties roles.
    op.drop_constraint("ck_tenant_memberships_valid_role","tenant_memberships",type_="check")
    op.create_check_constraint("ck_tenant_memberships_valid_role","tenant_memberships","role IN ('patient','provider','hospital_admin','claims_reviewer','finance_operator','finance_analyst','finance_approver','auditor','tenant_admin','system_admin')")
    for name,cols in TABLES:
        op.create_table(name,*cols)
        op.execute(f'ALTER TABLE {name} ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE {name} FORCE ROW LEVEL SECURITY')
        op.execute(f"CREATE POLICY {name}_tenant_rls ON {name} USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))")
    op.create_index("ix_fin_packet_claim","financial_authorization_packets",["tenant_id","claim_id","packet_version"])
    op.create_index("ix_payment_intent_status","payment_intents",["tenant_id","status","created_at"])
    op.create_index("ix_settlement_intent","settlement_events",["tenant_id","payment_intent_id","occurred_at"])
    op.create_index("ix_fin_recon_open","financial_reconciliation_exceptions",["tenant_id","status","created_at"])
    op.create_index("ix_fin_task_queue","financial_tasks",["tenant_id","status","due_at"])
    # Once locked/authorized, packet financial bindings are immutable at the database boundary.
    op.execute("""CREATE OR REPLACE FUNCTION reject_locked_financial_packet_mutation() RETURNS trigger AS $$ BEGIN IF OLD.locked_payload_sha256 IS NOT NULL AND (NEW.decision_history_sha256 IS DISTINCT FROM OLD.decision_history_sha256 OR NEW.evidence_snapshot_sha256 IS DISTINCT FROM OLD.evidence_snapshot_sha256 OR NEW.approved_amount IS DISTINCT FROM OLD.approved_amount OR NEW.line_reconciliation IS DISTINCT FROM OLD.line_reconciliation) THEN RAISE EXCEPTION 'locked financial packet is immutable'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql""")
    op.execute("CREATE TRIGGER trg_financial_packet_immutable BEFORE UPDATE ON financial_authorization_packets FOR EACH ROW EXECUTE FUNCTION reject_locked_financial_packet_mutation()")

def downgrade():
    op.drop_constraint("ck_tenant_memberships_valid_role","tenant_memberships",type_="check")
    op.create_check_constraint("ck_tenant_memberships_valid_role","tenant_memberships","role IN ('patient','provider','hospital_admin','claims_reviewer','auditor','tenant_admin','system_admin')")
    op.execute("DROP FUNCTION IF EXISTS reject_locked_financial_packet_mutation() CASCADE")
    for name,_ in reversed(TABLES):op.drop_table(name)
