"""Release 41: governed double-entry accounting ledger, ERA/EFT reconciliation and accounting close.
Revision ID: 0036_accounting_ledger_era_eft_close
Revises: 0035_financial_handoff_reconciliation
"""
from alembic import op
import sqlalchemy as sa
revision="0036_accounting_ledger_era_eft_close";down_revision="0035_financial_handoff_reconciliation";branch_labels=None;depends_on=None
TABLES=[
("accounting_periods",[sa.Column("period_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("period_key",sa.String(20),nullable=False),sa.Column("start_date",sa.Date(),nullable=False),sa.Column("end_date",sa.Date(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("lock_version",sa.Integer(),nullable=False),sa.Column("close_summary",sa.JSON(),nullable=False),sa.Column("close_sha256",sa.String(64)),sa.Column("closed_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("closed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","period_key",name="uq_accounting_period_key")]),
("ledger_journals",[sa.Column("journal_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("payment_intent_id",sa.String(128),sa.ForeignKey("payment_intents.payment_intent_id",ondelete="RESTRICT")),sa.Column("period_id",sa.String(128),sa.ForeignKey("accounting_periods.period_id",ondelete="RESTRICT"),nullable=False),sa.Column("journal_type",sa.String(60),nullable=False),sa.Column("source_type",sa.String(60),nullable=False),sa.Column("source_id",sa.String(180),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("total_debits",sa.Numeric(14,2),nullable=False),sa.Column("total_credits",sa.Numeric(14,2),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("previous_journal_sha256",sa.String(64)),sa.Column("journal_sha256",sa.String(64),nullable=False),sa.Column("posted_by_actor_type",sa.String(50),nullable=False),sa.Column("posted_by_actor_id",sa.String(128),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("trace_id",sa.String(128)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_ledger_journal_idem"),sa.UniqueConstraint("tenant_id","journal_sha256",name="uq_ledger_journal_sha")]),
("ledger_entries",[sa.Column("entry_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("journal_id",sa.String(128),sa.ForeignKey("ledger_journals.journal_id",ondelete="RESTRICT"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("entry_sequence",sa.Integer(),nullable=False),sa.Column("account_code",sa.String(80),nullable=False),sa.Column("direction",sa.String(6),nullable=False),sa.Column("amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("memo",sa.String(500),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","journal_id","entry_sequence",name="uq_ledger_entry_sequence")]),
("era_records",[sa.Column("era_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("payment_intent_id",sa.String(128),sa.ForeignKey("payment_intents.payment_intent_id",ondelete="RESTRICT"),nullable=False),sa.Column("era_reference",sa.String(180),nullable=False),sa.Column("payment_reference",sa.String(180),nullable=False),sa.Column("provider_ref",sa.String(160),nullable=False),sa.Column("paid_amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("remittance_payload",sa.JSON(),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("received_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","era_reference",name="uq_era_reference")]),
("eft_records",[sa.Column("eft_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("payment_intent_id",sa.String(128),sa.ForeignKey("payment_intents.payment_intent_id",ondelete="RESTRICT"),nullable=False),sa.Column("eft_reference",sa.String(180),nullable=False),sa.Column("bank_reference",sa.String(180),nullable=False),sa.Column("trace_number",sa.String(180),nullable=False),sa.Column("amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("received_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","eft_reference",name="uq_eft_reference")]),
("payment_reconciliations",[sa.Column("reconciliation_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("payment_intent_id",sa.String(128),sa.ForeignKey("payment_intents.payment_intent_id",ondelete="RESTRICT"),nullable=False),sa.Column("expected_amount",sa.Numeric(14,2),nullable=False),sa.Column("era_total",sa.Numeric(14,2),nullable=False),sa.Column("eft_total",sa.Numeric(14,2),nullable=False),sa.Column("matched_amount",sa.Numeric(14,2),nullable=False),sa.Column("unmatched_amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("reference_match",sa.Boolean(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("era_refs",sa.JSON(),nullable=False),sa.Column("eft_refs",sa.JSON(),nullable=False),sa.Column("journal_id",sa.String(128),sa.ForeignKey("ledger_journals.journal_id",ondelete="RESTRICT")),sa.Column("reconciliation_sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("reconciled_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","payment_intent_id",name="uq_payment_reconciliation_intent")]),
("returned_payments",[sa.Column("return_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("payment_intent_id",sa.String(128),sa.ForeignKey("payment_intents.payment_intent_id",ondelete="RESTRICT"),nullable=False),sa.Column("return_reference",sa.String(180),nullable=False),sa.Column("return_code",sa.String(80),nullable=False),sa.Column("amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("reason",sa.Text(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("journal_id",sa.String(128),sa.ForeignKey("ledger_journals.journal_id",ondelete="RESTRICT")),sa.Column("received_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","return_reference",name="uq_return_reference")]),
("accounting_adjustments",[sa.Column("adjustment_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("payment_intent_id",sa.String(128),sa.ForeignKey("payment_intents.payment_intent_id",ondelete="RESTRICT"),nullable=False),sa.Column("adjustment_type",sa.String(30),nullable=False),sa.Column("amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("reason_code",sa.String(80),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("requested_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("approved_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("journal_id",sa.String(128),sa.ForeignKey("ledger_journals.journal_id",ondelete="RESTRICT")),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_accounting_adjustment_idem")]),
("provider_remittance_status",[sa.Column("status_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("payment_intent_id",sa.String(128),sa.ForeignKey("payment_intents.payment_intent_id",ondelete="RESTRICT"),nullable=False),sa.Column("provider_ref",sa.String(160),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("remitted_amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("latest_era_reference",sa.String(180)),sa.Column("latest_eft_reference",sa.String(180)),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","payment_intent_id",name="uq_provider_remittance_intent")]),
("accounting_reconciliation_queue",[sa.Column("queue_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("payment_intent_id",sa.String(128),sa.ForeignKey("payment_intents.payment_intent_id",ondelete="RESTRICT"),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("age_days",sa.Integer(),nullable=False),sa.Column("aging_bucket",sa.String(20),nullable=False),sa.Column("priority",sa.Integer(),nullable=False),sa.Column("exception_codes",sa.JSON(),nullable=False),sa.Column("assigned_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("closed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","payment_intent_id",name="uq_accounting_queue_intent")]),
]
def upgrade():
    op.drop_constraint("ck_tenant_memberships_valid_role","tenant_memberships",type_="check")
    op.create_check_constraint("ck_tenant_memberships_valid_role","tenant_memberships","role IN ('patient','provider','hospital_admin','claims_reviewer','finance_operator','finance_analyst','finance_approver','accounting_controller','auditor','tenant_admin','system_admin')")
    for name,cols in TABLES:
        op.create_table(name,*cols);op.execute(f'ALTER TABLE {name} ENABLE ROW LEVEL SECURITY');op.execute(f'ALTER TABLE {name} FORCE ROW LEVEL SECURITY');op.execute(f"CREATE POLICY {name}_tenant_rls ON {name} USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))")
    op.create_index("ix_accounting_period_status","accounting_periods",["tenant_id","status","end_date"]);op.create_index("ix_ledger_journal_claim","ledger_journals",["tenant_id","claim_id","created_at"]);op.create_index("ix_ledger_entry_account","ledger_entries",["tenant_id","account_code","created_at"]);op.create_index("ix_payment_recon_status","payment_reconciliations",["tenant_id","status","updated_at"]);op.create_index("ix_accounting_queue_aging","accounting_reconciliation_queue",["tenant_id","status","age_days"])
    op.execute("""CREATE OR REPLACE FUNCTION reject_immutable_ledger_journal_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'posted ledger journals are immutable'; END; $$ LANGUAGE plpgsql""")
    op.execute("CREATE TRIGGER trg_ledger_journal_immutable BEFORE UPDATE OR DELETE ON ledger_journals FOR EACH ROW EXECUTE FUNCTION reject_immutable_ledger_journal_mutation()")
    op.execute("CREATE TRIGGER trg_ledger_entry_immutable BEFORE UPDATE OR DELETE ON ledger_entries FOR EACH ROW EXECUTE FUNCTION reject_immutable_ledger_journal_mutation()")
    op.execute("""CREATE OR REPLACE FUNCTION reject_closed_accounting_period_mutation() RETURNS trigger AS $$ BEGIN IF OLD.status='closed' THEN RAISE EXCEPTION 'closed accounting period is immutable'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql""")
    op.execute("CREATE TRIGGER trg_accounting_period_closed_immutable BEFORE UPDATE OR DELETE ON accounting_periods FOR EACH ROW EXECUTE FUNCTION reject_closed_accounting_period_mutation()")
def downgrade():
    op.drop_constraint("ck_tenant_memberships_valid_role","tenant_memberships",type_="check");op.create_check_constraint("ck_tenant_memberships_valid_role","tenant_memberships","role IN ('patient','provider','hospital_admin','claims_reviewer','finance_operator','finance_analyst','finance_approver','auditor','tenant_admin','system_admin')")
    op.execute("DROP FUNCTION IF EXISTS reject_immutable_ledger_journal_mutation() CASCADE");op.execute("DROP FUNCTION IF EXISTS reject_closed_accounting_period_mutation() CASCADE")
    for name,_ in reversed(TABLES):op.drop_table(name)
