"""Release 42: read-only financial analytics, reserve/payment integrity and control intelligence.
Revision ID: 0037_financial_intelligence_read_model
Revises: 0036_accounting_ledger_era_eft_close
"""
from alembic import op
import sqlalchemy as sa
revision="0037_financial_intelligence_read_model";down_revision="0036_accounting_ledger_era_eft_close";branch_labels=None;depends_on=None
TABLES=[
("claim_reserve_snapshots",[sa.Column("reserve_snapshot_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("decision_history_sha256",sa.String(64)),sa.Column("currency",sa.String(3),nullable=False),sa.Column("incurred_amount",sa.Numeric(14,2),nullable=False),sa.Column("approved_amount",sa.Numeric(14,2),nullable=False),sa.Column("net_paid_amount",sa.Numeric(14,2),nullable=False),sa.Column("outstanding_reserve",sa.Numeric(14,2),nullable=False),sa.Column("prior_outstanding_reserve",sa.Numeric(14,2),nullable=False),sa.Column("reserve_variance",sa.Numeric(14,2),nullable=False),sa.Column("adequacy_score",sa.Integer(),nullable=False),sa.Column("source_refs",sa.JSON(),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","claim_id","source_watermark_sha256",name="uq_claim_reserve_watermark")]),
("financial_analytics_snapshots",[sa.Column("snapshot_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("scope_type",sa.String(30),nullable=False),sa.Column("scope_id",sa.String(128),nullable=False),sa.Column("metrics",sa.JSON(),nullable=False),sa.Column("anomalies",sa.JSON(),nullable=False),sa.Column("citations",sa.JSON(),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_by_actor_type",sa.String(50),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","scope_type","scope_id","source_watermark_sha256",name="uq_fin_analytics_scope_watermark")]),
("financial_anomaly_investigations",[sa.Column("investigation_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE")),sa.Column("anomaly_code",sa.String(100),nullable=False),sa.Column("anomaly_score",sa.Integer(),nullable=False),sa.Column("severity",sa.String(20),nullable=False),sa.Column("explanation",sa.Text(),nullable=False),sa.Column("factors",sa.JSON(),nullable=False),sa.Column("evidence_citations",sa.JSON(),nullable=False),sa.Column("recommendations",sa.JSON(),nullable=False),sa.Column("adjudication_authority",sa.String(20),nullable=False),sa.Column("accounting_authority",sa.String(20),nullable=False),sa.Column("fund_movement_authority",sa.String(20),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False)]),
("financial_copilot_runs",[sa.Column("run_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("requested_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("query_text",sa.Text(),nullable=False),sa.Column("answer_text",sa.Text(),nullable=False),sa.Column("citations",sa.JSON(),nullable=False),sa.Column("retrieval_strategy",sa.String(100),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("adjudication_authority",sa.String(20),nullable=False),sa.Column("accounting_authority",sa.String(20),nullable=False),sa.Column("fund_movement_authority",sa.String(20),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False)]),
]
def upgrade():
    for name,cols in TABLES:
        op.create_table(name,*cols);op.execute(f'ALTER TABLE {name} ENABLE ROW LEVEL SECURITY');op.execute(f'ALTER TABLE {name} FORCE ROW LEVEL SECURITY');op.execute(f"CREATE POLICY {name}_tenant_rls ON {name} USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))")
    op.create_index("ix_claim_reserve_claim_time","claim_reserve_snapshots",["tenant_id","claim_id","created_at"]);op.create_index("ix_fin_analytics_scope_time","financial_analytics_snapshots",["tenant_id","scope_type","scope_id","created_at"]);op.create_index("ix_fin_anomaly_claim_score","financial_anomaly_investigations",["tenant_id","claim_id","anomaly_score"]);op.create_index("ix_fin_copilot_user_time","financial_copilot_runs",["tenant_id","requested_by_user_id","created_at"])
    op.execute("""CREATE OR REPLACE FUNCTION reject_financial_intelligence_snapshot_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'financial intelligence observations are immutable derived records'; END; $$ LANGUAGE plpgsql""")
    for table in ["claim_reserve_snapshots","financial_analytics_snapshots","financial_anomaly_investigations","financial_copilot_runs"]:op.execute(f"CREATE TRIGGER trg_{table}_immutable BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION reject_financial_intelligence_snapshot_mutation()")
def downgrade():
    op.execute("DROP FUNCTION IF EXISTS reject_financial_intelligence_snapshot_mutation() CASCADE")
    for name,_ in reversed(TABLES):op.drop_table(name)
