"""Release 43: financial investigation case management and governed remediation.
Revision ID: 0038_financial_investigation_case_management
Revises: 0037_financial_intelligence_read_model
"""
from alembic import op
import sqlalchemy as sa
revision="0038_financial_investigation_case_management";down_revision="0037_financial_intelligence_read_model";branch_labels=None;depends_on=None

def _tenant_cols():return []
def upgrade():
    op.create_table("financial_investigation_cases",
        sa.Column("case_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("source_investigation_id",sa.String(128),sa.ForeignKey("financial_anomaly_investigations.investigation_id",ondelete="RESTRICT"),nullable=False),sa.Column("anomaly_code",sa.String(100),nullable=False),sa.Column("anomaly_score",sa.Integer(),nullable=False),sa.Column("severity",sa.String(20),nullable=False),sa.Column("case_type",sa.String(60),nullable=False),sa.Column("cluster_key",sa.String(160),nullable=False),sa.Column("provider_organization_id",sa.String(128)),sa.Column("status",sa.String(40),nullable=False),sa.Column("priority",sa.Integer(),nullable=False),sa.Column("assigned_investigator_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="SET NULL")),sa.Column("root_cause_code",sa.String(80)),sa.Column("root_cause_rationale",sa.Text()),sa.Column("ai_recommendation",sa.JSON()),sa.Column("ai_disagreement_rationale",sa.Text()),sa.Column("case_version",sa.Integer(),nullable=False),sa.Column("created_by_actor_type",sa.String(50),nullable=False),sa.Column("created_by_actor_id",sa.String(128)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("closed_at",sa.DateTime(timezone=True)),sa.Column("closure_reason_code",sa.String(100)),sa.Column("closure_rationale",sa.Text()),sa.UniqueConstraint("tenant_id","source_investigation_id",name="uq_fin_case_source_investigation"))
    op.create_table("financial_investigation_evidence_packs",sa.Column("evidence_pack_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("case_id",sa.String(128),sa.ForeignKey("financial_investigation_cases.case_id",ondelete="CASCADE"),nullable=False),sa.Column("pack_version",sa.Integer(),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("evidence_items",sa.JSON(),nullable=False),sa.Column("citations",sa.JSON(),nullable=False),sa.Column("related_case_ids",sa.JSON(),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","case_id","pack_version",name="uq_fin_case_pack_version"))
    op.create_table("financial_investigation_leases",sa.Column("case_id",sa.String(128),sa.ForeignKey("financial_investigation_cases.case_id",ondelete="CASCADE"),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("investigator_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("lease_token_sha256",sa.String(64),nullable=False),sa.Column("lease_version",sa.Integer(),nullable=False),sa.Column("acquired_at",sa.DateTime(timezone=True),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("financial_investigation_annotations",sa.Column("annotation_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("case_id",sa.String(128),sa.ForeignKey("financial_investigation_cases.case_id",ondelete="CASCADE"),nullable=False),sa.Column("reviewer_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("target_type",sa.String(60),nullable=False),sa.Column("target_id",sa.String(128),nullable=False),sa.Column("body",sa.Text(),nullable=False),sa.Column("tags",sa.JSON(),nullable=False),sa.Column("body_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_fin_inv_annotation_idem"))
    op.create_table("financial_remediation_proposals",sa.Column("proposal_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("case_id",sa.String(128),sa.ForeignKey("financial_investigation_cases.case_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("remediation_type",sa.String(80),nullable=False),sa.Column("amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("reason_code",sa.String(100),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("evidence_pack_sha256",sa.String(64),nullable=False),sa.Column("root_cause_code",sa.String(80),nullable=False),sa.Column("material",sa.Boolean(),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("proposed_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("approved_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("approval_rationale",sa.Text()),sa.Column("referral_type",sa.String(80)),sa.Column("referral_id",sa.String(128)),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("executed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_fin_remediation_idem"))
    op.create_table("financial_investigation_tasks",sa.Column("task_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("case_id",sa.String(128),sa.ForeignKey("financial_investigation_cases.case_id",ondelete="CASCADE"),nullable=False),sa.Column("task_type",sa.String(80),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("priority",sa.Integer(),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True),nullable=False),sa.Column("assigned_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="SET NULL")),sa.Column("idempotency_key",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_fin_inv_task_idem"))
    op.create_table("financial_investigation_audit_events",sa.Column("audit_event_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("case_id",sa.String(128),sa.ForeignKey("financial_investigation_cases.case_id",ondelete="CASCADE"),nullable=False),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(100),nullable=False),sa.Column("actor_type",sa.String(50),nullable=False),sa.Column("actor_id",sa.String(128)),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("previous_event_sha256",sa.String(64)),sa.Column("event_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(160),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","case_id","sequence",name="uq_fin_inv_audit_sequence"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_fin_inv_audit_idem"))
    op.create_table("financial_investigation_evaluation_cases",sa.Column("evaluation_case_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("scenario_type",sa.String(80),nullable=False),sa.Column("input_payload",sa.JSON(),nullable=False),sa.Column("expected_controls",sa.JSON(),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_fin_case_status_priority","financial_investigation_cases",["tenant_id","status","priority"]);op.create_index("ix_fin_case_claim","financial_investigation_cases",["tenant_id","claim_id"]);op.create_index("ix_fin_remediation_case","financial_remediation_proposals",["tenant_id","case_id","status"]);op.create_index("ix_fin_inv_task_queue","financial_investigation_tasks",["tenant_id","status","due_at"])
    tables=["financial_investigation_cases","financial_investigation_evidence_packs","financial_investigation_leases","financial_investigation_annotations","financial_remediation_proposals","financial_investigation_tasks","financial_investigation_audit_events","financial_investigation_evaluation_cases"]
    for t in tables:
        op.execute(f'ALTER TABLE {t} ENABLE ROW LEVEL SECURITY');op.execute(f'ALTER TABLE {t} FORCE ROW LEVEL SECURITY');op.execute(f"CREATE POLICY {t}_tenant_rls ON {t} USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))")
    op.execute("""CREATE OR REPLACE FUNCTION reject_financial_investigation_immutable_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'financial investigation evidence/audit records are immutable'; END; $$ LANGUAGE plpgsql""")
    for t in ["financial_investigation_evidence_packs","financial_investigation_annotations","financial_investigation_audit_events","financial_investigation_evaluation_cases"]:op.execute(f"CREATE TRIGGER trg_{t}_immutable BEFORE UPDATE OR DELETE ON {t} FOR EACH ROW EXECUTE FUNCTION reject_financial_investigation_immutable_mutation()")
def downgrade():
    op.execute("DROP FUNCTION IF EXISTS reject_financial_investigation_immutable_mutation() CASCADE")
    for t in ["financial_investigation_evaluation_cases","financial_investigation_audit_events","financial_investigation_tasks","financial_remediation_proposals","financial_investigation_annotations","financial_investigation_leases","financial_investigation_evidence_packs","financial_investigation_cases"]:op.drop_table(t)
