"""Release 44: recovery operations, provider disputes and remediation outcome verification.
Revision ID: 0039_recovery_operations_provider_disputes
Revises: 0038_financial_investigation_case_management
"""
from alembic import op
import sqlalchemy as sa
revision="0039_recovery_operations_provider_disputes";down_revision="0038_financial_investigation_case_management";branch_labels=None;depends_on=None

def upgrade():
    op.create_table("recovery_cases",sa.Column("recovery_case_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("financial_investigation_case_id",sa.String(128),sa.ForeignKey("financial_investigation_cases.case_id",ondelete="RESTRICT"),nullable=False),sa.Column("source_proposal_id",sa.String(128),sa.ForeignKey("financial_remediation_proposals.proposal_id",ondelete="RESTRICT"),nullable=False),sa.Column("referral_type",sa.String(80),nullable=False),sa.Column("referral_id",sa.String(128),nullable=False),sa.Column("recovery_type",sa.String(80),nullable=False),sa.Column("provider_organization_id",sa.String(128)),sa.Column("currency",sa.String(3),nullable=False),sa.Column("identified_amount",sa.Numeric(14,2),nullable=False),sa.Column("target_recovery_amount",sa.Numeric(14,2),nullable=False),sa.Column("recovered_amount",sa.Numeric(14,2),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("priority",sa.Integer(),nullable=False),sa.Column("assigned_investigator_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="SET NULL")),sa.Column("case_version",sa.Integer(),nullable=False),sa.Column("effectiveness_score",sa.Integer(),nullable=False),sa.Column("last_verified_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("closed_at",sa.DateTime(timezone=True)),sa.Column("closure_reason_code",sa.String(100)),sa.Column("closure_rationale",sa.Text()),sa.UniqueConstraint("tenant_id","source_proposal_id",name="uq_recovery_source_proposal"))
    op.create_table("recovery_evidence_packs",sa.Column("evidence_pack_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("recovery_case_id",sa.String(128),sa.ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False),sa.Column("pack_version",sa.Integer(),nullable=False),sa.Column("evidence_items",sa.JSON(),nullable=False),sa.Column("citations",sa.JSON(),nullable=False),sa.Column("source_sha256",sa.String(64),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","recovery_case_id","pack_version",name="uq_recovery_pack_version"))
    op.create_table("recovery_leases",sa.Column("recovery_case_id",sa.String(128),sa.ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("investigator_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("lease_token_sha256",sa.String(64),nullable=False),sa.Column("lease_version",sa.Integer(),nullable=False),sa.Column("acquired_at",sa.DateTime(timezone=True),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("recovery_outcomes",sa.Column("outcome_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("recovery_case_id",sa.String(128),sa.ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False),sa.Column("outcome_type",sa.String(80),nullable=False),sa.Column("source_type",sa.String(80),nullable=False),sa.Column("source_id",sa.String(180),nullable=False),sa.Column("amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("external_reference",sa.String(180)),sa.Column("details",sa.JSON(),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(160),nullable=False),sa.Column("recorded_by_actor_type",sa.String(50),nullable=False),sa.Column("recorded_by_actor_id",sa.String(128)),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_outcome_idem"))
    op.create_table("provider_disputes",sa.Column("dispute_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("recovery_case_id",sa.String(128),sa.ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("provider_organization_id",sa.String(128),nullable=False),sa.Column("external_reference",sa.String(180),nullable=False),sa.Column("disputed_amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("reason_code",sa.String(100),nullable=False),sa.Column("statement",sa.Text(),nullable=False),sa.Column("evidence_refs",sa.JSON(),nullable=False),sa.Column("evidence_pack_sha256",sa.String(64),nullable=False),sa.Column("material",sa.Boolean(),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("submitted_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("assigned_resolver_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="SET NULL")),sa.Column("resolution_outcome",sa.String(80)),sa.Column("resolution_rationale",sa.Text()),sa.Column("resolution_amount",sa.Numeric(14,2)),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("submitted_at",sa.DateTime(timezone=True),nullable=False),sa.Column("resolved_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","external_reference",name="uq_provider_dispute_external"))
    op.create_table("recovery_correspondence",sa.Column("correspondence_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("recovery_case_id",sa.String(128),sa.ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False),sa.Column("dispute_id",sa.String(128),sa.ForeignKey("provider_disputes.dispute_id",ondelete="SET NULL")),sa.Column("direction",sa.String(20),nullable=False),sa.Column("channel",sa.String(30),nullable=False),sa.Column("subject",sa.String(300),nullable=False),sa.Column("body",sa.Text(),nullable=False),sa.Column("external_message_id",sa.String(180)),sa.Column("body_sha256",sa.String(64),nullable=False),sa.Column("actor_type",sa.String(50),nullable=False),sa.Column("actor_id",sa.String(128)),sa.Column("idempotency_key",sa.String(160),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_correspondence_idem"))
    op.create_table("recovery_tasks",sa.Column("task_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("recovery_case_id",sa.String(128),sa.ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False),sa.Column("task_type",sa.String(80),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("priority",sa.Integer(),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True),nullable=False),sa.Column("assigned_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="SET NULL")),sa.Column("idempotency_key",sa.String(160),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_task_idem"))
    op.create_table("recovery_audit_events",sa.Column("audit_event_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("recovery_case_id",sa.String(128),sa.ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(110),nullable=False),sa.Column("actor_type",sa.String(50),nullable=False),sa.Column("actor_id",sa.String(128)),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("previous_event_sha256",sa.String(64)),sa.Column("event_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","recovery_case_id","sequence",name="uq_recovery_audit_sequence"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_audit_idem"))
    op.create_table("recovery_evaluation_cases",sa.Column("evaluation_case_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("scenario_type",sa.String(80),nullable=False),sa.Column("input_payload",sa.JSON(),nullable=False),sa.Column("expected_controls",sa.JSON(),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_recovery_case_queue","recovery_cases",["tenant_id","status","priority"]);op.create_index("ix_recovery_claim","recovery_cases",["tenant_id","claim_id"]);op.create_index("ix_recovery_outcome_case","recovery_outcomes",["tenant_id","recovery_case_id","occurred_at"]);op.create_index("ix_provider_dispute_queue","provider_disputes",["tenant_id","status","submitted_at"]);op.create_index("ix_recovery_task_queue","recovery_tasks",["tenant_id","status","due_at"])
    tables=["recovery_cases","recovery_evidence_packs","recovery_leases","recovery_outcomes","provider_disputes","recovery_correspondence","recovery_tasks","recovery_audit_events","recovery_evaluation_cases"]
    for t in tables:
        op.execute(f'ALTER TABLE {t} ENABLE ROW LEVEL SECURITY');op.execute(f'ALTER TABLE {t} FORCE ROW LEVEL SECURITY');op.execute(f"CREATE POLICY {t}_tenant_rls ON {t} USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))")
    op.execute("""CREATE OR REPLACE FUNCTION reject_recovery_immutable_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'recovery evidence/outcome/correspondence/audit records are immutable'; END; $$ LANGUAGE plpgsql""")
    for t in ["recovery_evidence_packs","recovery_outcomes","recovery_correspondence","recovery_audit_events","recovery_evaluation_cases"]:op.execute(f"CREATE TRIGGER trg_{t}_immutable BEFORE UPDATE OR DELETE ON {t} FOR EACH ROW EXECUTE FUNCTION reject_recovery_immutable_mutation()")
def downgrade():
    op.execute("DROP FUNCTION IF EXISTS reject_recovery_immutable_mutation() CASCADE")
    for t in ["recovery_evaluation_cases","recovery_audit_events","recovery_tasks","recovery_correspondence","provider_disputes","recovery_outcomes","recovery_leases","recovery_evidence_packs","recovery_cases"]:op.drop_table(t)
