"""evidence-bound provider dispute resolution and recovery amendment
Revision ID: 0041_provider_dispute_resolution_recovery_amendment
Revises: 0040_provider_dispute_intelligence
"""
from alembic import op
import sqlalchemy as sa
revision="0041_provider_dispute_resolution_recovery_amendment";down_revision="0040_provider_dispute_intelligence";branch_labels=None;depends_on=None

def _rls(table):
    op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY');op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY');op.execute(f'''CREATE POLICY {table}_tenant_isolation ON "{table}" USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))''')
def upgrade():
    op.create_table("provider_dispute_decision_packets",sa.Column("packet_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("recovery_case_id",sa.String(128),sa.ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False),sa.Column("dispute_id",sa.String(128),sa.ForeignKey("provider_disputes.dispute_id",ondelete="CASCADE"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("primary_resolver_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("second_resolver_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("snapshot_id",sa.String(128),sa.ForeignKey("dispute_evidence_snapshots.snapshot_id",ondelete="RESTRICT"),nullable=False),sa.Column("snapshot_sha256",sa.String(64),nullable=False),sa.Column("recommendation_run_id",sa.String(128),sa.ForeignKey("dispute_recommendation_runs.recommendation_run_id",ondelete="RESTRICT")),sa.Column("outcome",sa.String(40),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("reason_codes",sa.JSON(),nullable=False),sa.Column("citation_refs",sa.JSON(),nullable=False),sa.Column("resolved_comparison_refs",sa.JSON(),nullable=False),sa.Column("checkpoint_refs",sa.JSON(),nullable=False),sa.Column("original_target_amount",sa.Numeric(14,2),nullable=False),sa.Column("amended_target_amount",sa.Numeric(14,2),nullable=False),sa.Column("financial_delta",sa.Numeric(14,2),nullable=False),sa.Column("material_target_change",sa.Boolean(),nullable=False),sa.Column("recommendation_disagreement",sa.Boolean(),nullable=False),sa.Column("recommendation_disagreement_reason",sa.Text()),sa.Column("completeness",sa.JSON(),nullable=False),sa.Column("blocker_codes",sa.JSON(),nullable=False),sa.Column("dual_control_required",sa.Boolean(),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("packet_version",sa.Integer(),nullable=False),sa.Column("expected_case_version",sa.Integer(),nullable=False),sa.Column("locked_payload_sha256",sa.String(64)),sa.Column("final_resolution_id",sa.String(128)),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("trace_id",sa.String(128)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("locked_at",sa.DateTime(timezone=True)),sa.Column("closed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_provider_dispute_packet_idem"),sa.UniqueConstraint("tenant_id","dispute_id","packet_version",name="uq_provider_dispute_packet_version"))
    op.create_index("ix_provider_dispute_packet","provider_dispute_decision_packets",["tenant_id","dispute_id","created_at"])
    op.create_table("provider_dispute_second_reviews",sa.Column("second_review_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("recovery_case_id",sa.String(128),sa.ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False),sa.Column("dispute_id",sa.String(128),sa.ForeignKey("provider_disputes.dispute_id",ondelete="CASCADE"),nullable=False),sa.Column("packet_id",sa.String(128),sa.ForeignKey("provider_dispute_decision_packets.packet_id",ondelete="CASCADE"),nullable=False),sa.Column("reviewer_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("action",sa.String(20),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("packet_version",sa.Integer(),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","packet_id","reviewer_user_id",name="uq_provider_dispute_second_review"))
    op.create_table("recovery_position_versions",sa.Column("position_version_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("recovery_case_id",sa.String(128),sa.ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False),sa.Column("dispute_id",sa.String(128),sa.ForeignKey("provider_disputes.dispute_id",ondelete="SET NULL")),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("target_recovery_amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("source_type",sa.String(80),nullable=False),sa.Column("source_id",sa.String(128),nullable=False),sa.Column("supersedes_position_version_id",sa.String(128)),sa.Column("previous_payload_sha256",sa.String(64)),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("effective_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","recovery_case_id","sequence",name="uq_recovery_position_sequence"))
    op.create_table("provider_dispute_final_resolutions",sa.Column("resolution_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("recovery_case_id",sa.String(128),sa.ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False),sa.Column("dispute_id",sa.String(128),sa.ForeignKey("provider_disputes.dispute_id",ondelete="RESTRICT"),nullable=False),sa.Column("packet_id",sa.String(128),sa.ForeignKey("provider_dispute_decision_packets.packet_id",ondelete="RESTRICT"),nullable=False),sa.Column("primary_resolver_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("second_resolver_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("outcome",sa.String(40),nullable=False),sa.Column("original_target_amount",sa.Numeric(14,2),nullable=False),sa.Column("amended_target_amount",sa.Numeric(14,2),nullable=False),sa.Column("financial_delta",sa.Numeric(14,2),nullable=False),sa.Column("snapshot_sha256",sa.String(64),nullable=False),sa.Column("packet_locked_sha256",sa.String(64),nullable=False),sa.Column("position_version_id",sa.String(128),sa.ForeignKey("recovery_position_versions.position_version_id",ondelete="RESTRICT"),nullable=False),sa.Column("correspondence_id",sa.String(128)),sa.Column("reversal_referral_id",sa.String(128)),sa.Column("provenance",sa.JSON(),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("trace_id",sa.String(128)),sa.Column("resolved_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","dispute_id",name="uq_provider_dispute_final_once"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_provider_dispute_final_idem"))
    op.create_table("recovery_amendment_referrals",sa.Column("reversal_referral_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("recovery_case_id",sa.String(128),sa.ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False),sa.Column("dispute_id",sa.String(128),sa.ForeignKey("provider_disputes.dispute_id",ondelete="RESTRICT"),nullable=False),sa.Column("resolution_id",sa.String(128),sa.ForeignKey("provider_dispute_final_resolutions.resolution_id",ondelete="RESTRICT"),nullable=False),sa.Column("referral_type",sa.String(80),nullable=False),sa.Column("destination",sa.String(80),nullable=False),sa.Column("amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("reason_code",sa.String(100),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("external_reference",sa.String(180)),sa.Column("verified_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","resolution_id",name="uq_recovery_amendment_resolution"))
    op.create_table("provider_dispute_resolution_audit_events",sa.Column("audit_event_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("recovery_case_id",sa.String(128),sa.ForeignKey("recovery_cases.recovery_case_id",ondelete="CASCADE"),nullable=False),sa.Column("dispute_id",sa.String(128),sa.ForeignKey("provider_disputes.dispute_id",ondelete="CASCADE"),nullable=False),sa.Column("packet_id",sa.String(128),sa.ForeignKey("provider_dispute_decision_packets.packet_id",ondelete="SET NULL")),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(120),nullable=False),sa.Column("actor_type",sa.String(40),nullable=False),sa.Column("actor_id",sa.String(128),nullable=False),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("previous_event_sha256",sa.String(64)),sa.Column("event_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("trace_id",sa.String(128)),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","dispute_id","sequence",name="uq_provider_dispute_resolution_audit_seq"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_provider_dispute_resolution_audit_idem"))
    tables=("provider_dispute_decision_packets","provider_dispute_second_reviews","recovery_position_versions","provider_dispute_final_resolutions","recovery_amendment_referrals","provider_dispute_resolution_audit_events")
    for t in tables:_rls(t)
    for t in ("provider_dispute_second_reviews","recovery_position_versions","provider_dispute_final_resolutions","provider_dispute_resolution_audit_events"):
        op.execute(f'CREATE TRIGGER {t}_immutable BEFORE UPDATE OR DELETE ON "{t}" FOR EACH ROW EXECUTE FUNCTION medclaimiq_reject_immutable_change()')
    op.execute('CREATE OR REPLACE FUNCTION reject_provider_dispute_resolution_immutable_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION \'provider dispute resolution immutable record cannot be changed\'; END; $$ LANGUAGE plpgsql')
def downgrade():
    for t in ("provider_dispute_resolution_audit_events","recovery_amendment_referrals","provider_dispute_final_resolutions","recovery_position_versions","provider_dispute_second_reviews","provider_dispute_decision_packets"):op.drop_table(t)
