"""recovery settlement evidence provider repayment verification and financial closeout
Revision ID: 0042_recovery_settlement_financial_closeout
Revises: 0041_provider_dispute_resolution_recovery_amendment
"""
from alembic import op
import sqlalchemy as sa
revision="0042_recovery_settlement_financial_closeout";down_revision="0041_provider_dispute_resolution_recovery_amendment";branch_labels=None;depends_on=None

def _rls(table):
    op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY');op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY');op.execute(f'''CREATE POLICY {table}_tenant_isolation ON "{table}" USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))''')
def upgrade():
    op.create_table("recovery_settlement_cases",sa.Column("settlement_case_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("recovery_case_id",sa.String(128),sa.ForeignKey("recovery_cases.recovery_case_id",ondelete="RESTRICT"),nullable=False),sa.Column("claim_id",sa.String(128),sa.ForeignKey("claims.claim_id",ondelete="CASCADE"),nullable=False),sa.Column("provider_organization_id",sa.String(128)),sa.Column("final_resolution_id",sa.String(128),sa.ForeignKey("provider_dispute_final_resolutions.resolution_id",ondelete="RESTRICT"),nullable=False),sa.Column("position_version_id",sa.String(128),sa.ForeignKey("recovery_position_versions.position_version_id",ondelete="RESTRICT"),nullable=False),sa.Column("position_payload_sha256",sa.String(64),nullable=False),sa.Column("target_amount",sa.Numeric(14,2),nullable=False),sa.Column("verified_amount",sa.Numeric(14,2),nullable=False),sa.Column("remaining_amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("case_version",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("certified_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","recovery_case_id",name="uq_recovery_settlement_case"));op.create_index("ix_recovery_settlement_queue","recovery_settlement_cases",["tenant_id","status","updated_at"])
    op.create_table("recovery_settlement_evidence",sa.Column("settlement_evidence_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("settlement_case_id",sa.String(128),sa.ForeignKey("recovery_settlement_cases.settlement_case_id",ondelete="CASCADE"),nullable=False),sa.Column("recovery_case_id",sa.String(128),sa.ForeignKey("recovery_cases.recovery_case_id",ondelete="RESTRICT"),nullable=False),sa.Column("evidence_type",sa.String(50),nullable=False),sa.Column("amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("installment_sequence",sa.Integer(),nullable=False),sa.Column("external_reference",sa.String(180),nullable=False),sa.Column("bank_reference",sa.String(180)),sa.Column("remittance_reference",sa.String(180)),sa.Column("provider_reference",sa.String(180)),sa.Column("evidence_refs",sa.JSON(),nullable=False),sa.Column("evidence_payload_sha256",sa.String(64),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("reference_match",sa.Boolean()),sa.Column("verification_rationale",sa.Text()),sa.Column("submitted_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("verified_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","external_reference",name="uq_recovery_settlement_external_ref"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_settlement_evidence_idem"));op.create_index("ix_recovery_settlement_evidence","recovery_settlement_evidence",["tenant_id","settlement_case_id","status"])
    op.create_table("recovery_ledger_correlations",sa.Column("correlation_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("settlement_case_id",sa.String(128),sa.ForeignKey("recovery_settlement_cases.settlement_case_id",ondelete="CASCADE"),nullable=False),sa.Column("settlement_evidence_id",sa.String(128),sa.ForeignKey("recovery_settlement_evidence.settlement_evidence_id",ondelete="RESTRICT"),nullable=False),sa.Column("journal_id",sa.String(128),sa.ForeignKey("ledger_journals.journal_id",ondelete="RESTRICT"),nullable=False),sa.Column("period_id",sa.String(128),sa.ForeignKey("accounting_periods.period_id",ondelete="RESTRICT"),nullable=False),sa.Column("amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("correlation_payload_sha256",sa.String(64),nullable=False),sa.Column("verified_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","settlement_evidence_id","journal_id",name="uq_recovery_ledger_correlation"))
    op.create_table("recovery_settlement_exceptions",sa.Column("exception_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("settlement_case_id",sa.String(128),sa.ForeignKey("recovery_settlement_cases.settlement_case_id",ondelete="CASCADE"),nullable=False),sa.Column("exception_code",sa.String(80),nullable=False),sa.Column("severity",sa.String(20),nullable=False),sa.Column("details",sa.JSON(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("resolved_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("resolved_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","settlement_case_id","exception_code","status",name="uq_recovery_settlement_exception_state"));op.create_index("ix_recovery_settlement_exception_queue","recovery_settlement_exceptions",["tenant_id","status","created_at"])
    op.create_table("recovery_completion_certificates",sa.Column("certificate_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("settlement_case_id",sa.String(128),sa.ForeignKey("recovery_settlement_cases.settlement_case_id",ondelete="RESTRICT"),nullable=False),sa.Column("recovery_case_id",sa.String(128),sa.ForeignKey("recovery_cases.recovery_case_id",ondelete="RESTRICT"),nullable=False),sa.Column("accounting_period_id",sa.String(128),sa.ForeignKey("accounting_periods.period_id",ondelete="RESTRICT"),nullable=False),sa.Column("prepared_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("approved_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("target_amount",sa.Numeric(14,2),nullable=False),sa.Column("verified_amount",sa.Numeric(14,2),nullable=False),sa.Column("remaining_amount",sa.Numeric(14,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("reason_codes",sa.JSON(),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("prepared_at",sa.DateTime(timezone=True),nullable=False),sa.Column("certified_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","settlement_case_id",name="uq_recovery_completion_certificate"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_completion_certificate_idem"))
    op.create_table("recovery_settlement_correspondence",sa.Column("correspondence_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("settlement_case_id",sa.String(128),sa.ForeignKey("recovery_settlement_cases.settlement_case_id",ondelete="CASCADE"),nullable=False),sa.Column("direction",sa.String(20),nullable=False),sa.Column("channel",sa.String(30),nullable=False),sa.Column("subject",sa.String(300),nullable=False),sa.Column("body",sa.Text(),nullable=False),sa.Column("external_message_id",sa.String(180)),sa.Column("body_sha256",sa.String(64),nullable=False),sa.Column("actor_id",sa.String(128),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_settlement_corr_idem"))
    op.create_table("recovery_settlement_tasks",sa.Column("task_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("settlement_case_id",sa.String(128),sa.ForeignKey("recovery_settlement_cases.settlement_case_id",ondelete="CASCADE"),nullable=False),sa.Column("task_type",sa.String(80),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("priority",sa.Integer(),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_settlement_task_idem"));op.create_index("ix_recovery_settlement_task_queue","recovery_settlement_tasks",["tenant_id","status","due_at"])
    op.create_table("recovery_settlement_audit_events",sa.Column("audit_event_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("settlement_case_id",sa.String(128),sa.ForeignKey("recovery_settlement_cases.settlement_case_id",ondelete="CASCADE"),nullable=False),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(120),nullable=False),sa.Column("actor_type",sa.String(50),nullable=False),sa.Column("actor_id",sa.String(128)),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("previous_event_sha256",sa.String(64)),sa.Column("event_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","settlement_case_id","sequence",name="uq_recovery_settlement_audit_seq"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_recovery_settlement_audit_idem"))
    op.create_table("recovery_settlement_evaluation_cases",sa.Column("evaluation_case_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("scenario_type",sa.String(80),nullable=False),sa.Column("input_payload",sa.JSON(),nullable=False),sa.Column("expected_controls",sa.JSON(),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    tables=("recovery_settlement_cases","recovery_settlement_evidence","recovery_ledger_correlations","recovery_settlement_exceptions","recovery_completion_certificates","recovery_settlement_correspondence","recovery_settlement_tasks","recovery_settlement_audit_events","recovery_settlement_evaluation_cases")
    for t in tables:_rls(t)
    op.execute("CREATE OR REPLACE FUNCTION reject_recovery_settlement_immutable_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'recovery settlement immutable record cannot be changed'; END; $$ LANGUAGE plpgsql")
    for t in ("recovery_ledger_correlations","recovery_settlement_correspondence","recovery_settlement_audit_events","recovery_settlement_evaluation_cases"):
        op.execute(f'CREATE TRIGGER {t}_immutable BEFORE UPDATE OR DELETE ON "{t}" FOR EACH ROW EXECUTE FUNCTION reject_recovery_settlement_immutable_mutation()')
    op.execute("CREATE OR REPLACE FUNCTION protect_verified_recovery_settlement_evidence() RETURNS trigger AS $$ BEGIN IF TG_OP = 'DELETE' OR OLD.status IN ('verified','rejected') THEN RAISE EXCEPTION 'verified recovery settlement evidence is immutable'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql")
    op.execute('CREATE TRIGGER recovery_settlement_evidence_final_immutable BEFORE UPDATE OR DELETE ON "recovery_settlement_evidence" FOR EACH ROW EXECUTE FUNCTION protect_verified_recovery_settlement_evidence()')
    op.execute("CREATE OR REPLACE FUNCTION protect_final_recovery_completion_certificate() RETURNS trigger AS $$ BEGIN IF TG_OP = 'DELETE' OR OLD.status IN ('certified','rejected') THEN RAISE EXCEPTION 'final recovery completion certificate is immutable'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql")
    op.execute('CREATE TRIGGER recovery_completion_certificate_final_immutable BEFORE UPDATE OR DELETE ON "recovery_completion_certificates" FOR EACH ROW EXECUTE FUNCTION protect_final_recovery_completion_certificate()')
def downgrade():
    for t in ("recovery_settlement_evaluation_cases","recovery_settlement_audit_events","recovery_settlement_tasks","recovery_settlement_correspondence","recovery_completion_certificates","recovery_settlement_exceptions","recovery_ledger_correlations","recovery_settlement_evidence","recovery_settlement_cases"):op.drop_table(t)
    op.execute("DROP FUNCTION IF EXISTS protect_final_recovery_completion_certificate()")
    op.execute("DROP FUNCTION IF EXISTS protect_verified_recovery_settlement_evidence()")
    op.execute("DROP FUNCTION IF EXISTS reject_recovery_settlement_immutable_mutation()")
