"""recovery settlement reconciliation intelligence provider statements and reporting
Revision ID: 0043_recovery_settlement_reconciliation_intelligence
Revises: 0042_recovery_settlement_financial_closeout
"""
from alembic import op
import sqlalchemy as sa
revision="0043_recovery_settlement_reconciliation_intelligence";down_revision="0042_recovery_settlement_financial_closeout";branch_labels=None;depends_on=None

def _rls(table):
    op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY');op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY');op.execute(f'''CREATE POLICY {table}_tenant_isolation ON "{table}" USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))''')
def upgrade():
    op.create_table("provider_recovery_balance_statements",sa.Column("statement_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("provider_organization_id",sa.String(128),nullable=False),sa.Column("statement_version",sa.Integer(),nullable=False),sa.Column("as_of_date",sa.Date(),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("target_recovery",sa.Numeric(14,2),nullable=False),sa.Column("verified_recovery",sa.Numeric(14,2),nullable=False),sa.Column("remaining_balance",sa.Numeric(14,2),nullable=False),sa.Column("under_recovery_amount",sa.Numeric(14,2),nullable=False),sa.Column("over_recovery_amount",sa.Numeric(14,2),nullable=False),sa.Column("open_case_count",sa.Integer(),nullable=False),sa.Column("certified_case_count",sa.Integer(),nullable=False),sa.Column("aging_summary",sa.JSON(),nullable=False),sa.Column("case_lines",sa.JSON(),nullable=False),sa.Column("source_refs",sa.JSON(),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_by_actor_type",sa.String(60),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","provider_organization_id","source_watermark_sha256",name="uq_provider_balance_statement_watermark"),sa.UniqueConstraint("tenant_id","provider_organization_id","statement_version",name="uq_provider_balance_statement_version"));op.create_index("ix_provider_balance_statement","provider_recovery_balance_statements",["tenant_id","provider_organization_id","created_at"])
    op.create_table("recovery_settlement_analytics_snapshots",sa.Column("snapshot_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("scope_type",sa.String(30),nullable=False),sa.Column("scope_id",sa.String(128),nullable=False),sa.Column("metrics",sa.JSON(),nullable=False),sa.Column("anomalies",sa.JSON(),nullable=False),sa.Column("citations",sa.JSON(),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_by_actor_type",sa.String(60),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","scope_type","scope_id","source_watermark_sha256",name="uq_recovery_settlement_analytics_watermark"));op.create_index("ix_recovery_settlement_analytics_scope","recovery_settlement_analytics_snapshots",["tenant_id","scope_type","scope_id","created_at"])
    op.create_table("recovery_settlement_exception_investigations",sa.Column("investigation_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("settlement_case_id",sa.String(128),sa.ForeignKey("recovery_settlement_cases.settlement_case_id",ondelete="CASCADE"),nullable=False),sa.Column("exception_code",sa.String(100),nullable=False),sa.Column("severity",sa.String(20),nullable=False),sa.Column("explanation",sa.Text(),nullable=False),sa.Column("factors",sa.JSON(),nullable=False),sa.Column("citations",sa.JSON(),nullable=False),sa.Column("recommendations",sa.JSON(),nullable=False),sa.Column("accounting_authority",sa.String(20),nullable=False),sa.Column("fund_movement_authority",sa.String(20),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_recovery_settlement_exception_investigation","recovery_settlement_exception_investigations",["tenant_id","settlement_case_id","created_at"])
    op.create_table("recovery_closeout_reports",sa.Column("report_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("report_scope",sa.String(30),nullable=False),sa.Column("scope_id",sa.String(128),nullable=False),sa.Column("report_version",sa.Integer(),nullable=False),sa.Column("manifest",sa.JSON(),nullable=False),sa.Column("source_refs",sa.JSON(),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("manifest_sha256",sa.String(64),nullable=False),sa.Column("created_by_actor_type",sa.String(60),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","report_scope","scope_id","source_watermark_sha256",name="uq_recovery_closeout_report_watermark"));op.create_index("ix_recovery_closeout_report","recovery_closeout_reports",["tenant_id","report_scope","scope_id","created_at"])
    op.create_table("provider_balance_statement_deliveries",sa.Column("delivery_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("statement_id",sa.String(128),sa.ForeignKey("provider_recovery_balance_statements.statement_id",ondelete="RESTRICT"),nullable=False),sa.Column("provider_organization_id",sa.String(128),nullable=False),sa.Column("channel",sa.String(30),nullable=False),sa.Column("released_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("delivery_payload_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("delivered_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","statement_id",name="uq_provider_balance_statement_delivery"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_provider_balance_statement_delivery_idem"))
    op.create_table("recovery_settlement_copilot_runs",sa.Column("run_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("requested_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("query_text",sa.Text(),nullable=False),sa.Column("answer_text",sa.Text(),nullable=False),sa.Column("citations",sa.JSON(),nullable=False),sa.Column("retrieval_strategy",sa.String(120),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("accounting_authority",sa.String(20),nullable=False),sa.Column("fund_movement_authority",sa.String(20),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_recovery_settlement_copilot","recovery_settlement_copilot_runs",["tenant_id","requested_by_user_id","created_at"])
    tables=("provider_recovery_balance_statements","recovery_settlement_analytics_snapshots","recovery_settlement_exception_investigations","recovery_closeout_reports","provider_balance_statement_deliveries","recovery_settlement_copilot_runs")
    for t in tables:_rls(t)
    op.execute("CREATE OR REPLACE FUNCTION reject_recovery_settlement_intelligence_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'recovery settlement intelligence derived record is immutable'; END; $$ LANGUAGE plpgsql")
    for t in tables:op.execute(f'CREATE TRIGGER {t}_immutable BEFORE UPDATE OR DELETE ON "{t}" FOR EACH ROW EXECUTE FUNCTION reject_recovery_settlement_intelligence_mutation()')
def downgrade():
    for t in ("recovery_settlement_copilot_runs","provider_balance_statement_deliveries","recovery_closeout_reports","recovery_settlement_exception_investigations","recovery_settlement_analytics_snapshots","provider_recovery_balance_statements"):op.drop_table(t)
    op.execute("DROP FUNCTION IF EXISTS reject_recovery_settlement_intelligence_mutation()")
