"""recovery portfolio control assurance regulatory submission governance
Revision ID: 0044_recovery_portfolio_control_assurance
Revises: 0043_recovery_settlement_reconciliation_intelligence
"""
from alembic import op
import sqlalchemy as sa
revision="0044_recovery_portfolio_control_assurance"
down_revision="0043_recovery_settlement_reconciliation_intelligence"
branch_labels=None
depends_on=None

def _rls(table):
    op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
    op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
    op.execute(f'''CREATE POLICY {table}_tenant_isolation ON "{table}" USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))''')

def upgrade():
    op.create_table("regulatory_reporting_periods",
        sa.Column("reporting_period_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("period_key",sa.String(50),nullable=False),sa.Column("report_type",sa.String(80),nullable=False),sa.Column("jurisdiction",sa.String(80),nullable=False),sa.Column("start_date",sa.Date(),nullable=False),sa.Column("end_date",sa.Date(),nullable=False),sa.Column("accounting_period_ids",sa.JSON(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("period_version",sa.Integer(),nullable=False),sa.Column("created_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","period_key",name="uq_regulatory_reporting_period_key"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_regulatory_reporting_period_idem"));op.create_index("ix_regulatory_reporting_period_status","regulatory_reporting_periods",["tenant_id","status","end_date"])
    op.create_table("portfolio_control_attestations",
        sa.Column("attestation_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("reporting_period_id",sa.String(128),sa.ForeignKey("regulatory_reporting_periods.reporting_period_id",ondelete="CASCADE"),nullable=False),sa.Column("attestation_version",sa.Integer(),nullable=False),sa.Column("control_results",sa.JSON(),nullable=False),sa.Column("material_blockers",sa.JSON(),nullable=False),sa.Column("control_effectiveness_pct",sa.String(20),nullable=False),sa.Column("source_refs",sa.JSON(),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_by_actor_type",sa.String(60),nullable=False),sa.Column("created_by_actor_id",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","reporting_period_id","source_watermark_sha256",name="uq_control_attestation_watermark"),sa.UniqueConstraint("tenant_id","reporting_period_id","attestation_version",name="uq_control_attestation_version"));op.create_index("ix_control_attestation_period","portfolio_control_attestations",["tenant_id","reporting_period_id","created_at"])
    op.create_table("regulatory_submission_packages",
        sa.Column("package_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("reporting_period_id",sa.String(128),sa.ForeignKey("regulatory_reporting_periods.reporting_period_id",ondelete="RESTRICT"),nullable=False),sa.Column("attestation_id",sa.String(128),sa.ForeignKey("portfolio_control_attestations.attestation_id",ondelete="RESTRICT"),nullable=False),sa.Column("package_version",sa.Integer(),nullable=False),sa.Column("correction_of_package_id",sa.String(128),sa.ForeignKey("regulatory_submission_packages.package_id",ondelete="RESTRICT")),sa.Column("amendment_reason",sa.Text()),sa.Column("manifest",sa.JSON(),nullable=False),sa.Column("validation_results",sa.JSON(),nullable=False),sa.Column("material_blockers",sa.JSON(),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("manifest_sha256",sa.String(64),nullable=False),sa.Column("locked_manifest_sha256",sa.String(64)),sa.Column("status",sa.String(30),nullable=False),sa.Column("maker_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("checker_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("locked_at",sa.DateTime(timezone=True)),sa.Column("certified_at",sa.DateTime(timezone=True)),sa.Column("staged_at",sa.DateTime(timezone=True)),sa.Column("submitted_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","reporting_period_id","package_version",name="uq_regulatory_submission_package_version"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_regulatory_submission_package_idem"));op.create_index("ix_regulatory_submission_package_status","regulatory_submission_packages",["tenant_id","status","created_at"])
    op.create_table("control_evidence_samples",
        sa.Column("sample_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("package_id",sa.String(128),sa.ForeignKey("regulatory_submission_packages.package_id",ondelete="CASCADE"),nullable=False),sa.Column("sample_sequence",sa.Integer(),nullable=False),sa.Column("source_type",sa.String(60),nullable=False),sa.Column("source_id",sa.String(128),nullable=False),sa.Column("source_sha256",sa.String(64),nullable=False),sa.Column("selection_reason",sa.String(200),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","package_id","sample_sequence",name="uq_control_evidence_sample_sequence"));op.create_index("ix_control_evidence_sample_package","control_evidence_samples",["tenant_id","package_id","sample_sequence"])
    op.create_table("regulatory_certifications",
        sa.Column("certification_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("reporting_period_id",sa.String(128),sa.ForeignKey("regulatory_reporting_periods.reporting_period_id",ondelete="RESTRICT"),nullable=False),sa.Column("package_id",sa.String(128),sa.ForeignKey("regulatory_submission_packages.package_id",ondelete="RESTRICT"),nullable=False),sa.Column("certification_sequence",sa.Integer(),nullable=False),sa.Column("maker_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("checker_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("locked_manifest_sha256",sa.String(64),nullable=False),sa.Column("previous_certification_sha256",sa.String(64)),sa.Column("certification_sha256",sa.String(64),nullable=False),sa.Column("certified_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","package_id",name="uq_regulatory_certification_package"),sa.UniqueConstraint("tenant_id","reporting_period_id","certification_sequence",name="uq_regulatory_certification_sequence"));op.create_index("ix_regulatory_certification_chain","regulatory_certifications",["tenant_id","reporting_period_id","certification_sequence"])
    op.create_table("regulatory_submission_receipts",
        sa.Column("receipt_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("package_id",sa.String(128),sa.ForeignKey("regulatory_submission_packages.package_id",ondelete="RESTRICT"),nullable=False),sa.Column("external_submission_id",sa.String(180),nullable=False),sa.Column("submission_status",sa.String(30),nullable=False),sa.Column("external_receipt_reference",sa.String(240),nullable=False),sa.Column("receipt_metadata",sa.JSON(),nullable=False),sa.Column("submitted_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("received_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","package_id",name="uq_regulatory_submission_receipt_package"),sa.UniqueConstraint("tenant_id","external_submission_id",name="uq_regulatory_submission_external_id"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_regulatory_submission_receipt_idem"))
    op.create_table("regulatory_audit_annotations",
        sa.Column("annotation_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("package_id",sa.String(128),sa.ForeignKey("regulatory_submission_packages.package_id",ondelete="CASCADE"),nullable=False),sa.Column("reviewer_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("annotation_type",sa.String(60),nullable=False),sa.Column("body",sa.Text(),nullable=False),sa.Column("source_refs",sa.JSON(),nullable=False),sa.Column("body_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_regulatory_audit_annotation_idem"));op.create_index("ix_regulatory_audit_annotation_package","regulatory_audit_annotations",["tenant_id","package_id","created_at"])
    op.create_table("regulatory_control_audit_events",
        sa.Column("audit_event_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(64),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("reporting_period_id",sa.String(128),sa.ForeignKey("regulatory_reporting_periods.reporting_period_id",ondelete="CASCADE"),nullable=False),sa.Column("package_id",sa.String(128)),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(80),nullable=False),sa.Column("actor_type",sa.String(60),nullable=False),sa.Column("actor_id",sa.String(128),nullable=False),sa.Column("details",sa.JSON(),nullable=False),sa.Column("previous_event_sha256",sa.String(64)),sa.Column("event_sha256",sa.String(64),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","reporting_period_id","sequence",name="uq_regulatory_control_audit_sequence"));op.create_index("ix_regulatory_control_audit","regulatory_control_audit_events",["tenant_id","reporting_period_id","sequence"])
    tables=("regulatory_reporting_periods","portfolio_control_attestations","regulatory_submission_packages","control_evidence_samples","regulatory_certifications","regulatory_submission_receipts","regulatory_audit_annotations","regulatory_control_audit_events")
    for t in tables:_rls(t)
    op.execute("CREATE OR REPLACE FUNCTION reject_recovery_control_assurance_immutable_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'certified control-assurance evidence is immutable'; END; $$ LANGUAGE plpgsql")
    for t in ("portfolio_control_attestations","control_evidence_samples","regulatory_certifications","regulatory_submission_receipts","regulatory_audit_annotations","regulatory_control_audit_events"):
        op.execute(f'CREATE TRIGGER {t}_immutable BEFORE UPDATE OR DELETE ON "{t}" FOR EACH ROW EXECUTE FUNCTION reject_recovery_control_assurance_immutable_mutation()')
    op.execute("""CREATE OR REPLACE FUNCTION guard_regulatory_package_locked_fields() RETURNS trigger AS $$ BEGIN IF OLD.locked_manifest_sha256 IS NOT NULL AND (NEW.manifest IS DISTINCT FROM OLD.manifest OR NEW.manifest_sha256 IS DISTINCT FROM OLD.manifest_sha256 OR NEW.source_watermark_sha256 IS DISTINCT FROM OLD.source_watermark_sha256 OR NEW.package_version IS DISTINCT FROM OLD.package_version) THEN RAISE EXCEPTION 'locked regulatory submission package content is immutable'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql""")
    op.execute('CREATE TRIGGER regulatory_submission_package_lock_guard BEFORE UPDATE ON "regulatory_submission_packages" FOR EACH ROW EXECUTE FUNCTION guard_regulatory_package_locked_fields()')

def downgrade():
    op.execute('DROP TRIGGER IF EXISTS regulatory_submission_package_lock_guard ON "regulatory_submission_packages"');op.execute("DROP FUNCTION IF EXISTS guard_regulatory_package_locked_fields()")
    for t in ("regulatory_control_audit_events","regulatory_audit_annotations","regulatory_submission_receipts","regulatory_certifications","control_evidence_samples","regulatory_submission_packages","portfolio_control_attestations","regulatory_reporting_periods"):op.drop_table(t)
    op.execute("DROP FUNCTION IF EXISTS reject_recovery_control_assurance_immutable_mutation()")
