"""Production regulatory submission transport, acknowledgment reconciliation and amendment operations."""
from alembic import op
import sqlalchemy as sa
revision="0045_regulatory_submission_transport"
down_revision="0044_recovery_portfolio_control_assurance"
branch_labels=None
depends_on=None

def upgrade():
    # immutable trigger names include guard_regulatory_submission_releases_immutable and guard_regulatory_acknowledgments_immutable
    op.create_table("regulatory_destinations",sa.Column("destination_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("destination_key",sa.String(100),nullable=False),sa.Column("regulator_name",sa.String(180),nullable=False),sa.Column("transport_type",sa.String(40),nullable=False),sa.Column("endpoint_reference",sa.String(240),nullable=False),sa.Column("schema_name",sa.String(120),nullable=False),sa.Column("schema_version",sa.String(40),nullable=False),sa.Column("registry_version",sa.Integer(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("failure_streak",sa.Integer(),nullable=False,server_default="0"),sa.Column("circuit_open_until",sa.DateTime(timezone=True)),sa.Column("last_failure_at",sa.DateTime(timezone=True)),sa.Column("created_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","destination_key","registry_version",name="uq_reg_destination_version"))
    op.create_table("regulatory_submission_releases",sa.Column("release_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("package_id",sa.String(128),sa.ForeignKey("regulatory_submission_packages.package_id",ondelete="RESTRICT"),nullable=False),sa.Column("certification_id",sa.String(128),sa.ForeignKey("regulatory_certifications.certification_id",ondelete="RESTRICT"),nullable=False),sa.Column("destination_id",sa.String(128),sa.ForeignKey("regulatory_destinations.destination_id",ondelete="RESTRICT"),nullable=False),sa.Column("package_version",sa.Integer(),nullable=False),sa.Column("locked_manifest_sha256",sa.String(64),nullable=False),sa.Column("certification_sha256",sa.String(64),nullable=False),sa.Column("schema_name",sa.String(120),nullable=False),sa.Column("schema_version",sa.String(40),nullable=False),sa.Column("release_reason",sa.Text(),nullable=False),sa.Column("released_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("release_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("released_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","package_id",name="uq_reg_release_package"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_reg_release_idem"))
    op.create_table("regulatory_transmissions",sa.Column("transmission_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("release_id",sa.String(128),sa.ForeignKey("regulatory_submission_releases.release_id",ondelete="RESTRICT"),nullable=False),sa.Column("package_id",sa.String(128),sa.ForeignKey("regulatory_submission_packages.package_id",ondelete="RESTRICT"),nullable=False),sa.Column("destination_id",sa.String(128),sa.ForeignKey("regulatory_destinations.destination_id",ondelete="RESTRICT"),nullable=False),sa.Column("supersedes_transmission_id",sa.String(128),sa.ForeignKey("regulatory_transmissions.transmission_id",ondelete="RESTRICT")),sa.Column("dispatch_key",sa.String(180),nullable=False),sa.Column("encrypted_envelope",sa.Text(),nullable=False),sa.Column("nonce_b64",sa.String(128),nullable=False),sa.Column("envelope_signature",sa.String(128),nullable=False),sa.Column("envelope_sha256",sa.String(64),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("attempt_count",sa.Integer(),nullable=False),sa.Column("max_attempts",sa.Integer(),nullable=False),sa.Column("next_attempt_at",sa.DateTime(timezone=True)),sa.Column("lease_owner",sa.String(128)),sa.Column("lease_expires_at",sa.DateTime(timezone=True)),sa.Column("provider_message_id",sa.String(240)),sa.Column("external_submission_reference",sa.String(240)),sa.Column("deadline_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","release_id",name="uq_reg_transmission_release"),sa.UniqueConstraint("tenant_id","dispatch_key",name="uq_reg_transmission_dispatch"))
    op.create_table("regulatory_delivery_attempts",sa.Column("attempt_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("transmission_id",sa.String(128),sa.ForeignKey("regulatory_transmissions.transmission_id",ondelete="CASCADE"),nullable=False),sa.Column("attempt_sequence",sa.Integer(),nullable=False),sa.Column("worker_id",sa.String(128),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("provider_message_id",sa.String(240)),sa.Column("external_submission_reference",sa.String(240)),sa.Column("error_code",sa.String(120)),sa.Column("error_message",sa.Text()),sa.Column("next_retry_at",sa.DateTime(timezone=True)),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("attempted_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","transmission_id","attempt_sequence",name="uq_reg_delivery_attempt_sequence"))
    op.create_table("regulatory_acknowledgments",sa.Column("acknowledgment_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("transmission_id",sa.String(128),sa.ForeignKey("regulatory_transmissions.transmission_id",ondelete="RESTRICT"),nullable=False),sa.Column("destination_id",sa.String(128),sa.ForeignKey("regulatory_destinations.destination_id",ondelete="RESTRICT"),nullable=False),sa.Column("external_event_id",sa.String(180),nullable=False),sa.Column("external_submission_reference",sa.String(240),nullable=False),sa.Column("acknowledgment_status",sa.String(40),nullable=False),sa.Column("rejection_code",sa.String(120)),sa.Column("rejection_reason",sa.Text()),sa.Column("receipt_payload",sa.JSON(),nullable=False),sa.Column("signature_verified",sa.Boolean(),nullable=False),sa.Column("receipt_sha256",sa.String(64),nullable=False),sa.Column("received_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","destination_id","external_event_id",name="uq_reg_ack_external_event"))
    op.create_table("regulatory_transport_incidents",sa.Column("incident_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("transmission_id",sa.String(128),sa.ForeignKey("regulatory_transmissions.transmission_id",ondelete="CASCADE"),nullable=False),sa.Column("incident_type",sa.String(80),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("details",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("resolved_at",sa.DateTime(timezone=True)))
    op.create_table("regulatory_transmission_audit_events",sa.Column("audit_event_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("transmission_id",sa.String(128),nullable=False),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(100),nullable=False),sa.Column("actor_type",sa.String(60),nullable=False),sa.Column("actor_id",sa.String(128),nullable=False),sa.Column("details",sa.JSON(),nullable=False),sa.Column("previous_event_sha256",sa.String(64)),sa.Column("event_sha256",sa.String(64),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","transmission_id","sequence",name="uq_reg_transmission_audit_sequence"))
    for table in ["regulatory_destinations","regulatory_submission_releases","regulatory_transmissions","regulatory_delivery_attempts","regulatory_acknowledgments","regulatory_transport_incidents","regulatory_transmission_audit_events"]:
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY');op.execute(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY');op.execute(f'''CREATE POLICY {table}_tenant_rls ON {table} USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))''')
    for table in ["regulatory_submission_releases","regulatory_acknowledgments","regulatory_transmission_audit_events"]:
        op.execute(f'''CREATE OR REPLACE FUNCTION guard_{table}_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION '{table} records are immutable'; END $$''');op.execute(f'''CREATE TRIGGER trg_{table}_immutable BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION guard_{table}_immutable()''')

def downgrade():
    for t in ["regulatory_transmission_audit_events","regulatory_transport_incidents","regulatory_acknowledgments","regulatory_delivery_attempts","regulatory_transmissions","regulatory_submission_releases","regulatory_destinations"]:op.drop_table(t)
