"""Production regulatory supervisory control, reconciliation certification and compliance operations."""
from alembic import op
import sqlalchemy as sa
revision="0046_regulatory_supervisory_control"
down_revision="0045_regulatory_submission_transport"
branch_labels=None
depends_on=None

def upgrade():
    # Immutable trigger contracts include guard_regulatory_supervisory_certifications_immutable and guard_regulatory_delivery_control_attestations_immutable.
    op.create_table("regulatory_reconciliation_cases",sa.Column("case_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("transmission_id",sa.String(128),sa.ForeignKey("regulatory_transmissions.transmission_id",ondelete="RESTRICT"),nullable=False),sa.Column("package_id",sa.String(128),sa.ForeignKey("regulatory_submission_packages.package_id",ondelete="RESTRICT"),nullable=False),sa.Column("destination_id",sa.String(128),sa.ForeignKey("regulatory_destinations.destination_id",ondelete="RESTRICT"),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("severity",sa.String(20),nullable=False),sa.Column("opened_reason",sa.String(120),nullable=False),sa.Column("acknowledgment_status",sa.String(40)),sa.Column("rejection_root_cause",sa.String(80)),sa.Column("rejection_root_cause_rationale",sa.Text()),sa.Column("amendment_effectiveness",sa.String(40)),sa.Column("amendment_effectiveness_rationale",sa.Text()),sa.Column("source_snapshot_sha256",sa.String(64),nullable=False),sa.Column("source_refs",sa.JSON(),nullable=False),sa.Column("case_version",sa.Integer(),nullable=False),sa.Column("prepared_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("sla_deadline_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","transmission_id",name="uq_reg_recon_case_transmission"))
    op.create_table("regulatory_delivery_control_attestations",sa.Column("attestation_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("case_id",sa.String(128),sa.ForeignKey("regulatory_reconciliation_cases.case_id",ondelete="CASCADE"),nullable=False),sa.Column("attestation_version",sa.Integer(),nullable=False),sa.Column("controls",sa.JSON(),nullable=False),sa.Column("material_blockers",sa.JSON(),nullable=False),sa.Column("evidence_samples",sa.JSON(),nullable=False),sa.Column("control_effectiveness_pct",sa.Numeric(7,2),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("prepared_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","case_id","attestation_version",name="uq_reg_delivery_attestation_version"))
    op.create_table("regulatory_compliance_exceptions",sa.Column("exception_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("case_id",sa.String(128),sa.ForeignKey("regulatory_reconciliation_cases.case_id",ondelete="CASCADE"),nullable=False),sa.Column("exception_code",sa.String(100),nullable=False),sa.Column("severity",sa.String(20),nullable=False),sa.Column("material",sa.Boolean(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("details",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("resolved_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("resolved_at",sa.DateTime(timezone=True)),sa.Column("resolution_rationale",sa.Text()))
    op.create_table("regulatory_supervisory_certifications",sa.Column("certification_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("case_id",sa.String(128),sa.ForeignKey("regulatory_reconciliation_cases.case_id",ondelete="RESTRICT"),nullable=False),sa.Column("attestation_id",sa.String(128),sa.ForeignKey("regulatory_delivery_control_attestations.attestation_id",ondelete="RESTRICT"),nullable=False),sa.Column("certification_sequence",sa.Integer(),nullable=False),sa.Column("prepared_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("supervisor_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("conclusion",sa.String(40),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("previous_certification_sha256",sa.String(64)),sa.Column("certification_sha256",sa.String(64),nullable=False),sa.Column("certified_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","case_id","certification_sequence",name="uq_reg_supervisory_cert_sequence"),sa.UniqueConstraint("tenant_id","attestation_id",name="uq_reg_supervisory_cert_attestation"))
    op.create_table("regulatory_supervisor_annotations",sa.Column("annotation_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("case_id",sa.String(128),sa.ForeignKey("regulatory_reconciliation_cases.case_id",ondelete="CASCADE"),nullable=False),sa.Column("reviewer_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("annotation_type",sa.String(60),nullable=False),sa.Column("body",sa.Text(),nullable=False),sa.Column("source_refs",sa.JSON(),nullable=False),sa.Column("body_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_reg_supervisor_annotation_idem"))
    op.create_table("regulatory_supervisor_correspondence",sa.Column("correspondence_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("case_id",sa.String(128),sa.ForeignKey("regulatory_reconciliation_cases.case_id",ondelete="CASCADE"),nullable=False),sa.Column("direction",sa.String(20),nullable=False),sa.Column("channel",sa.String(30),nullable=False),sa.Column("subject",sa.String(200),nullable=False),sa.Column("body",sa.Text(),nullable=False),sa.Column("external_reference",sa.String(240)),sa.Column("actor_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_reg_supervisor_corr_idem"))
    op.create_table("regulatory_calendar_deadlines",sa.Column("deadline_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("destination_id",sa.String(128),sa.ForeignKey("regulatory_destinations.destination_id",ondelete="RESTRICT"),nullable=False),sa.Column("deadline_key",sa.String(120),nullable=False),sa.Column("due_date",sa.Date(),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("linked_case_id",sa.String(128),sa.ForeignKey("regulatory_reconciliation_cases.case_id",ondelete="SET NULL")),sa.Column("created_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","destination_id","deadline_key",name="uq_reg_calendar_deadline_key"))
    op.create_table("regulatory_supervisory_audit_events",sa.Column("audit_event_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("case_id",sa.String(128),sa.ForeignKey("regulatory_reconciliation_cases.case_id",ondelete="CASCADE"),nullable=False),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(90),nullable=False),sa.Column("actor_type",sa.String(60),nullable=False),sa.Column("actor_id",sa.String(128),nullable=False),sa.Column("details",sa.JSON(),nullable=False),sa.Column("previous_event_sha256",sa.String(64)),sa.Column("event_sha256",sa.String(64),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","case_id","sequence",name="uq_reg_supervisory_audit_sequence"))
    tables=["regulatory_reconciliation_cases","regulatory_delivery_control_attestations","regulatory_compliance_exceptions","regulatory_supervisory_certifications","regulatory_supervisor_annotations","regulatory_supervisor_correspondence","regulatory_calendar_deadlines","regulatory_supervisory_audit_events"]
    for table in tables:
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY');op.execute(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY');op.execute(f'''CREATE POLICY {table}_tenant_rls ON {table} USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))''')
    for table in ["regulatory_delivery_control_attestations","regulatory_supervisory_certifications","regulatory_supervisor_annotations","regulatory_supervisor_correspondence","regulatory_supervisory_audit_events"]:
        op.execute(f'''CREATE OR REPLACE FUNCTION guard_{table}_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION '{table} records are immutable'; END $$''');op.execute(f'''CREATE TRIGGER trg_{table}_immutable BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION guard_{table}_immutable()''')

def downgrade():
    for t in ["regulatory_supervisory_audit_events","regulatory_calendar_deadlines","regulatory_supervisor_correspondence","regulatory_supervisor_annotations","regulatory_supervisory_certifications","regulatory_compliance_exceptions","regulatory_delivery_control_attestations","regulatory_reconciliation_cases"]:op.drop_table(t)
