"""Regulatory examination, inquiry response and supervisory evidence management."""
from alembic import op
import sqlalchemy as sa
revision="0047_regulatory_examination"
down_revision="0046_regulatory_supervisory_control"
branch_labels=None
depends_on=None

def upgrade():
    op.create_table("regulatory_examination_cases",
        sa.Column("examination_case_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("supervisory_case_id",sa.String(128),sa.ForeignKey("regulatory_reconciliation_cases.case_id",ondelete="RESTRICT"),nullable=False),sa.Column("transmission_id",sa.String(128),sa.ForeignKey("regulatory_transmissions.transmission_id",ondelete="RESTRICT"),nullable=False),sa.Column("package_id",sa.String(128),sa.ForeignKey("regulatory_submission_packages.package_id",ondelete="RESTRICT"),nullable=False),sa.Column("destination_id",sa.String(128),sa.ForeignKey("regulatory_destinations.destination_id",ondelete="RESTRICT"),nullable=False),sa.Column("external_inquiry_reference",sa.String(240),nullable=False),sa.Column("inquiry_type",sa.String(60),nullable=False),sa.Column("question_classification",sa.String(80),nullable=False),sa.Column("inquiry_summary",sa.Text(),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("severity",sa.String(20),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("source_refs",sa.JSON(),nullable=False),sa.Column("case_version",sa.Integer(),nullable=False),sa.Column("assigned_preparer_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("response_due_at",sa.DateTime(timezone=True),nullable=False),sa.Column("follow_up_due_at",sa.DateTime(timezone=True)),sa.Column("created_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","external_inquiry_reference",name="uq_reg_exam_external_inquiry"))
    op.create_index("ix_reg_exam_case_status","regulatory_examination_cases",["tenant_id","status","response_due_at"])
    op.create_table("regulatory_examination_document_requests",sa.Column("document_request_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("examination_case_id",sa.String(128),sa.ForeignKey("regulatory_examination_cases.examination_case_id",ondelete="CASCADE"),nullable=False),sa.Column("request_code",sa.String(120),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("requested_refs",sa.JSON(),nullable=False),sa.Column("satisfied_refs",sa.JSON(),nullable=False),sa.Column("created_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("satisfied_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("satisfied_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","examination_case_id","request_code",name="uq_reg_exam_doc_request_code"))
    op.create_table("regulatory_examination_evidence_packs",sa.Column("evidence_pack_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("examination_case_id",sa.String(128),sa.ForeignKey("regulatory_examination_cases.examination_case_id",ondelete="CASCADE"),nullable=False),sa.Column("pack_version",sa.Integer(),nullable=False),sa.Column("evidence_refs",sa.JSON(),nullable=False),sa.Column("citations",sa.JSON(),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("locked_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","examination_case_id","pack_version",name="uq_reg_exam_pack_version"))
    op.create_table("regulatory_examination_responses",sa.Column("response_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("examination_case_id",sa.String(128),sa.ForeignKey("regulatory_examination_cases.examination_case_id",ondelete="CASCADE"),nullable=False),sa.Column("evidence_pack_id",sa.String(128),sa.ForeignKey("regulatory_examination_evidence_packs.evidence_pack_id",ondelete="RESTRICT"),nullable=False),sa.Column("response_version",sa.Integer(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("response_text",sa.Text(),nullable=False),sa.Column("cited_refs",sa.JSON(),nullable=False),sa.Column("ai_assisted",sa.Boolean(),nullable=False),sa.Column("ai_metadata",sa.JSON(),nullable=False),sa.Column("prepared_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("approved_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("approval_rationale",sa.Text()),sa.Column("previous_response_sha256",sa.String(64)),sa.Column("response_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("sent_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","examination_case_id","response_version",name="uq_reg_exam_response_version"),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_reg_exam_response_idem"))
    op.create_table("regulatory_examination_correspondence",sa.Column("correspondence_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("examination_case_id",sa.String(128),sa.ForeignKey("regulatory_examination_cases.examination_case_id",ondelete="CASCADE"),nullable=False),sa.Column("response_id",sa.String(128),sa.ForeignKey("regulatory_examination_responses.response_id",ondelete="SET NULL")),sa.Column("direction",sa.String(20),nullable=False),sa.Column("channel",sa.String(40),nullable=False),sa.Column("subject",sa.String(240),nullable=False),sa.Column("body",sa.Text(),nullable=False),sa.Column("external_reference",sa.String(240)),sa.Column("supplemental_submission_reference",sa.String(240)),sa.Column("delivered",sa.Boolean(),nullable=False),sa.Column("actor_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_reg_exam_corr_idem"))
    op.create_table("regulatory_examination_findings",sa.Column("finding_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("examination_case_id",sa.String(128),sa.ForeignKey("regulatory_examination_cases.examination_case_id",ondelete="CASCADE"),nullable=False),sa.Column("finding_code",sa.String(120),nullable=False),sa.Column("severity",sa.String(20),nullable=False),sa.Column("material",sa.Boolean(),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("source_refs",sa.JSON(),nullable=False),sa.Column("created_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("resolved_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("resolved_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","examination_case_id","finding_code",name="uq_reg_exam_finding_code"))
    op.create_table("regulatory_remediation_commitments",sa.Column("commitment_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("examination_case_id",sa.String(128),sa.ForeignKey("regulatory_examination_cases.examination_case_id",ondelete="CASCADE"),nullable=False),sa.Column("commitment_key",sa.String(120),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("owner_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("evidence_refs",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","examination_case_id","commitment_key",name="uq_reg_exam_commitment_key"))
    op.create_table("regulatory_examination_audit_events",sa.Column("audit_event_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("examination_case_id",sa.String(128),sa.ForeignKey("regulatory_examination_cases.examination_case_id",ondelete="CASCADE"),nullable=False),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(100),nullable=False),sa.Column("actor_type",sa.String(60),nullable=False),sa.Column("actor_id",sa.String(128),nullable=False),sa.Column("details",sa.JSON(),nullable=False),sa.Column("previous_event_sha256",sa.String(64)),sa.Column("event_sha256",sa.String(64),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","examination_case_id","sequence",name="uq_reg_exam_audit_sequence"))
    tables=["regulatory_examination_cases","regulatory_examination_document_requests","regulatory_examination_evidence_packs","regulatory_examination_responses","regulatory_examination_correspondence","regulatory_examination_findings","regulatory_remediation_commitments","regulatory_examination_audit_events"]
    for table in tables:
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY')
        op.execute(f'''CREATE POLICY {table}_tenant_isolation ON {table} USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))''')
    # Explicit immutable trigger contracts for auditability:
    # guard_regulatory_examination_evidence_packs_immutable
    # guard_regulatory_examination_responses_finalized_immutable
    # guard_regulatory_examination_correspondence_immutable
    # guard_regulatory_examination_audit_events_immutable
    op.execute('''CREATE OR REPLACE FUNCTION guard_regulatory_examination_immutable() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'regulatory examination provenance is immutable'; END; $$ LANGUAGE plpgsql''')
    for table in ["regulatory_examination_evidence_packs","regulatory_examination_correspondence","regulatory_examination_audit_events"]:
        op.execute(f'CREATE TRIGGER guard_{table}_immutable BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION guard_regulatory_examination_immutable()')
    op.execute('''CREATE OR REPLACE FUNCTION guard_regulatory_examination_response_finalized() RETURNS trigger AS $$ BEGIN IF OLD.status IN ('approved','sent') THEN RAISE EXCEPTION 'approved/sent regulatory examination response is immutable'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql''')
    op.execute('CREATE TRIGGER guard_regulatory_examination_responses_finalized_immutable BEFORE UPDATE OR DELETE ON regulatory_examination_responses FOR EACH ROW EXECUTE FUNCTION guard_regulatory_examination_response_finalized()')

def downgrade():
    for t in ["regulatory_examination_audit_events","regulatory_remediation_commitments","regulatory_examination_findings","regulatory_examination_correspondence","regulatory_examination_responses","regulatory_examination_evidence_packs","regulatory_examination_document_requests","regulatory_examination_cases"]:op.drop_table(t)
    op.execute('DROP FUNCTION IF EXISTS guard_regulatory_examination_response_finalized')
    op.execute('DROP FUNCTION IF EXISTS guard_regulatory_examination_immutable')
