"""Regulatory examination findings remediation, corrective action governance and closure assurance."""
from alembic import op
import sqlalchemy as sa
revision="0048_regulatory_remediation"
down_revision="0047_regulatory_examination"
branch_labels=None
depends_on=None

def upgrade():
    op.create_table("regulatory_remediation_plans",
        sa.Column("plan_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("examination_case_id",sa.String(128),sa.ForeignKey("regulatory_examination_cases.examination_case_id",ondelete="CASCADE"),nullable=False),sa.Column("finding_id",sa.String(128),sa.ForeignKey("regulatory_examination_findings.finding_id",ondelete="RESTRICT"),nullable=False),sa.Column("finding_code",sa.String(120),nullable=False),sa.Column("plan_version",sa.Integer(),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("root_cause",sa.Text(),nullable=False),sa.Column("corrective_action_summary",sa.Text(),nullable=False),sa.Column("preventive_action_summary",sa.Text(),nullable=False),sa.Column("control_redesign_proposal",sa.Text(),nullable=False),sa.Column("financial_impact_analysis",sa.Text(),nullable=False),sa.Column("accounting_impact_analysis",sa.Text(),nullable=False),sa.Column("risk_score",sa.Integer(),nullable=False),sa.Column("risk_level",sa.String(20),nullable=False),sa.Column("ai_assisted",sa.Boolean(),nullable=False),sa.Column("ai_recommendation",sa.JSON(),nullable=False),sa.Column("ai_authority",sa.String(20),nullable=False),sa.Column("owner_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("prepared_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("approved_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("approval_rationale",sa.Text()),sa.Column("previous_plan_sha256",sa.String(64)),sa.Column("plan_sha256",sa.String(64),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","finding_id","plan_version",name="uq_reg_rem_plan_version"))
    op.create_index("ix_reg_rem_plan_status","regulatory_remediation_plans",["tenant_id","status","due_at"])
    op.create_table("regulatory_remediation_tasks",sa.Column("task_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("plan_id",sa.String(128),sa.ForeignKey("regulatory_remediation_plans.plan_id",ondelete="CASCADE"),nullable=False),sa.Column("task_key",sa.String(120),nullable=False),sa.Column("task_type",sa.String(50),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("owner_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("dependency_keys",sa.JSON(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True),nullable=False),sa.Column("evidence_refs",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","plan_id","task_key",name="uq_reg_rem_task_key"))
    op.create_table("regulatory_remediation_checkpoints",sa.Column("checkpoint_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("plan_id",sa.String(128),sa.ForeignKey("regulatory_remediation_plans.plan_id",ondelete="CASCADE"),nullable=False),sa.Column("checkpoint_key",sa.String(120),nullable=False),sa.Column("checkpoint_type",sa.String(50),nullable=False),sa.Column("evidence_refs",sa.JSON(),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("locked_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","plan_id","checkpoint_key",name="uq_reg_rem_checkpoint_key"))
    op.create_table("regulatory_control_retests",sa.Column("retest_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("plan_id",sa.String(128),sa.ForeignKey("regulatory_remediation_plans.plan_id",ondelete="CASCADE"),nullable=False),sa.Column("control_key",sa.String(120),nullable=False),sa.Column("retest_sequence",sa.Integer(),nullable=False),sa.Column("methodology",sa.Text(),nullable=False),sa.Column("expected_result",sa.Text(),nullable=False),sa.Column("observed_result",sa.Text(),nullable=False),sa.Column("outcome",sa.String(20),nullable=False),sa.Column("evidence_refs",sa.JSON(),nullable=False),sa.Column("retested_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("retested_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","plan_id","control_key","retest_sequence",name="uq_reg_rem_retest_seq"))
    op.create_table("regulatory_remediation_waivers",sa.Column("waiver_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("plan_id",sa.String(128),sa.ForeignKey("regulatory_remediation_plans.plan_id",ondelete="CASCADE"),nullable=False),sa.Column("waiver_key",sa.String(120),nullable=False),sa.Column("waiver_type",sa.String(40),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("risk_acceptance",sa.Text(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("requested_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("decided_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("decision_rationale",sa.Text()),sa.Column("expires_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("decided_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","plan_id","waiver_key",name="uq_reg_rem_waiver_key"))
    op.create_table("regulatory_remediation_followups",sa.Column("followup_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("plan_id",sa.String(128),sa.ForeignKey("regulatory_remediation_plans.plan_id",ondelete="CASCADE"),nullable=False),sa.Column("response_version",sa.Integer(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("response_text",sa.Text(),nullable=False),sa.Column("cited_refs",sa.JSON(),nullable=False),sa.Column("prepared_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("approved_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("previous_response_sha256",sa.String(64)),sa.Column("response_sha256",sa.String(64),nullable=False),sa.Column("approval_rationale",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","plan_id","response_version",name="uq_reg_rem_followup_version"))
    op.create_table("regulatory_remediation_closure_certifications",sa.Column("certification_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("plan_id",sa.String(128),sa.ForeignKey("regulatory_remediation_plans.plan_id",ondelete="CASCADE"),nullable=False),sa.Column("certification_sequence",sa.Integer(),nullable=False),sa.Column("conclusion",sa.String(30),nullable=False),sa.Column("closure_rationale",sa.Text(),nullable=False),sa.Column("certified_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("previous_certification_sha256",sa.String(64)),sa.Column("certification_sha256",sa.String(64),nullable=False),sa.Column("certified_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","plan_id","certification_sequence",name="uq_reg_rem_close_cert_seq"))
    op.create_table("regulatory_remediation_audit_events",sa.Column("audit_event_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("plan_id",sa.String(128),sa.ForeignKey("regulatory_remediation_plans.plan_id",ondelete="CASCADE"),nullable=False),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(100),nullable=False),sa.Column("actor_type",sa.String(60),nullable=False),sa.Column("actor_id",sa.String(128),nullable=False),sa.Column("details",sa.JSON(),nullable=False),sa.Column("previous_event_sha256",sa.String(64)),sa.Column("event_sha256",sa.String(64),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","plan_id","sequence",name="uq_reg_rem_audit_seq"))
    tables=["regulatory_remediation_plans","regulatory_remediation_tasks","regulatory_remediation_checkpoints","regulatory_control_retests","regulatory_remediation_waivers","regulatory_remediation_followups","regulatory_remediation_closure_certifications","regulatory_remediation_audit_events"]
    for table in tables:
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY');op.execute(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY');op.execute(f'''CREATE POLICY {table}_tenant_isolation ON {table} USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))''')
    # Explicit immutable trigger contracts:
    # guard_regulatory_remediation_checkpoints_immutable
    # guard_regulatory_control_retests_immutable
    # guard_regulatory_remediation_followups_finalized_immutable
    # guard_regulatory_remediation_closure_certifications_immutable
    # guard_regulatory_remediation_audit_events_immutable
    op.execute("""CREATE OR REPLACE FUNCTION guard_regulatory_remediation_immutable() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'regulatory remediation provenance is immutable'; END; $$ LANGUAGE plpgsql""")
    for table in ["regulatory_remediation_checkpoints","regulatory_control_retests","regulatory_remediation_closure_certifications","regulatory_remediation_audit_events"]:
        op.execute(f'CREATE TRIGGER guard_{table}_immutable BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION guard_regulatory_remediation_immutable()')
    op.execute("""CREATE OR REPLACE FUNCTION guard_regulatory_remediation_followup_finalized() RETURNS trigger AS $$ BEGIN IF OLD.status='approved' THEN RAISE EXCEPTION 'approved regulatory remediation follow-up is immutable'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql""")
    op.execute('CREATE TRIGGER guard_regulatory_remediation_followups_finalized_immutable BEFORE UPDATE OR DELETE ON regulatory_remediation_followups FOR EACH ROW EXECUTE FUNCTION guard_regulatory_remediation_followup_finalized()')

def downgrade():
    for t in ["regulatory_remediation_audit_events","regulatory_remediation_closure_certifications","regulatory_remediation_followups","regulatory_remediation_waivers","regulatory_control_retests","regulatory_remediation_checkpoints","regulatory_remediation_tasks","regulatory_remediation_plans"]:op.drop_table(t)
    op.execute('DROP FUNCTION IF EXISTS guard_regulatory_remediation_followup_finalized');op.execute('DROP FUNCTION IF EXISTS guard_regulatory_remediation_immutable')
