"""Regulatory remediation portfolio oversight, cross-finding risk and enterprise control validation."""
from alembic import op
import sqlalchemy as sa
revision="0049_regulatory_portfolio_oversight"
down_revision="0048_regulatory_remediation"
branch_labels=None
depends_on=None

def upgrade():
    op.create_table("enterprise_control_library",sa.Column("control_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("control_key",sa.String(120),nullable=False),sa.Column("control_version",sa.Integer(),nullable=False),sa.Column("name",sa.String(240),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("control_family",sa.String(120),nullable=False),sa.Column("owner_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("created_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","control_key","control_version",name="uq_enterprise_control_version"))
    op.create_table("regulatory_control_finding_maps",sa.Column("mapping_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("control_id",sa.String(128),sa.ForeignKey("enterprise_control_library.control_id",ondelete="RESTRICT"),nullable=False),sa.Column("plan_id",sa.String(128),sa.ForeignKey("regulatory_remediation_plans.plan_id",ondelete="RESTRICT"),nullable=False),sa.Column("mapping_rationale",sa.Text(),nullable=False),sa.Column("mapped_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("mapped_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","control_id","plan_id",name="uq_reg_port_control_plan"))
    op.create_table("regulatory_portfolio_snapshots",sa.Column("snapshot_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("period_key",sa.String(120),nullable=False),sa.Column("snapshot_version",sa.Integer(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("plan_count",sa.Integer(),nullable=False),sa.Column("open_plan_count",sa.Integer(),nullable=False),sa.Column("overdue_task_count",sa.Integer(),nullable=False),sa.Column("repeat_finding_count",sa.Integer(),nullable=False),sa.Column("recurring_root_cause_count",sa.Integer(),nullable=False),sa.Column("systemic_cluster_count",sa.Integer(),nullable=False),sa.Column("average_risk_score",sa.Integer(),nullable=False),sa.Column("portfolio_risk_score",sa.Integer(),nullable=False),sa.Column("control_effectiveness_pct",sa.Integer(),nullable=False),sa.Column("critical_path",sa.JSON(),nullable=False),sa.Column("portfolio_metrics",sa.JSON(),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("prepared_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","period_key","snapshot_version",name="uq_reg_port_snapshot_version"))
    op.create_index("ix_reg_port_snapshot_period","regulatory_portfolio_snapshots",["tenant_id","period_key","created_at"])
    op.create_table("regulatory_systemic_risk_clusters",sa.Column("cluster_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("snapshot_id",sa.String(128),sa.ForeignKey("regulatory_portfolio_snapshots.snapshot_id",ondelete="CASCADE"),nullable=False),sa.Column("cluster_key",sa.String(200),nullable=False),sa.Column("cluster_type",sa.String(50),nullable=False),sa.Column("severity",sa.String(20),nullable=False),sa.Column("member_plan_ids",sa.JSON(),nullable=False),sa.Column("member_count",sa.Integer(),nullable=False),sa.Column("recommendation",sa.JSON(),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","snapshot_id","cluster_key",name="uq_reg_port_cluster_key"))
    op.create_table("regulatory_control_testing_campaigns",sa.Column("campaign_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("snapshot_id",sa.String(128),sa.ForeignKey("regulatory_portfolio_snapshots.snapshot_id",ondelete="RESTRICT"),nullable=False),sa.Column("campaign_key",sa.String(120),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("methodology",sa.Text(),nullable=False),sa.Column("control_ids",sa.JSON(),nullable=False),sa.Column("prepared_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","snapshot_id","campaign_key",name="uq_reg_port_campaign_key"))
    op.create_table("regulatory_control_testing_results",sa.Column("result_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("campaign_id",sa.String(128),sa.ForeignKey("regulatory_control_testing_campaigns.campaign_id",ondelete="CASCADE"),nullable=False),sa.Column("control_id",sa.String(128),sa.ForeignKey("enterprise_control_library.control_id",ondelete="RESTRICT"),nullable=False),sa.Column("outcome",sa.String(20),nullable=False),sa.Column("observations",sa.Text(),nullable=False),sa.Column("evidence_refs",sa.JSON(),nullable=False),sa.Column("tested_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("tested_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","campaign_id","control_id",name="uq_reg_port_test_control"))
    op.create_table("regulatory_portfolio_risk_acceptances",sa.Column("acceptance_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("snapshot_id",sa.String(128),sa.ForeignKey("regulatory_portfolio_snapshots.snapshot_id",ondelete="CASCADE"),nullable=False),sa.Column("risk_key",sa.String(200),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("requested_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("decided_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT")),sa.Column("decision_rationale",sa.Text()),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("decided_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","snapshot_id","risk_key",name="uq_reg_port_risk_key"))
    op.create_table("regulatory_management_attestations",sa.Column("attestation_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("snapshot_id",sa.String(128),sa.ForeignKey("regulatory_portfolio_snapshots.snapshot_id",ondelete="CASCADE"),nullable=False),sa.Column("conclusion",sa.String(30),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("attested_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("attestation_sha256",sa.String(64),nullable=False),sa.Column("attested_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","snapshot_id",name="uq_reg_port_management_attestation"))
    op.create_table("regulatory_portfolio_certifications",sa.Column("certification_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("snapshot_id",sa.String(128),sa.ForeignKey("regulatory_portfolio_snapshots.snapshot_id",ondelete="CASCADE"),nullable=False),sa.Column("certification_sequence",sa.Integer(),nullable=False),sa.Column("conclusion",sa.String(30),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("certified_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("previous_certification_sha256",sa.String(64)),sa.Column("certification_sha256",sa.String(64),nullable=False),sa.Column("certified_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","snapshot_id","certification_sequence",name="uq_reg_port_cert_seq"))
    op.create_table("regulatory_portfolio_audit_events",sa.Column("audit_event_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("snapshot_id",sa.String(128),sa.ForeignKey("regulatory_portfolio_snapshots.snapshot_id",ondelete="CASCADE"),nullable=False),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(100),nullable=False),sa.Column("actor_type",sa.String(60),nullable=False),sa.Column("actor_id",sa.String(128),nullable=False),sa.Column("details",sa.JSON(),nullable=False),sa.Column("previous_event_sha256",sa.String(64)),sa.Column("event_sha256",sa.String(64),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","snapshot_id","sequence",name="uq_reg_port_audit_seq"))
    tables=["enterprise_control_library","regulatory_control_finding_maps","regulatory_portfolio_snapshots","regulatory_systemic_risk_clusters","regulatory_control_testing_campaigns","regulatory_control_testing_results","regulatory_portfolio_risk_acceptances","regulatory_management_attestations","regulatory_portfolio_certifications","regulatory_portfolio_audit_events"]
    for table in tables:
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY');op.execute(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY');op.execute(f'''CREATE POLICY {table}_tenant_isolation ON {table} USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))''')
    # Explicit immutable trigger contracts for auditors/source-contract verification:
    # guard_regulatory_portfolio_snapshots_immutable
    # guard_regulatory_systemic_risk_clusters_immutable
    # guard_regulatory_control_testing_results_immutable
    # guard_regulatory_management_attestations_immutable
    # guard_regulatory_portfolio_certifications_immutable
    # guard_regulatory_portfolio_audit_events_immutable
    op.execute("""CREATE OR REPLACE FUNCTION guard_regulatory_portfolio_immutable() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'regulatory portfolio assurance provenance is immutable'; END; $$ LANGUAGE plpgsql""")
    for table in ["regulatory_portfolio_snapshots","regulatory_systemic_risk_clusters","regulatory_control_testing_results","regulatory_management_attestations","regulatory_portfolio_certifications","regulatory_portfolio_audit_events"]:
        op.execute(f'CREATE TRIGGER guard_{table}_immutable BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION guard_regulatory_portfolio_immutable()')

def downgrade():
    for t in ["regulatory_portfolio_audit_events","regulatory_portfolio_certifications","regulatory_management_attestations","regulatory_portfolio_risk_acceptances","regulatory_control_testing_results","regulatory_control_testing_campaigns","regulatory_systemic_risk_clusters","regulatory_portfolio_snapshots","regulatory_control_finding_maps","enterprise_control_library"]:op.drop_table(t)
    op.execute('DROP FUNCTION IF EXISTS guard_regulatory_portfolio_immutable')
