"""Predictive remediation risk intelligence, scenario analysis and assurance forecasting."""
from alembic import op
import sqlalchemy as sa
revision="0050_regulatory_predictive_assurance"
down_revision="0049_regulatory_portfolio_oversight"
branch_labels=None
depends_on=None

def upgrade():
    op.create_table("regulatory_predictive_forecasts",sa.Column("forecast_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("snapshot_id",sa.String(128),sa.ForeignKey("regulatory_portfolio_snapshots.snapshot_id",ondelete="RESTRICT"),nullable=False),sa.Column("forecast_version",sa.Integer(),nullable=False),sa.Column("horizon_days",sa.Integer(),nullable=False),sa.Column("model_version",sa.String(120),nullable=False),sa.Column("remediation_failure_risk",sa.Integer(),nullable=False),sa.Column("deadline_breach_risk",sa.Integer(),nullable=False),sa.Column("recurrence_risk",sa.Integer(),nullable=False),sa.Column("control_deterioration_risk",sa.Integer(),nullable=False),sa.Column("assurance_readiness_forecast",sa.Integer(),nullable=False),sa.Column("drivers",sa.JSON(),nullable=False),sa.Column("explanation",sa.JSON(),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("prepared_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","snapshot_id","forecast_version",name="uq_reg_predictive_forecast_version"))
    op.create_index("ix_reg_predictive_forecast_snapshot","regulatory_predictive_forecasts",["tenant_id","snapshot_id"])
    op.create_table("regulatory_scenario_simulations",sa.Column("simulation_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("forecast_id",sa.String(128),sa.ForeignKey("regulatory_predictive_forecasts.forecast_id",ondelete="CASCADE"),nullable=False),sa.Column("scenario_key",sa.String(140),nullable=False),sa.Column("scenario_type",sa.String(60),nullable=False),sa.Column("assumptions",sa.JSON(),nullable=False),sa.Column("projected_metrics",sa.JSON(),nullable=False),sa.Column("recommendation",sa.JSON(),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","forecast_id","scenario_key",name="uq_reg_scenario_key"))
    op.create_table("regulatory_predictive_reviews",sa.Column("review_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("forecast_id",sa.String(128),sa.ForeignKey("regulatory_predictive_forecasts.forecast_id",ondelete="CASCADE"),nullable=False),sa.Column("review_sequence",sa.Integer(),nullable=False),sa.Column("disposition",sa.String(30),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("selected_management_actions",sa.JSON(),nullable=False),sa.Column("reviewed_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("reviewed_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","forecast_id","review_sequence",name="uq_reg_predictive_review_seq"))
def downgrade():
    op.drop_table("regulatory_predictive_reviews");op.drop_table("regulatory_scenario_simulations");op.drop_index("ix_reg_predictive_forecast_snapshot",table_name="regulatory_predictive_forecasts");op.drop_table("regulatory_predictive_forecasts")
