"""Continuous assurance, control drift detection and supervisory early warning."""
from alembic import op
import sqlalchemy as sa
revision="0051_regulatory_continuous_assurance"
down_revision="0050_regulatory_predictive_assurance"
branch_labels=None
depends_on=None

def upgrade():
    op.create_table("regulatory_assurance_observations",sa.Column("observation_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("forecast_id",sa.String(128),sa.ForeignKey("regulatory_predictive_forecasts.forecast_id",ondelete="RESTRICT"),nullable=False),sa.Column("observation_key",sa.String(140),nullable=False),sa.Column("signal_type",sa.String(80),nullable=False),sa.Column("control_id",sa.String(128)),sa.Column("finding_id",sa.String(128)),sa.Column("commitment_id",sa.String(128)),sa.Column("observed_value",sa.Integer(),nullable=False),sa.Column("expected_value",sa.Integer(),nullable=False),sa.Column("evidence_age_days",sa.Integer(),nullable=False),sa.Column("evidence_refs",sa.JSON(),nullable=False),sa.Column("source_watermark_sha256",sa.String(64),nullable=False),sa.Column("observed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("recorded_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.UniqueConstraint("tenant_id","forecast_id","observation_key","observed_at",name="uq_reg_assurance_observation"))
    op.create_index("ix_reg_assurance_forecast","regulatory_assurance_observations",["tenant_id","forecast_id"])
    op.create_table("regulatory_control_drift_events",sa.Column("drift_event_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("observation_id",sa.String(128),sa.ForeignKey("regulatory_assurance_observations.observation_id",ondelete="RESTRICT"),nullable=False),sa.Column("severity",sa.String(24),nullable=False),sa.Column("drift_score",sa.Integer(),nullable=False),sa.Column("threshold_version",sa.String(80),nullable=False),sa.Column("indicators",sa.JSON(),nullable=False),sa.Column("recommendation",sa.JSON(),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("detected_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_reg_drift_status","regulatory_control_drift_events",["tenant_id","status","severity"])
    op.create_table("regulatory_early_warnings",sa.Column("warning_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("drift_event_id",sa.String(128),sa.ForeignKey("regulatory_control_drift_events.drift_event_id",ondelete="CASCADE"),nullable=False),sa.Column("warning_type",sa.String(80),nullable=False),sa.Column("priority",sa.String(24),nullable=False),sa.Column("message",sa.Text(),nullable=False),sa.Column("requires_human_investigation",sa.Boolean(),nullable=False),sa.Column("emitted_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("regulatory_assurance_investigations",sa.Column("investigation_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("drift_event_id",sa.String(128),sa.ForeignKey("regulatory_control_drift_events.drift_event_id",ondelete="RESTRICT"),nullable=False),sa.Column("review_sequence",sa.Integer(),nullable=False),sa.Column("disposition",sa.String(40),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("corrective_response",sa.JSON(),nullable=False),sa.Column("reviewed_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("reviewed_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","drift_event_id","review_sequence",name="uq_reg_assurance_investigation_seq"))
def downgrade():
    op.drop_table("regulatory_assurance_investigations");op.drop_table("regulatory_early_warnings");op.drop_index("ix_reg_drift_status",table_name="regulatory_control_drift_events");op.drop_table("regulatory_control_drift_events");op.drop_index("ix_reg_assurance_forecast",table_name="regulatory_assurance_observations");op.drop_table("regulatory_assurance_observations")
