"""Continuous control testing, evidence sampling and independent assurance orchestration."""
from alembic import op
import sqlalchemy as sa
revision="0052_regulatory_control_testing"
down_revision="0051_regulatory_continuous_assurance"
branch_labels=None
depends_on=None

def upgrade():
    op.create_table("regulatory_control_test_plans",sa.Column("test_plan_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("control_id",sa.String(128),nullable=False),sa.Column("test_type",sa.String(48),nullable=False),sa.Column("frequency",sa.String(40),nullable=False),sa.Column("plan_version",sa.Integer(),nullable=False),sa.Column("sampling_strategy",sa.JSON(),nullable=False),sa.Column("evidence_requirements",sa.JSON(),nullable=False),sa.Column("independent_tester_role",sa.String(80),nullable=False),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("created_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","control_id","plan_version",name="uq_reg_control_test_plan_version"))
    op.create_index("ix_reg_control_test_plan","regulatory_control_test_plans",["tenant_id","control_id","active"])
    op.create_table("regulatory_control_test_runs",sa.Column("test_run_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("test_plan_id",sa.String(128),sa.ForeignKey("regulatory_control_test_plans.test_plan_id",ondelete="RESTRICT"),nullable=False),sa.Column("control_id",sa.String(128),nullable=False),sa.Column("test_window_start",sa.DateTime(timezone=True),nullable=False),sa.Column("test_window_end",sa.DateTime(timezone=True),nullable=False),sa.Column("population_size",sa.Integer(),nullable=False),sa.Column("population_watermark_sha256",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("scheduled_retest_at",sa.DateTime(timezone=True)),sa.Column("prepared_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_reg_control_test_run","regulatory_control_test_runs",["tenant_id","control_id","status"])
    op.create_table("regulatory_evidence_samples",sa.Column("sample_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("test_run_id",sa.String(128),sa.ForeignKey("regulatory_control_test_runs.test_run_id",ondelete="CASCADE"),nullable=False),sa.Column("sample_key",sa.String(160),nullable=False),sa.Column("entity_id",sa.String(128)),sa.Column("risk_score",sa.Integer(),nullable=False),sa.Column("selection_reason",sa.Text(),nullable=False),sa.Column("evidence_refs",sa.JSON(),nullable=False),sa.Column("provenance",sa.JSON(),nullable=False),sa.Column("result",sa.String(24),nullable=False),sa.Column("exception_code",sa.String(80)),sa.Column("tested_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","test_run_id","sample_key",name="uq_reg_evidence_sample_key"))
    op.create_index("ix_reg_evidence_sample","regulatory_evidence_samples",["tenant_id","test_run_id","result"])
    op.create_table("regulatory_control_test_conclusions",sa.Column("conclusion_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False),sa.Column("test_run_id",sa.String(128),sa.ForeignKey("regulatory_control_test_runs.test_run_id",ondelete="RESTRICT"),nullable=False),sa.Column("conclusion_version",sa.Integer(),nullable=False),sa.Column("effectiveness",sa.String(48),nullable=False),sa.Column("exception_summary",sa.JSON(),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("independent",sa.Boolean(),nullable=False),sa.Column("concluded_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("concluded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","test_run_id","conclusion_version",name="uq_reg_test_conclusion_version"))

def downgrade():
    op.drop_table("regulatory_control_test_conclusions");op.drop_index("ix_reg_evidence_sample",table_name="regulatory_evidence_samples");op.drop_table("regulatory_evidence_samples");op.drop_index("ix_reg_control_test_run",table_name="regulatory_control_test_runs");op.drop_table("regulatory_control_test_runs");op.drop_index("ix_reg_control_test_plan",table_name="regulatory_control_test_plans");op.drop_table("regulatory_control_test_plans")
