"""regulatory assurance exceptions and deficiency aggregation

Revision ID: 0053_reg_assurance_deficiencies
Revises: 0052_regulatory_control_testing
"""
from alembic import op
import sqlalchemy as sa
revision="0053_reg_assurance_deficiencies";down_revision="0052_regulatory_control_testing";branch_labels=None;depends_on=None

def upgrade():
    op.create_table("regulatory_assurance_exceptions",
        sa.Column("exception_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True),sa.Column("sample_id",sa.String(128),nullable=False,index=True),sa.Column("test_run_id",sa.String(128),nullable=False,index=True),sa.Column("control_id",sa.String(128),nullable=False,index=True),sa.Column("entity_id",sa.String(128),nullable=True,index=True),sa.Column("exception_type",sa.String(64),nullable=False),sa.Column("deficiency_kind",sa.String(32),nullable=False),sa.Column("severity_score",sa.Integer(),nullable=False),sa.Column("evidence_refs",sa.JSON(),nullable=False),sa.Column("provenance",sa.JSON(),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("created_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("regulatory_assurance_deficiencies",
        sa.Column("deficiency_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True),sa.Column("deficiency_key",sa.String(160),nullable=False,index=True),sa.Column("version",sa.Integer(),nullable=False),sa.Column("control_id",sa.String(128),nullable=False,index=True),sa.Column("deficiency_kind",sa.String(32),nullable=False),sa.Column("severity",sa.String(24),nullable=False,index=True),sa.Column("severity_score",sa.Integer(),nullable=False),sa.Column("exception_ids",sa.JSON(),nullable=False),sa.Column("affected_entities",sa.JSON(),nullable=False),sa.Column("compensating_control",sa.JSON(),nullable=False),sa.Column("remediation_refs",sa.JSON(),nullable=False),sa.Column("repeated_exception_count",sa.Integer(),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("payload_sha256",sa.String(64),nullable=False),sa.Column("created_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","deficiency_key","version",name="uq_reg_assurance_deficiency_version"))
    op.create_table("regulatory_enterprise_assurance_issues",
        sa.Column("issue_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True),sa.Column("deficiency_key",sa.String(160),nullable=False,index=True),sa.Column("issue_type",sa.String(48),nullable=False),sa.Column("candidate_material_weakness",sa.Boolean(),nullable=False),sa.Column("severity",sa.String(24),nullable=False),sa.Column("affected_controls",sa.JSON(),nullable=False),sa.Column("affected_entities",sa.JSON(),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("sla_due_at",sa.DateTime(timezone=True),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("escalated_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=True),sa.Column("escalated_at",sa.DateTime(timezone=True),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("regulatory_deficiency_closures",
        sa.Column("closure_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True),sa.Column("deficiency_key",sa.String(160),nullable=False,index=True),sa.Column("closure_version",sa.Integer(),nullable=False),sa.Column("retest_refs",sa.JSON(),nullable=False),sa.Column("conclusion",sa.String(32),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("independent",sa.Boolean(),nullable=False),sa.Column("closed_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("closed_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","deficiency_key","closure_version",name="uq_reg_deficiency_closure_version"))

def downgrade():
    op.drop_table("regulatory_deficiency_closures");op.drop_table("regulatory_enterprise_assurance_issues");op.drop_table("regulatory_assurance_deficiencies");op.drop_table("regulatory_assurance_exceptions")
