"""enterprise deficiency lifecycle and material weakness governance
Revision ID: 0054_reg_deficiency_lifecycle
Revises: 0053_reg_assurance_deficiencies
"""
from alembic import op
import sqlalchemy as sa
revision="0054_reg_deficiency_lifecycle"; down_revision="0053_reg_assurance_deficiencies"; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("regulatory_deficiency_investigations",
      sa.Column("investigation_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True),sa.Column("deficiency_key",sa.String(160),nullable=False,index=True),sa.Column("enterprise_issue_id",sa.String(128),nullable=True,index=True),sa.Column("severity",sa.String(24),nullable=False,index=True),sa.Column("candidate_classification",sa.String(48),nullable=False),sa.Column("cross_control_impacts",sa.JSON(),nullable=False),sa.Column("root_cause_refs",sa.JSON(),nullable=False),sa.Column("recurrence_count",sa.Integer(),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("created_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("regulatory_deficiency_dispositions",
      sa.Column("disposition_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True),sa.Column("deficiency_key",sa.String(160),nullable=False,index=True),sa.Column("version",sa.Integer(),nullable=False),sa.Column("classification",sa.String(48),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("independent_challenge",sa.JSON(),nullable=False),sa.Column("decided_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("decided_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","deficiency_key","version",name="uq_reg_deficiency_disposition_version"))
    op.create_table("regulatory_corrective_action_plans",
      sa.Column("plan_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True),sa.Column("deficiency_key",sa.String(160),nullable=False,index=True),sa.Column("owner_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("title",sa.String(240),nullable=False),sa.Column("actions",sa.JSON(),nullable=False),sa.Column("milestones",sa.JSON(),nullable=False),sa.Column("regulatory_commitment_refs",sa.JSON(),nullable=False),sa.Column("compensating_control",sa.JSON(),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True),nullable=False,index=True),sa.Column("status",sa.String(32),nullable=False),sa.Column("approved_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=True),sa.Column("approved_at",sa.DateTime(timezone=True),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("regulatory_deficiency_executive_attestations",
      sa.Column("attestation_id",sa.String(128),primary_key=True),sa.Column("tenant_id",sa.String(128),sa.ForeignKey("tenants.tenant_id",ondelete="CASCADE"),nullable=False,index=True),sa.Column("deficiency_key",sa.String(160),nullable=False,index=True),sa.Column("version",sa.Integer(),nullable=False),sa.Column("conclusion",sa.String(32),nullable=False),sa.Column("independent_validation_refs",sa.JSON(),nullable=False),sa.Column("retest_refs",sa.JSON(),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("human_attestation",sa.Boolean(),nullable=False),sa.Column("attested_by_user_id",sa.String(128),sa.ForeignKey("user_accounts.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("attested_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","deficiency_key","version",name="uq_reg_deficiency_exec_attestation_version"))

def downgrade():
    op.drop_table("regulatory_deficiency_executive_attestations"); op.drop_table("regulatory_corrective_action_plans"); op.drop_table("regulatory_deficiency_dispositions"); op.drop_table("regulatory_deficiency_investigations")
