"use client";
import {useEffect,useState} from "react";
import {BadgeCheck,Banknote,ShieldCheck,TriangleAlert} from "lucide-react";
import {reviewerApi} from "@/lib/api";
import type {RecoverySettlementCase,RecoverySettlementPortfolio,RecoverySettlementWorkbench} from "@/lib/schemas";
export default function RecoverySettlementsPage(){
 const [queue,setQueue]=useState<RecoverySettlementCase[]>([]),[portfolio,setPortfolio]=useState<RecoverySettlementPortfolio|null>(null),[wb,setWb]=useState<RecoverySettlementWorkbench|null>(null),[error,setError]=useState("");
 const loadQueue=async()=>{try{const [q,p]=await Promise.all([reviewerApi.recoverySettlementQueue(),reviewerApi.recoverySettlementPortfolio()]);setQueue(q);setPortfolio(p)}catch(e){setError(e instanceof Error?e.message:"Load failed")}};
 const load=async(id:string)=>{try{setWb(await reviewerApi.recoverySettlementWorkbench(id));setError("")}catch(e){setError(e instanceof Error?e.message:"Load failed")}};
 useEffect(()=>{void loadQueue();const es=new EventSource("/api/reviewer/queue/events");const f=()=>{void loadQueue();if(wb?.case?.settlement_case_id)void load(wb.case.settlement_case_id)};["recovery_settlement.case.created","recovery_settlement.evidence.submitted","recovery_settlement.evidence.verified","recovery_settlement.ledger.correlated","recovery_settlement.exception.resolved","recovery_settlement.certificate.prepared","recovery_settlement.certificate.decided","recovery_settlement.correspondence.recorded"].forEach(t=>es.addEventListener(t,f));return()=>es.close()},[wb?.case?.settlement_case_id]);
 return <div className="space-y-5"><section className="card p-6 border-cyan-400/20"><div className="flex justify-between"><div><div className="panel-title">recovery settlement closeout</div><h1 className="text-2xl font-bold mt-1">Provider Repayment Verification</h1><p className="text-sm text-slate-400 mt-2 max-w-5xl">Verify external repayment, remittance, recoupment-offset and refund/credit evidence against the controlling recovery position and immutable ledger journals. MedClaimIQ never creates the bank transaction or collects funds.</p></div><Banknote className="h-9 w-9 text-cyan-300"/></div></section>{error&&<div className="card p-3 text-red-300">{error}</div>}
 <section className="grid md:grid-cols-5 gap-3">{[["Cases",portfolio?.cases],["Open",portfolio?.open_cases],["Target",portfolio?.target_recovery],["Verified",portfolio?.verified_recovery],["Remaining",portfolio?.remaining_balance]].map(([k,v])=><div className="card p-4" key={String(k)}><div className="text-xs text-slate-500">{k}</div><div className="text-xl font-bold">{String(v??0)}</div></div>)}</section>
 <section className="grid xl:grid-cols-[360px_1fr] gap-5"><div className="card p-4"><div className="panel-title">Settlement aging / closeout queue</div>{queue.map((x)=><button key={x.settlement_case_id} onClick={()=>void load(x.settlement_case_id)} className="w-full text-left border border-[#20364e] rounded-xl p-3 mt-2 hover:border-cyan-400"><div className="flex justify-between"><b>{x.status}</b><span>v{x.case_version}</span></div><div className="text-xs text-slate-500">{x.recovery_case_id}</div><div className="text-xs mt-1">{x.verified_amount}/{x.target_amount} {x.currency} · remaining {x.remaining_amount}</div></button>)}</div>
 <div>{!wb?<div className="card p-8 text-slate-500">Select a recovery settlement case.</div>:<div className="space-y-5"><section className="card p-5"><div className="flex justify-between"><div><div className="panel-title">Controlling recovery position</div><h2 className="text-xl font-semibold">{wb.case.target_amount} {wb.case.currency}</h2></div><span className="badge">{wb.case.status}</span></div><div className="grid md:grid-cols-3 gap-3 mt-4 text-sm"><div>Verified <b>{wb.case.verified_amount}</b></div><div>Remaining <b>{wb.case.remaining_amount}</b></div><div>Position <span className="mono text-xs">{wb.case.position_version_id}</span></div></div><div className="mono text-[10px] break-all text-slate-500 mt-3">{wb.case.position_payload_sha256}</div></section>
 <section className="grid xl:grid-cols-2 gap-5"><div className="card p-5"><div className="panel-title">Repayment / remittance evidence</div>{wb.evidence.map((x)=><div key={x.settlement_evidence_id} className="border-b border-[#20364e] py-3 text-sm"><div className="flex justify-between"><b>#{x.installment_sequence} · {x.evidence_type}</b><span>{x.status}</span></div><div>{x.amount} {x.currency} · {x.external_reference}</div><div className="text-xs text-slate-500">bank {x.bank_reference||"—"} · remit {x.remittance_reference||"—"} · ref-match {String(x.reference_match)}</div></div>)}</div><div className="card p-5"><div className="panel-title">Ledger correlation</div>{wb.ledger_correlations.map((x)=><div key={x.correlation_id} className="py-2 text-sm border-b border-[#20364e]"><b>{x.amount} {x.currency}</b> · {x.status}<div className="text-xs text-slate-500">journal {x.journal_id} · period {x.period_id}</div></div>)}{wb.ledger_correlations.length===0&&<div className="text-sm text-slate-500 mt-3">No verified ledger correlation yet.</div>}</div></section>
 <section className="grid xl:grid-cols-2 gap-5"><div className="card p-5"><div className="flex gap-2 items-center"><TriangleAlert className="h-4 w-4 text-amber-300"/><div className="panel-title">Settlement exceptions / SLA</div></div>{wb.exceptions.map((x)=><div key={x.exception_id} className="text-sm mt-2"><b>{x.exception_code}</b> · {x.status} · {x.severity}</div>)}{wb.tasks.map((x)=><div key={x.task_id} className="text-xs mt-2 text-slate-400">{x.task_type} · {x.status}{x.sla_breached?" · BREACHED":""}</div>)}</div><div className="card p-5"><div className="flex gap-2 items-center"><BadgeCheck className="h-4 w-4 text-emerald-300"/><div className="panel-title">Independent human closeout</div></div>{wb.certificate?<div className="mt-3 text-sm"><b>{wb.certificate.status}</b><div>Period {wb.certificate.accounting_period_id}</div><div className="text-xs text-slate-500">prepared {wb.certificate.prepared_by_user_id} · approved {wb.certificate.approved_by_user_id||"pending independent finance approver"}</div><div className="mono text-[10px] break-all mt-2">{wb.certificate.payload_sha256}</div></div>:<p className="text-sm text-slate-500 mt-3">Certificate can be prepared only after balance and ledger correlation reconcile exactly.</p>}</div></section>
 <section className="card p-5 border-emerald-400/20"><div className="flex gap-2 items-center"><ShieldCheck className="text-emerald-300"/><div className="panel-title">Authority boundary</div></div><p className="text-sm mt-3 text-slate-300">AI, LangGraph, RAG, MCP and workers may analyze or match evidence only. They cannot collect funds, create bank transactions, post or approve accounting, authorize payment, or certify financially material recovery closeout. Final certification is independent-human finance approval.</p></section></div>}</div></section></div>
}
