from __future__ import annotations

REOPENED_SUPERVISORY_RECOVERY_INVESTIGATION_AUTHORITY = {
    "recommendation_only": True,
    "ai_can_reconstruct_multi_cycle_evidence": True,
    "ai_can_reconstruct_persistent_emergent_root_causes": True,
    "ai_can_assess_prior_recertification_reclosure_assumptions": True,
    "ai_can_analyze_repeated_control_retransformation_failure": True,
    "ai_can_map_cross_entity_causal_propagation": True,
    "ai_can_assess_regulator_followup_impact": True,
    "ai_can_propose_enterprise_systemic_failure_classification": True,
    "ai_can_prepare_renewed_recovery_strategy": True,
    "ai_can_authorize_recovery_remediation": False,
    "ai_can_confirm_root_cause": False,
    "ai_can_confirm_systemic_failure_classification": False,
    "ai_can_accept_residual_systemic_risk": False,
    "ai_can_certify_recovery_effectiveness": False,
    "ai_can_reopen_or_reclose_program": False,
    "ai_can_close_regulatory_commitments": False,
    "ai_can_represent_regulator_intent": False,
    "worker_can_authorize_recovery_remediation": False,
    "worker_can_confirm_root_cause": False,
    "worker_can_certify_recovery": False,
    "release94_human_reopening_reference_required": True,
    "human_root_cause_confirmation_required": True,
    "human_systemic_failure_classification_confirmation_required": True,
    "independent_internal_audit_challenge_required": True,
    "executive_reauthorization_required": True,
    "accounting_mutation_allowed": False,
    "payment_authority_allowed": False,
    "funds_collection_allowed": False,
    "funds_movement_allowed": False,
}


def reopened_supervisory_recovery_investigation_contract() -> dict:
    return {
        "name": "production_regulatory_examination_reopened_supervisory_recovery_investigation_multi_cycle_root_cause_reconstruction_and_enterprise_recovery_reauthorization",
        "capabilities": [
            "release94_human_reopening_provenance_validation",
            "formal_reopened_supervisory_recovery_investigation",
            "full_multi_cycle_evidence_reconstruction",
            "persistent_vs_emergent_root_cause_reconstruction",
            "prior_executive_recertification_reclosure_assumption_validation",
            "repeated_control_retransformation_failure_analysis",
            "cross_entity_causal_propagation_mapping",
            "regulator_followup_impact_assessment",
            "enterprise_systemic_failure_classification",
            "renewed_recovery_strategy_candidates",
            "evidence_bound_remediation_reauthorization_packages",
            "human_root_cause_confirmation",
            "human_systemic_failure_classification_confirmation",
            "independent_internal_audit_challenge",
            "executive_reauthorization_readiness",
            "human_only_enterprise_recovery_reauthorization",
            "immutable_investigation_classification_authorization_versions",
            "sse_supervisory_dashboard_summary",
            "audit_export_manifest",
        ],
        "authority": REOPENED_SUPERVISORY_RECOVERY_INVESTIGATION_AUTHORITY,
        "traceability": "human enterprise reopening -> reopened supervisory recovery investigation -> multi-cycle evidence reconstruction -> persistent/emergent root-cause reconstruction -> enterprise systemic-failure classification -> independent challenge -> renewed recovery strategy -> human enterprise recovery reauthorization",
    }
