"use client";
import { FormEvent,useState } from "react";
import { BookOpenCheck,ShieldCheck,TriangleAlert } from "lucide-react";
import { reviewerApi } from "@/lib/api";
import { useEventStream } from "@/lib/hooks/use-event-stream";
import { Kpi } from "@/components/ui/primitives";
import type { AccountingLedger } from "@/lib/schemas";
export default function AccountingPage(){
 const [claimId,setClaimId]=useState("");const [data,setData]=useState<AccountingLedger|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [closeRationale,setCloseRationale]=useState("Accounting controller confirms balanced double-entry journals, reconciled ERA/EFT evidence, no pending adjustments, and governed period close controls.");
 const load=async(e?:FormEvent)=>{e?.preventDefault();if(!claimId)return;setBusy(true);setError(null);try{setData(await reviewerApi.accountingLedger(claimId))}catch(x){setError(x instanceof Error?x.message:"Accounting record unavailable")}finally{setBusy(false)}};
 const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError(null);try{await fn();await load()}catch(x){setError(x instanceof Error?x.message:"Accounting action failed")}finally{setBusy(false)}};
 const {state}=useEventStream(claimId?`/api/reviewer/claims/${encodeURIComponent(claimId)}/events`:null,()=>{if(data)void load()});
 return <div className="space-y-5"><section className="card p-6 border-cyan-400/20"><div className="flex justify-between"><div><div className="panel-title">double-entry payer accounting · SSE {state}</div><h1 className="text-2xl font-bold mt-1">Ledger, ERA/EFT & Accounting Close</h1><p className="text-sm text-slate-400 mt-2 max-w-4xl">Correlates already human-authorized financial instructions with ERA/EFT evidence, posts balanced immutable journals, surfaces aging/exceptions, and requires a human accounting controller for period close. No AI/agent/worker can authorize funds or close accounting.</p></div><BookOpenCheck className="h-9 w-9 text-cyan-300"/></div></section>
 <form onSubmit={load} className="card p-4 flex gap-3"><input className="input flex-1" value={claimId} onChange={e=>setClaimId(e.target.value)} placeholder="Claim ID"/><button className="btn btn-primary" disabled={busy}>Open accounting record</button></form>
 {error&&<div className="rounded-xl border border-rose-500/30 p-3 text-sm text-rose-200"><TriangleAlert className="inline h-4 w-4 mr-2"/>{error}</div>}
 {data&&<><section className="grid md:grid-cols-4 gap-3"><Kpi label="Journals" value={String(data.journals.length)}/><Kpi label="Reconciliations" value={String(data.reconciliations.length)}/><Kpi label="Aging queue" value={String(data.aging_queue.filter((x)=>x.status!=="closed").length)}/><Kpi label="Periods" value={String(data.periods.length)}/></section>
 <section className="grid xl:grid-cols-2 gap-5"><div className="card p-5"><div className="panel-title">ERA/EFT reconciliation</div><div className="mt-3 space-y-2">{data.reconciliations.length?data.reconciliations.map((r)=><div key={r.reconciliation_id} className="rounded-xl border border-[#1f3852] p-3 text-sm"><div className="flex justify-between"><b>{r.status}</b><span>{r.matched_amount}/{r.expected_amount}</span></div><div className="text-xs text-slate-500 mt-1">ERA {r.era_total} · EFT {r.eft_total} · reference match {String(r.reference_match)}</div></div>):<p className="text-sm text-slate-500">No ERA/EFT reconciliation yet.</p>}</div></div>
 <div className="card p-5"><div className="panel-title">Immutable journal chain</div><div className="mt-3 space-y-2">{data.journals.map((j)=><details key={j.journal_id} className="rounded-xl border border-[#1f3852] p-3"><summary className="cursor-pointer text-sm font-semibold">{j.journal_type} · DR {j.total_debits} / CR {j.total_credits}</summary><div className="mono text-[10px] break-all text-slate-500 mt-2">{j.journal_sha256}</div>{j.entries.map((e)=><div key={e.entry_id} className="text-xs mt-1 flex justify-between"><span>{e.direction.toUpperCase()} {e.account_code}</span><span>{e.amount} {e.currency}</span></div>)}</details>)}</div></div></section>
 <section className="grid xl:grid-cols-2 gap-5"><div className="card p-5"><div className="panel-title">Reconciliation aging</div><div className="mt-3 space-y-2 text-sm">{data.aging_queue.map((q)=><div key={q.queue_id} className="flex justify-between rounded-xl border border-[#1f3852] p-3"><span>{q.aging_bucket} · priority {q.priority}{q.exception_codes?.length?` · ${q.exception_codes.join(", ")}`:""}</span><span>{q.status}</span></div>)}</div></div><div className="card p-5"><div className="panel-title">Accounting periods</div><div className="mt-3 space-y-3">{data.periods.map((p)=><div key={p.period_id} className="rounded-xl border border-[#1f3852] p-3 text-sm"><div className="flex justify-between"><b>{p.period_key}</b><span>{p.status}</span></div>{p.status==="open"&&<div className="mt-3 flex gap-2"><input className="input flex-1" value={closeRationale} onChange={e=>setCloseRationale(e.target.value)}/><button className="btn btn-primary" disabled={busy} onClick={()=>void act(()=>reviewerApi.closeAccountingPeriod(p.period_id,p.lock_version,closeRationale))}>Human close</button></div>}{p.close_sha256&&<div className="mono text-[10px] break-all text-slate-500 mt-2">{p.close_sha256}</div>}</div>)}</div></div></section>
 <section className="grid xl:grid-cols-2 gap-5"><div className="card p-5"><div className="panel-title">Provider remittance status</div><div className="mt-3 space-y-2 text-sm">{data.provider_remittance.length?data.provider_remittance.map((r)=><div key={r.payment_intent_id} className="rounded-xl border border-[#1f3852] p-3"><div className="flex justify-between"><b>{r.provider_ref}</b><span>{r.status}</span></div><div className="text-xs text-slate-500 mt-1">Remitted {r.remitted_amount} · ERA {r.latest_era_reference||"—"} · EFT {r.latest_eft_reference||"—"}</div></div>):<p className="text-slate-500">No provider remittance evidence recorded.</p>}</div></div><div className="card p-5"><div className="panel-title">Returns, adjustments & recoupments</div><div className="mt-3 space-y-2 text-sm">{[...data.returns,...data.adjustments].length?[...data.returns,...data.adjustments].map((x)=><div key={x.return_id||x.adjustment_id} className="rounded-xl border border-[#1f3852] p-3"><div className="flex justify-between"><b>{x.return_code?`Return ${x.return_code}`:x.adjustment_type}</b><span>{x.status}</span></div><div className="text-xs text-slate-500 mt-1">{x.amount} · journal {x.journal_id||"pending"}</div></div>):<p className="text-slate-500">No returns or governed accounting adjustments.</p>}</div></div></section>
 <section className="card p-5 border-cyan-500/20"><div className="flex items-center gap-2"><ShieldCheck className="text-cyan-300"/><div className="panel-title">Accounting authority boundary</div></div><p className="text-sm text-slate-300 mt-3">LLM journal posting: <b>false</b> · LangGraph: <b>false</b> · RAG: <b>false</b> · MCP: <b>false</b> · worker close: <b>false</b> · automatic fund movement: <b>false</b> · human accounting-controller close: <b>true</b>.</p></section></>}</div>
}
