"use client";
import { useEffect, useState } from "react";
import { ClipboardCheck, FileCheck2, Gauge, ShieldCheck } from "lucide-react";
import { reviewerApi } from "@/lib/api";
import { ActionDialog, InfoDialog, type DialogField } from "@/components/ui/action-dialog";
import type { PortfolioDashboard, PortfolioSnapshot } from "@/lib/regulatory-schemas";

type Spec={title:string;description:string;fields:DialogField[];submitLabel:string;run:(v:Record<string,string>)=>Promise<void>};
const message=(e:unknown)=>e instanceof Error?e.message:String(e);
export default function RegulatoryPortfolioOversightPage(){
 const [data,setData]=useState<PortfolioDashboard|null>(null),[snapshot,setSnapshot]=useState<PortfolioSnapshot|null>(null),[error,setError]=useState(""),[dialog,setDialog]=useState<Spec|null>(null),[busy,setBusy]=useState(false),[packageHash,setPackageHash]=useState("");
 const refresh=async()=>{try{const x=await reviewerApi.regulatoryPortfolioDashboard();setData(x);if(x.latest)setSnapshot(x.latest);setError("")}catch(e){setError(message(e))}};
 useEffect(()=>{void refresh();const es=new EventSource("/api/reviewer/queue/events");const h=()=>void refresh();es.addEventListener("review-event",h);return()=>es.close()},[]);
 const inspect=async(id:string)=>{try{setSnapshot(await reviewerApi.regulatoryPortfolioSnapshot(id));setError("")}catch(e){setError(message(e))}};
 const submit=async(v:Record<string,string>)=>{if(!dialog)return;setBusy(true);try{await dialog.run(v);setDialog(null)}catch(e){setError(message(e))}finally{setBusy(false)}};
 const prepare=()=>setDialog({title:"Prepare portfolio snapshot",description:"Create an immutable reporting-period snapshot for enterprise regulatory assurance.",submitLabel:"Create snapshot",fields:[{name:"period",label:"Reporting period",required:true,defaultValue:new Date().toISOString().slice(0,7)}],run:async v=>{const s=await reviewerApi.createRegulatoryPortfolioSnapshot(v.period);setSnapshot(s);await refresh()}});
 const control=()=>setDialog({title:"Register enterprise control",description:"Register a human-owned enterprise control used for regulatory reporting and remediation validation.",submitLabel:"Register control",fields:[{name:"key",label:"Control key",required:true,defaultValue:"REG-REPORT-EVIDENCE"},{name:"name",label:"Control name",required:true,defaultValue:"Regulatory reporting evidence binding"},{name:"owner",label:"Human control owner user ID",required:true,defaultValue:"acct-controller"}],run:async v=>{await reviewerApi.createEnterpriseControl({control_key:v.key,name:v.name,description:"Enterprise control governing evidence-bound regulatory reporting and remediation validation.",control_family:"regulatory_reporting",owner_user_id:v.owner});await refresh()}});
 const campaign=async()=>{if(!snapshot)return;const controls=snapshot.controls.map(x=>x.control_id);if(!controls.length){setError("Register an enterprise control first.");return}try{await reviewerApi.createPortfolioTestingCampaign(snapshot.snapshot_id,{campaign_key:`independent-${Date.now()}`,methodology:"Independently sample mapped findings and completed CAPA evidence, replay the enterprise control, and preserve immutable test evidence.",control_ids:controls,due_at:new Date(Date.now()+14*86400000).toISOString()});await inspect(snapshot.snapshot_id)}catch(e){setError(message(e))}};
 const attest=()=>{if(!snapshot)return;setDialog({title:"Management attestation",description:"Management attestation is a human record and does not replace independent certification.",submitLabel:"Record attestation",fields:[{name:"rationale",label:"Attestation rationale",type:"textarea",required:true,defaultValue:"Management independently reviewed portfolio recurrence, CAPA critical path, control testing, and residual systemic risk."}],run:async v=>{await reviewerApi.managementAttestPortfolio(snapshot.snapshot_id,{conclusion:"effective",rationale:v.rationale});await inspect(snapshot.snapshot_id)}})};
 const certify=()=>{if(!snapshot)return;setDialog({title:"Independent portfolio certification",description:"Independent certification confirms control testing, systemic-risk treatment and source provenance after management attestation.",submitLabel:"Certify portfolio",fields:[{name:"rationale",label:"Certification rationale",type:"textarea",required:true,defaultValue:"Independent human certifier confirms management attestation, control testing, systemic-risk treatment, and immutable source provenance."}],run:async v=>{await reviewerApi.certifyRegulatoryPortfolio(snapshot.snapshot_id,{conclusion:"effective",rationale:v.rationale});await inspect(snapshot.snapshot_id)}})};
 const board=async()=>{if(!snapshot)return;try{const p=await reviewerApi.regulatoryPortfolioBoardPackage(snapshot.snapshot_id);setPackageHash(p.manifest_sha256)}catch(e){setError(message(e))}};
 return <div className="space-y-5"><header><div className="panel-title">Regulatory operations</div><h1 className="text-2xl font-bold mt-1">Regulatory Remediation Portfolio Oversight</h1><p className="text-sm text-slate-400 mt-2">Cross-examination findings → systemic-risk clusters → enterprise controls → independent testing → management attestation → independent certification.</p></header><section className="card p-4"><div className="flex gap-2 items-center font-semibold"><ShieldCheck className="h-4 w-4 text-teal-300"/>Authority boundary</div><p className="text-sm text-slate-400 mt-2">AI, agents and workers can aggregate, cluster, score and recommend only. Attestation, certification and risk acceptance remain human-controlled.</p></section><div className="flex gap-2 flex-wrap"><button onClick={prepare} className="btn btn-primary"><Gauge className="h-4 w-4"/>Prepare portfolio snapshot</button><button onClick={control} className="btn">Register enterprise control</button>{snapshot&&<><button onClick={()=>void campaign()} className="btn"><ClipboardCheck className="h-4 w-4"/>Start independent testing</button><button onClick={attest} className="btn">Management attestation</button><button onClick={certify} className="btn btn-primary"><ShieldCheck className="h-4 w-4"/>Independent certify portfolio</button><button onClick={()=>void board()} className="btn"><FileCheck2 className="h-4 w-4"/>Board / regulatory package</button></>}</div>{error&&<div role="alert" className="card border-rose-500/30 p-3 text-rose-200">{error}</div>}
 {snapshot?<><section className="grid grid-cols-2 md:grid-cols-5 gap-3">{Object.entries(snapshot.metrics).map(([k,v])=><Metric key={k} label={k} value={String(v??0)}/>)}</section><section className="card p-4 space-y-3"><div className="flex justify-between"><h2 className="font-semibold">Systemic control / recurrence clusters</h2><span className="text-xs text-slate-500">snapshot {snapshot.snapshot_version} · {snapshot.status}</span></div>{snapshot.clusters.length?snapshot.clusters.map(c=><div key={c.cluster_key} className="border border-[#233b55] rounded-xl p-3 text-sm"><div className="flex justify-between gap-3"><b>{c.type}</b><span>{c.severity} · {c.member_count} findings/plans</span></div><div className="text-xs text-slate-500 mt-1 break-all">{c.cluster_key}</div><div className="text-xs text-slate-400 mt-2">Recommendation authority: {c.recommendation?.authority??"none"} · human control review required</div></div>):<State text="No systemic recurrence clusters in this snapshot."/>}</section><section className="card p-4"><h2 className="font-semibold mb-2">Corrective-action critical path</h2>{snapshot.critical_path.length?snapshot.critical_path.map(x=><div key={`${x.plan_id}-${x.task_key}`} className="text-sm border-b border-[#233b55] py-2"><b>{x.task_key}</b> · due {x.due_at} · dependencies {x.dependency_count}</div>):<State text="No critical-path tasks in this snapshot."/>}</section><details className="card p-4"><summary className="cursor-pointer text-sm text-slate-400">Immutable portfolio provenance</summary><pre className="text-xs whitespace-pre-wrap overflow-auto max-h-[520px] bg-slate-950 p-3 rounded mt-2">{JSON.stringify(snapshot,null,2)}</pre></details></>:<State text={data?"No portfolio snapshot exists yet. Create one to begin oversight.":"Loading portfolio oversight…"}/>}<ActionDialog open={Boolean(dialog)} title={dialog?.title??""} description={dialog?.description} fields={dialog?.fields??[]} submitLabel={dialog?.submitLabel} busy={busy} onClose={()=>setDialog(null)} onSubmit={submit}/><InfoDialog open={Boolean(packageHash)} title="Board / regulatory assurance package" body={`Immutable manifest SHA-256: ${packageHash}`} onClose={()=>setPackageHash("")}/></div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="card p-4"><div className="text-xs text-slate-500 capitalize">{label.replaceAll("_"," ")}</div><div className="text-xl font-semibold mt-1">{value}</div></div>}
function State({text}:{text:string}){return <div className="rounded-xl border border-dashed border-[#31506f] p-5 text-sm text-slate-500">{text}</div>}
