"use client";
import {useEffect,useState} from "react";
import {Activity,FileCheck2,Search,ShieldCheck,TriangleAlert} from "lucide-react";
import {reviewerApi} from "@/lib/api";
import {Kpi,Panel,Row} from "@/components/ui/primitives";
import type {ProviderRecoveryBalanceStatement,RecoverySettlementCloseoutReport,RecoverySettlementCopilot,RecoverySettlementExceptionInvestigation,RecoverySettlementIntelligencePortfolio,RecoverySettlementTrace} from "@/lib/schemas";
export default function RecoverySettlementIntelligencePage(){
 const [portfolio,setPortfolio]=useState<RecoverySettlementIntelligencePortfolio|null>(null),[providerId,setProviderId]=useState("org-a"),[statement,setStatement]=useState<ProviderRecoveryBalanceStatement|null>(null),[periodId,setPeriodId]=useState(""),[report,setReport]=useState<RecoverySettlementCloseoutReport|null>(null),[query,setQuery]=useState("Explain settlement aging, remaining recovery balance, exceptions, and closeout evidence with settlement and ledger citations."),[copilot,setCopilot]=useState<RecoverySettlementCopilot|null>(null),[investigation,setInvestigation]=useState<RecoverySettlementExceptionInvestigation|null>(null),[trace,setTrace]=useState<RecoverySettlementTrace|null>(null),[error,setError]=useState("");
 const load=async()=>{try{setPortfolio(await reviewerApi.recoverySettlementIntelligencePortfolio());setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load settlement intelligence")}};
 useEffect(()=>{void load();const es=new EventSource("/api/reviewer/queue/events");const refresh=()=>void load();["recovery_settlement_intelligence.statement.generated","recovery_settlement_intelligence.statement.delivered","recovery_settlement_intelligence.analytics.refreshed","recovery_settlement_intelligence.closeout_report.generated","recovery_settlement_intelligence.exception.investigated"].forEach(x=>es.addEventListener(x,refresh));return()=>es.close()},[]);
 const provider=async()=>{try{setStatement(await reviewerApi.providerRecoveryBalanceStatement(providerId));setError("")}catch(e){setError(e instanceof Error?e.message:"Statement unavailable")}};
 const publish=async()=>{if(!statement?.statement_id)return;await reviewerApi.publishProviderRecoveryBalanceStatement(statement.statement_id);await provider()};
 const closeout=async()=>{if(!periodId)return;try{setReport(await reviewerApi.recoverySettlementCloseoutReport(periodId));setError("")}catch(e){setError(e instanceof Error?e.message:"Closeout report unavailable")}};
 const ask=async()=>{try{setCopilot(await reviewerApi.recoverySettlementCopilot(query,providerId||undefined));setError("")}catch(e){setError(e instanceof Error?e.message:"Copilot unavailable")}};
 const investigate=async(caseId:string,code:string)=>{setInvestigation(await reviewerApi.investigateRecoverySettlementException(caseId,code))};const showTrace=async(caseId:string)=>{setTrace(await reviewerApi.recoverySettlementIntelligenceTraceability(caseId))};
 return <div className="space-y-5"><section className="card p-6 border-teal-400/20"><div className="flex justify-between"><div><div className="panel-title">read-only recovery settlement intelligence</div><h1 className="text-2xl font-bold mt-1">Settlement Reconciliation Intelligence & Regulatory Closeout Reporting</h1><p className="text-sm text-slate-400 mt-2 max-w-5xl">Provider balance statements, aging, under/over-recovery detection, settlement/ledger reconciliation analytics, closeout reporting, audit manifests and citation-grounded financial RAG. This layer cannot alter balances, journals, payment instructions, completion certificates, bank transactions, collections or funds.</p></div><Activity className="h-9 w-9 text-teal-300"/></div></section>
 {error&&<div className="rounded-xl border border-rose-500/30 p-3 text-sm text-rose-200"><TriangleAlert className="inline h-4 w-4 mr-2"/>{error}</div>}
 <section className="flex gap-3"><button className="btn btn-primary" onClick={()=>void load()}>Refresh portfolio</button></section>
 {portfolio&&<><section className="grid md:grid-cols-4 xl:grid-cols-8 gap-3"><Kpi label="Cases" value={String(portfolio.kpis.settlement_cases)}/><Kpi label="Target" value={portfolio.kpis.target_recovery}/><Kpi label="Verified" value={portfolio.kpis.verified_recovery}/><Kpi label="Remaining" value={portfolio.kpis.remaining_balance}/><Kpi label="Effectiveness" value={`${portfolio.kpis.recovery_effectiveness_pct}%`}/><Kpi label="Under-recovery" value={portfolio.kpis.under_recovery_amount}/><Kpi label="Over-recovery" value={portfolio.kpis.over_recovery_amount}/><Kpi label="Exceptions" value={String(portfolio.kpis.open_exception_count)}/></section><section className="grid xl:grid-cols-2 gap-5"><Panel title="Provider recovery history">{portfolio.providers.map((p)=><Row key={p.provider_organization_id} title={p.provider_organization_id} right={p.remaining_balance} sub={`target ${p.target_recovery} · verified ${p.verified_recovery} · statement v${p.statement_version}`}/>)}</Panel><Panel title="Settlement aging intelligence">{Object.entries(portfolio.aging).map(([k,v])=><Row key={k} title={k} right={String(v)} sub="open balance cases"/>)}</Panel></section><Panel title="Under/over-recovery & settlement exception signals">{portfolio.settlement_exceptions.length?portfolio.settlement_exceptions.map((x,i:number)=><div key={`${x.code}-${i}`} className="rounded-xl border border-[#1f3852] p-3 text-sm"><div className="flex justify-between"><b>{x.code}</b><span>{x.severity}</span></div><div className="text-xs text-slate-500 mt-1">case {x.settlement_case_id}</div><button className="btn btn-ghost mt-2" onClick={()=>void investigate(x.settlement_case_id,x.code)}>Explain cited exception</button></div>):<p className="text-sm text-slate-500">No deterministic settlement exceptions detected.</p>}{investigation&&<div className="rounded-xl border border-amber-500/20 p-3 text-sm"><b>{investigation.exception_code}</b><p className="mt-2 text-slate-400">{investigation.explanation}</p></div>}</Panel><Panel title="End-to-end settlement traceability">{portfolio.cases.map((x)=><div key={x.settlement_case_id} className="rounded-xl border border-[#1f3852] p-3 text-sm"><div className="flex justify-between"><b>{x.settlement_case_id}</b><span>{x.remaining_balance}</span></div><button className="btn btn-ghost mt-2" onClick={()=>void showTrace(x.settlement_case_id)}>Trace position → settlement → ledger → certificate</button></div>)}{trace&&<div className="rounded-xl border border-teal-500/20 p-3 text-xs"><div className="font-semibold">{trace.settlement_case_id}</div><pre className="mt-2 whitespace-pre-wrap break-all text-slate-500">{JSON.stringify(trace.lineage,null,2)}</pre></div>}</Panel></>}
 <section className="grid xl:grid-cols-2 gap-5"><Panel title="Immutable provider balance statement"><div className="flex gap-2"><input className="input flex-1" value={providerId} onChange={e=>setProviderId(e.target.value)} placeholder="Provider organization ID"/><button className="btn btn-primary" onClick={()=>void provider()}>Generate/read</button></div>{statement&&<div className="mt-3 space-y-2 text-sm"><Row title={`Statement v${statement.statement_version}`} right={statement.remaining_balance} sub={`target ${statement.target_recovery} · verified ${statement.verified_recovery} · delivered ${String(statement.delivered)}`}/><div className="mono text-[10px] text-slate-500 break-all">{statement.payload_sha256}</div><button className="btn btn-ghost" onClick={()=>void publish()} disabled={statement.delivered}><FileCheck2 className="h-4 w-4"/>Human release to provider portal</button></div>}</Panel><Panel title="Accounting-period closeout/audit package"><div className="flex gap-2"><input className="input flex-1" value={periodId} onChange={e=>setPeriodId(e.target.value)} placeholder="Accounting period ID"/><button className="btn btn-primary" onClick={()=>void closeout()}>Generate report</button></div>{report&&<div className="mt-3 text-sm"><Row title={report.period_key} right={report.period_status} sub={`${report.certificate_count} recovery certificates · verified ${report.total_verified}`}/><div className="mono text-[10px] text-slate-500 break-all mt-2">manifest {report.manifest_sha256}</div></div>}</Panel></section>
 <section className="card p-5"><div className="panel-title">Settlement / ledger financial RAG</div><div className="mt-3 flex gap-3"><input className="input flex-1" value={query} onChange={e=>setQuery(e.target.value)}/><button className="btn btn-primary" onClick={()=>void ask()}><Search className="h-4 w-4"/>Ask</button></div>{copilot&&<div className="mt-4 rounded-xl border border-teal-500/20 p-4"><p className="text-sm">{copilot.answer}</p><div className="mt-3 space-y-1">{copilot.citations.map((c)=><div key={c.citation_id} className="mono text-[10px] text-slate-500">[{c.type}] {c.citation_id} · {c.retrieval_score}</div>)}</div></div>}</section>
 <section className="card p-5 border-emerald-500/20"><div className="flex gap-2 items-center"><ShieldCheck className="text-emerald-300"/><div className="panel-title">Read-only financial authority boundary</div></div><p className="text-sm text-slate-300 mt-3">AI balance mutation: <b>false</b> · journal posting: <b>false</b> · payment authorization: <b>false</b> · closeout certificate mutation: <b>false</b> · bank transaction creation: <b>false</b> · collections: <b>false</b> · automatic fund movement: <b>false</b>.</p></section></div>
}
