"use client";
import { useEffect,useState } from "react";
import { BookOpenCheck,FileSearch2,RefreshCcw,ShieldCheck,TriangleAlert } from "lucide-react";
import { reviewerApi } from "@/lib/api";
import type { EvidenceSearchResult, ProviderDisputeIntelligenceWorkbench, ProviderDisputeQueueItem, ProviderDisputeResolution, ReversalReferral } from "@/lib/schemas";

export default function ProviderDisputeIntelligencePage(){
  const [queue,setQueue]=useState<ProviderDisputeQueueItem[]>([]),[wb,setWb]=useState<ProviderDisputeIntelligenceWorkbench|null>(null),[resolution,setResolution]=useState<ProviderDisputeResolution|null>(null),[sel,setSel]=useState<{caseId:string;disputeId:string}|null>(null),[query,setQuery]=useState("recoupment overpayment provider agreement reimbursement policy"),[search,setSearch]=useState<EvidenceSearchResult|null>(null),[outcome,setOutcome]=useState("reduce_recovery"),[target,setTarget]=useState("0"),[rationale,setRationale]=useState("Independent human finance review resolves the cited provider evidence and effective reimbursement-policy conflicts before amending the governed recovery target."),[leaseToken,setLeaseToken]=useState(""),[error,setError]=useState("");
  const loadQueue=async()=>{try{setQueue(await reviewerApi.providerDisputeIntelligenceQueue())}catch(e){setError(e instanceof Error?e.message:"Queue load failed")}};
  const load=async(caseId:string,disputeId:string)=>{setSel({caseId,disputeId});try{const [intel,res]=await Promise.all([reviewerApi.providerDisputeIntelligenceWorkbench(caseId,disputeId),reviewerApi.providerDisputeResolution(caseId,disputeId)]);setWb(intel);setResolution(res);if(!target||target==="0")setTarget(String(res.current_target_recovery_amount||0));setError("")}catch(e){setError(e instanceof Error?e.message:"Workbench load failed")}};
  useEffect(()=>{void loadQueue();const es=new EventSource("/api/reviewer/queue/events");const refresh=()=>{void loadQueue();if(sel)void load(sel.caseId,sel.disputeId)};["provider_dispute_intelligence.reingestion.queued","provider_dispute_intelligence.reingestion.completed","provider_dispute_intelligence.fhir.ready","provider_dispute_intelligence.snapshot.locked","provider_dispute_intelligence.rag.completed","provider_dispute_intelligence.agent.completed","provider_dispute_intelligence.missing_evidence.requested","provider_dispute_intelligence.provider_response.received","provider_dispute_intelligence.checkpoint.resumed","provider_dispute_resolution.packet.created","provider_dispute_resolution.packet.locked","provider_dispute_resolution.second_review.completed","provider_dispute_resolution.closed","provider_dispute_resolution.reconciliation.verified","provider_dispute_resolution.recovery.closed"].forEach(x=>es.addEventListener(x,refresh));return()=>es.close()},[sel?.caseId,sel?.disputeId]);
  const build=async()=>{if(!sel)return;try{await reviewerApi.buildProviderDisputeSnapshot(sel.caseId,sel.disputeId);await load(sel.caseId,sel.disputeId)}catch(e){setError(e instanceof Error?e.message:"Snapshot failed")}};
  const doSearch=async()=>{if(!sel)return;try{setSearch(await reviewerApi.searchProviderDisputeEvidence(sel.caseId,sel.disputeId,query))}catch(e){setError(e instanceof Error?e.message:"Search failed")}};
  const recommend=async()=>{if(!sel)return;try{await reviewerApi.runProviderDisputeRecommendation(sel.caseId,sel.disputeId);await load(sel.caseId,sel.disputeId)}catch(e){setError(e instanceof Error?e.message:"Recommendation failed")}};
  const prepareResolution=async()=>{if(!sel||!wb)return;try{const citations=(wb.latest_rag?.items||[]).slice(0,8).map((x)=>x.item_id).filter(Boolean);const resolved=(wb.comparisons||[]).filter((x)=>x.severity==="material").map((x)=>x.comparison_id);const checkpoints=(wb.checkpoints||[]).map((x)=>x.checkpoint_id);await reviewerApi.saveProviderDisputeResolutionPacket(sel.caseId,sel.disputeId,{outcome,amended_target_amount:target,rationale,reason_codes:["evidence_policy_review_complete"],citation_refs:citations,resolved_comparison_refs:resolved,checkpoint_refs:checkpoints,recommendation_disagreement_reason:"The authorized human reviewer independently weighs the cited evidence and records any divergence from recommendation-only analysis.",expected_case_version:resolution.recovery_case_version,expected_packet_version:resolution.packet?.packet_version});await load(sel.caseId,sel.disputeId)}catch(e){setError(e instanceof Error?e.message:"Decision packet failed")}};
  const lockResolution=async()=>{if(!sel||!resolution?.packet)return;try{await reviewerApi.lockProviderDisputeResolutionPacket(sel.caseId,sel.disputeId,resolution.packet.packet_id,resolution.packet.packet_version);await load(sel.caseId,sel.disputeId)}catch(e){setError(e instanceof Error?e.message:"Lock failed")}};
  const secondReview=async()=>{if(!sel||!resolution?.packet)return;try{await reviewerApi.secondReviewProviderDisputeResolution(sel.caseId,sel.disputeId,resolution.packet.packet_id,resolution.packet.packet_version,"Independent second human finance approver confirms the locked evidence-bound provider dispute decision packet and material recovery amendment.");await load(sel.caseId,sel.disputeId)}catch(e){setError(e instanceof Error?e.message:"Second review failed")}};
  const closeResolution=async()=>{if(!sel||!resolution?.packet)return;try{await reviewerApi.closeProviderDisputeResolution(sel.caseId,sel.disputeId,resolution.packet.packet_id,resolution.packet.packet_version,resolution.recovery_case_version);await load(sel.caseId,sel.disputeId)}catch(e){setError(e instanceof Error?e.message:"Final resolution failed")}};
  const acquireRecoveryLease=async()=>{if(!sel)return;try{const x=await reviewerApi.acquireRecoveryLease(sel.caseId,resolution.recovery_case_version);setLeaseToken(x.lease_token);await load(sel.caseId,sel.disputeId)}catch(e){setError(e instanceof Error?e.message:"Recovery lease failed")}};
  const verifyReferral=async(ref:ReversalReferral)=>{if(!sel||!leaseToken)return;try{await reviewerApi.verifyProviderDisputeReconciliation(sel.caseId,sel.disputeId,ref.reversal_referral_id,{status:"verified",external_reference:`HUMAN-VERIFY-${Date.now()}`,expected_case_version:resolution.recovery_case_version,lease_token:leaseToken});await load(sel.caseId,sel.disputeId)}catch(e){setError(e instanceof Error?e.message:"Reconciliation verification failed")}};
  const finalizeRecovery=async()=>{if(!sel||!leaseToken)return;try{await reviewerApi.finalizeProviderDisputeRecovery(sel.caseId,sel.disputeId,{rationale:"Human recovery investigator closes the recovery case after final dispute resolution and downstream accounting/reconciliation amendment verification are complete.",expected_case_version:resolution.recovery_case_version,lease_token:leaseToken});await load(sel.caseId,sel.disputeId)}catch(e){setError(e instanceof Error?e.message:"Recovery closure failed")}};
  return <div className="space-y-5">
    <section className="card p-6 border-cyan-400/20"><div className="flex justify-between gap-4"><div><div className="panel-title">Evidence intelligence + governed human resolution</div><h1 className="text-2xl font-bold mt-1">Provider Dispute Evidence & Policy Review · Final Recovery Resolution</h1><p className="text-sm text-slate-400 mt-2 max-w-5xl">Re-ingest validated provider evidence, compare it with the governed recovery position, retrieve the exact effective provider agreement and reimbursement policy, and prepare citation-bound recommendations for independent human dispute resolution.</p></div><FileSearch2 className="h-9 w-9 text-cyan-300"/></div></section>
    {error&&<div className="card p-3 text-red-300">{error}</div>}
    <section className="grid xl:grid-cols-[360px_1fr] gap-5"><div className="card p-4"><div className="panel-title">Open provider disputes</div><div className="space-y-2 mt-3">{queue.map((d)=><button key={d.dispute_id} className="w-full text-left rounded-xl border border-[#20364e] p-3 hover:border-cyan-400" onClick={()=>void load(d.recovery_case_id,d.dispute_id)}><div className="flex justify-between"><b>{d.reason_code}</b><span>{d.status}</span></div><div className="text-xs text-slate-500 mono">{d.external_reference}</div><div className="text-xs mt-1">{d.disputed_amount} {d.currency} · sources {d.evidence_sources} · AI runs {d.recommendation_runs}</div></button>)}</div></div>
    <div className="space-y-5">{!wb?<div className="card p-8 text-slate-500">Select a provider dispute.</div>:<>
      <section className="card p-5"><div className="flex justify-between"><div><div className="panel-title">Dispute evidence snapshot</div><h2 className="text-xl font-semibold">{wb.dispute.external_reference}</h2></div><span className="badge">{wb.dispute.status}</span></div><div className="grid md:grid-cols-4 gap-3 mt-4 text-sm"><div>Disputed <b>{wb.dispute.disputed_amount} {wb.dispute.currency}</b></div><div>Modalities <b>{wb.snapshot?.modalities?.join(", ")||"not locked"}</b></div><div>Sources <b>{wb.snapshot?.source_count||0}</b></div><div>Snapshot <b>v{wb.snapshot?.snapshot_version||0}</b></div></div><div className="flex gap-2 mt-4"><button className="btn btn-primary" onClick={()=>void build()}>Lock evidence snapshot</button><button className="btn btn-primary" onClick={()=>void recommend()}>Run recommendation-only agent</button></div>{wb.snapshot&&<div className="mono text-[10px] break-all text-slate-500 mt-3">{wb.snapshot.snapshot_sha256}</div>}</section>
      <section className="grid xl:grid-cols-2 gap-5"><div className="card p-5"><div className="flex items-center gap-2"><BookOpenCheck className="h-4 w-4 text-teal-300"/><div className="panel-title">Effective contract / policy versions</div></div>{wb.snapshot?.policy_sources?.map((x)=><div key={x.source_id} className="py-2 border-b border-[#20364e] text-sm"><b>{x.title}</b><div className="text-xs text-slate-500">{x.source_kind} · v{x.source_version} · {x.effective_from}</div><div className="mono text-[10px] text-slate-600 break-all">{x.content_sha256}</div></div>)}</div><div className="card p-5"><div className="panel-title">Provider evidence processing</div>{wb.reingestions.map((x)=><div key={x.reingestion_id} className="py-2 border-b border-[#20364e] text-sm"><b>{x.modality}</b> · {x.status}<div className="text-xs text-slate-500">{x.file_validation_status} · malware {x.malware_verdict} · chunks {x.chunk_count}</div></div>)}</div></section>
      <section className="card p-5"><div className="flex items-center gap-2"><TriangleAlert className="h-4 w-4 text-amber-300"/><div className="panel-title">Changed facts & policy contradictions</div></div><div className="grid md:grid-cols-2 gap-3 mt-3">{wb.comparisons.map((x)=><div key={x.comparison_id} className="rounded-xl border border-[#20364e] p-3"><div className="flex justify-between text-sm"><b>{x.field}</b><span>{x.comparison_type}</span></div><div className="text-xs text-slate-400 mt-1">{x.description}</div><div className="text-xs text-slate-500 mt-2">severity {x.severity} · confidence {x.confidence}</div></div>)}</div></section>
      <section className="card p-5"><div className="panel-title">Citation drill-down</div><div className="flex gap-2 mt-3"><input className="input flex-1" value={query} onChange={e=>setQuery(e.target.value)}/><button className="btn btn-primary" onClick={()=>void doSearch()}>Search evidence</button></div>{(search?.items||wb.latest_rag?.items||[]).map((x,i:number)=><div key={i} className="mt-3 rounded-xl border border-[#20364e] p-3 text-sm"><div className="flex justify-between"><b>{x.source_scope}</b><span>#{x.rank} · {Number(x.score).toFixed(3)}</span></div><div className="text-slate-300 mt-1">{x.text_preview}</div><pre className="text-[10px] text-slate-500 overflow-auto mt-2">{JSON.stringify(x.citation,null,2)}</pre></div>)}</section>
      <section className="grid xl:grid-cols-2 gap-5"><div className="card p-5"><div className="panel-title">Recommendation-only agent</div>{wb.recommendations.map((r)=><div key={r.recommendation_run_id} className="mt-3 rounded-xl border border-[#20364e] p-3"><div className="flex justify-between"><b>{r.recommendation}</b><span>{Math.round(r.confidence*100)}%</span></div><p className="text-sm text-slate-400 mt-2">{r.summary}</p><div className="text-xs text-emerald-300 mt-2">Authority: {r.adjudication_authority}</div></div>)}</div><div className="card p-5"><div className="panel-title">Human checkpoints & missing evidence</div>{wb.checkpoints.map((x)=><div key={x.checkpoint_id} className="text-sm py-2 border-b border-[#20364e]">{x.stage} · <b>{x.status}</b></div>)}{wb.missing_evidence_requests.map((x)=><div key={x.request_id} className="text-sm py-2 border-b border-[#20364e]">Requested: {x.document_types.join(", ")} · {x.status}</div>)}</div></section>
      <section className="card p-5 border-violet-400/20"><div className="panel-title">Evidence-bound human dispute resolution</div><div className="grid md:grid-cols-3 gap-3 mt-3"><select className="input" value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="uphold_recovery">Uphold recovery</option><option value="reduce_recovery">Reduce recovery</option><option value="withdraw_recovery">Withdraw recovery</option></select><input className="input" value={target} onChange={e=>setTarget(e.target.value)} placeholder="Amended target"/><input className="input" value={rationale} onChange={e=>setRationale(e.target.value)}/></div><div className="flex flex-wrap gap-2 mt-3"><button className="btn btn-primary" onClick={()=>void prepareResolution()}>Prepare decision packet</button><button className="btn" onClick={()=>void lockResolution()} disabled={!resolution?.packet}>Validate & lock</button><button className="btn" onClick={()=>void secondReview()} disabled={!resolution?.packet?.dual_control_required}>Independent second review</button><button className="btn" onClick={()=>void closeResolution()} disabled={!resolution?.packet?.locked_payload_sha256}>Final human resolution</button></div>{resolution?.packet&&<div className="mt-3 text-xs"><b>Packet v{resolution.packet.packet_version}</b> · {resolution.packet.status} · dual control {String(resolution.packet.dual_control_required)} · blockers {(resolution.packet.blocker_codes||[]).join(", ")||"none"}<div className="mono text-[10px] break-all text-slate-500">{resolution.packet.locked_payload_sha256||resolution.packet.snapshot_sha256}</div></div>}{resolution?.final_resolution&&<div className="mt-4 rounded-xl border border-emerald-500/20 p-3 text-sm"><b>Controlling recovery position:</b> {resolution.final_resolution.amended_target_amount} · {resolution.final_resolution.outcome}<div className="text-xs text-slate-500">Position {resolution.final_resolution.position_version_id} · referral {resolution.final_resolution.reversal_referral_id||"none"}</div></div>}{resolution?.reversal_referrals?.map((ref)=><div key={ref.reversal_referral_id} className="mt-3 rounded-xl border border-[#20364e] p-3 text-sm"><b>{ref.referral_type}</b> · {ref.amount} · {ref.status}<div className="flex gap-2 mt-2"><button className="btn" onClick={()=>void acquireRecoveryLease()}>Acquire recovery lease</button><button className="btn" disabled={!leaseToken} onClick={()=>void verifyReferral(ref)}>Verify accounting/reconciliation outcome</button><button className="btn" disabled={!leaseToken} onClick={()=>void finalizeRecovery()}>Final recovery closure</button></div></div>)}</section>
      <section className="card p-5 border-emerald-500/20"><div className="flex items-center gap-2"><ShieldCheck className="text-emerald-300"/><div className="panel-title">Authority boundary</div></div><p className="text-sm mt-3 text-slate-300">AI, RAG, LangGraph, MCP and background workers may analyze and recommend only. Only authorized independent human finance approvers can create the controlling provider-dispute resolution, and material changes require a second independent human. Accounting reversal referrals remain pending human finance action; no AI or worker can post journals, authorize payment, collect funds, or move money.</p></section>
    </>}</div></section>
  </div>;
}
