"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { AlertTriangle, BookOpenCheck, RefreshCw, ShieldCheck } from "lucide-react";
import { reviewerApi } from "@/lib/api";
import { Kpi } from "@/components/ui/primitives";
import type { RegulatoryCommitment, RegulatoryExaminationDashboard } from "@/lib/regulatory-schemas";
type CommitmentRow=RegulatoryCommitment&{caseId:string;inquiry:string};
const message=(e:unknown)=>e instanceof Error?e.message:String(e);
export default function RegulatoryExaminationCommitmentsPage(){
 const [dashboard,setDashboard]=useState<RegulatoryExaminationDashboard|null>(null),[rows,setRows]=useState<CommitmentRow[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const d=await reviewerApi.regulatoryExaminationDashboard();setDashboard(d);const relevant=d.cases.filter(c=>c.open_commitments>0).slice(0,20);const traces=await Promise.allSettled(relevant.map(c=>reviewerApi.regulatoryExaminationTraceability(c.examination_case_id)));const next:CommitmentRow[]=[];traces.forEach((r,i)=>{if(r.status==="fulfilled")r.value.commitments.forEach(c=>next.push({...c,caseId:relevant[i].examination_case_id,inquiry:relevant[i].external_inquiry_reference}))});setRows(next);setError("")}catch(e){setError(message(e))}finally{setLoading(false)}};
 useEffect(()=>{void load();const es=new EventSource("/api/reviewer/queue/events");const h=()=>void load();es.addEventListener("review-event",h);return()=>es.close()},[]);
 const now=Date.now(),open=rows.filter(r=>r.status==="open"),overdue=open.filter(r=>r.due_at&&new Date(r.due_at).getTime()<now),evidenceBacked=open.filter(r=>r.evidence_refs.length>0);
 return <div className="space-y-5"><div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><header><div className="panel-title">Regulatory operations</div><h1 className="text-2xl font-bold mt-1">Commitment Lifecycle & Follow-Up Assurance</h1><p className="mt-2 max-w-4xl text-sm text-slate-400">Live supervisory monitoring of confirmed commitments from owner execution through evidence-backed, human-certified completion. AI and workers cannot certify completion or change regulatory obligations.</p></header><button className="btn" onClick={()=>void load()} disabled={loading}><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/>Refresh</button></div>
 {error&&<div role="alert" className="card border-rose-500/30 p-3 text-rose-200"><AlertTriangle className="inline h-4 w-4 mr-2"/>{error}</div>}
 <section className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3"><Kpi label="Confirmed commitments" value={String(rows.length)} detail="Across active examination traces"/><Kpi label="Open commitments" value={String(open.length)} detail={`${dashboard?.cases.filter(c=>c.open_commitments>0).length??0} inquiries affected`}/><Kpi label="Milestones at risk" value={String(overdue.length)} detail="Past commitment due date"/><Kpi label="Evidence completeness" value={open.length?`${Math.round(evidenceBacked.length/open.length*100)}%`:"100%"} detail="Open commitments with evidence refs"/></section>
 <section className="card p-5"><div className="flex items-center gap-2"><BookOpenCheck className="h-4 w-4 text-teal-300"/><h2 className="font-semibold">Commitment register</h2></div><div className="table-wrap mt-3"><table><caption className="sr-only">Regulatory commitment register with evidence and due-date risk</caption><thead><tr><th>Commitment</th><th>Inquiry</th><th>Status</th><th>Due date</th><th>Evidence</th><th>Risk</th></tr></thead><tbody>{loading&&<tr><td colSpan={6}>Loading commitment traceability…</td></tr>}{!loading&&rows.length===0&&<tr><td colSpan={6}>No commitments are currently recorded in open examination traces.</td></tr>}{rows.map(r=>{const late=r.status==="open"&&Boolean(r.due_at)&&new Date(r.due_at!).getTime()<now;return <tr key={`${r.caseId}-${r.commitment_key}`}><td className="font-semibold">{r.commitment_key}</td><td>{r.inquiry}</td><td><span className="badge">{r.status}</span></td><td>{String(r.due_at??"—")}</td><td>{r.evidence_refs.length} reference(s)</td><td><span className={late?"badge badge-critical":"badge badge-low"}>{late?"overdue":"on track"}</span></td></tr>})}</tbody></table></div></section>
 <section className="card p-5"><div className="flex items-start gap-3"><ShieldCheck className="h-5 w-5 text-teal-300 mt-0.5"/><div><h2 className="font-semibold">Governed traceability</h2><p className="mt-2 text-sm text-slate-400">Commitment → owner → milestone → evidence → effectiveness validation → human certification → regulator follow-up.</p><div className="flex gap-2 mt-4"><Link href="/review/regulatory-examinations" className="btn">Examination workspace</Link><Link href="/review/regulatory-remediation" className="btn btn-primary">Remediation workbench</Link></div></div></div></section></div>
}
