from app.domain.regulatory_examination_repeated_recovery_failure_investigation import REPEATED_RECOVERY_FAILURE_INVESTIGATION_AUTHORITY
from app.evaluation.regulatory_examination_repeated_recovery_failure_investigation import remediation_reauthorization_readiness
a=REPEATED_RECOVERY_FAILURE_INVESTIGATION_AUTHORITY
assert not a["ai_can_authorize_remediation"] and not a["ai_can_accept_residual_systemic_risk"] and not a["ai_can_certify_recovery_effectiveness"]
r=remediation_reauthorization_readiness({"recovery_evidence_reconstructed":True,"root_cause_human_confirmed":True,"cross_entity_scope_validated":True,"failed_rehabilitation_assessed":True,"independent_internal_audit_challenge_complete":True,"regulator_follow_up_assessed":True,"renewed_recovery_strategy_documented":True})
assert r["ready_for_human_authorization"] and not r["automated_authorization_allowed"]
print("Release 87 repeated-recovery-failure investigation governance verification passed")
