from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
required=['backend/app/domain/financial_investigation.py','backend/app/models/financial_investigation.py','backend/app/repositories/financial_investigation.py','backend/app/services/financial_investigation.py','backend/app/api/v1/financial_investigation.py','backend/app/workers/financial_investigation.py','backend/app/evaluation/financial_investigation.py','backend/alembic/versions/0038_financial_investigation_case_management.py','frontend/app/review/financial-investigations/page.tsx','config/financial_investigation.yaml','docs/FINANCIAL_INVESTIGATION_PAYMENT_INTEGRITY.md','data/evaluation/financial_investigation_cases.json','sample-data/financial-investigation/financial_investigation_scenario.json']
missing=[x for x in required if not (ROOT/x).exists()];assert not missing,missing
domain=(ROOT/'backend/app/domain/financial_investigation.py').read_text();service=(ROOT/'backend/app/services/financial_investigation.py').read_text();worker=(ROOT/'backend/app/workers/financial_investigation.py').read_text();migration=(ROOT/'backend/alembic/versions/0038_financial_investigation_case_management.py').read_text();runtime=(ROOT/'backend/app/workers/production_runtime.py').read_text();values=(ROOT/'infra/helm/medclaimiq/values.yaml').read_text();bff=(ROOT/'frontend/app/api/reviewer/[...path]/route.ts').read_text()
for token in ['"ai_can_close_case": False','"ai_can_place_payment_hold": False','"ai_can_create_accounting_adjustment": False','"ai_can_approve_remediation": False','"background_worker_can_move_funds": False','"material_remediation_dual_approval_required": True','"recommendation_only": True']:assert token in domain,token
for token in ['create_from_anomaly','cluster_key','FinancialInvestigationEvidencePackModel','acquire_lease','AI-vs-human disagreement rationale','pending_second_approval','execute_referral','close_case','event_sha256','source_watermark_sha256']:assert token in service,token
for forbidden in ['approve_remediation(', 'execute_referral(', 'place_hold(', 'authorize_packet(', '_post_journal(', 'close_period(', 'handoff(']:assert forbidden not in worker,f'worker authority violation {forbidden}'
assert 'ENABLE ROW LEVEL SECURITY' in migration and 'FORCE ROW LEVEL SECURITY' in migration and 'reject_financial_investigation_immutable_mutation' in migration
assert 'financial-investigation' in runtime and 'financial-investigation:' in values and 'financial-investigations' in bff
print('financial investigation/payment integrity/governed remediation verifier: PASS')
