"use client";
import { useEffect, useState } from "react";
import { FileCheck2, FileSearch2, Send, ShieldCheck } from "lucide-react";
import { reviewerApi } from "@/lib/api";
import { ActionDialog, type DialogField } from "@/components/ui/action-dialog";
import type { RegulatoryExaminationCase, RegulatoryExaminationDashboard, RegulatoryExaminationTrace, RegulatoryFinding, RegulatoryResponse } from "@/lib/regulatory-schemas";

type DialogSpec={title:string;description?:string;fields:DialogField[];submitLabel:string;run:(values:Record<string,string>)=>Promise<void>};
const msg=(error:unknown)=>error instanceof Error?error.message:String(error);
export default function RegulatoryExaminationsPage(){
 const [data,setData]=useState<RegulatoryExaminationDashboard|null>(null),[trace,setTrace]=useState<RegulatoryExaminationTrace|null>(null),[error,setError]=useState(""),[dialog,setDialog]=useState<DialogSpec|null>(null),[busy,setBusy]=useState(false);
 const refresh=async()=>{try{setData(await reviewerApi.regulatoryExaminationDashboard());setError("")}catch(e){setError(msg(e))}};
 useEffect(()=>{void refresh();const es=new EventSource("/api/reviewer/queue/events");const h=()=>void refresh();es.addEventListener("review-event",h);return()=>es.close()},[]);
 const inspect=async(c:RegulatoryExaminationCase)=>{try{setTrace(await reviewerApi.regulatoryExaminationTraceability(c.examination_case_id));setError("")}catch(e){setError(msg(e))}};
 const currentCase=()=>data?.cases.find(c=>c.examination_case_id===trace?.case.examination_case_id)??null;
 const submit=async(values:Record<string,string>)=>{if(!dialog)return;setBusy(true);try{await dialog.run(values);setDialog(null)}catch(e){setError(msg(e))}finally{setBusy(false)}};
 const evidence=async(c:RegulatoryExaminationCase)=>{try{await reviewerApi.buildRegulatoryExaminationEvidencePack(c.examination_case_id,c.case_version);await refresh();await inspect(c)}catch(e){setError(msg(e))}};
 const draft=(c:RegulatoryExaminationCase)=>setDialog({title:"Prepare cited examination response",description:"Leave the response blank to request a guarded AI-assisted draft. The resulting draft still requires independent human approval.",submitLabel:"Prepare draft",fields:[{name:"response",label:"Human-edited response",type:"textarea",placeholder:"Optional: enter the response text yourself"}],run:async v=>{await reviewerApi.draftRegulatoryExaminationResponse(c.examination_case_id,{response_text:v.response.trim()||null,cited_refs:[],use_ai_assistance:!v.response.trim(),expected_case_version:c.case_version});await refresh();await inspect(c)}});
 const approve=(c:RegulatoryExaminationCase,r:RegulatoryResponse)=>setDialog({title:"Independent response approval",description:"Record the maker-checker rationale. Approval is immutable and remains a human authority action.",submitLabel:"Approve response",fields:[{name:"rationale",label:"Approval rationale",type:"textarea",required:true,placeholder:"Explain the independent evidence and citation review performed."}],run:async v=>{await reviewerApi.approveRegulatoryExaminationResponse(c.examination_case_id,r.response_id,{approval_rationale:v.rationale,expected_case_version:c.case_version});await refresh();await inspect(c)}});
 const openCapa=(finding:RegulatoryFinding)=>setDialog({title:"Open governed corrective action",description:"Create an evidence-bound remediation plan for this material finding.",submitLabel:"Create remediation plan",fields:[{name:"owner",label:"Human remediation owner user ID",required:true},{name:"root",label:"Root cause",type:"textarea",required:true,defaultValue:finding.description??""}],run:async v=>{if(!trace)return;await reviewerApi.createRegulatoryRemediationPlan(trace.case.examination_case_id,{finding_code:finding.finding_code,root_cause:v.root,corrective_action_summary:"Implement the evidence-bound corrective action and document completion evidence.",preventive_action_summary:"Implement preventive monitoring, reviewer controls, and recurrence detection.",control_redesign_proposal:"Redesign the affected control with deterministic validation, maker-checker review, immutable evidence checkpoints, and fail-closed escalation.",financial_impact_analysis:"Read-only financial impact analysis; financial changes remain separately governed.",accounting_impact_analysis:"Read-only accounting impact analysis; journal changes remain separately governed.",owner_user_id:v.owner,due_at:new Date(Date.now()+30*86400000).toISOString(),use_ai_assistance:true});window.location.assign("/review/regulatory-remediation")}});
 const deliver=(c:RegulatoryExaminationCase,r:RegulatoryResponse)=>setDialog({title:"Secure regulator delivery",description:"Delivery uses the governed regulator portal channel and preserves immutable response provenance.",submitLabel:"Deliver approved response",fields:[{name:"subject",label:"Response subject",required:true,defaultValue:"Response to regulatory examination inquiry"}],run:async v=>{await reviewerApi.deliverRegulatoryExaminationResponse(c.examination_case_id,r.response_id,{channel:"regulator_portal",subject:v.subject,external_reference:null,supplemental_submission_reference:null,expected_case_version:c.case_version});await refresh();await inspect(c)}});
 return <div className="space-y-5"><header><div className="panel-title">Regulatory operations</div><h1 className="text-2xl font-bold mt-1">Regulatory Examination & Inquiry Response</h1><p className="text-sm text-slate-400 mt-2 max-w-4xl">Certified filing → regulator inquiry → immutable evidence pack → cited retrieval → guarded drafting → human maker/checker approval → secure response → closure provenance.</p></header>
  <section className="card p-4"><div className="flex gap-2 items-center font-semibold"><ShieldCheck className="h-4 w-4 text-teal-300"/>Authority boundary — human controlled</div><p className="text-sm text-slate-400 mt-2">AI, LangGraph, RAG, MCP and workers may retrieve, summarize and draft only. Response approval and regulatory representation remain human-controlled.</p></section>
  {error&&<div role="alert" className="card border-rose-500/30 p-3 text-rose-200">{error}</div>}
  {!data?<State text="Loading examination dashboard…"/>:<><section className="grid grid-cols-2 md:grid-cols-4 gap-3">{Object.entries(data.kpis).map(([k,v])=><Metric key={k} label={k} value={String(v??0)}/>)}</section><section className="card p-4"><h2 className="font-semibold">Regulatory inquiry queue</h2><div className="mt-3 space-y-2">{data.cases.length===0?<State text="No open regulatory inquiry cases."/>:data.cases.map(c=><article key={c.examination_case_id} className="rounded-xl border border-[#233b55] p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><b>{c.external_inquiry_reference}</b><span className="badge">{c.status} · {c.severity}</span></div><div className="text-slate-400 mt-1">{c.question_classification} · due {String(c.response_due_at??"—")} · version {c.case_version}</div><div className="text-xs text-slate-500 mt-1">open requests {c.open_document_requests} · material findings {c.open_material_findings} · commitments {c.open_commitments}</div><div className="flex gap-2 mt-3 flex-wrap"><button className="btn" onClick={()=>void evidence(c)}><FileCheck2 className="h-4 w-4"/>Lock evidence pack</button><button className="btn" onClick={()=>draft(c)}><FileSearch2 className="h-4 w-4"/>Draft cited response</button><button className="btn btn-ghost" onClick={()=>void inspect(c)}>Traceability</button></div></article>)}</div></section></>}
  {trace&&<section className="card p-4 space-y-3"><h2 className="font-semibold">Evidence / response workspace</h2><div className="text-xs text-slate-400">Evidence packs {trace.evidence_packs.length} · responses {trace.responses.length} · findings {trace.findings.length} · commitments {trace.commitments.length}</div><div className="space-y-2">{trace.findings.map(f=><div key={f.finding_code} className="border border-[#233b55] rounded-xl p-3 text-sm"><b>{f.finding_code}</b> · {f.status} · material {String(f.material)}{f.material&&f.status!=="resolved"&&<button className="btn ml-2" onClick={()=>openCapa(f)}>Open governed CAPA</button>}</div>)}</div>{trace.responses.map(r=><div key={r.response_id} className="border border-[#233b55] rounded-xl p-3"><div className="flex justify-between"><b>Response version {r.version}</b><span className="badge">{r.status}</span></div><div className="text-xs text-slate-500 mt-1">AI assisted {String(r.ai_assisted)} · authority {r.authority} · hash {r.response_sha256}</div><div className="flex gap-2 mt-3">{r.status==="draft"&&currentCase()&&<button className="btn btn-primary" onClick={()=>approve(currentCase()!,r)}>Independent human approve</button>}{r.status==="approved"&&currentCase()&&<button className="btn btn-primary" onClick={()=>deliver(currentCase()!,r)}><Send className="h-4 w-4"/>Secure deliver</button>}</div></div>)}</section>}
  <ActionDialog open={Boolean(dialog)} title={dialog?.title??""} description={dialog?.description} fields={dialog?.fields??[]} submitLabel={dialog?.submitLabel} busy={busy} onClose={()=>setDialog(null)} onSubmit={submit}/>
 </div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="card p-4"><div className="text-xs text-slate-500 capitalize">{label.replaceAll("_"," ")}</div><div className="text-xl font-semibold mt-1">{value}</div></div>}
function State({text}:{text:string}){return <div className="rounded-xl border border-dashed border-[#31506f] p-5 text-sm text-slate-500">{text}</div>}
