"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { AlertTriangle, ClipboardCheck, FileSearch2, RefreshCw, ShieldCheck } from "lucide-react";
import { reviewerApi } from "@/lib/api";
import { Kpi } from "@/components/ui/primitives";
import type { PortfolioDashboard, RegulatoryExaminationDashboard, RemediationDashboard } from "@/lib/regulatory-schemas";
const message=(e:unknown)=>e instanceof Error?e.message:String(e);
export default function RegulatoryExaminationReadinessPage(){
 const [exam,setExam]=useState<RegulatoryExaminationDashboard|null>(null),[remediation,setRemediation]=useState<RemediationDashboard|null>(null),[portfolio,setPortfolio]=useState<PortfolioDashboard|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const [a,b,c]=await Promise.allSettled([reviewerApi.regulatoryExaminationDashboard(),reviewerApi.regulatoryRemediationDashboard(),reviewerApi.regulatoryPortfolioDashboard()]);if(a.status==="fulfilled")setExam(a.value);else setError(message(a.reason));if(b.status==="fulfilled")setRemediation(b.value);if(c.status==="fulfilled")setPortfolio(c.value);setLoading(false)};
 useEffect(()=>{void load();const es=new EventSource("/api/reviewer/queue/events");const h=()=>void load();es.addEventListener("review-event",h);return()=>es.close()},[]);
 const cases=exam?.cases??[];const open=cases.filter(c=>c.status!=="closed");const requests=open.reduce((n,c)=>n+c.open_document_requests,0),findings=open.reduce((n,c)=>n+c.open_material_findings,0),commitments=open.reduce((n,c)=>n+c.open_commitments,0),ready=open.filter(c=>!c.open_document_requests&&!c.open_material_findings&&!c.open_commitments).length;
 return <div className="space-y-5"><div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><header><div className="panel-title">Regulatory operations</div><h1 className="text-2xl font-bold mt-1">Examination Readiness</h1><p className="text-sm text-slate-400 mt-2 max-w-4xl">Live preparation view across regulator inquiries, evidence completeness, material findings, commitments, corrective actions and portfolio assurance. Submission authority remains human-controlled.</p></header><button className="btn" onClick={()=>void load()} disabled={loading}><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/>Refresh</button></div>
 {error&&<div role="alert" className="card border-rose-500/30 p-3 text-rose-200"><AlertTriangle className="inline h-4 w-4 mr-2"/>{error}</div>}
 <section className="grid sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8 gap-3"><Kpi label="Open inquiries" value={String(open.length)}/><Kpi label="Overdue responses" value={String(exam?.kpis.overdue??0)}/><Kpi label="Open requests" value={String(requests)}/><Kpi label="Material findings" value={String(findings)}/><Kpi label="Open commitments" value={String(commitments)}/><Kpi label="Package ready" value={`${ready}/${open.length||0}`}/><Kpi label="Active remediation" value={String(remediation?.plans.filter(p=>p.status!=="closed").length??0)}/><Kpi label="Portfolio assurance" value={portfolio?.latest?.status??"not prepared"}/></section>
 <section className="card p-5"><div className="flex items-center gap-2"><ClipboardCheck className="h-4 w-4 text-teal-300"/><h2 className="font-semibold">Readiness by inquiry</h2></div><div className="table-wrap mt-3"><table><caption className="sr-only">Live regulatory examination readiness by inquiry</caption><thead><tr><th>Inquiry</th><th>Status</th><th>Evidence requests</th><th>Material findings</th><th>Commitments</th><th>Response due</th><th>Readiness</th></tr></thead><tbody>{loading&&!exam&&<tr><td colSpan={7}>Loading live readiness metrics…</td></tr>}{!loading&&open.length===0&&<tr><td colSpan={7}>No open regulatory examinations.</td></tr>}{open.map(c=>{const isReady=!c.open_document_requests&&!c.open_material_findings&&!c.open_commitments;return <tr key={c.examination_case_id}><td className="font-semibold">{c.external_inquiry_reference}</td><td><span className="badge">{c.status}</span></td><td>{c.open_document_requests}</td><td>{c.open_material_findings}</td><td>{c.open_commitments}</td><td>{String(c.response_due_at??"—")}</td><td><span className={isReady?"badge badge-low":"badge badge-high"}>{isReady?"package ready":"action required"}</span></td></tr>})}</tbody></table></div></section>
 <section className="grid md:grid-cols-3 gap-4"><Action title="Examination workspace" body="Lock evidence packs, prepare cited responses, independently approve and securely deliver regulator responses." href="/review/regulatory-examinations" icon={<FileSearch2 className="h-5 w-5"/>}/><Action title="Commitment assurance" body="Track confirmed commitments, due dates and evidence completeness across open examinations." href="/review/regulatory-examination-commitments" icon={<ShieldCheck className="h-5 w-5"/>}/><Action title="Remediation" body="Manage corrective actions, evidence checkpoints, independent retests and closure certification." href="/review/regulatory-remediation" icon={<RefreshCw className="h-5 w-5"/>}/></section>
 </div>
}
function Action({title,body,href,icon}:{title:string;body:string;href:string;icon:React.ReactNode}){return <Link href={href} className="card p-5 hover:border-teal-400/40"><div className="text-teal-300">{icon}</div><h2 className="font-semibold mt-3">{title}</h2><p className="text-sm text-slate-400 mt-2">{body}</p><div className="text-xs text-teal-300 mt-4">Open workbench →</div></Link>}
