"use client";
import {useEffect,useState} from "react";
import {FileCheck2,LockKeyhole,ShieldCheck,UploadCloud} from "lucide-react";
import {reviewerApi} from "@/lib/api";
import {Kpi,Panel,Row} from "@/components/ui/primitives";
import type {RecoveryControlAssuranceDashboard,RecoveryControlAssuranceWorkbench,RecoveryControlPackage} from "@/lib/schemas";

export default function RecoveryControlAssurancePage(){
 const [dash,setDash]=useState<RecoveryControlAssuranceDashboard|null>(null),[periodId,setPeriodId]=useState(""),[work,setWork]=useState<RecoveryControlAssuranceWorkbench|null>(null),[error,setError]=useState("");
 const load=async()=>{try{setDash(await reviewerApi.recoveryControlAssuranceDashboard());setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load control assurance")}};
 const open=async(id=periodId)=>{if(!id)return;try{setPeriodId(id);setWork(await reviewerApi.recoveryControlAssuranceWorkbench(id));setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load reporting period")}};
 useEffect(()=>{void load();const es=new EventSource("/api/reviewer/queue/events");const refresh=()=>{void load();if(periodId)void open(periodId)};["recovery_control_assurance.attestation.prepared","recovery_control_assurance.package.prepared","recovery_control_assurance.package.locked","recovery_control_assurance.package.certified","recovery_control_assurance.submission.staged","recovery_control_assurance.submission.receipt_recorded"].forEach(x=>es.addEventListener(x,refresh));return()=>es.close()},[periodId]);
 const prepare=async()=>{if(!periodId)return;await reviewerApi.prepareRecoveryControlAttestation(periodId);await open(periodId)};
 const createPackage=async()=>{if(!periodId)return;await reviewerApi.createRegulatorySubmissionPackage(periodId);await open(periodId)};
 const lock=async(p:RecoveryControlPackage)=>{await reviewerApi.lockRegulatorySubmissionPackage(p.package_id,p.source_watermark_sha256);await open(periodId)};
 const certify=async(p:RecoveryControlPackage)=>{await reviewerApi.certifyRegulatorySubmissionPackage(p.package_id,"Independent human checker certifies the locked recovery/accounting package after deterministic controls, tie-outs and provider-statement completeness are reviewed.");await open(periodId)};
 const stage=async(p:RecoveryControlPackage)=>{await reviewerApi.stageRegulatorySubmissionPackage(p.package_id,"Authorized human audit/regulatory user stages this maker-checker certified package; MedClaimIQ does not automatically submit to a regulator.");await open(periodId)};
 return <div className="space-y-5"><section className="card p-6 border-teal-400/20"><div className="panel-title">governed reporting certification</div><h1 className="text-2xl font-bold mt-1">Recovery Portfolio Control Assurance & Regulatory Submission Governance</h1><p className="text-sm text-slate-400 mt-2 max-w-5xl">Deterministic control attestations, reconciliation-to-ledger tie-outs, provider statement completeness, evidence sampling, report-version locking, maker-checker certification, human submission staging, receipts and immutable amendment chains. AI and workers cannot certify reports, submit as a human authority, change financial records or move funds.</p></section>
 {error&&<div className="rounded-xl border border-rose-500/30 p-3 text-rose-200 text-sm">{error}</div>}
 {dash&&<section className="grid md:grid-cols-5 gap-3"><Kpi label="Periods" value={dash.kpis.reporting_periods}/><Kpi label="Packages" value={dash.kpis.packages}/><Kpi label="Certified" value={dash.kpis.certified_packages}/><Kpi label="Submitted" value={dash.kpis.submitted_packages}/><Kpi label="Control effectiveness" value={`${dash.kpis.average_control_effectiveness_pct}%`}/></section>}
 <section className="card p-5"><div className="panel-title">Operational reporting queue</div><div className="mt-3 space-y-2">{dash?.operational_queue?.map((x)=><button key={x.reporting_period_id} onClick={()=>void open(x.reporting_period_id)} className="w-full rounded-xl border border-[#1f3852] p-3 text-left"><div className="flex justify-between"><b>{x.period_key}</b><span>{x.latest_package_status}</span></div><div className="text-xs text-slate-500 mt-1">control {x.control_effectiveness_pct??"not prepared"}% · blockers {x.material_blockers?.length??0}</div></button>)}</div></section>
 {work&&<><section className="card p-5"><div className="flex justify-between gap-3"><div><div className="panel-title">{work.period.period_key}</div><div className="text-sm text-slate-400 mt-1">{work.period.report_type} · {work.period.jurisdiction}</div></div><div className="flex gap-2"><button className="btn btn-ghost" onClick={()=>void prepare()}><FileCheck2 className="h-4 w-4"/>Prepare controls</button><button className="btn btn-primary" onClick={()=>void createPackage()}>Prepare package</button></div></div>{work.latest_attestation&&<div className="mt-4"><div className="text-sm">Control effectiveness <b>{work.latest_attestation.control_effectiveness_pct}%</b></div><div className="mt-2 space-y-2">{work.latest_attestation.control_results.map((c)=><div key={c.control_code} className={`rounded-xl border p-3 text-sm ${c.passed?"border-emerald-500/20":"border-rose-500/30"}`}><div className="flex justify-between"><b>{c.control_code}</b><span>{c.passed?"PASS":"BLOCK"}</span></div><div className="mono text-[10px] text-slate-500 mt-1 break-all">{JSON.stringify(c.details)}</div></div>)}</div></div>}</section>
 <section className="card p-5"><div className="panel-title">Submission package versions</div><div className="mt-3 space-y-3">{work.packages.map((p)=><div key={p.package_id} className="rounded-xl border border-[#1f3852] p-4"><div className="flex justify-between"><b>Package v{p.package_version}</b><span>{p.status}</span></div><div className="mono text-[10px] text-slate-500 mt-2 break-all">manifest {p.manifest_sha256}</div><div className="text-xs text-slate-500 mt-1">maker {p.maker_user_id} · checker {p.checker_user_id??"pending"} · blockers {p.material_blockers.length}</div><div className="flex flex-wrap gap-2 mt-3">{p.status==="draft"&&<button className="btn btn-ghost" onClick={()=>void lock(p)}><LockKeyhole className="h-4 w-4"/>Lock report version</button>}{p.status==="locked"&&<button className="btn btn-primary" onClick={()=>void certify(p)}><ShieldCheck className="h-4 w-4"/>Independent human certify</button>}{p.status==="certified"&&<button className="btn btn-primary" onClick={()=>void stage(p)}><UploadCloud className="h-4 w-4"/>Human stage submission</button>}</div></div>)}</div></section>
 <section className="grid xl:grid-cols-2 gap-5"><Panel title="Immutable certification chain">{work.certification_chain.map((x)=><Row key={x.certification_id} title={`#${x.sequence} · ${x.package_id}`} sub={`${x.maker_user_id} → ${x.checker_user_id}`} hash={x.certification_sha256}/>)}</Panel><Panel title="Audit chain">{work.audit_chain.map((x)=><Row key={x.sequence} title={`#${x.sequence} · ${x.event_type}`} sub={`${x.actor_type} · ${x.actor_id}`} hash={x.event_sha256}/>)}</Panel></section></>}
 <section className="card p-5 border-emerald-500/20"><div className="flex gap-2 items-center"><ShieldCheck className="text-emerald-300"/><div className="panel-title">Authority boundary</div></div><p className="text-sm text-slate-300 mt-3">AI may prepare, retrieve, summarize and flag controls. Certification: <b>human maker-checker only</b>. Regulatory submission: <b>human-staged with external receipt provenance</b>. Financial record mutation, payment authorization, collections and fund movement: <b>none</b>.</p></section></div>
}
