"use client";
import { FormEvent, useState } from "react";
import { Activity, Search, ShieldCheck, TriangleAlert } from "lucide-react";
import { reviewerApi } from "@/lib/api";
import { useEventStream } from "@/lib/hooks/use-event-stream";
import { Kpi, Panel, Row, Empty } from "@/components/ui/primitives";
import type { FinancialAnomalyInvestigation, FinancialCopilot, FinancialIntelligenceClaim, FinancialIntelligencePortfolio } from "@/lib/schemas";

export default function FinancialIntelligencePage(){
  const [claimId,setClaimId]=useState("");
  const [claim,setClaim]=useState<FinancialIntelligenceClaim|null>(null);
  const [portfolio,setPortfolio]=useState<FinancialIntelligencePortfolio|null>(null);
  const [query,setQuery]=useState("Explain the current reserve, payment integrity risks, and accounting close blockers with ledger citations.");
  const [copilot,setCopilot]=useState<FinancialCopilot|null>(null);const [investigation,setInvestigation]=useState<FinancialAnomalyInvestigation|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  const loadPortfolio=async()=>{setBusy(true);setError(null);try{setPortfolio(await reviewerApi.financialIntelligencePortfolio())}catch(x){setError(x instanceof Error?x.message:"Financial intelligence unavailable")}finally{setBusy(false)}};
  const loadClaim=async(e?:FormEvent)=>{e?.preventDefault();if(!claimId)return;setBusy(true);setError(null);try{setClaim(await reviewerApi.financialIntelligenceClaim(claimId))}catch(x){setError(x instanceof Error?x.message:"Claim analytics unavailable")}finally{setBusy(false)}};
  const ask=async()=>{setBusy(true);setError(null);try{setCopilot(await reviewerApi.financialCopilot(query,claimId||undefined))}catch(x){setError(x instanceof Error?x.message:"Copilot unavailable")}finally{setBusy(false)}};
  const investigate=async(code:string)=>{if(!claimId)return;setBusy(true);setError(null);try{setInvestigation(await reviewerApi.investigateFinancialAnomaly(claimId,code))}catch(x){setError(x instanceof Error?x.message:"Investigation unavailable")}finally{setBusy(false)}};
  const {state}=useEventStream(claimId?`/api/reviewer/claims/${encodeURIComponent(claimId)}/events`:null,()=>{if(claim)void loadClaim()});
  return <div className="space-y-5">
    <section className="card p-6 border-emerald-400/20"><div className="flex justify-between gap-4"><div><div className="panel-title">read-only finance intelligence · SSE {state}</div><h1 className="text-2xl font-bold mt-1">Reserve, Payment Integrity & Accounting Control Intelligence</h1><p className="text-sm text-slate-400 mt-2 max-w-5xl">Read-only analytics over governed governed financial and ledger records: paid-vs-incurred, reserve adequacy, leakage/overpayment indicators, reconciliation anomaly scoring, provider patterns, recoupment aging, period-close readiness, and ledger-cited financial RAG. AI/agents cannot alter journals, reserves, payment authorization, accounting periods, adjudication or funds.</p></div><Activity className="h-9 w-9 text-emerald-300"/></div></section>
    <section className="grid xl:grid-cols-[1fr_auto] gap-3"><form onSubmit={loadClaim} className="card p-4 flex gap-3"><input className="input flex-1" value={claimId} onChange={e=>setClaimId(e.target.value)} placeholder="Claim ID"/><button className="btn btn-primary" disabled={busy}>Analyze claim</button></form><button className="btn btn-ghost" disabled={busy} onClick={()=>void loadPortfolio()}>Load portfolio KPIs</button></section>
    {error&&<div className="rounded-xl border border-rose-500/30 p-3 text-sm text-rose-200"><TriangleAlert className="inline h-4 w-4 mr-2"/>{error}</div>}
    {portfolio&&<><section className="grid md:grid-cols-4 xl:grid-cols-8 gap-3"><Kpi label="Claims" value={String(portfolio.kpis.claims_analyzed)}/><Kpi label="Incurred" value={portfolio.kpis.incurred_amount}/><Kpi label="Net paid" value={portfolio.kpis.net_paid_amount}/><Kpi label="Reserve" value={portfolio.kpis.outstanding_reserve}/><Kpi label="Leakage" value={portfolio.kpis.financial_leakage_exposure}/><Kpi label="High risk" value={String(portfolio.kpis.high_risk_claims)}/><Kpi label="Open recoupments" value={String(portfolio.kpis.open_recoupments)}/><Kpi label="Close readiness" value={`${portfolio.kpis.period_close_readiness_average}%`}/></section>
    <section className="grid xl:grid-cols-3 gap-5"><Panel title="Provider payment-pattern intelligence">{portfolio.provider_patterns.length?portfolio.provider_patterns.map((p)=><Row key={p.provider_ref} title={p.provider_ref} right={`${p.pattern_risk_score}/100`} sub={`remitted ${p.remitted_total} · returns ${p.returned_amount} · open exceptions ${p.open_exception_count} · recoupments ${p.recoupment_amount}`}/>):<Empty/>}</Panel><Panel title="Recoupment aging">{portfolio.recoupment_aging.length?portfolio.recoupment_aging.map((r)=><Row key={r.adjustment_id} title={`${r.claim_id} · ${r.amount}`} right={`${r.age_days}d`} sub={r.status}/>):<Empty/>}</Panel><Panel title="Accounting close readiness">{portfolio.period_close_readiness.length?portfolio.period_close_readiness.map((p)=><Row key={p.period_id} title={`${p.period_key} · ${p.status}`} right={`${p.readiness_score}%`} sub={p.blockers.length?p.blockers.map((b)=>`${b.code} (${b.count})`).join(" · "):"No deterministic blockers"}/>):<Empty/>}</Panel></section>
    <Panel title="Accounting control exceptions">{portfolio.accounting_control_exceptions.length?portfolio.accounting_control_exceptions.map((x,i:number)=><Row key={`${x.period_id}-${x.code}-${i}`} title={`${x.period_key} · ${x.code}`} right={String(x.count)} sub={`readiness weight ${x.weight}`}/>):<Empty text="No deterministic accounting control exceptions detected."/>}</Panel></>}
    {claim&&<><section className="grid md:grid-cols-4 xl:grid-cols-8 gap-3"><Kpi label="Incurred" value={claim.metrics.approved_incurred}/><Kpi label="Net paid" value={claim.metrics.net_paid}/><Kpi label="Reserve" value={claim.metrics.outstanding_reserve}/><Kpi label="Reserve variance" value={claim.metrics.reserve_variance}/><Kpi label="Adequacy" value={`${claim.metrics.reserve_adequacy_score}%`}/><Kpi label="Leakage" value={claim.metrics.financial_leakage_exposure}/><Kpi label="Anomaly" value={`${claim.metrics.reconciliation_anomaly_score}/100`}/><Kpi label="Recon age" value={`${claim.metrics.max_reconciliation_age_days}d`}/></section>
    <section className="grid xl:grid-cols-2 gap-5"><Panel title="Explainable anomaly factors">{claim.anomaly_factors.length?claim.anomaly_factors.map((f)=><div key={f.factor} className="rounded-xl border border-[#1f3852] p-3 text-sm"><div className="flex justify-between gap-3"><b>{f.factor}</b><span>+{f.points}</span></div><div className="text-xs text-slate-500 mt-1 break-all">{JSON.stringify(f.detail)}</div><button className="btn btn-ghost mt-2" disabled={busy} onClick={()=>void investigate(f.factor)}>Explain with cited records</button></div>):<Empty text="No deterministic payment-integrity anomaly factors detected."/>}{investigation&&<div className="rounded-xl border border-amber-500/20 p-3 text-sm"><b>{investigation.anomaly_code} · {investigation.anomaly_score}/100</b><p className="text-slate-400 mt-2">{investigation.explanation}</p><div className="text-xs text-emerald-300 mt-2">Authority: accounting none · fund movement none</div></div>}</Panel><Panel title="Immutable reserve history">{claim.reserve_history.length?claim.reserve_history.map((r)=><Row key={r.reserve_snapshot_id} title={r.outstanding_reserve} right={`${r.adequacy_score}%`} sub={`variance ${r.reserve_variance} · ${r.created_at}`}/>):<Empty/>}</Panel></section>
    <Panel title="Ledger citation drill-down">{claim.citations.length?claim.citations.map((c)=><div key={c.citation_id} className="rounded-xl border border-[#1f3852] p-3 text-sm"><div className="flex justify-between gap-3"><b>{c.type}</b><span className="mono text-[10px] text-slate-500">{c.citation_id}</span></div>{c.sha256&&<div className="mono text-[10px] break-all text-slate-500 mt-1">{c.sha256}</div>}</div>):<Empty/>}</Panel></>}
    <section className="card p-5"><div className="panel-title">Financial RAG / Copilot · ledger citations required</div><div className="mt-3 flex gap-3"><input className="input flex-1" value={query} onChange={e=>setQuery(e.target.value)}/><button className="btn btn-primary" onClick={()=>void ask()} disabled={busy}><Search className="h-4 w-4"/>Ask</button></div>{copilot&&<div className="mt-4 rounded-xl border border-emerald-500/20 p-4"><p className="text-sm text-slate-200">{copilot.answer}</p><div className="mt-3 space-y-1">{copilot.citations.map((c)=><div key={c.citation_id} className="mono text-[10px] text-slate-500">[{c.type}] {c.citation_id} · score {c.retrieval_score}</div>)}</div><div className="text-xs text-emerald-300 mt-3">Authority: adjudication none · accounting none · fund movement none</div></div>}</section>
    <section className="card p-5 border-emerald-500/20"><div className="flex items-center gap-2"><ShieldCheck className="text-emerald-300"/><div className="panel-title">Read-only authority boundary</div></div><p className="text-sm text-slate-300 mt-3">LLM ledger mutation: <b>false</b> · LangGraph: <b>false</b> · RAG: <b>false</b> · MCP: <b>false</b> · analytics worker source mutation: <b>false</b> · AI reserve mutation: <b>false</b> · AI payment authorization: <b>false</b> · AI period close: <b>false</b> · automatic fund movement: <b>false</b>.</p></section>
  </div>
}
