"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, FileCheck2, RefreshCw, ShieldCheck } from "lucide-react";
import { reviewerApi } from "@/lib/api";
import { ActionDialog, type DialogField } from "@/components/ui/action-dialog";
import type { EvidenceReference, RemediationDashboard, RemediationFollowup, RemediationPlan, RemediationTask, RemediationTrace } from "@/lib/regulatory-schemas";

type Spec={title:string;description:string;fields:DialogField[];submitLabel:string;run:(v:Record<string,string>)=>Promise<void>};
const message=(e:unknown)=>e instanceof Error?e.message:String(e);
const ref=(type:string,id:string):EvidenceReference=>({type,id});
export default function RegulatoryRemediationPage(){
 const [data,setData]=useState<RemediationDashboard|null>(null),[trace,setTrace]=useState<RemediationTrace|null>(null),[error,setError]=useState(""),[dialog,setDialog]=useState<Spec|null>(null),[busy,setBusy]=useState(false);
 const refresh=async()=>{try{setData(await reviewerApi.regulatoryRemediationDashboard());setError("")}catch(e){setError(message(e))}};
 useEffect(()=>{void refresh();const es=new EventSource("/api/reviewer/queue/events");const h=()=>void refresh();es.addEventListener("review-event",h);return()=>es.close()},[]);
 const inspect=async(p:RemediationPlan)=>{try{setTrace(await reviewerApi.regulatoryRemediationTraceability(p.plan_id));setError("")}catch(e){setError(message(e))}};
 const reloadTrace=async()=>{if(trace?.plan.plan_id)setTrace(await reviewerApi.regulatoryRemediationTraceability(trace.plan.plan_id))};
 const submit=async(v:Record<string,string>)=>{if(!dialog)return;setBusy(true);try{await dialog.run(v);setDialog(null)}catch(e){setError(message(e))}finally{setBusy(false)}};
 const approve=(p:RemediationPlan)=>setDialog({title:"Independent remediation-plan approval",description:"Record the independent review of root cause, corrective/preventive actions, control redesign and read-only financial/accounting impact analysis.",submitLabel:"Approve plan",fields:[{name:"rationale",label:"Approval rationale",type:"textarea",required:true,defaultValue:"I independently reviewed the finding, root cause, CAPA scope, control redesign, and read-only financial/accounting impact analysis."}],run:async v=>{await reviewerApi.approveRegulatoryRemediationPlan(p.plan_id,v.rationale);await refresh();await inspect(p)}});
 const addTask=()=>setDialog({title:"Add corrective-action task",description:"Task ownership, dependencies and due date become part of the immutable remediation trace.",submitLabel:"Add task",fields:[{name:"key",label:"Task key",required:true},{name:"owner",label:"Human task owner user ID",required:true},{name:"type",label:"Task type",type:"select",defaultValue:"corrective",options:["corrective","preventive","control_redesign","data_correction","training","process","monitoring"].map(x=>({value:x,label:x.replaceAll("_"," ")}))},{name:"description",label:"Task description",type:"textarea",required:true},{name:"dependencies",label:"Dependency task keys",placeholder:"task-a, task-b"}],run:async v=>{if(!trace)return;await reviewerApi.addRegulatoryRemediationTask(trace.plan.plan_id,{task_key:v.key,task_type:v.type,description:v.description,owner_user_id:v.owner,dependency_keys:v.dependencies.split(",").map(x=>x.trim()).filter(Boolean),due_at:new Date(Date.now()+14*86400000).toISOString()});await refresh();await reloadTrace()}});
 const completeTask=(task:RemediationTask)=>setDialog({title:`Complete ${task.task_key} with evidence`,description:"Completion is rejected without an explicit immutable implementation-evidence reference.",submitLabel:"Complete task",fields:[{name:"evidence",label:"Implementation evidence/reference ID",required:true}],run:async v=>{if(!trace)return;await reviewerApi.completeRegulatoryRemediationTask(trace.plan.plan_id,task.task_key,[ref("implementation_evidence",v.evidence)]);await reloadTrace()}});
 const checkpoint=()=>setDialog({title:"Lock implementation checkpoint",description:"Create an immutable evidence checkpoint for control implementation.",submitLabel:"Lock checkpoint",fields:[{name:"key",label:"Checkpoint key",defaultValue:"implementation-v1",required:true},{name:"evidence",label:"Control evidence/reference ID",required:true}],run:async v=>{if(!trace)return;await reviewerApi.addRegulatoryRemediationCheckpoint(trace.plan.plan_id,{checkpoint_key:v.key,checkpoint_type:"implementation_evidence",evidence_refs:[ref("control_evidence",v.evidence)]});await reloadTrace()}});
 const retest=()=>setDialog({title:"Record independent control retest",description:"The retest result must be evidence-bound and is kept separate from implementation ownership.",submitLabel:"Record retest",fields:[{name:"control",label:"Control key",required:true},{name:"observed",label:"Observed retest result",type:"textarea",required:true},{name:"evidence",label:"Retest evidence/reference ID",required:true}],run:async v=>{if(!trace)return;await reviewerApi.addRegulatoryControlRetest(trace.plan.plan_id,{control_key:v.control,methodology:"Independent replay/sample-based control effectiveness retest.",expected_result:"Redesigned control operates effectively with immutable evidence and no unexplained exceptions.",observed_result:v.observed,outcome:"pass",evidence_refs:[ref("retest_evidence",v.evidence)]});await refresh();await reloadTrace()}});
 const followup=()=>setDialog({title:"Draft regulator follow-up",description:"Follow-up text is linked to remediation evidence and remains subject to independent human approval.",submitLabel:"Create follow-up draft",fields:[{name:"response",label:"Regulator follow-up response",type:"textarea",required:true},{name:"evidence",label:"Remediation evidence/reference ID",required:true}],run:async v=>{if(!trace)return;await reviewerApi.draftRegulatoryRemediationFollowup(trace.plan.plan_id,{response_text:v.response,cited_refs:[ref("remediation_evidence",v.evidence)]});await reloadTrace()}});
 const approveFollowup=(f:RemediationFollowup)=>setDialog({title:"Independent follow-up approval",description:"Record the maker-checker rationale before regulator correspondence can advance.",submitLabel:"Approve follow-up",fields:[{name:"rationale",label:"Approval rationale",type:"textarea",required:true}],run:async v=>{if(!trace)return;await reviewerApi.approveRegulatoryRemediationFollowup(trace.plan.plan_id,f.followup_id,v.rationale);await reloadTrace()}});
 const certify=(p:RemediationPlan)=>setDialog({title:"Independent closure certification",description:"Closure requires completed actions, implementation evidence, effective retests and governed regulator follow-up.",submitLabel:"Certify closure",fields:[{name:"rationale",label:"Closure-certification rationale",type:"textarea",required:true,defaultValue:"I independently verified completed CAPA tasks, immutable implementation evidence, passing control retests, regulator follow-up governance, and remediation effectiveness."}],run:async v=>{await reviewerApi.certifyRegulatoryRemediationClosure(p.plan_id,{conclusion:"effective",closure_rationale:v.rationale});await refresh();await inspect(p)}});
 return <div className="space-y-5"><header><div className="panel-title">Regulatory operations</div><h1 className="text-2xl font-bold mt-1">Regulatory Findings Remediation & Closure Assurance</h1><p className="text-sm text-slate-400 mt-2">Finding → versioned corrective-action plan → evidence-bound implementation → independent retest → approved follow-up → independent closure certification.</p></header><section className="card p-4"><div className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-4 w-4 text-teal-300"/>Human authority boundary</div><p className="text-sm text-slate-400 mt-2">AI, RAG, agents and workers can recommend, summarize and monitor only. They cannot approve remediation or certify closure.</p></section>{error&&<div role="alert" className="card border-rose-500/30 p-3 text-rose-200">{error}</div>}
 {data?<><section className="grid grid-cols-2 md:grid-cols-5 gap-3">{Object.entries(data.kpis).map(([k,v])=><Metric key={k} label={k} value={String(v??0)}/>)}</section><section className="card p-4"><h2 className="font-semibold">Corrective-action queue</h2><div className="space-y-2 mt-3">{data.plans.length===0?<State text="No active corrective-action plans."/>:data.plans.map(p=><article key={p.plan_id} className="rounded-xl border border-[#233b55] p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><b>{p.finding_code} · plan version {p.plan_version}</b><span className="badge">{p.status} · {p.risk_level} ({p.risk_score})</span></div><div className="text-xs text-slate-500 mt-1">owner {p.owner_user_id} · AI authority {p.ai_authority} · due {String(p.due_at??"—")}</div><div className="flex gap-2 mt-3 flex-wrap">{p.status==="draft"&&<button className="btn btn-primary" onClick={()=>approve(p)}>Independent approve</button>}<button className="btn" onClick={()=>void inspect(p)}>Traceability</button>{["approved","retesting","closure_ready"].includes(p.status)&&<button className="btn btn-primary" onClick={()=>certify(p)}><CheckCircle2 className="h-4 w-4"/>Independent certify closure</button>}</div></article>)}</div></section></>:<State text="Loading remediation portfolio…"/>}
 {trace&&<section className="card p-4 space-y-3"><div className="flex flex-col xl:flex-row xl:items-center justify-between gap-3"><div><h2 className="font-semibold">Evidence-bound remediation workbench</h2><div className="text-xs text-slate-400 mt-1">Tasks {trace.tasks.length} · checkpoints {trace.checkpoints.length} · retests {trace.retests.length} · waivers {trace.waivers.length} · follow-ups {trace.followups.length} · certifications {trace.certifications.length}</div></div><div className="flex gap-2 flex-wrap"><button className="btn" onClick={addTask}>Add CAPA task</button><button className="btn" onClick={checkpoint}><FileCheck2 className="h-4 w-4"/>Lock evidence</button><button className="btn" onClick={retest}><RefreshCw className="h-4 w-4"/>Independent retest</button><button className="btn" onClick={followup}>Draft regulator follow-up</button></div></div><div className="space-y-2">{trace.tasks.map(t=><div key={t.task_key} className="border border-[#233b55] rounded-xl p-3 text-sm"><b>{t.task_key}</b> · {t.task_type} · {t.status} · deps {t.dependencies.join(", ")||"none"}{t.status!=="completed"&&<button className="btn ml-2" onClick={()=>completeTask(t)}>Complete with evidence</button>}</div>)}</div><div className="space-y-2">{trace.retests.map(r=><div key={`${r.control_key}-${r.sequence}`} className="border border-[#233b55] rounded-xl p-3 text-sm">Retest <b>{r.control_key}</b> · {r.outcome} · <span className="mono text-xs">{r.payload_sha256}</span></div>)}</div><div className="space-y-2">{trace.followups.map(f=><div key={f.followup_id} className="border border-[#233b55] rounded-xl p-3 text-sm">Follow-up version {f.version} · {f.status} · <span className="mono text-xs">{f.response_sha256}</span>{f.status==="draft"&&<button className="btn ml-2" onClick={()=>approveFollowup(f)}>Independent approve</button>}</div>)}</div><details><summary className="cursor-pointer text-sm text-slate-400">Full immutable provenance</summary><pre className="text-xs whitespace-pre-wrap overflow-auto max-h-[520px] bg-slate-950 p-3 rounded mt-2">{JSON.stringify(trace,null,2)}</pre></details></section>}
 <ActionDialog open={Boolean(dialog)} title={dialog?.title??""} description={dialog?.description} fields={dialog?.fields??[]} submitLabel={dialog?.submitLabel} busy={busy} onClose={()=>setDialog(null)} onSubmit={submit}/></div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="card p-4"><div className="text-xs text-slate-500 capitalize">{label.replaceAll("_"," ")}</div><div className="text-xl font-semibold mt-1">{value}</div></div>}
function State({text}:{text:string}){return <div className="rounded-xl border border-dashed border-[#31506f] p-5 text-sm text-slate-500">{text}</div>}
